file="activity_time_vo.go"
pkg="template"
class="ActivityTimeTemplateVO"
comment = "活动时间模板配置"
[[variables]]
name="Id"
type="int"
tag="id"
comment="id"

[[variables]]
name="ActivityId"
type="int"
tag="activity_id"
comment="活动ID"

[[variables]]
name="AfterOpensvrDays"
type="int32"
tag="after_opensvr_days"
comment="开服几天后开始第一次活动"

[[variables]]
name="KaiQiOpensvrDay"
type="int32"
tag="kaiqi_opensvr_day"
comment="开服几天后必定开启活动"

[[variables]]
name="KaiQiHeFuDay"
type="int32"
tag="kaiqi_hefu_day"
comment="合服几天后必定开启活动"

[[variables]]
name="AfterKaifuDayOver"
type="int32"
tag="after_kaifu_day_over"
comment="开服几天后结束开启活动"

[[variables]]
name="AfterHefuDays"
type="int32"
tag="after_hefu_days"
comment="合服几天后必定开启活动"

[[variables]]
name="AfterHefuDayOver"
type="int32"
tag="after_hefu_day_over"
comment="合服几天后结束开启活动"

[[variables]]
name="TimeQuantum"
type="string"
tag="time_quantum" 
comment="时间段"

[[variables]]
name="Weekday"
type="string"
tag="weekday"
comment="每周几开"

[[variables]]
name="Monthday"
type="string"
tag="monthday"
comment="每月几号开"


[[variables]]
name="BeginTime"
type="string"
tag="begin_time"
comment="活动开始时间"

[[variables]]
name="EndTime"
type="string"
tag="end_time"
comment="活动结束时间"

[[variables]]
name="ActivityTimes"
type="int64"
tag="activity_times"
comment="活动持续时间"

[[variables]]
name="PopTimes"
type="int64"
tag="pop_times"
comment="活动弹窗时间"

[[variables]]
name="BeginNoticeTime"
type="int64"
tag="begin_notice_time"
comment="活动开始前多久开始刷公告"

[[variables]]
name="EndNoticeTime"
type="int64"
tag="end_notice_time"
comment="活动结束前多久开始刷公告"

[[variables]]
name="IconRemindTime"
type="int64"
tag="icon_remind_time"
comment="距离活动开始前多久弹提示"

[[variables]]
name="AwardTimes"
type="int32"
tag="award_times"
comment="每日可获得的奖励次数"

[[variables]]
name="BeiShu"
type="int32" 
tag="beishu"
comment="奖励倍数"