file="activity_vo.go"
pkg="template"
class="ActivityTemplateVO"
comment = "活动模板配置"
[[variables]]
name="Id"
type="int"
tag="id"
comment="id"

[[variables]]
name="Name"
type="string"
tag="name"
comment="活动名称"

[[variables]]
name="ActiveType"
type="int32"
tag="active_type"
comment="活动类型"

[[variables]]
name="Mapid"
type="int32"
tag="mapid"
comment="活动地图ID"

[[variables]]
name="SubMapid"
type="int32"
tag="sub_mapid"
comment="子活动地图ID"

[[variables]]
name="LevMin"
type="int32"
tag="lev_min"
comment="参与最小等级限制"

[[variables]]
name="LevMax"
type="int32"
tag="lev_max"
comment="参与最大等级限制"

[[variables]]
name="KaiqiId"
type="int32"
tag="kaiqi_id"
comment="功能开启ID"

[[variables]]
name="NeedKaiqiId"
type="int32"
tag="need_kaiqi_id"
comment="进入需要的功能开启ID"

[[variables]]
name="JoinCount"
type="int32"
tag="join_count"
comment="每天限制参与次数"

[[variables]]
name="NoticeInterval"
type="int64"
tag="notice_interval"
comment="公告间隔时间"

[[variables]]
name="NoticeContentBegin"
type="string"
tag="notice_content_begin"
comment="活动开始时公告内容"

[[variables]]
name="NoticeContentEnd"
type="string"
tag="notice_content_end"
comment="活动结束时公告内容"

[[variables]]
name="NoticeContentSoonbegin"
type="string"
tag="notice_content_soonbegin"
comment="即将开始时的公告内容"

[[variables]]
name="NoticeContentSoonend"
type="string"
tag="notice_content_soonend"
comment="即将结束时公告的内容"
