file="alchemy_vo.go"
pkg="template"
class="AlchemyTemplateVO"
comment = "炼丹配置"
[[variables]]
name="Id"
type="int"
tag="id"
comment="id"

[[variables]]
name="SynthetiseId"
type="int32"
tag="synthetise_id"
comment="合成丹药id"

[[variables]]
name="SynthetiseNum"
type="int32"
tag="synthetise_num"
comment="合成丹药数量"

[[variables]]
name="NeedItemId1"
type="int32"
tag="need_item_id1"
comment="需要物品id1"

[[variables]]
name="NeedItemNum1"
type="int32"
tag="need_item_num1"
comment="需要物品数量1"

[[variables]]
name="NeedItemId2"
type="int32"
tag="need_item_id2"
comment="需要物品id2"

[[variables]]
name="NeedItemNum2"
type="int32"
tag="need_item_num2"
comment="需要物品数量2"

[[variables]]
name="NeedItemId3"
type="int32"
tag="need_item_id3"
comment="需要物品id3"

[[variables]]
name="NeedItemNum3"
type="int32"
tag="need_item_num3"
comment="需要物品数量3"

[[variables]]
name="Time"
type="int32"
tag="time"
comment="单个丹药练成所需时间(毫秒)"

[[variables]]
name="AccelerateMoney"
type="int32"
tag="accelerate_money"
comment="单个丹药加速消耗元宝"



