file="alliance_vo.go"
pkg="template"
class="AllianceTemplateVO"
comment = "仙盟模板配置"
[[variables]]
name="Id"
type="int"
tag="id"
comment="id"

[[variables]]
name="UnionType"
type="int32"
tag="union_type"
comment="仙盟版本"


[[variables]]
name="UnionLevel"
type="int32"
tag="union_level"
comment="仙盟等级"

[[variables]]
name="UnionBuild"
type="int64"
tag="union_build"
comment="升级所需建设度"

[[variables]]
name="NextLevelId"
type="int32"
tag="next_level_id"
comment="下一级id"

[[variables]]
name="UnionParentLevel"
type="int32"
tag="union_parent_level"
comment="升级所需的前置等级"


[[variables]]
name="UnionMax"
type="int32"
tag="union_max"
comment="联盟最高人数"


[[variables]]
name="UnionPost2"
type="int32"
tag="union_post2"
comment="副盟主数量"

[[variables]]
name="UnionPost3"
type="int32"
tag="union_post3"
comment="堂主数量"

[[variables]]
name="UnionPost4"
type="int32" 
tag="union_post4"
comment="精英数量"


[[variables]]
name="UnionStorage"
type="int32"
tag="union_storage"
comment="仙盟仓库数量"