file="alliance_skill_vo.go"
pkg="template"
class="AllianceSkillTemplateVO"
comment = "仙术模板配置"
[[variables]]
name="Id"
type="int"
tag="id"
comment="id"

[[variables]]
name="Name"
type="string"
tag="name"
comment="仙术名称"

[[variables]]
name="Type"
type="int32"
tag="type"
comment="仙术类型"

[[variables]]
name="Level"
type="int32"
tag="level"
comment="仙法等级"

[[variables]]
name="Des"
type="string"
tag="des"
comment="仙法描述"

[[variables]]
name="DesInfo"
type="string"
tag="des_info"
comment="仙法描述（扩展）"

[[variables]]
name="NeedContribution"
type="int64"
tag="need_contribution"
comment="升级所需贡献度"

[[variables]]
name="SkillId"
type="int32"
tag="skill_id"
comment="属性id"

[[variables]]
name="NextId"
type="int32"
tag="next_id"
comment="下级id"

[[variables]]
name="need_level_id"
type="int32"
tag="need_level_id"
comment="前置等级id"

[[variables]]
name="NeedUnionLevel"
type="int32"
tag="need_union_level"
comment="需要的仙盟等级"

[[variables]]
name="OpenNeedLevel"
type="int32"
tag="open_need_level"
comment="仙术开启所需仙盟等级"

[[variables]]
name="shunxu"
type="int32"
tag="shunxu"
comment="前端技能顺序"