file="anquanqu_vo.go"
pkg="template"
class="AnquanquTemplateVO"
comment = "安全区"
[[variables]]
name="Id"
type="int"
tag="id"
comment="id"

[[variables]]
name="NextId"
type="int32"
tag="next_id"
comment="下一个id"

[[variables]]
name="PosX"
type="float64"
tag="pos_x"
comment="位置x"

[[variables]]
name="PosZ"
type="float64"
tag="pos_z"
comment="位置z"
