file="arena_rank_vo.go"
pkg="template"
class="ArenaRankTemplateVO"
comment = "3v3排行榜配置"
[[variables]]
name="Id"
type="int"
tag="id"
comment="id"

[[variables]]
name="RankMin"
type="int32"
tag="rank_min"
comment="排名区间最小值"

[[variables]]
name="RankMax"
type="int32"
tag="rank_max"
comment="排名区间最大值"

[[variables]]
name="GetSilver"
type="int32"
tag="rew_silver"
comment="排名获得的银两"

[[variables]]
name="GetBindGold"
type="int32"
tag="rew_bind_gold"
comment="排名获得的绑元"

[[variables]]
name="GetGold"
type="int32" 
tag="rew_gold"
comment="排名获得的元宝"

[[variables]]
name="GetItemId"
type="string"
tag="rew_item_id"
comment="排名获得的物品"

[[variables]]
name="GetItemCount"
type="string"
tag="rew_item_count"
comment="排名获得的物品数量"

