file="arenapvp_taotai_vo.go"
pkg="template"
class="ArenapvpTaoTaiTemplateVO"
comment = "竞技场pvp淘汰配置"
[[variables]]
name="Id"
type="int"
tag="id"
comment="id"

[[variables]]
name="Type"
type="int32"
tag="changci"
comment="类型"

[[variables]]
name="WinSilver"
type="int32"
tag="win_silver"
comment="银两"

[[variables]]
name="WinGold"
type="int32"
tag="win_gold"
comment="元宝"

[[variables]]
name="WinBindGold"
type="int32"
tag="win_bind_gold"
comment="绑元"

[[variables]]
name="WinItemId"
type="string"
tag="win_item_id"
comment="物品id"

[[variables]]
name="WinItemCount"
type="string"
tag="win_item_count"
comment="物品数量"

[[variables]]
name="WinJifen"
type="int32"
tag="win_jifen"
comment="积分"

[[variables]]
name="LoseSilver" 
type="int32" 
tag="lose_silver"
comment="银两"

[[variables]] 
name="LoseGold"
type="int32"
tag="lose_gold"
comment="元宝"

[[variables]]
name="LoseBindGold"
type="int32"
tag="lose_bind_gold"
comment="绑元"

[[variables]]
name="LoseItemId"
type="string"
tag="lose_item_id"
comment="物品id"

[[variables]]
name="LoseItemCount"
type="string"
tag="lose_item_count"
comment="物品数量"

[[variables]]
name="LoseJifen"
type="int32"
tag="rew_jifen"
comment="积分"

