file="arena_constant_vo.go"
pkg="template"
class="ArenaConstantTemplateVO"
comment = "竞技场常量模板配置"
[[variables]]
name="Id"
type="int"
tag="id"
comment="id"

[[variables]]
name="MapId"
type="int32"
tag="map_id"
comment="pk地图"

[[variables]]
name="MapId1"
type="int32"
tag="map_id1"
comment="青龙地图"

[[variables]]
name="MapId2"
type="int32"
tag="map_id2"
comment="白虎地图"

[[variables]]
name="MapId3"
type="int32"
tag="map_id3"
comment="朱雀地图"

[[variables]]
name="MapId4"
type="int32"
tag="map_id4"
comment="玄武地图"

[[variables]]
name="PosX1"
type="float64"
tag="pos_x1"
comment="位置1 x"

[[variables]]
name="PosY1"
type="float64"
tag="pos_y1"
comment="位置1 y"

[[variables]]
name="PosZ1"
type="float64"
tag="pos_z1"
comment="位置1 z"

[[variables]]
name="PosX2"
type="float64"
tag="pos_x2"
comment="位置2 x"

[[variables]]
name="PosY2"
type="float64"
tag="pos_y2"
comment="位置2 y"

[[variables]]
name="PosZ2"
type="float64"
tag="pos_z2"
comment="位置2 z"


[[variables]]
name="RebornAmountMax"
type="int32"
tag="reborn_amount_max"
comment="复活次数"

[[variables]]
name="RevivePar"
type="int32"
tag="revive_par"
comment="复活系数"

[[variables]]
name="ReviveValue"
type="int32"
tag="revive_value"
comment="复活系数"


[[variables]]
name="ReviveItem"
type="int32"
tag="revive_item"
comment="复活单id"

[[variables]]
name="BattleTime"
type="int32"
tag="battle_time"
comment="倒计时"

[[variables]]
name="TherionWinCount"
type="int32"
tag="therion_win_count"
comment="获胜轮次"

# ------废弃start--------


[[variables]]
name="TreeGetTime"
type="int64"
tag="tree_get_time"
comment="采集时间"

[[variables]]
name="EquipBoxRate"
type="string"
tag="equip_box_rate"
comment="掉落宝箱比例"

[[variables]]
name="EquipBoxId"
type="string"
tag="equip_box_id"
comment="掉落宝箱id"

[[variables]]
name="EquipBoxTime"
type="int64"
tag="equip_box_time"
comment="宝箱采集时间"

[[variables]]
name="TreeId"
type="int32"
tag="tree_id"
comment="经验树id"

[[variables]]
name="WinCount"
type="int32"
tag="win_count"
comment="最大奖励次数"

[[variables]]
name="CaijiItem"
type="int32"
tag="caiji_item"
comment="采集掉落宝箱id"

[[variables]]
name="CaijiItemCount"
type="int32"
tag="caiji_item_count"
comment="采集掉落宝箱数量"

[[variables]]
name="TeamCount"
type="int32"
tag="team_count"
comment="四圣兽队伍数量"

[[variables]]
name="TreeExp"
type="int32"
tag="tree_exp"
comment="经验"

[[variables]]
name="TreeExpPoint"
type="int32"
tag="tree_exp_point"
comment="经验点"

[[variables]]
name="PreBoxItem"
type="string"
tag="pre_box_item"
comment="宝箱预览"

# ------废弃end--------

[[variables]]
name="AttrMin"
type="int32"
tag="attr_min"
comment="属性区间"

[[variables]]
name="AttrMax"
type="int32"
tag="attr_max"
comment="属性区间"



[[variables]]
name="ReviveMin"
type="int32"
tag="revive_min"
comment="复活最小"

[[variables]]
name="ReviveMax"
type="int32"
tag="revive_max"
comment="复活最大"

[[variables]]
name="RiZhiTimeMin"
type="int32"
tag="rizhi_time_min"
comment="假人日志刷新时间下限(单位毫秒)"

[[variables]]
name="RiZhiTimeMax"
type="int32"
tag="rizhi_time_max"
comment="假人日志刷新时间上限(单位毫秒)"

[[variables]]
name="RiZhiMax"
type="int32"
tag="rizhi_max"
comment="假人日志刷新时间上限(单位毫秒)"

[[variables]]
name="BeginTime"
type="string"
tag="begin_time"
comment="活动开始时间"

[[variables]]
name="EndTime"
type="string"
tag="end_time"
comment="活动结束时间"

[[variables]]
name="JiFenMaxDay"
type="int32"
tag="jifen_max_day"
comment="每天获取积分上限"

[[variables]]
name="TitleId"
type="int32"
tag="title_id"
comment="连胜称号id"

[[variables]]
name="RankCount"
type="int32"
tag="rank_count"
comment="排行榜人数"

[[variables]]
name="RankFirstRew"
type="int32"
tag="rank_first"
comment="第一奖励物品id"




