file="arenapvp_vo.go"
pkg="template"
class="ArenapvpTemplateVO"
comment = "竞技场pvp配置"

[[variables]]
name="Id"
type="int"
tag="id"
comment="id"

[[variables]]
name="NextId"
type="int32" 
tag="next_id"
comment="下一场id"

[[variables]]
name="Type"
type="int32" 
tag="changci" 
comment="场次类型"

[[variables]]
name="PVPPlayerCount"  
type="int32" 
tag="player_all_count" 
comment="总人数"
 
[[variables]] 
name="PVPCount"
type="int32" 
tag="huichang_count" 
comment="场数"

[[variables]]
name="MapId"
type="int32"
tag="map_id"
comment="地图id"

[[variables]]
name="BirthPos1"
type="string"
tag="birth_pos1"
comment="出生点1"

[[variables]]
name="BirthPos2"
type="string"
tag="birth_pos2"
comment="出生点2" 

[[variables]]
name="BirthGuanzhong"
type="string"
tag="birth_guanzhong"
comment="观众出生点"

[[variables]]
name="RebornCountMax"
type="int32"
tag="reborn_count_max"
comment="复活次数"

[[variables]]
name="BeginTime"
type="string"
tag="begin_time"
comment="开始时间"

[[variables]]
name="EndTime"
type="string"
tag="end_time"
comment="结束时间"

[[variables]]
name="ZhanDouTime"
type="int64"
tag="zhandou_time"
comment="倒计时"

[[variables]]
name="JingchaiUseBindgold"
type="int32"
tag="jingchai_use_bindgold"
comment="竞猜消耗绑元"

[[variables]]
name="JingcaiWinBindgold"
type="int32"
tag="jingcai_win_bindgold"
comment="竞猜正确绑元"

[[variables]]
name="JingcaiWinGetItemId"
type="string"
tag="jingcai_win_get_item_id"
comment="竞猜正确奖励id"

[[variables]]
name="JingcaiWinGetItemCount"
type="string"
tag="jingcai_win_get_item_count"
comment="竞猜正确奖励数量"

[[variables]]
name="JingcaiLoseGetItemId"
type="string"
tag="jingcai_lose_get_item_id"
comment="竞猜错误奖励id"

[[variables]]
name="JingcaiLoseGetItemCount"
type="string"
tag="jingcai_lose_get_item_count"
comment="竞猜错误奖励数量"