file="arena_vo.go"
pkg="template"
class="ArenaTemplateVO"
comment = "竞技场配置"

[[variables]]
name="Id"
type="int"
tag="id"
comment="id"

[[variables]]
name="Type"
type="int32"
tag="type"
comment="类型"

[[variables]]
name="LianXuCount"
type="int32"
tag="lianxu_count"
comment="连续次数"

[[variables]]
name="LianXuGetJifen"
type="int32"
tag="lianxu_get_jifen"
comment="连续获得积分"

[[variables]]
name="LianxuGetItemId"
type="string"
tag="lianxu_get_item_id"
comment="竞技场奖励物品" 

[[variables]]
name="LianxuGetItemCount"
type="string"
tag="lianxu_get_item_count"
comment="竞技场奖励数量"


# ------废弃start--------

[[variables]]
name="ArenaNum"
type="int32"
tag="arena_num"
comment="竞技场等级"

[[variables]]
name="ArenaSilver"
type="int32"
tag="arena_silver"
comment="竞技场银两奖励"

[[variables]]
name="ArenaItemId"
type="string"
tag="arena_item_id"
comment="竞技场奖励物品"

[[variables]]
name="ArenaItemAmount"
type="string"
tag="arena_item_amount"
comment="竞技场奖励数量"
# ------废弃end--------