file="arenapvp_constant_vo.go"
pkg="template"
class="ArenapvpConstantTemplateVO"
comment = "竞技场pvp常量模板配置"
[[variables]]
name="Id"
type="int"
tag="id"
comment="id"

[[variables]]
name="IsJiaren"
type="int32" 
tag="is_jiaren"
comment="是否优先匹配假人"

[[variables]]
name="CunhuoFristTiem"
type="int32"
tag="cunhuo_frist_tiem"
comment="进入会场多少时间获得积分"

[[variables]]
name="CunhuoTime"
type="int32"
tag="cunhuo_time"
comment="会场获得积分间隔"

[[variables]]
name="CunhuoJifen"
type="int32"
tag="cunhuo_jifen"
comment="会场获得积分数量"

[[variables]]
name="XingYunFirstTime"
type="int64"
tag="xingyun_first_time"
comment="幸运奖开始时间"

[[variables]]
name="XingYunTime"
type="int64"
tag="xingyun_time"
comment="幸运奖循环时间"

[[variables]]
name="XingYunPlayerCount"
type="int32"
tag="xingyun_player_count"
comment="幸运奖人数"

[[variables]]
name="XinyunRobotRate"
type="int32"
tag="xinyun_robot_rate"
comment="幸运奖假人概率"

[[variables]]
name="XingYunItemId"
type="int32"
tag="xingyun_item_id"
comment="幸运奖物品id"

[[variables]]
name="JifenBekillPercent"
type="int32"
tag="jifen_bekill_percent" 
comment="死亡损失积分百分比"
 
[[variables]]
name="ZhenshiPlayerRobot"
type="int32"
tag="zhenshi_player_robot"
comment="插入机器人条件" 
 
[[variables]]
name="RobotAddTime"
type="int64"
tag="robot_add_time"
comment="插入机器人间隔"
 
[[variables]]
name="RobotMax"
type="int32"
tag="robot_max"
comment="机器人上限"
 
[[variables]]
name="AttrRatioMin"
type="int64"
tag="attr_min"
comment="机器人下限"
 
[[variables]]
name="AttrRatioMax"
type="int64"  
tag="attr_max"
comment="机器人上限"
 
[[variables]]
name="RuchangUseBindgold"
type="int32"  
tag="ruchang_use_bindgold"
comment="门票价格"
