

file="attr_vo.go"
pkg="template"
class="AttrTemplateVO"
comment = "属性配置"
[[variables]]
name="Id"
type="int"
tag="id"
comment="id"

[[variables]]
name="Hp"
type="int32"
tag="hp"
comment="血量"

[[variables]]
name="Tp"
type="int32"
tag="tp"
comment="体力"

[[variables]]
name="Attack"
type="int32"
tag="attack"
comment="攻击"

[[variables]]
name="Defence"
type="int32"
tag="defence"
comment="防御"

[[variables]]
name="Critical"
type="int32"
tag="critical"
comment="暴击"

[[variables]]
name="Tough"
type="int32"
tag="tough"
comment="坚韧"

[[variables]]
name="Block"
type="int32"
tag="block"
comment="格挡"

[[variables]]
name="Abnormality"
type="int32"
tag="abnormality"
comment="破格"

[[variables]]
name="Hit"
type="int32"
tag="hit"
comment="命中"

[[variables]]
name="Dodge"
type="int32"
tag="dodge"
comment="闪避"

[[variables]]
name="HunyuanAtt"
type="int32"
tag="hunyuan_att"
comment="混元攻击"

[[variables]]
name="HunyuanDef"
type="int32"
tag="hunyuan_def"
comment="混元防御"

[[variables]]
name="HarmPercent"
type="int32"
tag="harm_percent"
comment="增伤万分比"

[[variables]]
name="HarmValue"
type="int32"
tag="harm_value"
comment="增伤值"



[[variables]]
name="CuthurtPercent"
type="int32"
tag="cuthurt_percent"
comment="减伤万分比"

[[variables]]
name="CuthurtValue"
type="int32"
tag="cuthurt_value"
comment="减伤值"


[[variables]]
name="BingdongRes"
type="int32"
tag="bingdong_res"
comment="冰冻抗体"


[[variables]]
name="PojiaRes"
type="int32"
tag="pojia_res"
comment="破甲抗体"

[[variables]]
name="KuileiRes"
type="int32"
tag="kuilei_res"
comment="傀儡抗体"

[[variables]]
name="KujieRes"
type="int32"
tag="kujie_res"
comment="枯竭抗体"

[[variables]]
name="ShimingRes"
type="int32"
tag="shiming_res"
comment="失明抗体"

[[variables]]
name="HunmiRes"
type="int32"
tag="hunmi_res"
comment="昏迷抗体"

[[variables]]
name="XuruoRes"
type="int32"
tag="xuruo_res"
comment="虚弱抗体"

[[variables]]
name="JiaoxieRes"
type="int32"
tag="jiaoxie_res"
comment="缴械抗体"

[[variables]]
name="ZhongduRes"
type="int32"
tag="zhongdu_res"
comment="中毒抗体"

[[variables]]
name="ZhuoshaoRes"
type="int32"
tag="zhuoshao_res"
comment="灼烧抗性"

[[variables]]
name="JiansuRes"
type="int32"
tag="jiansu_res"
comment="减速抗性"

[[variables]]
name="DingshenRes"
type="int32"
tag="dingshen_res"
comment="定身抗性"


[[variables]]
name="MoveSpeed"
type="int32"
tag="speed_move"
comment="移动速度"

[[variables]]
name="FantanAdd"
type="int32"
tag="fantan_add"
comment="反弹伤害"

[[variables]]
name="FantanPercent"
type="int32"
tag="fantan_percent"
comment="反弹万分比"


[[variables]]
name="CritRatePercent"
type="int32"
tag="crit_rate_percent"
comment="强制暴击万分比"

[[variables]]
name="CritHarmPercent"
type="int32"
tag="crit_harm_percent"
comment="强制暴击伤害万分比"

[[variables]]
name="HitRatePercent"
type="int32"
tag="hit_rate_percent"
comment="强制命中率"

[[variables]]
name="DodgeRatePercent"
type="int32"
tag="dodge_rate_percent"
comment="强制闪避"


[[variables]]
name="BlockRatePercent"
type="int32"
tag="block_rate_percent"
comment="强制格挡"

[[variables]]
name="SpellCdPercent"
type="int32"
tag="spell_cd_percent"
comment="cd"

[[variables]]
name="AddExp"
type="int32"
tag="add_exp"
comment="增加经验比例"


[[variables]]
name="HpPercent"
type="int32"
tag="hp_percent"
comment="生命万分比"


[[variables]]
name="AttackPercent"
type="int32"
tag="attack_percent"
comment="攻击万分比"


[[variables]]
name="DefPercent"
type="int32"
tag="def_percent"
comment="防御万分比"






