file="baby_pregnant_vo.go"
pkg="template"
class="BabyPregnantTemplateVO"
comment = "宝宝怀孕模板配置"
[[variables]]
name="Id"
type="int"
tag="id"
comment="id"
 
[[variables]]
name="BupinQujian"
type="string"
tag="bupin_qujian"
comment="补品值"
 
[[variables]]
name="Quality"
type="int32"
tag="quality"
comment="品质"
 
[[variables]]
name="NameNv"
type="string"
tag="name_nv"
comment="女宝宝名称"
 
[[variables]]
name="NameNan"
type="string"
tag="name_nan"
comment="男宝宝名称"
 
[[variables]]
name="AttrType"
type="int32"
tag="attr_type"
comment="属性二进制"
 
[[variables]]
name="DanBeiQujian"
type="string"
tag="danbei_qujian"
comment="属性倍数区间"
 
[[variables]]
name="TalentCount"
type="int32"
tag="talent_count"
comment="天赋数量"
 
[[variables]]
name="TalentBeginId"
type="int32"
tag="talent_begin_id"
comment="天赋池id"
 
[[variables]]
name="GrowthNum"
type="int32"
tag="growth_num"
comment="成长值"
 
[[variables]]
name="LevelMax"
type="int32"
tag="level_max"
comment="读书最高等级"
 
[[variables]]
name="AttrShareRate"
type="int32"
tag="attr_share_rate"
comment="属性提供比率"

[[variables]]
name="Rate"
type="int64"
tag="rate"
comment="宝宝出生概率"
 