file="baby_unlock_talent_vo.go"
pkg="template"
class="BabyUnlockTalentTemplateVO"
comment = "宝宝解锁天赋模板配置"
[[variables]]
name="Id"
type="int"
tag="id"
comment="id"
 
[[variables]]
name="NextId"
type="int"
tag="next_id"
comment="下一级"
 
[[variables]]
name="Times"
type="int32"
tag="times"
comment="次数"
 
[[variables]]
name="UseGold"
type="int32"
tag="use_gold"
comment="消耗元宝"
 
[[variables]]
name="SuodingGold"
type="int32"
tag="suoding_gold"
comment="锁定消耗元宝"
  