

file="baby_toy_suit_vo.go"
pkg="template"
class="BabyToySuitTemplateVO"
comment = "宝宝玩具套装属性配置"
[[variables]]
name="Id"
type="int"
tag="id"
comment="id"

[[variables]]
name="Type"
type="int32"
tag="type"
comment="属性类型"

[[variables]]
name="Value1"
type="int32"
tag="value1"
comment="当type=1时,此字段为攻击时附加buff的id"

[[variables]]
name="Num"
type="int32"
tag="num"
comment="激活属性所需数量"

