

file="baby_tou_suit_group_vo.go"
pkg="template"
class="BabyToySuitGroupTemplateVO"
comment = "宝宝玩具套装配置"
[[variables]]
name="Id"
type="int"
tag="id"
comment="id"

[[variables]]
name="Name"
type="string"
tag="name"
comment="套装名称"

[[variables]]
name="MaxNum"
type="int32"
tag="max_num"
comment="套装最大数量"

[[variables]]
name="SuitId1"
type="int32"
tag="suit_id1"
comment="套装效果一"

[[variables]]
name="SuitId2"
type="int32"
tag="suit_id2"
comment="套装效果二"

[[variables]]
name="SuitId3"
type="int32"
tag="suit_id3"
comment="套装效果三"
