file="baby_constant_vo.go"
pkg="template"
class="BabyConstantTemplateVO"
comment = "宝宝常量模板配置"
[[variables]]
name="Id"
type="int"
tag="id"
comment="id"
 
[[variables]]
name="RiverItem"
type="int32"
tag="river_item"
comment="字母河水物品"

[[variables]]
name="BupinItemId"
type="int32" 
tag="bupin_item_id"
comment="补品物品id"
 
[[variables]]
name="BupinItemCount"
type="int32" 
tag="bupin_item_count"
comment="补品消耗数量"

[[variables]]
name="BupinMax"
type="int32" 
tag="bupin_max"
comment="最大食用次数"
 
[[variables]]
name="BupinQujian"
type="string" 
tag="bupin_qujian"
comment="补品随机值"

[[variables]]
name="BornTime"
type="int64"
tag="time_down"
comment="出生倒计时"

[[variables]]
name="GoldZaoChan" 
type="int32"
tag="gold_zaochan"
comment="加速出生消耗元宝"

[[variables]]
name="BabyCount"
type="int32"
tag="baby_count"
comment="基础宝宝数量"
 
[[variables]]
name="ZsTianFuReturnRate"
type="int32"
tag="zs_tianfu_return_rate"
comment="转世后天赋技能返还的道具万分比"
 
[[variables]]
name="GoldChaoSheng"
type="string" 
tag="gold_chaosheng"
comment="超生消耗元宝"
 
[[variables]]
name="BooksId"
type="string" 
tag="books_id"
comment="四书五经物品"
  
[[variables]]
name="GaiMingKaId"
type="int32" 
tag="gaimingka_id"
comment="宝宝改名卡"
  
[[variables]]
name="LimitSkiiNum"
type="int32" 
tag="limit_skii_num"
comment="天赋技能数量"

[[variables]]
name="BaoBaoCard"
type="int32" 
tag="baobao_card"
comment="宝宝卡id"

[[variables]]
name="XiLianItemId"
type="int32"
tag="xilian_item_id"
comment="洗练消耗物品"

[[variables]]
name="XiLianItemCount"
type="int32"
tag="xilian_item_count"
comment="洗练消耗数量"

[[variables]]
name="XiLianCoefficient"
type="int32"
tag="xilian_coefficient"
comment="洗练消耗系数"

[[variables]]
name="XiLianCoefficientFixed"
type="int32"
tag="xilian_coefficient_2"
comment="洗练消耗固定值"

[[variables]]
name="XilianNum"
type="int32"
tag="xilian_num"
comment="洗练次数"
 
[[variables]]
name="GrowthCoefficient"
type="int32"
tag="growth_coefficient"
comment="成长系数"
 
[[variables]]
name="TishiChushengTime"
type="string"
tag="tishi_chusheng_time"
comment="出生提示"