file="baby_dongfang_vo.go"
pkg="template"
class="BabyDongFangTemplateVO"
comment = "宝宝洞房模板配置"
[[variables]]
name="Id"
type="int"
tag="id"
comment="id"

[[variables]]
name="NextId"
type="int"
tag="next_id"
comment="下一级" 

[[variables]]
name="BabyCount"
type="int32"
tag="baby_count"
comment="宝宝数量"

[[variables]]
name="PregnantRate"
type="int32"
tag="pregnant_rate"
comment="怀孕概率"

[[variables]]
name="PregnantItem"
type="int32"
tag="pregnant_item"
comment="洞房消耗物品"
 
[[variables]]
name="PregnantCount"
type="int32"
tag="pregnant_count"
comment="洞房消耗物品数量"
  
[[variables]]
name="FailReturnItem"
type="string"
tag="fail_return_item"
comment="失败返回物品"
 
[[variables]]
name="FailReturnItemCount"
type="string"
tag="fail_return_item_count"
comment="失败返回物品数量"
  