file="baby_quality_vo.go"
pkg="template"
class="BabyQualityTemplateVO"
comment = "宝宝品质模板配置"
[[variables]]
name="Id"
type="int"
tag="id" 
comment="id"
 
[[variables]]
name="QuJian"
type="string"
tag="qujian"
comment="补品区间"
 
[[variables]]
name="NextId"
type="int"
tag="next_id"
comment="下一级id"
 
[[variables]]
name="Type1"
type="int32"
tag="type_1"
comment="品质1"
 
[[variables]]
name="Type2"
type="int32"
tag="type_2"
comment="品质2"
 
[[variables]]
name="Type3"
type="int32"
tag="type_3"
comment="品质3"
 
[[variables]]
name="Type4"
type="int32"
tag="type_4"
comment="品质4"
 
[[variables]]
name="Rate1"
type="int32"
tag="rate_1"
comment="权重"
 
[[variables]]
name="Rate2"
type="int32"
tag="rate_2"
comment="权重2"
 
[[variables]]
name="Rate3"
type="int32"
tag="rate_3"
comment="权重3"
 
[[variables]]
name="Rate4"
type="int32"
tag="rate_4"
comment="权重4"
 
  