file="baby_learn_vo.go"
pkg="template"
class="BabyLearnTemplateVO"
comment = "宝宝读书模板配置"
[[variables]]
name="Id"
type="int"
tag="id"
comment="id"
 
[[variables]]
name="NextId"
type="int"
tag="next_id"
comment="下一级id"
 
[[variables]]
name="Level"
type="int32"
tag="level"
comment="读书等级"

[[variables]]
name="Experience"
type="int32" 
tag="experience"
comment="经验"

[[variables]]
name="AttrType"
type="int32"
tag="attr_type"
comment="属性二进制"

[[variables]]
name="BeiShu"
type="int32"
tag="beishu"
comment="属性倍数"

[[variables]]
name="ZsReturnItem"
type="string"
tag="zs_return_item"
comment="转世返还物品"

[[variables]]
name="ZsReturnCount"
type="string" 
tag="zs_return_count"
comment="转世返还数量"

