

file="baby_toy_uplevel_vo.go"
pkg="template"
class="BabyToyUplevelTemplateVO"
comment = "宝宝玩具升级配置"
[[variables]]
name="Id"
type="int"
tag="id"
comment="id"

[[variables]]
name="SuitType"
type="int32"
tag="type"
comment="套装类型"

[[variables]]
name="Position"
type="int32"
tag="position"
comment="部位"

[[variables]]
name="Level"
type="int32"
tag="level"
comment="玩具等级"

[[variables]]
name="NextId"
type="int32"
tag="next_id"
comment="下级id"

[[variables]]
name="Rate"
type="int32"
tag="success_rate"
comment="强化概率"

[[variables]]
name="Hp"
type="int32"
tag="hp"
comment="生命"

[[variables]]
name="Attack"
type="int32"
tag="attack"
comment="攻击"

[[variables]]
name="Defence"
type="int32"
tag="defence"
comment="防御"

[[variables]]
name="ReturnRate"
type="int32"
tag="return_rate"
comment="回退概率"

[[variables]]
name="FailReturnStrengthenId"
type="int32"
tag="fail_return_strengthen_id"
comment="回退等级"

[[variables]]
name="silver_num"
type="int32"
tag="silver_num"
comment="强化消耗"

[[variables]]
name="NeedItem"
type="int32"
tag="need_item"
comment="强化消耗的物品id"

[[variables]]
name="ItemCount"
type="int32" 
tag="need_item_num"
comment="强化消耗的物品数量"

