file="baby_talent_vo.go"
pkg="template"
class="BabyTalentTemplateVO"
comment = "宝宝天赋模板配置"
[[variables]]
name="Id"
type="int"
tag="id"
comment="id"
 
[[variables]]
name="NextId"
type="int"
tag="next_id"
comment="下一级id"
  
[[variables]]
name="Type"
type="int32"
tag="type"
comment="技能类型"

[[variables]]
name="SkillId"
type="int32"
tag="skill_id"
comment="技能id"
 
[[variables]]
name="Rate"
type="int32"
tag="rate"
comment="权重"


 