file="baguamijing_buchang_vo.go"
pkg="template"
class="BaGuaMiJingBuChangTemplateVO"
comment="八卦秘境补偿"

[[variables]]
name="Id"
type="int"
tag="id"
comment="id"

[[variables]]
name="Level"
type="int32"
tag="number"
comment="八卦秘境层数"

[[variables]]
name="ItemId"
type="string"
tag="return_item_id"
comment="返还物品id"

[[variables]]
name="ItemCount"
type="string"
tag="return_item_count"
comment="返还物品数量"
