file="baokujifen_vo.go"
pkg="template"
class="BaoKuJiFenTemplateVO"
comment = "装备宝库积分商城配置"
[[variables]]
name="Id"
type="int"
tag="id"
comment="id"

[[variables]]
name="Type"
type="int32"
tag="type"
comment="宝库类型"

[[variables]]
name="ZhuanshuMin"
type="int32"
tag="zhuanshu_min"
comment="最小转数"

[[variables]]
name="ZhuanshuMax"
type="int32"
tag="zhuanshu_max"
comment="最大转数"

[[variables]]
name="LevelMin"
type="int32"
tag="level_min"
comment="最小等级"

[[variables]]
name="LevelMax"
type="int32"
tag="level_max"
comment="最大等级"

[[variables]]
name="ItemIdKaiTianNan"
type="int32"
tag="item_id"
comment="开天男兑换物品id"

[[variables]]
name="ItemIdKaiTianNv"
type="int32"
tag="item_id_kaitian_nv"
comment="开天女兑换物品id"

[[variables]]
name="ItemIdYiJianNan"
type="int32"
tag="item_id_yijian_nan"
comment="弈剑男兑换物品id"

[[variables]]
name="ItemIdYiJianNv"
type="int32"
tag="item_id_yijian_nv"
comment="弈剑女兑换物品id"

[[variables]]
name="ItemIdPoYueNan"
type="int32"
tag="item_id_poyue_nan"
comment="破月男兑换物品id"

[[variables]]
name="ItemIdPoYueNv"
type="int32"
tag="item_id_poyue_nv"
comment="破月女兑换物品id"

[[variables]]
name="BuyCount"
type="int32"
tag="buy_count"
comment="一次性兑换数量"

[[variables]]
name="UseJiFen"
type="int32"
tag="use_jifen"
comment="消耗积分"

[[variables]]
name="MaxCount"
type="int32"
tag="max_count"
comment="每天最多兑换次数"

[[variables]]
name="Pos"
type="int32"
tag="pos"
comment="排序"