file="bargain_shop_vo.go"
pkg="template"
class="BargainShopTemplateVO"
comment = "打折礼包配置"
[[variables]]
name="Id"
type="int"
tag="id"
comment="id"

[[variables]]
name="Group"
type="int32"
tag="group"
comment="活动id"

[[variables]]
name="Type"
type="int32"
tag="type"
comment="类型"

[[variables]]
name="ItemId"
type="string"
tag="item_id"
comment="物品id"

[[variables]]
name="ItemCount"
type="string"
tag="item_count"
comment="数量"

[[variables]]
name="Profession"
type="int32"
tag="profession"
comment="职业"

[[variables]]
name="Gender"
type="int32"
tag="gender"
comment="性别"
 
[[variables]]
name="YuanGold"
type="int32"
tag="yuan_gold"
comment="原价"

[[variables]]
name="BargainBegain"
type="int32"
tag="bargain_begain"
comment="折扣起始id"


