file="bargain_vo.go"
pkg="template"
class="BargainTemplateVo"
comment = "打折配置"

[[variables]]
name="Id"
type="int"
tag="id"
comment="id"

[[variables]]
name="NextId"
type="int"
tag="next_id" 
comment="下一级id" 

[[variables]]
name="BargainTimes"
type="int32"
tag="bargain_times" 
comment="打折次数"

[[variables]]
name="DazheMin"
type="int32"
tag="dazhe_min"
comment="打折下限"

[[variables]]
name="DazheMax"
type="int32"
tag="dazhe_max"
comment="打折上限" 