file="biaobai_vo.go"
pkg="template"
class="MarryDevelopTemplateVO"
comment = "表白培养配置"
[[variables]]
name="Id"
type="int"
tag="id"
comment="id"

[[variables]]
name="Level"
type="int32"
tag="level"
comment="表白系统等级"

[[variables]]
name="NextId"
type="int32"
tag="next_id"
comment="下一级id"

[[variables]]
name="Experience"
type="int32"
tag="experience"
comment="经验值"

[[variables]]
name="Percent"
type="int32"
tag="percent"
comment="配偶提供百分比"

[[variables]]
name="AddHp"
type="int32"
tag="hp"
comment="该等级增加的生命"

[[variables]]
name="AddAttack"
type="int32"
tag="attack"
comment="该等级增加的攻击"

[[variables]]
name="AddDefence"
type="int32"
tag="defence"
comment="该等级增加的防御"

