file="biaoche_vo.go"
pkg="template"
class="BiaocheTemplateVO"
comment = "镖车模板配置"
[[variables]]
name="Id"
type="int"
tag="id"
comment="id"

[[variables]]
name="Type"
type="int32"
tag="type"
comment="镖车类型"

[[variables]]
name="BiaocheId"
type="int32"
tag="biaoche_id"
comment="镖车id"

[[variables]]
name="BiologyId"
type="int32"
tag="biology_id"
comment="镖车起点NPC"

[[variables]]
name="BiaocheSilver"
type="int32"
tag="biaoche_silver"
comment="押镖所需银两"

[[variables]]
name="BiaocheGold"
type="int32"
tag="biaoche_gold"
comment="押镖所需元宝"

[[variables]]
name="BiaocheAwardSilver"
type="int32"
tag="biaoche_award_silver"
comment="押镖成功奖励银两"

[[variables]]
name="BiaocheAwardGold"
type="int32"
tag="biaoche_award_gold"
comment="押镖成功奖励元宝"

[[variables]]
name="BiaocheAwardItemId"
type="string"
tag="biaoche_award_item_id"
comment="押镖成功获得物品id"

[[variables]]
name="BiaocheAwardItemCount"
type="string"
tag="biaoche_award_item_count"
comment="押镖成功获得物品数量"

[[variables]]
name="JiebiaoAwardSilver"
type="int32"
tag="jiebiao_award_silver"
comment="劫镖获得银两"

[[variables]]
name="JiebiaoAwardGold"
type="int32"
tag="jiebiao_award_gold"
comment="劫镖获得元宝"

[[variables]]
name="JiebiaoAwardItemId"
type="string"
tag="jiebiao_award_item_id"
comment="劫镖成功获得的物品id"

[[variables]]
name="JiebiaoAwardItemCount"
type="string"
tag="jiebiao_award_item_count"
comment="劫镖成功获得的物品数量"


[[variables]]
name="BiaocheLoseSilver"
type="int32"
tag="biaoche_lose_silver"
comment="押镖失败获得银两"

[[variables]]
name="BiaocheLoseGold"
type="int32"
tag="biaoche_lose_gold"
comment="押镖失败获得元宝"

[[variables]]
name="BiaocheLoseItemId"
type="string"
tag="biaoche_lose_item_id"
comment="押镖失败获得的物品id"

[[variables]]
name="BiaocheLoseItemCount"
type="string"
tag="biaoche_lose_item_count"
comment="押镖失败获得的物品数量"