file="biology_vo.go"
pkg="template"
class="BiologyTemplateVO"
comment = "生物配置"
[[variables]]
name="Id"
type="int"
tag="id"
comment="id"

[[variables]]
name="Name"
type="string"
tag="name"
comment="名字"

[[variables]]
name="Remarks"
type="string"
tag="remarks"
comment="所在地图"

[[variables]]
name="Level"
type="int"
tag="level"
comment="等级"

[[variables]]
name="Jingjie"
type="int32"
tag="jingjie"
comment="境界"


[[variables]]
name="SetType"
type="int"
tag="set_type"
comment="生物类型"

[[variables]]
name="Type"
type="int"
tag="type"
comment="生物显示类型"

[[variables]]
name="ScriptType"
type="int"
tag="script_type"
comment="脚本类型"

[[variables]]
name="Faction"
type="int"
tag="faction"
comment="阵营,关联阵营表"


[[variables]]
name="ThreatType"
type="int"
tag="threat_type"
comment="posX"

[[variables]]
name="Force"
type="int"
tag="force"
comment="战力"

[[variables]]
name="Hp"
type="int"
tag="hp"
comment="血量"

[[variables]]
name="Attack"
type="int"
tag="attack"
comment="攻击"

[[variables]]
name="Defence"
type="int"
tag="defence"
comment="防御"

[[variables]]
name="Critical"
type="int"
tag="critical"
comment="暴击"

[[variables]]
name="Tough"
type="int"
tag="tough"
comment="坚韧"

[[variables]]
name="Block"
type="int"
tag="block"
comment="格挡"

[[variables]]
name="Abnormality"
type="int"
tag="abnormality"
comment="破格"

[[variables]]
name="Hit"
type="int"
tag="hit"
comment="命中"

[[variables]]
name="Dodge"
type="int"
tag="dodge"
comment="闪避"

[[variables]]
name="HunyuanAtt"
type="int"
tag="hunyuan_att"
comment="混元伤害"

[[variables]]
name="HunyuanDef"
type="int"
tag="hunyuan_def"
comment="混元防御"


[[variables]]
name="ForceHit"
type="int"
tag="force_hit"
comment="强制命中"

[[variables]]
name="ForceCritical"
type="int"
tag="force_critical"
comment="强制暴击"


[[variables]]
name="SpeedMove"
type="int"
tag="speed_move"
comment="移动速度"


[[variables]]
name="AutoRecoverMaxhealth"
type="int"
tag="auto_recover_maxhealth"
comment="脱离战斗是否回血"

[[variables]]
name="AutoRecoverTime"
type="int32"
tag="auto_recover_time"
comment="自动回血速度"

[[variables]]
name="AutoRecoverNum"
type="int32"
tag="auto_recover_num"
comment="自动回血万分比"



[[variables]]
name="BaseDamge"
type="int"
tag="base_damge"
comment="固定伤害"

[[variables]]
name="DropOwnerType"
type="int"
tag="drop_owner_type"
comment="奖励归属类型"

[[variables]]
name="ExpBase"
type="int"
tag="exp_base"
comment="固定经验值奖励"

[[variables]]
name="ExpPoint"
type="int"
tag="exp_point"
comment="经验点数奖励"


[[variables]]
name="DropCombine"
type="string"
tag="drop_combine"
comment="掉落包组合"

[[variables]]
name="DropType"
type="int32"
tag="drop_type"
comment="掉落类型"

[[variables]]
name="DropFlag"
type="int32"
tag="drop_flag"
comment="掉落值"


[[variables]]
name="Patrolradius"
type="int"
tag="patrolradius"
comment="巡逻范围"

[[variables]]
name="Alertradius"
type="int"
tag="alertradius"
comment="视野范围"

[[variables]]
name="Randradius"
type="int"
tag="randradius"
comment="追击范围"

[[variables]]
name="AttackId"
type="int"
tag="attack_id"
comment="攻击技能id"

[[variables]]
name="SkillId1"
type="int"
tag="skill_id_1"
comment="技能id1"

[[variables]]
name="SkillRate1"
type="int"
tag="skill_rate1"
comment="技能id1概率"


[[variables]]
name="SkillId2"
type="int"
tag="skill_id_2"
comment="技能id2"

[[variables]]
name="SkillRate2"
type="int"
tag="skill_rate2"
comment="技能id2概率"

[[variables]]
name="ModleId"
type="int"
tag="modle_id"
comment="模型id"

[[variables]]
name="Dialogue"
type="string"
tag="dialogue"
comment="对话"

[[variables]]
name="Speak"
type="string"
tag="speak"
comment="对话"

[[variables]]
name="DurationTime"
type="int"
tag="duration_time"
comment="冒泡持续时间"

[[variables]]
name="IntervalTime"
type="int"
tag="interval_time"
comment="冒泡间隔时间"

[[variables]]
name="TitleId"
type="int"
tag="title_id"
comment="称号id"

[[variables]]
name="HalfBodyPic"
type="int"
tag="half_body_pic"
comment="半身像id"

[[variables]]
name="Conversation"
type="string"
tag="conversation"
comment="对话内容"

[[variables]]
name="IsShowBlood"
type="int"
tag="is_show_blood"
comment="显示血量"

[[variables]]
name="Hpbar"
type="int"
tag="hp_bar"
comment="头顶显血"


[[variables]]
name="LifeNumber"
type="int"
tag="life_number"
comment="头顶血条数量"

[[variables]]
name="IsShowAction"
type="int"
tag="is_show_action"
comment="是否播放休闲动画"

[[variables]]
name="TalkSound"
type="string"
tag="talk_sound"
comment="NPC语音"


[[variables]]
name="RebornType"
type="int"
tag="reborn_type"
comment="重生类型"

[[variables]]
name="CaiJiTime"
type="int32"
tag="caiji_time"
comment="采集时间"

[[variables]]
name="RebornTime"
type="string"
tag="reborn_time"
comment="重生时间"

[[variables]]
name="XiaoshiTime"
type="int32"
tag="xiaoshi_time"
comment="消失时间"

[[variables]]
name="BuffIds"
type="string"
tag="buff_ids"
comment="状态"

[[variables]]
name="PortalId"
type="int32"
tag="portal_id"
comment="传送阵id"


[[variables]]
name="ActivityGroupId"
type="string"
tag="activity_group_id"
comment="活动组ID，用于活动掉落"

[[variables]]
name="IsJitui"
type="int32"
tag="is_jitui"
comment="特殊效果免疫"


[[variables]]
name="Pengzhuang"
type="float64"
tag="pengzhuang"
comment="碰撞长度"


[[variables]]
name="PengzhuangKuan"
type="float64"
tag="pengzhuang_kuan"
comment="碰撞宽度"

[[variables]]
name="NeedPilao"
type="int32"
tag="need_pilao"
comment="所需疲劳值"

[[variables]]
name="ZhuoQi"
type="int32"
tag="zhuoqi"
comment="浊气值"

[[variables]]
name="CaiJiRecoverTime"
type="int64"
tag="caiji_recover_time"
comment="采集点刷新时间"

[[variables]]
name="CaiJiLimitCount"
type="int32"
tag="caiji_limit_count"
comment="采集点可采集次数"

[[variables]]
name="CaiJiIsXiaoShi"
type="int32"
tag="caiji_is_xiaoshi"
comment="采集点被采集到次数为0时，场景上的采集点模型是否消失"

[[variables]]
name="CaiJiChooseDrop"
type="string"
tag="caiji_choose_drop"
comment="采集物被采集选的掉落id"

[[variables]]
name="BossMizangRate"
type="int32"
tag="boss_mizang_rate"
comment="密藏比例"

[[variables]]
name="MiZangId"
type="int32"
tag="mizang_id"
comment="密藏id"


