file="biology_pos_vo.go"
pkg="template"
class="BiologyPosTemplateVO"
comment = "服务器生物生成配置"
[[variables]]
name="Id"
type="int"
tag="id"
comment="id"

[[variables]]
name="BiologyId"
type="int32"
tag="biology_id"
comment="怪物id"

[[variables]]
name="MapId"
type="int32"
tag="map_id"
comment="地图id"

[[variables]]
name="NextId"
type="int32"
tag="next_id"
comment="下一id"
   
[[variables]]
name="PosX"
type="float64"
tag="pos_x"
comment="x坐标"

[[variables]]
name="PosY"
type="float64"
tag="pos_y"
comment="y坐标"

[[variables]]
name="PosZ"
type="float64"
tag="pos_z"
comment="z坐标"
