file="blood_shield_vo.go"
pkg="template"
class="BloodShieldTemplateVO"
comment = "血盾配置"
[[variables]]
name="Id"
type="int"
tag="id"
comment="id"


[[variables]]
name="Type"
type="int32"
tag="type"
comment="血盾阶别"


[[variables]]
name="Name"
type="string"
tag="name"
comment="血盾名称"

[[variables]]
name="NextId"
type="int32"
tag="next_id"
comment="下一个id"


[[variables]]
name="Star"
type="int32"
tag="star"
comment="不同阶别下对应的星数"

[[variables]]
name="UpdatePercent"
type="int32"
tag="update_percent"
comment="升星成功率"

[[variables]]
name="UseMoney"
type="int32"
tag="use_money"
comment="进级所需银两"

[[variables]]
name="UseBlood"
type="int32"
tag="use_blood"
comment="升级所需血炼值"

[[variables]]
name="UseItem"
type="string"
tag="use_item"
comment="进阶所需物品id"

[[variables]]
name="ItemCount"
type="string"
tag="item_count"
comment="进阶所需物品数量"

[[variables]]
name="TimesMin"
type="int32"
tag="times_min"
comment="最小次数"

[[variables]]
name="TimesMax"
type="int32"
tag="times_max"
comment="最大次数"

[[variables]]
name="AddMin"
type="int32"
tag="add_min"
comment="每次增加祝福值最小值"

[[variables]]
name="AddMax"
type="int32"
tag="add_max"
comment="每次增加祝福值最大值"


[[variables]]
name="ZhufuMax"
type="int32"
tag="zhufu_max"
comment="前端祝福值显示值"


[[variables]]
name="SpellId"
type="int32"
tag="spell_id"
comment="升级时获得技能ID"


[[variables]]
name="MedicinalLimit"
type="int32"
tag="medicinal_limit"
comment="食用血盾碎片上限"


[[variables]]
name="Note"
type="int32"
tag="note"
comment="系统公告"



