file="body_shield_vo.go"
pkg="template"
class="BodyShieldTemplateVO"
comment = "护体盾配置"
[[variables]]
name="Id"
type="int"
tag="id"
comment="id"

[[variables]]
name="NextId"
type="int32"
tag="next_id"
comment="下一个id"

[[variables]]
name="Name"
type="string"
tag="name"
comment="护体盾名称"

[[variables]]
name="Number"
type="int32"
tag="number"
comment="阶数"

[[variables]]
name="UpdateWfb"
type="int32"
tag="update_wfb"
comment="进阶成功率"

[[variables]]
name="UseMoney"
type="int32"
tag="use_money"
comment="进级所需元宝"

[[variables]]
name="UseItem"
type="int32"
tag="use_item"
comment="进阶所需物品id"

[[variables]]
name="ItemCount"
type="int32"
tag="item_count"
comment="进阶所需物品数量"

[[variables]]
name="TimesMin"
type="int32"
tag="times_min"
comment="最小次数"

[[variables]]
name="TimesMax"
type="int32"
tag="times_max"
comment="最大次数"

[[variables]]
name="AddMin"
type="int32"
tag="add_min"
comment="每次增加祝福值最小值"

[[variables]]
name="AddMax"
type="int32"
tag="add_max"
comment="每次增加祝福值最大值"


[[variables]]
name="ZhufuMax"
type="int32"
tag="zhufu_max"
comment="前端祝福值显示值"

[[variables]]
name="Attr"
type="int32"
tag="attr"
comment="护体盾属性"


[[variables]]
name="ModelId"
type="int32"
tag="model_id"
comment="模型ID"


[[variables]]
name="UseYinliang"
type="int32"
tag="use_yinliangr"
comment="进阶消耗银两"



[[variables]]
name="ShidanLimit"
type="int32"
tag="shidan_limit"
comment="金甲丹食丹等级上限"


[[variables]]
name="IsClear"
type="int32"
tag="is_clear"
comment="本阶进阶过天是否清空祝福值 0不清 1清"

