

file="boss_mizang_vo.go"
pkg="template"
class="BossMizangTemplateVO"
comment = "boss密藏配置"
[[variables]]
name="Id"
type="int"
tag="id"
comment="id"


[[variables]]
name="SilverItemId"
type="int32"
tag="silver_item_id"
comment="物品id"

[[variables]]
name="SilverItemCount"
type="int32"
tag="silver_item_count"
comment="物品数量"

[[variables]]
name="SilverDrop"
type="string"
tag="silver__drop"
comment="掉落"

[[variables]]
name="SilverRateAdd"
type="int32"
tag="silver_rate_add"
comment="比例"


[[variables]]
name="GoldItemId"
type="int32"
tag="gold_item_id"
comment="物品id"

[[variables]]
name="GoldItemCount"
type="int32"
tag="gold_item_count"
comment="物品数量"

[[variables]]
name="GoldDrop"
type="string"
tag="gold_drop"
comment="掉落"

[[variables]]
name="GoldRateAdd"
type="int32"
tag="gold_rate_add"
comment="比例"


[[variables]]
name="CaijiBiologyId"
type="int32"
tag="caiji_biology_id"
comment="采集物"
