

file="box_vo.go"
pkg="template"
class="BoxTemplateVO"
comment = "宝箱配置"
[[variables]]
name="Id"
type="int"
tag="id"
comment="id"

[[variables]]
name="NextId"
type="int32"
tag="next_id"
comment="后续id"

[[variables]]
name="Times"
type="int32"
tag="times"
comment="多次开启"

[[variables]]
name="Type"
type="int32"
tag="type"
comment="宝箱类型"

[[variables]]
name="ZhuanshuMin"
type="int32"
tag="zhuanshu_min"
comment="最小转数"

[[variables]]
name="LevelMin"
type="int32"
tag="level_min"
comment="最小等级"



[[variables]]
name="DropId"
type="string"
tag="drop_id"
comment="掉落包id(开天男)"

[[variables]]
name="DropIdNv"
type="string"
tag="drop_id_nv"
comment="掉落包id(开天女)"

[[variables]]
name="UseItemId"
type="string"
tag="use_item_id"
comment="开启宝箱消耗的物品id(开天)"

[[variables]]
name="UseItemAmount"
type="string"
tag="use_item_amount"
comment="开启宝箱消耗的物品数量(开天)"

[[variables]]
name="DropId2"
type="string"
tag="drop_id2"
comment="掉落包id(奕剑男)"

[[variables]]
name="DropId2Nv"
type="string"
tag="drop_id2_nv"
comment="掉落包id(奕剑女)"

[[variables]]
name="UseItemId2"
type="string"
tag="use_item_id2"
comment="开启宝箱消耗的物品id(奕剑)"

[[variables]]
name="UseItemAmount2"
type="string"
tag="use_item_amount2"
comment="开启宝箱消耗的物品数量(奕剑)"

[[variables]]
name="DropId3"
type="string"
tag="drop_id3"
comment="掉落包id(破月)"

[[variables]]
name="DropId3Nv"
type="string"
tag="drop_id3_nv"
comment="掉落包id(破月女)"

[[variables]]
name="UseItemId3"
type="string"
tag="use_item_id3"
comment="开启宝箱消耗的物品id(破月)"

[[variables]]
name="UseItemAmount3"
type="string"
tag="use_item_amount3"
comment="开启宝箱消耗的物品数量(破月)"


[[variables]]
name="FixationItemNum"
type="int32"
tag="fixation_item_num"
comment="自由选择物品种类"



[[variables]]
name="UseSilver"
type="int32"
tag="use_silver"
comment="开启宝箱消耗银两"

[[variables]]
name="UseGold"
type="int32"
tag="use_gold"
comment="开启宝箱消耗元宝"

[[variables]]
name="UseBindgold"
type="int32"
tag="use_bindgold"
comment="开启宝箱消耗绑元"
