file="buff_dongtai_vo.go"
pkg="template"
class="BuffDongTaiTemplateVO"
comment = "buff动态配置"
[[variables]]
name="Id"
type="int"
tag="id"
comment="id"

[[variables]]
name="NextId"
type="int32"
tag="next_id"
comment="后续id"

[[variables]]
name="BuffId"
type="int32"
tag="buff_id"
comment="基础buff"

[[variables]]
name="Lev"
type="int32"
tag="lev"
comment="等级"

[[variables]]
name="TimeDuration"
type="int64"
tag="time_duration"
comment="buff持续时间"

[[variables]]
name="SpeedMovePercent"
type="int32"
tag="speed_move_percent"
comment="改变移动速度万分比"


[[variables]]
name="ToughAdd"
type="int32"
tag="tough_add"
comment="改变坚韧固定值"


[[variables]]
name="ToughPercent"
type="int32"
tag="tough_percent"
comment="改变坚韧万分比值"

