file="buff_vo.go"
pkg="template"
class="BuffTemplateVO"
comment = "buff配置"
[[variables]]
name="Id"
type="int"
tag="id"
comment="id"

[[variables]]
name="Name"
type="string"
tag="name"
comment="名称"

[[variables]]
name="Group"
type="int32"
tag="group"
comment="组"

[[variables]]
name="Lev"
type="int32"
tag="lev"
comment="等级"

[[variables]]
name="BuffType"
type="int32"
tag="buff_type"
comment="buff类型"

[[variables]]
name="TypeEffect"
type="int32"
tag="type_effect"
comment="效果类型"

[[variables]]
name="TypeRemove"
type="int32"
tag="type_remove"
comment="打断类型"

[[variables]]
name="TypeLimit"
type="int64"
tag="type_limit"
comment="限制类型"

[[variables]]
name="TypeTouch"
type="int32"
tag="type_touch"
comment="触发类型"

[[variables]]
name="ImmuneType"
type="int32"
tag="immune_type"
comment="免疫类型"

[[variables]]
name="SubId"
type="string"
tag="sub_id"
comment="状态生效后给予的状态id"


[[variables]]
name="SubRate"
type="string"
tag="sub_rate"
comment="状态生效后给予的状态概率"

[[variables]]
name="IsForever"
type="int32"
tag="is_forever"
comment="永久"


[[variables]]
name="TimeDuration"
type="int64"
tag="time_duration"
comment="状态持续时间"


[[variables]]
name="FirstTouch"
type="int64"
tag="first_touch"
comment="第一次触发时间当buff非获得生效时使用"


[[variables]]
name="Frequency"
type="int64"
tag="frequency"
comment="状态触发频率"

[[variables]]
name="Replace"
type="int32"
tag="replace"
comment="是否覆盖"


[[variables]]
name="StackType"
type="int32"
tag="stack_type"
comment="状态叠加类型"

[[variables]]
name="StackMax"
type="int32"
tag="stack_max"
comment="状态叠加次数"

[[variables]]
name="LifemaxAdd"
type="int32"
tag="lifemax_add"
comment="改变最大生命的固定值"

[[variables]]
name="LifemaxPercent"
type="int32"
tag="lifemax_percent"
comment="改变最大生命的上限万分比"

[[variables]]
name="TpmaxAdd"
type="int32"
tag="tpmax_add"
comment="改变最大体力的固定值"

[[variables]]
name="TpmaxPercent"
type="int32"
tag="tpmax_percent"
comment="改变最大体力的上限万分比"

[[variables]]
name="AttackAdd"
type="int32"
tag="attack_add"
comment="改变攻击力的固定值"

[[variables]]
name="AttackPercent"
type="int32"
tag="attack_percent"
comment="改变攻击力的万分比"

[[variables]]
name="DefenseAdd"
type="int32"
tag="defense_add"
comment="改变防御的固定值"

[[variables]]
name="DefensePercent"
type="int32"
tag="defense_percent"
comment="改变防御的万分比"

[[variables]]
name="CriticalAdd"
type="int32"
tag="critical_add"
comment="改变暴击的固定值"

[[variables]]
name="CriticalPercent"
type="int32"
tag="critical_percent"
comment="改变暴击的万分比"

[[variables]]
name="ToughAdd"
type="int32"
tag="tough_add"
comment="改变坚韧的固定值"

[[variables]]
name="ToughPercent"
type="int32"
tag="tough_percent"
comment="改变坚韧的万分比"

[[variables]]
name="BlockAdd"
type="int32"
tag="block_add"
comment="改变格挡的固定值"

[[variables]]
name="BlockPercent"
type="int32"
tag="block_percent"
comment="改变格挡的万分比"

[[variables]]
name="AbnormalityAdd"
type="int32"
tag="abnormality_add"
comment="改变破格的固定值"

[[variables]]
name="AbnormalityPercent"
type="int32"
tag="abnormality_percent"
comment="改变破格的万分比"


[[variables]]
name="HitAdd"
type="int32"
tag="hit_add"
comment="改变命中的固定值"

[[variables]]
name="HitPercent"
type="int32"
tag="hit_percent"
comment="改变命中的万分比"

[[variables]]
name="DodgeAdd"
type="int32"
tag="dodge_add"
comment="改变闪避的固定值"

[[variables]]
name="DodgePercent"
type="int32"
tag="dodge_percent"
comment="改变闪避的万分比"


[[variables]]
name="HunyuanAttAdd"
type="int32"
tag="hunyuan_att_add"
comment="改变混元的固定值"

[[variables]]
name="HunyuanAttPercent"
type="int32"
tag="hunyuan_att_percent"
comment="改变混元的万分比"

[[variables]]
name="HunyuanDefAdd"
type="int32"
tag="hunyuan_def_add"
comment="改变混元防御的固定值"

[[variables]]
name="HunyuanDefPercent"
type="int32"
tag="hunyuan_def_percent"
comment="改变混元防御万分比"

[[variables]]
name="LifeAdd"
type="int32"
tag="life_add"
comment="改变生命的固定值"

[[variables]]
name="LifePercent"
type="int32"
tag="life_percent"
comment="改变生命的万分比"

[[variables]]
name="LifePercentMax"
type="int32"
tag="life_percent_max"
comment="改变生命的万分比"

[[variables]]
name="TpAdd"
type="int32"
tag="tp_add"
comment="改变体力的固定值"

[[variables]]
name="TpPercent"
type="int32"
tag="tp_percent"
comment="改变体力的万分比"

[[variables]]
name="SpellCdPercent"
type="int32"
tag="spell_cd_percent"
comment="改变技能cd的万分比"

[[variables]]
name="FantanAdd"
type="int32"
tag="fantan_add"
comment="反弹值"

[[variables]]
name="FantanPercent"
type="int32"
tag="fantan_percent"
comment="反弹万分比"

[[variables]]
name="HudunAdd"
type="int32"
tag="hudun_add"
comment="护盾值"

[[variables]]
name="HudunPercent"
type="int32"
tag="hudun_add"
comment="护盾万分比"

[[variables]]
name="SpeedMovePercent"
type="int32"
tag="speed_move_percent"
comment="改变速度的万分比"

[[variables]]
name="HarmBase"
type="int32"
tag="harm_base"
comment="额外增加伤害的固定值"

[[variables]]
name="HarmPercent"
type="int32"
tag="harm_percent"
comment="额外增加伤害的万分比"

[[variables]]
name="CuthurtBase"
type="int32"
tag="cuthurt_base"
comment="减少伤害的固定值"

[[variables]]
name="CuthurtPercent"
type="int32"
tag="cuthurt_percent"
comment="减少伤害的万分比"


[[variables]]
name="CritRatePercent"
type="int32"
tag="crit_rate_percent"
comment="改变暴击几率的万分比"


[[variables]]
name="CritHarmPercent"
type="int32"
tag="crit_harm_percent"
comment="改变暴击伤害的万分比"



[[variables]]
name="HitRatePercent"
type="int32"
tag="hit_rate_percent"
comment="改变命中几率的万分比"


[[variables]]
name="BlockRatePercent"
type="int32"
tag="block_rate_percent"
comment="改变破格的万分比"

[[variables]]
name="DodgeRatePercent"
type="int32"
tag="dodge_rate_percent"
comment="改变闪避的万分比"

[[variables]]
name="OfflineSaveType"
type="int32"
tag="offline_save_type"
comment="下线保存类型"


[[variables]]
name="EffectType"
type="int32"
tag="effect_type"
comment="特殊效果类型"


[[variables]]
name="EffectTypeBase"
type="int32"
tag="effect_type_base"
comment="特殊效果值"

[[variables]]
name="EffectTypePercent"
type="int32"
tag="effect_type_persent"
comment="特殊效果万分比"

[[variables]]
name="ShowType"
type="int32"
tag="show_type"
comment="广播类型"

[[variables]]
name="GetExp"
type="int32"
tag="get_exp"
comment="每次触发buff时获得经验值"

[[variables]]
name="GetExpPoint"
type="int32"
tag="get_exp_point"
comment="每次触发buff时获得经验点"

[[variables]]
name="ModelId"
type="int32"
tag="model_id"
comment="变形"


[[variables]]
name="Description"
type="string"
tag="description"
comment="描述"

[[variables]]
name="Alias"
type="string"
tag="alias"
comment="简称"

[[variables]]
name="AddExp"
type="int32"
tag="add_exp"
comment="添加经验"

[[variables]]
name="RelativeFastness"
type="int32"
tag="relative_fastness"
comment="状态与抗性相对应的类型"

[[variables]]
name="BuffPiaozi"
type="int32"
tag="buff_piaozi"
comment="buff飘字"

[[variables]]
name="SkillId"
type="int32"
tag="skill_id"
comment="子技能"

[[variables]]
name="ParentBuffId"
type="string"
tag="parent_buff_id"
comment="前置技能"