file="caiji_activity_vo.go"
pkg="template"
class="CollectActivityTemplateVO"
comment = "活动采集模板配置"
[[variables]]
name="Id"
type="int"
tag="id"
comment="id"

[[variables]]
name="Group"
type="int32"
tag="group"
comment="活动id"

[[variables]]
name="BiologyId"
type="int32"
tag="biology_id"
comment="采集物id"

[[variables]]
name="RebornCount"
type="int32"
tag="reborn_count"
comment="刷新数量"

[[variables]]
name="RebornMapId"
type="int32"
tag="reborn_map_id"
comment="刷新地图id"

[[variables]]
name="RebornTime"
type="string"
tag="reborn_time"
comment="刷新时间点"
