file="qudao_vo.go"
pkg="template"
class="QuDaoTemplateVO"
comment = "渠道模板配置"
[[variables]]
name="Id"
type="int"
tag="id"
comment="id"

[[variables]]
name="Type"
type="int32"
tag="type"
comment="平台类型"

[[variables]]
name="Name"
type="string"
tag="name"
comment="平台名称"

[[variables]]
name="UnionVersion"
type="int32"
tag="union_type"
comment="仙盟版本"

[[variables]]
name="PlatName"
type="string"
tag="plat_name"
comment="比武大会显示平台名"

[[variables]]
name="ChuanYinNum"
type="int32"
tag="chuanyin_num"
comment="战力榜前几的玩家上下线有传音公告显示"

[[variables]]
name="IsFriend"
type="int32"
tag="is_friend"
comment="是否需要添加好友才能聊天"

