file="character_level_vo.go"
pkg="template"
class="CharacterLevelTemplateVO"
comment = "等级配置"
[[variables]]
name="Id"
type="int"
tag="id"
comment="id"

[[variables]]
name="NextId"
type="int32"
tag="next_id"
comment="下一级id"


[[variables]]
name="Experience"
type="int64"
tag="experience"
comment="经验"

[[variables]]
name="SpeedMove"
type="int32"
tag="speed_move"
comment="移动速度"

[[variables]]
name="BaseAttack"
type="int32"
tag="base_attack"
comment="基础攻击"

[[variables]]
name="BaseDefense"
type="int32"
tag="base_defense"
comment="基础防御"

[[variables]]
name="BaseCritical"
type="int32"
tag="base_critical"
comment="基础暴击"

[[variables]]
name="BaseTough"
type="int32"
tag="base_tough"
comment="基础坚韧"

[[variables]]
name="BaseBlock"
type="int32"
tag="base_block"
comment="基础格挡"

[[variables]]
name="BaseBreak"
type="int32"
tag="base_break"
comment="基础破格"

[[variables]]
name="NeedItemId3"
type="int32"
tag="need_item_id3"
comment="需要物品id3"

[[variables]]
name="BaseMaxhp"
type="int32"
tag="base_maxhp"
comment="基础最大血量"

[[variables]]
name="BaseMaxtp"
type="int32"
tag="base_maxtp"
comment="基础最大体力"

[[variables]]
name="HotrexpModul"
type="int32"
tag="hotrexp_modul"
comment="uplve点"

[[variables]]
name="MedicinesHpMax"
type="int32"
tag="medicines_hp_max"
comment="生命丹药使用上线"


[[variables]]
name="MedicinesAttackMax"
type="int32"
tag="medicines_attack_max"
comment="攻击丹药使用上线"

[[variables]]
name="MedicinesDefenceMax"
type="int32"
tag="medicines_defence_max"
comment="防御丹药使用上线"

[[variables]]
name="MedicinesBlockMax"
type="int32"
tag="medicines_block_max"
comment="格挡丹药使用上线"

[[variables]]
name="MedicinesBreakMax"
type="int32"
tag="medicines_break_max"
comment="破格丹药使用上线"

[[variables]]
name="MedicinesCriticalMax"
type="int32"
tag="medicines_critical_max"
comment="暴击丹药使用上线"


[[variables]]
name="MedicinesToughMax"
type="int32"
tag="medicines_tough_max"
comment="坚韧丹药使用上线"

[[variables]]
name="HpReplyTime"
type="int32"
tag="hp_reply_time"
comment="hp回复时间"
[[variables]]
name="HpReply"
type="int32"
tag="hp_reply"
comment="hp回复"

[[variables]]
name="TpReplyTime"
type="int32"
tag="tp_reply_time"
comment="tp回复时间"

[[variables]]
name="TpReply"
type="int32"
tag="tp_reply"
comment="tp回复"
