file="chat_constant_vo.go"
pkg="template"
class="ChatConstantTemplateVO"
comment = "聊天常量配置"
[[variables]]
name="Id"
type="int"
tag="id"
comment="id"

[[variables]]
name="Text"
type="string"
tag="text"
comment="text"

[[variables]]
name="Type"
type="int32"
tag="type"
comment="类型"


[[variables]]
name="Value"
type="string"
tag="value"
comment="值"
