file="chess_vo.go"
pkg="template"
class="ChessTemplateVO"
comment = "苍龙棋局掉落配置"
[[variables]]
name="Id"
type="int"
tag="id"
comment="id"

[[variables]]
name="Type"
type="int32"
tag="type"
comment="棋局类型"

[[variables]]
name="ChessId"
type="int32"
tag="chess_id"
comment="棋局id"

[[variables]]
name="DropId"
type="int32"
tag="drop_id"
comment="掉落包id"

[[variables]]
name="Rate"
type="int32"
tag="rate"
comment="随机到掉落包的概率"

[[variables]]
name="MustGet1"
type="int32"
tag="must_get1"
comment="一定次数必定获取的掉落包"

[[variables]]
name="MustAmount1"
type="int32"
tag="must_amount1"
comment="破解次数"

[[variables]]
name="MustGet2"
type="int32"
tag="must_get2"
comment="一定次数必定获取的掉落包"

[[variables]]
name="MustAmount2"
type="int32"
tag="must_amount2"
comment="破解次数"

[[variables]]
name="MustGet3"
type="int32"
tag="must_get3"
comment="一定次数必定获取的掉落包"

[[variables]]
name="MustAmount3"
type="int32"
tag="must_amount3"
comment="破解次数"

[[variables]]
name="MustGet4"
type="int32"
tag="must_get4"
comment="一定次数必定获取的掉落包"

[[variables]]
name="MustAmount4"
type="int32"
tag="must_amount4"
comment="破解次数"

[[variables]]
name="MustGet5"
type="int32"
tag="must_get5"
comment="一定次数必定获取的掉落包"

[[variables]]
name="MustAmount5"
type="int32"
tag="must_amount5"
comment="破解次数"

[[variables]]
name="MustGet6"
type="int32"
tag="must_get6"
comment="一定次数必定获取的掉落包"

[[variables]]
name="MustAmount6"
type="int32"
tag="must_amount6"
comment="破解次数"

[[variables]]
name="MustGet7"
type="int32"
tag="must_get7"
comment="一定次数必定获取的掉落包"

[[variables]]
name="MustAmount7"
type="int32"
tag="must_amount7"
comment="破解次数"

[[variables]]
name="MustGet8"
type="int32"
tag="must_get8"
comment="一定次数必定获取的掉落包"

[[variables]]
name="MustAmount8"
type="int32"
tag="must_amount8"
comment="破解次数"

[[variables]]
name="SilverUse"
type="int32"
tag="silver_use"
comment="银两消耗"

[[variables]]
name="GoldUse"
type="int32"
tag="gold_use"
comment="元宝消耗"

[[variables]]
name="BindGoldUse"
type="int32"
tag="bindgold_use"
comment="绑元消耗"

[[variables]]
name="UseItemId"
type="int32"
tag="use_item_id"
comment="消耗物品id"

[[variables]]
name="UseItemCount"
type="int32"
tag="use_item_count"
comment="消耗物品数量"

[[variables]]
name="GiftItem"
type="int32"
tag="gift_item"
comment="破解赠送id"

[[variables]]
name="GiftItemCount"
type="int32"
tag="gift_item_count"
comment="破解赠送数量"