file="choujiang_poker_vo.go"
pkg="template"
class="ChouJiangPokerTemplateVO"
comment = "摸金奖励配置"

[[variables]]
name="Id" 
type="int"
tag="id"
comment="id"

[[variables]]
name="Type"
type="int32"
tag="type"
comment="收集类型"

[[variables]]
name="GroupId"
type="int32"
tag="group_id"
comment="活动id"

[[variables]]
name="RawItem"
type="string"
tag="raw_item"
comment="奖励物品id"

[[variables]]
name="RawCount"
type="string" 
tag="raw_count"
comment="奖励物品数量"

[[variables]]
name="RawYinliang"
type="int32" 
tag="raw_yinliang"
comment="奖励银两"

[[variables]]
name="RawBindGold"
type="int32" 
tag="raw_bind_gold"
comment="奖励绑元"

[[variables]]
name="RawGold"
type="int32" 
tag="raw_gold"
comment="奖励元宝"

