file="lucky_drew_vo.go"
pkg="template"
class="LuckyDrewTemplateVO"
comment = "幸运抽奖配置"
[[variables]]
name="Id"
type="int"
tag="id"
comment="id"

[[variables]]
name="Type"
type="int32"
tag="type"
comment="抽奖类型"

[[variables]]
name="ChouJiangId"
type="int32"
tag="choujiang_id"
comment="抽奖id"

[[variables]]
name="DropId"
type="int32"
tag="drop_id"
comment="掉落包id"

[[variables]]
name="Rate"
type="int32"
tag="rate"
comment="随机到掉落包的概率"

[[variables]]
name="RewCount"
type="int32"
tag="rew_count"
comment="后台规则次数条件"

[[variables]]
name="RewTimes1"
type="int32"
tag="rew_times1"
comment="倍数"

[[variables]]
name="Percent1"
type="int32"
tag="percent1"
comment="概率"

[[variables]]
name="RewTimes2"
type="int32"
tag="rew_times2"
comment="倍数"

[[variables]]
name="Percent2"
type="int32"
tag="percent2"
comment="概率"

[[variables]]
name="MustGet1"
type="int32"
tag="must_get1"
comment="一定次数必定获取的掉落包"

[[variables]]
name="MustAmount1"
type="int32"
tag="must_amount1"
comment="参与次数"

[[variables]]
name="MustGet2"
type="int32"
tag="must_get2"
comment="一定次数必定获取的掉落包"

[[variables]]
name="MustAmount2"
type="int32"
tag="must_amount2"
comment="参与次数"

[[variables]]
name="MustGet3"
type="int32"
tag="must_get3"
comment="一定次数必定获取的掉落包"

[[variables]]
name="MustAmount3"
type="int32"
tag="must_amount3"
comment="参与次数"

[[variables]]
name="MustGet4"
type="int32"
tag="must_get4"
comment="一定次数必定获取的掉落包"

[[variables]]
name="MustAmount4"
type="int32"
tag="must_amount4"
comment="参与次数"

[[variables]]
name="MustGet5"
type="int32"
tag="must_get5"
comment="一定次数必定获取的掉落包"

[[variables]]
name="MustAmount5"
type="int32"
tag="must_amount5"
comment="参与次数"

[[variables]]
name="MustGet6"
type="int32"
tag="must_get6"
comment="一定次数必定获取的掉落包"

[[variables]]
name="MustAmount6"
type="int32"
tag="must_amount6"
comment="参与次数"

[[variables]]
name="MustGet7"
type="int32"
tag="must_get7"
comment="一定次数必定获取的掉落包"

[[variables]]
name="MustAmount7"
type="int32"
tag="must_amount7"
comment="参与次数"

[[variables]]
name="MustGet8"
type="int32"
tag="must_get8"
comment="一定次数必定获取的掉落包"

[[variables]]
name="MustAmount8"
type="int32"
tag="must_amount8"
comment="参与次数"

[[variables]]
name="Level"
type="int32"
tag="level"
comment="抽奖等级类型"

[[variables]]
name="ItemId"
type="string"
tag="item_id"
comment="消耗id"

[[variables]]
name="ItemCount"
type="string" 
tag="item_count"
comment="消耗数量"

[[variables]]
name="CostTimes"
type="int32"  
tag="cost_times"
comment="消耗次数"

[[variables]]
name="GiveItemId"
type="string"
tag="give_item_id"
comment="额外奖励id"

[[variables]]
name="GiveItemCount"
type="string" 
tag="give_item_count"
comment="额外奖励数量"

[[variables]]
name="TitleId"
type="int32"
tag="titleId"
comment="称号id"


