file="chuangshi_constant_vo.go"
pkg="template"
class="ChuangShiConstantTemplateVO"
comment = "创世常量模板配置"

[[variables]]
name="Id"
type="int"
tag="id"
comment="id"

  
[[variables]]
name="GenghunUseItemId"
type="int32"
tag="genghun_use_item_id"
comment="阵营更换消耗物品id"
  
[[variables]]
name="GenghunUseItemCount"
type="int32" 
tag="genghun_use_item_count"
comment="阵营更换消耗物品数量"
  
[[variables]]
name="ZhenyingFayanVipLevel"
type="int32"
tag="zhenyingfayan_vip_level"
comment="阵营发言vip"
  
[[variables]]
name="ZhenyingFayanPlayerLevel"
type="int32"
tag="zhenyingfayan_player_level"
comment="阵营发言玩家等级"
  
[[variables]]
name="ZhanquFayanVipLevel"
type="int32"
tag="zhanqufayan_vip_level"
comment="战区发言vip"
  
[[variables]]
name="ZhanquFayanPlayerLevel"
type="int32"
tag="zhanqufayan_player_level"
comment="战区发言玩家等级"
  
[[variables]]
name="ZhanquFayanUseItemId"
type="int32"
tag="zhanqufayan_use_item_id"
comment="战区发言物品id"
  
[[variables]]
name="ZhanquFayanUseItemCount"
type="int32"
tag="zhanqufayan_use_item_count"
comment="战区发言物品数量"
  
[[variables]]
name="TanheNeedTime"
type="int64"
tag="tanhe_need_time"
comment="弹劾神王离线时间"
  
[[variables]]
name="YongbingCountMax"
type="int32"
tag="yongbing_count_max"
comment="佣兵最多存在数量"
  
[[variables]]
name="BaomingWeekday"
type="string"
tag="baoming_weekday"
comment="神王竞选报名日"
  
[[variables]]
name="BaomingTime"
type="string"
tag="baoming_time"
comment="神王竞选报名时间"
  
[[variables]]
name="XuanjuWeekday"
type="string"
tag="xuanju_weekday"
comment="神王选举日"
  
[[variables]]
name="XuanjuTime" 
type="string"
tag="xuanju_time"
comment="神王选举时间"
  
[[variables]]
name="CityRewTime"
type="int64"
tag="city_rew_time"
comment="城池产出间隔时间"
  
[[variables]]
name="GongchengTime"
type="int64"
tag="gongcheng_time"
comment="选择攻城目标限制时间"
  
[[variables]]
name="JinzhiGenghuanTime"
type="int64"
tag="jinzhigenghuan_time"
comment="更换阵营限制时间" 
  
[[variables]]
name="MengzhuGenghuanTime"
type="int64"
tag="mengzhu_genghuan_time"
comment="跟随盟主更换阵营限制时间" 
  
[[variables]]
name="GerenZiyuanDay"
type="int64"
tag="geren_ziyuan_day"
comment="个人工资最大时间" 


     