file="chuangshi_zhenying_vo.go"
pkg="template"
class="ChuangShiZhenyingTemplateVO"
comment = "创世阵营配置"

[[variables]]
name="Id"
type="int"
tag="id"
comment="id"
 
[[variables]]
name="Camp"
type="int32"
tag="camp"
comment="阵营"
 
[[variables]]
name="Name"
type="string"
tag="name"
comment="名字"
 
[[variables]]
name="FashionId"
type="int32"
tag="fashion_id"
comment="时装id"
 