file="chuangshi_city_constant_vo.go"
pkg="template"
class="ChuangShiCityConstantTemplateVO"
comment = "创世城常量模板配置"

[[variables]]
name="Id"
type="int"
tag="id"
comment="id"
 
[[variables]]
name="MapId"
type="int32"
tag="map_id"
comment="地图id"
 
[[variables]]
name="BirthPos1"
type="string"
tag="birth_pos1"
comment="出生地点1"

[[variables]]
name="BirthPos2"
type="string"
tag="birth_pos2"
comment="出生地点2"

[[variables]]
name="IsJinRu"
type="int32"
tag="is_jinru"
comment="非城战期间进入"

[[variables]]
name="JinRuTime"
type="string"
tag="jinru_time"
comment="进入时间"

[[variables]]
name="JinruPlayerMax"
type="int32"
tag="jinru_player_max"
comment="人数限制"


 