file="chuangshi_war_map_vo.go"
pkg="template"
class="ChuangShiWarMapTemplateVO"
comment = "创世城战配置"
[[variables]]
name="Id"
type="int"
tag="id"
comment="id"

[[variables]]
name="MapId"
type="int32" 
tag="map_id"
comment="地图id"  

[[variables]]
name="OccupyFlagTime"
type="int32"
tag="occupy_flag_time"
comment="采集旗子所需要的时间(毫秒)"

[[variables]]
name="FirstXianzhi"
type="int32"
tag="first_xianzhi"
comment="限制区域1"

[[variables]]
name="SecondXianzhi"
type="int32"
tag="second_xianzhi"
comment="限制区域2"

[[variables]]
name="LahuiPos1"
type="string"
tag="lahui_pos1"
comment="区域1固定点"

[[variables]]
name="LahuiPos2"
type="string"
tag="lahui_pos2"
comment="区域2固定点"


[[variables]]
name="ProtectPosX"
type="float64"
tag="pos_x1"
comment="保护罩地图x坐标"

[[variables]]
name="ProtectPosY"
type="float64"
tag="pos_y1"
comment="保护罩地图y坐标"

[[variables]]
name="ProtectPosZ"
type="float64"
tag="pos_z1"
comment="保护罩地图z坐标"

[[variables]]
name="ProtectId"
type="int32"
tag="zhaozi_id"
comment="保护罩id"

[[variables]]
name="ProtectRebornTime"
type="int64"
tag="zhaozi_reborn_time"
comment="保护罩生成时间"

[[variables]]
name="YuXiPosX"
type="float64"
tag="pos_x2"
comment="玉玺采集物地图x坐标"

[[variables]]
name="YuXiPosY"
type="float64"
tag="pos_y2"
comment="玉玺采集物地图y坐标"

[[variables]]
name="YuXiPosZ"
type="float64"
tag="pos_z2"
comment="玉玺采集物地图z坐标"

[[variables]]
name="YuxiId"
type="int32"
tag="yuxi_id"
comment="玉玺采集物id"

[[variables]]
name="ProtectQuYuPos"
type="int32"
tag="zhaozi_quyu_pos"
comment="防护罩限制区域"

[[variables]]
name="ProtectLaHuiPos"
type="string"
tag="zhaozi_lahui_pos"
comment="防护罩驱逐固定点"
