file="chuangshi_city_vo.go"
pkg="template"
class="ChuangShiCityTemplateVO"
comment = "创世城模板配置"

[[variables]]
name="Id"
type="int"
tag="id"
comment="id"
 
[[variables]]
name="Camp"
type="int32"
tag="camp"
comment="阵营"
 
[[variables]]
name="Type"
type="int32"
tag="type"
comment="城市类型"
 
[[variables]]
name="Name"
type="string"
tag="name"
comment="名字"
 
[[variables]]
name="SuoyinId"
type="int32"
tag="suoyin_id"
comment="索引"
 
[[variables]]
name="NearCityId"
type="string"
tag="near_city_id"
comment="相邻城池id"

[[variables]]
name="ZhenyingRewJifen"
type="int32"
tag="zhenying_rew_jifen"
comment="阵营积分"

[[variables]]
name="ZhenyingRewZuanshi"
type="int32"
tag="zhenying_rew_zuanshi"
comment="阵营奖励钻石"

[[variables]]
name="PlayerRewJifen"
type="int32"
tag="player_rew_jifen"
comment="个人积分"

[[variables]]
name="PlayerRewZuanshi"
type="int32"
tag="player_rew_zuanshi"
comment="个人奖励钻石"

[[variables]]
name="CityConstantId"
type="int32"
tag="city_constant_id"
comment="城常量id"
 