file="chuangshi_yugao_vo.go"
pkg="template"
class="ChuangShiYuGaoTemplateVO"
comment = "创世之战常量模板配置"

[[variables]]
name="Id"
type="int"
tag="id"
comment="id"
 
[[variables]]
name="StartTime"
type="string"
tag="yugao_star_time"
comment="预告开始时间"
 
[[variables]]
name="DaoJiShiDay"
type="int32"
tag="daojishi_day"
comment="预告持续时间"
 
[[variables]]
name="JiaRenTime"
type="int64"
tag="jiaren_time"
comment="增加虚假人数间隔时间"
 
[[variables]]
name="JiaRenCount"
type="int32"
tag="jiaren_count"
comment="增加的人数"
 
[[variables]]
name="BaoMingGet"
type="string"
tag="baoming_get"
comment="报名活动的物品id"

[[variables]]
name="BaoMingGetCount"
type="string"
tag="baoming_get_count"
comment="报名活动的物品数量"
 