file="chuangshi_war_award_vo.go"
pkg="template"
class="ChuangShiWarAwardTemplateVO"
comment = "创世城战奖励配置"
[[variables]]
name="Id"
type="int"
tag="id"
comment="id"

[[variables]]
name="Type"
type="int32"
tag="type"
comment="类型" 

[[variables]]
name="WarAwardJifen"
type="int64"
tag="war_award_jifen"
comment="获得的创世积分"

[[variables]]
name="WarAwardSilver"
type="int64"
tag="war_award_silver"
comment="奖励银两"

[[variables]]
name="WarAwardGold"
type="int64"
tag="war_award_gold"
comment="奖励元宝"

[[variables]]
name="WarAwardBindgold"
type="int64"
tag="war_award_bindgold"
comment="奖励绑定元宝"

[[variables]]
name="WarAwardItemId"
type="string"
tag="war_award_item_id"
comment="奖励物品id" 

[[variables]]
name="WarAwardItemCount"
type="string"
tag="war_award_item_id_count"
comment="奖励物品数量"
