file="chuangshi_chengfang_jianshe_vo.go"
pkg="template"
class="ChuangShiChengFangJianSheTemplateVO"
comment = "创世城池建设等级模板配置"

[[variables]]
name="Id"
type="int"
tag="id"
comment="id"
  
[[variables]]
name="NextId"
type="int32"
tag="next_id"
comment="下一级id"
  
[[variables]]
name="Type"
type="int32"
tag="type"
comment="类型"
  
[[variables]]
name="Level"
type="int32"
tag="level" 
comment="等级"
  
[[variables]]
name="NeedExp"
type="int32"
tag="need_exp" 
comment="升级经验"

[[variables]]
name="Hp"
type="int32"
tag="hp"
comment="生命"

[[variables]]
name="Attack"
type="int32"
tag="attack"
comment="攻击"

[[variables]]
name="Defence"
type="int32"
tag="defence"
comment="防御"

[[variables]]
name="TianqiId" 
type="int32"
tag="tianqi_id"
comment="天气关联id"

[[variables]]
name="FallMin"
type="int32"
tag="fall_min"
comment="掉落下限"

[[variables]] 
name="FallMax"
type="int32"
tag="fall_max" 
comment="掉落上限"
 
[[variables]] 
name="FallPercent"
type="int32"
tag="fall_percent"
comment="掉落概率"

