file="chuangshi_chengfang_jianshe_tianqi_vo.go"
pkg="template"
class="ChuangShiChengFangJianSheTianQiTemplateVO"
comment = "创世城池建设天气模板配置"

[[variables]]
name="Id"
type="int"
tag="id"
comment="id"
  
[[variables]]
name="ShouChengTianqiBuffId"
type="int32"
tag="shoucheng_tianqi_buff_id"
comment="守城初始天气buffid"
  
[[variables]]
name="GongChengTianqiBuffId"
type="int32"
tag="gongcheng_tianqi_buff_id"   
comment="攻城初始天气buffid"
  
[[variables]]
name="GongChengWanfaBuffId"
type="int32"
tag="gongcheng_wanfa_buff_id"  
comment="攻城使用万法后的天气buffid"
  
[[variables]]
name="TianqiItemId"
type="int32"
tag="tianqi_item_id"  
comment="天气激活物品id" 
  
[[variables]]
name="TianqiItemCount"
type="int32" 
tag="tianqi_item_count"    
comment="天气激活物品数量"
  
[[variables]]
name="ValidTime"
type="int64" 
tag="jihuo_chixu_time"    
comment="天气激活有效时间"
  
[[variables]]
name="Name"
type="string" 
tag="name"    
comment="天气名字"


 