file="chuangshi_chengfang_vo.go"
pkg="template"
class="ChuangShiChengFangTemplateVO"
comment = "创世城池建设模板配置"

[[variables]]
name="Id"
type="int"
tag="id"
comment="id"
  
[[variables]]
name="Name"
type="string"
tag="name"
comment="建筑名字"
  
[[variables]]
name="Type"
type="int32"
tag="type"
comment="类型"
  
[[variables]]
name="LevelBeginId"
type="int32"
tag="level_begin_id" 
comment="升级关联id"
  
[[variables]]
name="LevelItemId"
type="int32"
tag="level_item_id"  
comment="升级物品id"

