file="chuangshi_war_guard_vo.go"
pkg="template"
class="ChuangShiWarGuardTemplateVO"
comment = "创世守卫配置"
[[variables]]
name="Id"
type="int"
tag="id"
comment="id"

[[variables]]
name="Name"
type="string"
tag="name"
comment="名称"

[[variables]]
name="BiologyId"
type="int32"
tag="biology_id"
comment="生物id"

[[variables]]
name="Map"
type="int32"
tag="map"
comment="地图id"

[[variables]]
name="SceneId"
type="int32"
tag="scene_id"
comment="守卫id"

[[variables]]
name="GuardSummon"
type="int32"
tag="guard_summon"
comment="默认召唤方式"

[[variables]]
name="NeedSilver"
type="int32"
tag="need_silver"
comment="需要银两"

[[variables]]
name="NeedGold"
type="int32"
tag="need_gold"
comment="需要元宝"

[[variables]]
name="NeedBindGold"
type="int32"
tag="need_bind_gold"
comment="需要绑元"

[[variables]]
name="NeedItemId"
type="string"
tag="need_item_id"
comment="需要物品id"

[[variables]]
name="NeedItemCount"
type="string"
tag="need_item_count"
comment="需要物品数量"

