file="chuangshi_war_vo.go"
pkg="template"
class="ChuangShiWarTemplateVO"
comment = "创世城战配置"
[[variables]]
name="Id"
type="int"
tag="id"
comment="id"

[[variables]]
name="RebornSitu"
type="int32"
tag="reborn_situ"
comment="原地复活的最高次数"

[[variables]]
name="FristTiem"
type="int64"
tag="frist_tiem"
comment="进入后多少毫秒获得奖励"

[[variables]]
name="RewTiem"
type="int64"
tag="rew_tiem"
comment="多少毫秒发一次奖励"
 
[[variables]]
name="RewExp"
type="int64"
tag="rew_exp"
comment="单次发放经验值"

[[variables]]
name="RewExpPoint"
type="int32"
tag="rew_exp_point"
comment="单次发放的经验点"

[[variables]]
name="RewSilver"
type="int64"
tag="rew_silver"
comment="奖励银两"

[[variables]]
name="MapId"
type="int32"
tag="map_id"
comment="地图id"

[[variables]]
name="RewExpSafeArea"
type="int64"
tag="rew_exp_anquanqu"
comment="安全区单次发放经验值"

[[variables]]
name="RewExpPointSafeArea"
type="int32"
tag="rew_exp_point_anquanqu"
comment="安全区单次发放的经验点"

[[variables]]
name="RewSilverSafeArea"
type="int64"
tag="rew_silver_anquanqu"
comment="安全区奖励银两"

[[variables]]
name="KillJiFen"
type="int32"
tag="kill_jifen"
comment="击杀获得积分"

[[variables]]
name="FristJiFenTime"
type="int64"
tag="frist_jifen_time"
comment="进入后多少毫秒获得积分"

[[variables]] 
name="RewJiFenTime"
type="int64"
tag="rew_jifen_time"
comment="多少毫秒发一次积分"

[[variables]]
name="RewJiFen"
type="int32"
tag="rew_jifen"
comment="单次发放积分"

[[variables]]
name="ProtectBuffId"
type="int32"
tag="wudi_buff_id"
comment="防护罩无敌buff"
