file="circle_bargain_vo.go"
pkg="template"
class="CircleBargainTemplateVO"
comment = "转生礼包折扣配置"

[[variables]]
name="Id" 
type="int"
tag="id"
comment="id"

[[variables]]
name="Type"
type="int32"
tag="type"
comment="折扣组"

[[variables]]
name="ItemCountMin"
type="int32"
tag="item_count_min" 
comment="数量最小值"

[[variables]]
name="ItemCountMax"
type="int32" 
tag="item_count_max"
comment="数量最大值"

[[variables]]
name="Discount"
type="int32" 
tag="discount"
comment="折扣"


