file="constant_vo.go"
pkg="template"
class="ConstantTemplateVO"
comment = "常量配置"
[[variables]]
name="Id"
type="int"
tag="id"
comment="id"

[[variables]]
name="Text"
type="string"
tag="text"
comment="text"

[[variables]]
name="Type"
type="int32"
tag="type"
comment="类型"



[[variables]]
name="Value"
type="int64"
tag="value"
comment="值"
