file="tower_vo.go"
pkg="template"
class="TowerTemplateVO"
comment = "打宝塔模板配置"
[[variables]]
name="Id"
type="int"
tag="id"
comment="id"

[[variables]]
name="NextId"
type="int32"
tag="next_id"
comment="下一个id"

[[variables]]
name="LevelMin"
type="int32"
tag="level_min"
comment="最低等级"

[[variables]]
name="LevelMax"
type="int32"
tag="level_max"
comment="最高等级"

[[variables]]
name="MapId"
type="int32"
tag="map_id"
comment="地图id"

[[variables]]
name="BossId"
type="int32"
tag="boss_id"
comment="配置0非boss层"

[[variables]]
name="BossPosX"
type="float64"
tag="boss_pos_x"
comment="Boss刷新x"

[[variables]]
name="BossPosY"
type="float64"
tag="boss_pos_y"
comment="Boss刷新y"

[[variables]]
name="BossPosZ"
type="float64"
tag="boss_pos_z"
comment="Boss刷新z"

[[variables]]
name="ZhifeiItem"
type="int32"
tag="zhifei_item"
comment="需要的物品id"

[[variables]]
name="ZhifeiItemCount"
type="int32"
tag="zhifei_item_count"
comment="需要的物品数量"

[[variables]]
name="RewardPreviewId"
type="string"
tag="reward_preview_id"
comment="奖励预览"

[[variables]]
name="XujiaId"
type="string"
tag="xujia_id"
comment="小怪id"

[[variables]]
name="XujiaItem"
type="string"
tag="xujia_item"
comment="小怪掉落id"
