file="daily_vo.go"
pkg="template"
class="DailyTemplateVO"
comment = "日环任务模板配置"
[[variables]]
name="Id"
type="int"
tag="id"
comment="id"


[[variables]]
name="NextId"
type="int32"
tag="next_id"
comment="下一个id"

[[variables]]
name="Times"
type="int32"
tag="times_min"
comment="第X个任务"

[[variables]]
name="TimesMax"
type="int32"
tag="times_max"
comment="第X个任务"

[[variables]]
name="LevelMin"
type="int32"
tag="level_min"
comment="最低等级"

[[variables]]
name="LevelMax"
type="int32"
tag="level_max"
comment="最高等级"

[[variables]]
name="QuestId"
type="int32"
tag="quest_id"
comment="关联任务表的ID,为该条数据的条件"

[[variables]]
name="Percent"
type="int32"
tag="percent"
comment="随机到该任务的几率"

[[variables]]
name="RewSilver"
type="int32"
tag="rew_silver"
comment="完成任务奖励的银两"

[[variables]]
name="RewBindGold"
type="int32"
tag="rew_bind_gold"
comment="完成任务奖励的绑元"

[[variables]]
name="RewGold"
type="int32"
tag="rew_gold"
comment="完成任务奖励的元宝"


[[variables]]
name="RewExp"
type="int32"
tag="rew_xp"
comment="奖励经验值"

[[variables]]
name="RewExpPoint"
type="int32"
tag="rew_exp_point"
comment="奖励经验点数"

[[variables]]
name="RewItemId"
type="string"
tag="rew_item_id"
comment="奖励物品"

[[variables]]
name="RewItemCount"
type="string"
tag="rew_item_count"
comment="奖励物品数量"

[[variables]]
name="DropId"
type="int32"
tag="drop_id"
comment="日环抽奖"







