file="dianxing_jiefeng_vo.go"
pkg="template"
class="DianXingJieFengTemplateVO"
comment = "点星解封配置"
[[variables]]
name="Id"
type="int"
tag="id"
comment="id"

[[variables]]
name="NextId"
type="int32"
tag="next_id"
comment="下一个id"

[[variables]]
name="Level"
type="int32"
tag="level"
comment="等级"

[[variables]]
name="UpdateWfb"
type="int32"
tag="update_wfb"
comment="升阶成功率"

[[variables]]
name="UseSilver"
type="int32"
tag="use_silver"
comment="升级所需银两数量"

[[variables]]
name="UseItem"
type="int32"
tag="use_item"
comment="升级所需物品id"

[[variables]]
name="ItemCount"
type="int32"
tag="item_count"
comment="升级所需物品数量"

[[variables]]
name="TimesMin"
type="int32"
tag="times_min"
comment="最小次数"

[[variables]]
name="TimesMax"
type="int32"
tag="times_max"
comment="最大次数"

[[variables]]
name="AddMin"
type="int32"
tag="add_min"
comment="每次解封增加的进度最小值"

[[variables]]
name="AddMax"
type="int32"
tag="add_max"
comment="每次解封增加的进度最大值"

[[variables]]
name="ZhufuMax"
type="int32"
tag="zhufu_max"
comment="前端显示的进度值"

[[variables]]
name="AttrPercent"
type="int32"
tag="percent"
comment="该等级增加的属性万分比"

[[variables]]
name="Hp"
type="int32"
tag="hp"
comment="该等级增加的生命"

[[variables]]
name="Attack"
type="int32"
tag="attack"
comment="该等级增加的攻击"

[[variables]]
name="Defence"
type="int32"
tag="defence"
comment="该等级增加的防御"

[[variables]]
name="MountPercent"
type="int32"
tag="mount_percent"
comment="坐骑属性万分比"

[[variables]]
name="WingPercent"
type="int32"
tag="wing_percent"
comment="战翼属性万分比"

[[variables]]
name="FieldPercent"
type="int32"
tag="field_percent"
comment="领域属性万分比"

[[variables]]
name="ShenFaPercent"
type="int32"
tag="shenfa_percent"
comment="身法属性万分比"

[[variables]]
name="BodyShieldPercent"
type="int32"
tag="body_shield_percent"
comment="护体盾属性万分比"

[[variables]]
name="AnQiPercent"
type="int32"
tag="anqi_percent"
comment="暗器属性万分比"

[[variables]]
name="FaBaoPercent"
type="int32"
tag="fabao_percent"
comment="法宝属性万分比"

[[variables]]
name="XianTiPercent"
type="int32"
tag="xianti_percent"
comment="仙体属性万分比"

[[variables]]
name="TianMoTiPercent"
type="int32"
tag="tianmoti_percent"
comment="天魔体属性万分比"

[[variables]]
name="ShiHunFanPercent"
type="int32"
tag="shihunfan_percent"
comment="噬魂幡属性万分比"

[[variables]]
name="LingTongMountPercent"
type="int32"
tag="lingtong_zuoqi_percent"
comment="灵骑属性万分比"

[[variables]]
name="LingTongWeaponPercent"
type="int32"
tag="lingtong_binghun_percent"
comment="灵兵属性万分比"

[[variables]]
name="LingTongWingPercent"
type="int32"
tag="lingtong_zhanyi_percent"
comment="灵翼属性万分比"

[[variables]]
name="LingTongFaBaoPercent"
type="int32"
tag="lingtong_fabao_percent"
comment="灵宝属性万分比"

[[variables]]
name="LingTongXianTiPercent"
type="int32"
tag="lingtong_xianti_percent"
comment="灵体属性万分比"

[[variables]]
name="LingTongLingYuPercent"
type="int32"
tag="lingtong_lingyu_percent"
comment="灵域属性万分比"

[[variables]]
name="LingTongShenFaPercent"
type="int32"
tag="lingtong_shenfa_percent"
comment="灵身属性万分比"