

file="dragon_chair_vo.go"
pkg="template"
class="DragonChairTemplateVO"
comment = "抢龙椅配置"
[[variables]]
name="Id"
type="int"
tag="id"
comment="id"

[[variables]]
name="FirstGold"
type="int32"
tag="first_gold"
comment="元宝底数"

[[variables]]
name="CoefficientGold"
type="float64"
tag="coefficient_gold"
comment="元宝系数1"

[[variables]]
name="ValueGold"
type="int32"
tag="value_gold"
comment="元宝固定值"

[[variables]]
name="FirstAttrId"
type="int32"
tag="first_attr_id"
comment="属性底数id"

[[variables]]
name="CoefficientAttr"
type="float64"
tag="coefficient_attr"
comment="属性系数1"

[[variables]]
name="ValueAttrId"
type="int32"
tag="value_attr_id"
comment="属性固定值id"

[[variables]]
name="TitleId"
type="int32"
tag="title_id"
comment="称号id"

[[variables]]
name="SilverWorship"
type="int32"
tag="silver_worship"
comment="膜拜给予的银两奖励"

[[variables]]
name="BindGoldWorship"
type="int32"
tag="bind_gold_worship"
comment="膜拜给予的绑元奖励"

[[variables]]
name="ExpWorship"
type="int32"
tag="exp_worship"
comment="膜拜给予的经验奖励"

[[variables]]
name="ExpPointWorship"
type="int32"
tag="exp_point_worship"
comment="膜拜给予的经验点奖励"

[[variables]]
name="ItemWorship"
type="string"
tag="item_worship"
comment="膜拜给予的物品奖励"

[[variables]]
name="ItemCountWorship"
type="string"
tag="item_count_worship"
comment="膜拜给予的物品奖励数量"

[[variables]]
name="WorshipCount"
type="int32"
tag="worship_count"
comment="每日最大膜拜次数"


[[variables]]
name="WorshipChestSilver"
type="int32"
tag="worship_chest_silver"
comment="每次膜拜给金库增加银两数量"

[[variables]]
name="AutoSilver"
type="int32"
tag="auto_silver"
comment="每次自动往帝王金库添加的银两数量"

[[variables]]
name="AutoSilverTime"
type="int32"
tag="auto_silver_time"
comment="向帝王金库自动添加银两的间隔时间(毫秒)"


[[variables]]
name="ChestMax"
type="int32"
tag="chest_max"
comment="国库存银的最大上限"

[[variables]]
name="ChanchuSilver0"
type="int32"
tag="chanchu_silver0"
comment="当占领时间不在所有区间内的每分钟产出"

[[variables]]
name="ZhanlingTime1"
type="string"
tag="zhanling_time1"
comment="占领时间区间"

[[variables]]
name="ChanchuSilver1"
type="int32"
tag="chanchu_silver1"
comment="第一个占领区间产出的银两"

[[variables]]
name="ZhanlingTime2"
type="string"
tag="zhanling_time2"
comment="占领时间区间2"

[[variables]]
name="ChanchuSilver2"
type="int32"
tag="chanchu_silver2"
comment="第二个占领区间产出的银两"

[[variables]]
name="ZhanlingTime3"
type="string"
tag="zhanling_time3"
comment="占领时间区间3"

[[variables]]
name="ChanchuSilver3"
type="int32"
tag="chanchu_silver3"
comment="第三个占领区间产出的银两"

[[variables]]
name="ZhanlingTime4"
type="string"
tag="zhanling_time4"
comment="占领时间区间4"

[[variables]]
name="ChanchuSilver4"
type="int32"
tag="chanchu_silver4"
comment="第四个占领区间产出的银两"


[[variables]]
name="SpecialDrop"
type="string"
tag="special_drop"
comment="特殊掉落"

[[variables]]
name="CommonDrop"
type="string"
tag="common_drop"
comment="普通掉落"

[[variables]]
name="DropTime1"
type="int32"
tag="drop_time1"
comment="获得时间(毫秒)"

[[variables]]
name="DropTime2"
type="int32"
tag="drop_time2"
comment="获得时间(毫秒)"

[[variables]]
name="DropTime3"
type="int32"
tag="drop_time3"
comment="获得时间(毫秒)"

[[variables]]
name="DropTime4"
type="int32"
tag="drop_time4"
comment="获得时间(毫秒)"

[[variables]]
name="GoldPercent"
type="int32"
tag="gold_percent"
comment="返还的元宝的万分比"
