file="dragon_vo.go"
pkg="template"
class="DragonTemplateVO"
comment = "神龙现世配置"
[[variables]]
name="Id"
type="int"
tag="id"
comment="id"

[[variables]]
name="NextId"
type="int32"
tag="next_id"
comment="下一培养阶段"

[[variables]]
name="DragonItemId"
type="string"
tag="dragon_item_id"
comment="神龙喂食所需的物品id"

[[variables]]
name="DragonItemAmount"
type="string"
tag="dragon_item_amount"
comment="神龙喂食所需的物品数量"

[[variables]]
name="DragonModelId"
type="int32"
tag="dragon_model_id"
comment="龙神各阶段模型id"

[[variables]]
name="DragonSkill"
type="int32"
tag="dragon_skill"
comment="技能id"


[[variables]]
name="DragonMount"
type="int32"
tag="dragon_mount"
comment="坐骑id"

[[variables]]
name="DragonChandi"
type="string"
tag="dragon_chandi"
comment="材料产出地"

[[variables]]
name="ItemId"
type="int32"
tag="item_id"
comment="坐骑幻化卡id"