

file="drop_baoku_vo.go"
pkg="template"
class="DropBaoKuTemplateVO"
comment = "掉落配置"
[[variables]]
name="Id"
type="int"
tag="id"
comment="id"

[[variables]]
name="DropId"
type="int32"
tag="drop_id"
comment="掉落包id"

[[variables]]
name="ItemId"
type="int32"
tag="item_id"
comment="掉落物品id"

[[variables]]
name="Rate"
type="int64"
tag="rate"
comment="掉落概率,最大为20亿"

[[variables]]
name="MinCount"
type="int32"
tag="min_count"
comment="掉落最小数量"

[[variables]]
name="MaxCount"
type="int32"
tag="max_count"
comment="掉落最大数量"

[[variables]]
name="MinStack"
type="int32"
tag="min_stack"
comment="最小堆数"

[[variables]]
name="MaxStack"
type="int32"
tag="max_stack"
comment="最大堆数"

[[variables]]
name="GoldEquipMin"
type="int32"
tag="gold_equip_min"
comment="金装最小强化等级"

[[variables]]
name="GoldEquipMax"
type="int32"
tag="gold_equip_max"
comment="金装最大强化等级"

[[variables]]
name="StrengthenPoolId"
type="int32"
tag="strengthen_pool_id"
comment="金装升星等级池id"

[[variables]]
name="FristFujiaId"
type="int32"
tag="frist_fujia_id"
comment="关联金装附件属性表"

[[variables]]
name="BindType"
type="int32"
tag="bind_type"
comment="是否绑定"

[[variables]]
name="ExistTime"
type="int32"
tag="exist_time"
comment="存活时间"

[[variables]]
name="ProtectedTime"
type="int32"
tag="protected_time"
comment="保护时间"

[[variables]]
name="FailTime"
type="int32"
tag="fail_time"
comment="物品失效时间"

[[variables]]
name="IsDropAgin"
type="int32"
tag="is_drop_agin"
comment="是否支持再次掉落0-否1-是"

[[variables]]
name="IsDropSuppress"
type="int32"
tag="is_drop_suppress"
comment="是否受到掉落压制"

