file="eat_dan_vo.go"
pkg="template"
class="EatDanTemplateVO"
comment = "食丹配置"
[[variables]]
name="Id"
type="int"
tag="id"
comment="id"

[[variables]]
name="NextId"
type="int32"
tag="next_id"
comment="下一个id"

[[variables]]
name="DanId1"
type="int32"
tag="limit_dan_id1"
comment="限制食丹1"

[[variables]]
name="DanIdNum1"
type="int32"
tag="limit_dan_num1"
comment="限制食丹数量1"

[[variables]]
name="DanId2"
type="int32"
tag="limit_dan_id2"
comment="限制食丹2"

[[variables]]
name="DanIdNum2"
type="int32"
tag="limit_dan_num2"
comment="限制食丹数量2"

[[variables]]
name="DanId3"
type="int32"
tag="limit_dan_id3"
comment="限制食丹3"

[[variables]]
name="DanIdNum3"
type="int32"
tag="limit_dan_num3"
comment="限制食丹数量3"

[[variables]]
name="DanId4"
type="int32"
tag="limit_dan_id4"
comment="限制食丹4"

[[variables]]
name="DanIdNum4"
type="int32"
tag="limit_dan_num4"
comment="限制食丹数量4"

[[variables]]
name="DanId5"
type="int32"
tag="limit_dan_id5"
comment="限制食丹5"

[[variables]]
name="DanIdNum5"
type="int32"
tag="limit_dan_num5"
comment="限制食丹数量5"

[[variables]]
name="DanId6"
type="int32"
tag="limit_dan_id6"
comment="限制食丹6"

[[variables]]
name="DanIdNum6"
type="int32"
tag="limit_dan_num6"
comment="限制食丹数量6"

[[variables]]
name="DanId7"
type="int32"
tag="limit_dan_id7"
comment="限制食丹7"

[[variables]]
name="DanIdNum7"
type="int32"
tag="limit_dan_num7"
comment="限制食丹数量7"







