


file="equip_vo.go"
pkg="template"
class="EquipTemplateVO"
comment = "装备模板"
[[variables]]
name="Id"
type="int"
tag="id"
comment="id"

[[variables]]
name="MaxStrengthen"
type="int"
tag="max_strengthen"
comment="装备强化上限"

[[variables]]
name="StoneType"
type="int32"
tag="stone_type"
comment="镶嵌宝石类型"

[[variables]]
name="AddStatusid"
type="int32"
tag="add_statusid"
comment="装备添加状态"

[[variables]]
name="Series"
type="int32"
tag="series"
comment="套装"

[[variables]]
name="NeedItem1"
type="int32"
tag="need_item1"
comment="进阶需要物品1"

[[variables]]
name="NeedItemNum1"
type="int32"
tag="need_item_num1"
comment="进阶需要物品1数量"

[[variables]]
name="NeedItem2"
type="int32"
tag="need_item2"
comment="进阶需要物品2"

[[variables]]
name="NeedItemNum2"
type="int32"
tag="need_item_num2"
comment="进阶需要物品2数量"

[[variables]]
name="NeedItem3"
type="int32"
tag="need_item3"
comment="进阶需要物品3"

[[variables]]
name="NeedItemNum3"
type="int32"
tag="need_item_num3"
comment="进阶需要物品3数量"


[[variables]]
name="SuccessRate"
type="int32"
tag="success_rate"
comment="进阶成功几率"

[[variables]]
name="Next"
type="int32"
tag="next"
comment="下一阶物品"




[[variables]]
name="TaozhuangId"
type="int32"
tag="taozhuang_id"
comment="套装id"

[[variables]]
name="Hp"
type="int64"
tag="hp"
comment="血量"

[[variables]]
name="Attack"
type="int64"
tag="attack"
comment="攻击"

[[variables]]
name="Defence"
type="int64"
tag="defence"
comment="防御"
