file="equip_strengthen_vo.go"
pkg="template"
class="EquipStrengthenTemplateVO"
comment = "装备强化模板"

[[variables]]
name="Id"
type="int"
tag="id"
comment="id"

[[variables]]
name="Type"
type="int32"
tag="type"
comment="装备强化类型"

[[variables]]
name="NextId"
type="int32"
tag="next_id"
comment="下一阶id"

[[variables]]
name="Position"
type="int32"
tag="position"
comment="位置"

[[variables]]
name="Level"
type="int32"
tag="level"
comment="等级"

[[variables]]
name="SuccessRate"
type="int32"
tag="success_rate"
comment="成功率"

[[variables]]
name="ReturnRate"
type="int32"
tag="return_rate"
comment="回退概率"

[[variables]]
name="FailReturnStrengthenId"
type="int32"
tag="fail_return_strengthen_id"
comment="回退id"


[[variables]]
name="SilverNum"
type="int32"
tag="silver_num"
comment="银两数"

[[variables]]
name="NeedItem"
type="int32"
tag="need_item"
comment="需要物品"

[[variables]]
name="NeedItemNum"
type="int32"
tag="need_item_num"
comment="需要物品1数量"



[[variables]]
name="Hp"
type="int64"
tag="hp"
comment="血量"

[[variables]]
name="Attack"
type="int64"
tag="attack"
comment="攻击"

[[variables]]
name="Defence"
type="int64"
tag="defence"
comment="防御"
