file="exp_make_vo.go"
pkg="template"
class="MadeTemplateVO"
comment = "活动炼制模板配置"
[[variables]]
name="Id"
type="int"
tag="id"
comment="id"

[[variables]]
name="GroupId"
type="int32"
tag="group"
comment="活动id" 

[[variables]]
name="LevelMin"
type="int32"
tag="Level_min"
comment="最小区间"

[[variables]]
name="LevelMax"
type="int32"
tag="Level_max"
comment="最大区间"

[[variables]]
name="Exp"
type="int32"
tag="exp"
comment="经验"

[[variables]]
name="ExpPoint"
type="int32"
tag="uplev"
comment="经验点"

[[variables]]
name="CostBase"
type="string"
tag="cost_base"
comment="所需消耗"

 