file="fabao_vo.go"
pkg="template"
class="FaBaoTemplateVO"
comment = "法宝配置"
[[variables]]
name="Id"
type="int"
tag="id"
comment="id"

[[variables]]
name="NextId"
type="int32"
tag="next_id"
comment="下一个id"



[[variables]]
name="Type"
type="int32"
tag="type"
comment="名字"

[[variables]]
name="Name"
type="string"
tag="name"
comment="名字"

[[variables]]
name="Number"
type="int32"
tag="number"
comment="阶数"


[[variables]]
name="Pos"
type="int32"
tag="pos"
comment="顺序显示"


[[variables]]
name="UpdateWfb"
type="int32"
tag="update_wfb"
comment="升阶成功率"


[[variables]]
name="UseMoney"
type="int32"
tag="use_money"
comment="升阶所需元宝"


[[variables]]
name="UseItem"
type="int32"
tag="use_item"
comment="升级所需物品"

[[variables]]
name="ItemCount"
type="int32"
tag="item_count"
comment="升阶所需物品数量"

[[variables]]
name="TimesMin"
type="int32"
tag="times_min"
comment="最小次数"

[[variables]]
name="TimesMax"
type="int32"
tag="times_max"
comment="最大次数"

[[variables]]
name="AddMin"
type="int32"
tag="add_min"
comment="每次培养增加的进度最小值"

[[variables]]
name="AddMax"
type="int32"
tag="add_max"
comment="每次培养增加的进度最大值"


[[variables]]
name="ZhufuMax"
type="int32"
tag="zhufu_max"
comment="前端显示的进度值"

[[variables]]
name="FaBaoUpstarBeginId"
type="int32"
tag="fabao_upstar_begin_id"
comment="升星起始id"


[[variables]]
name="ModelId"
type="int32"
tag="model_id"
comment="模型ID"


[[variables]]
name="UseYinliang"
type="int32"
tag="use_yinliang"
comment="所需银两"


[[variables]]
name="ShidanLimit"
type="int32"
tag="shidan_limit"
comment="食丹等级上限"

[[variables]]
name="Icon"
type="int32"
tag="icon"
comment="法宝"


[[variables]]
name="MagicConditionType1"
type="int32"
tag="magic_condition_type1"
comment="幻化条件类型1"

[[variables]]
name="MagicConditionParameter1"
type="string"
tag="magic_condition_parameter1"
comment="幻化条件类型参数1"

[[variables]]
name="MagicConditionType2"
type="int32"
tag="magic_condition_type2"
comment="幻化条件类型2"

[[variables]]
name="MagicConditionParameter2"
type="string"
tag="magic_condition_parameter2"
comment="幻化条件类型参数2"


[[variables]]
name="MagicConditionType3"
type="int32"
tag="magic_condition_type3"
comment="幻化条件类型3"

[[variables]]
name="MagicConditionParameter3"
type="string"
tag="magic_condition_parameter3"
comment="幻化条件类型参数3"


[[variables]]
name="UiScale"
type="string"
tag="ui_scale"
comment="ui"


[[variables]]
name="Hp"
type="int32"
tag="hp"
comment="该等级增加的生命"


[[variables]]
name="Attack"
type="int32"
tag="attack"
comment="该等级增加的攻击"



[[variables]]
name="Defence"
type="int32"
tag="defence"
comment="该等级增加的防御"


[[variables]]
name="IsClear"
type="int32"
tag="is_clear"
comment="过天是否清空祝福值"








