file="famous_vo.go"
pkg="template"
class="FamousTemplateVo"
comment = "名人培养配置"

[[variables]]
name="Id"
type="int"
tag="id"
comment="id"

[[variables]]
name="GroupId"
type="int32"
tag="group" 
comment="活动id" 

[[variables]]
name="Name"
type="string"
tag="name"
comment="名人名称"

[[variables]]
name="UseItemId"
type="string"
tag="use_item_id"
comment="消耗物品id"

[[variables]]
name="UseItemCount"
type="string"
tag="use_item_count"
comment="消耗物品数量" 

[[variables]]
name="ItemIncreaseFavorable"
type="string"
tag="item_increase_favorable"
comment="增加的好感值" 


[[variables]]
name="UseLimit"
type="string"
tag="use_limit"
comment="喂养次数限制" 

[[variables]]
name="DropId"
type="string" 
tag="drop_id"
comment="喂养奖励掉落包" 
