file="house_vo.go"
pkg="template"
class="HouseTemplateVO"
comment = "房子配置"
[[variables]]
name="Id"
type="int"
tag="id"
comment="id"

[[variables]]
name="NextId"
type="int32"
tag="next_id"
comment="下一级di"

[[variables]]
name="Level"
type="int32"
tag="level"
comment="等级"

[[variables]]
name="Type"
type="int32"
tag="type"
comment="房子类型"

[[variables]]
name="HouseIndex"
type="int32"
tag="number"
comment="房子序号" 

[[variables]]
name="UseItemId"
type="string"
tag="use_item_id"
comment="升级所需物品ID"

[[variables]]
name="UseItemCount"
type="string"
tag="use_item_count"
comment="升级所需物品数量"

[[variables]]
name="BrokenPercent"
type="int32"
tag="broken_percent"
comment="损坏几率" 

[[variables]]
name="FixItemId"
type="string"
tag="fix_item_id"
comment="维修消耗物品ID"

[[variables]]
name="FixItemCount"
type="string"
tag="fix_item_count"
comment="维修消耗物品数量"

[[variables]]
name="Rent"
type="int32"
tag="rent"
comment="租金：根据房子类型获得对应的银两/绑元"

[[variables]]
name="HousePrice"
type="int32"
tag="house_price"
comment="房价：根据房子类型出售房子可获得的银两/绑元数量"

[[variables]]
name="AdvanceSalePercent"
type="int32"
tag="advance_sale_percent"
comment="提前出售获得的房价万分比"

[[variables]]
name="UplevGetItem"
type="string"
tag="uplev_get_item"
comment="每次装修可获得物品ID"

[[variables]]
name="UplevGetItemCount"
type="string"
tag="uplev_get_item_count"
comment="每次装修可获得物品数量" 