file="house_constant_vo.go"
pkg="template"
class="HouseConstantTemplateVO"
comment = "房子常量模板配置"
[[variables]]
name="Id"
type="int"
tag="id"
comment="id"
 
[[variables]]
name="BrokenCd"
type="int64"
tag="broken_cd"
comment="房子损坏CD"
 
[[variables]]
name="UplevLimitCount"
type="int32"
tag="uplev_limit_count"
comment="每日装修次数"
 
[[variables]]
name="JiaRiZhiTime"
type="string"
tag="jiarizhi_time"
comment="虚拟日志时间间隔"
 
[[variables]]
name="RiZhiCount"
type="int32"
tag="rizhi_count"
comment="总日志数量"
 
[[variables]]
name="FirstFangZiType"
type="int32"
tag="first_fangzi_type"
comment="初始房子类型"
 
[[variables]]
name="FangZiCountMax"
type="int32" 
tag="fangzi_count_max"
comment="房子最大数量"