file="fashion_vo.go"
pkg="template"
class="FashionTemplateVO"
comment = "时装配置"
[[variables]]
name="Id"
type="int"
tag="id"
comment="id"

[[variables]]
name="Name11"
type="string"
tag="name_1_1"
comment="时装名称-开天男"

[[variables]]
name="Name12"
type="string"
tag="name_1_2"
comment="时装名称-开天女"

[[variables]]
name="Name21"
type="string"
tag="name_2_1"
comment="时装名称-奕剑男"

[[variables]]
name="Name22"
type="string"
tag="name_2_2"
comment="时装名称-奕剑女"

[[variables]]
name="Name31"
type="string"
tag="name_3_1"
comment="时装名称-破月男"

[[variables]]
name="Name32"
type="string"
tag="name_3_2"
comment="时装名称-破月女"

[[variables]]
name="Type"
type="int32"
tag="type"
comment="时装类型"

[[variables]]
name="Pos"
type="int32"
tag="pos"
comment="排序"

[[variables]]
name="NeedItemId"
type="int32"
tag="need_item_id"
comment="需要物品id(开天男)"

[[variables]]
name="NeedItemIdNv"
type="int32"
tag="need_item_id_nv"
comment="需要物品id(开天女)"

[[variables]]
name="NeedItemId2"
type="int32"
tag="need_item_id2"
comment="需要物品id(奕剑男)"

[[variables]]
name="NeedItemId2Nv"
type="int32"
tag="need_item_id2_nv"
comment="需要物品id(奕剑女)"

[[variables]]
name="NeedItemId3"
type="int32"
tag="need_item_id3"
comment="需要物品id(破月男)"

[[variables]]
name="NeedItemId3Nv"
type="int32"
tag="need_item_id3_nv"
comment="需要物品id(破月女)"

[[variables]]
name="NeedItemCount"
type="int32"
tag="need_item_count"
comment="需要物品数量"

[[variables]]
name="Time"
type="int64"
tag="time"
comment="有效性"

[[variables]]
name="Attr"
type="int32"
tag="attr"
comment="属性"

[[variables]]
name="FashionUpgradeBeginId"
type="int32"
tag="fashion_upgrade_begin_id"
comment="时装升星起始ID"

[[variables]]
name="Access"
type="string"
tag="access"
comment="获取途径"

[[variables]]
name="ModelId1_1"
type="int32"
tag="model_id_1_1"
comment="开天男"

[[variables]]
name="ModelId1_2"
type="int32"
tag="model_id_1_2"
comment="开天女"

[[variables]]
name="ModelId2_1"
type="int32"
tag="model_id_2_1"
comment="奕剑男"

[[variables]]
name="ModelId2_2"
type="int32"
tag="model_id_2_2"
comment="奕剑女"


[[variables]]
name="ModelId3_1"
type="int32"
tag="model_id_3_1"
comment="破月男"

[[variables]]
name="ModelId3_2"
type="int32"
tag="model_id_3_2"
comment="破月女"
