file="fei_sheng_qianneng_vo.go"
pkg="template"
class="FeiShengQianNengTemplateVO"
comment = "飞升潜能模板配置"
[[variables]]
name="Id"
type="int"
tag="id"
comment="id"

[[variables]]
name="Type"
type="int32"
tag="type"
comment="潜能类型" 

[[variables]]
name="Hp"
type="int64"
tag="hp"
comment="生命"

[[variables]]
name="Attack"
type="int64"
tag="attack"
comment="攻击"

[[variables]]
name="Defence"
type="int64"
tag="defence"
comment="防御"
