file="fei_sheng_vo.go"
pkg="template"
class="FeiShengTemplateVO"
comment = "飞升模板配置"
[[variables]]
name="Id"
type="int"
tag="id"
comment="id"

[[variables]]
name="NextId"
type="int"
tag="next_id"
comment="下一级di"

[[variables]]
name="Level"
type="int32"
tag="level"
comment="飞升等级"

[[variables]]
name="GongDe"
type="int32"
tag="gongde"
comment="所需功德"

[[variables]]
name="Rate"
type="int32"
tag="rate"
comment="飞升概率"

[[variables]]
name="ItemId"
type="int32"
tag="item_id"
comment="提升概率物品"

[[variables]]
name="ItemCount"
type="int32"
tag="item_count"
comment="提升概率物品数量"

[[variables]]
name="AddRate"
type="int32"
tag="add_rate"
comment="增加的概率"

[[variables]]
name="Hp"
type="int64"
tag="hp"
comment="生命"

[[variables]]
name="Attack"
type="int64"
tag="attack"
comment="攻击"

[[variables]]
name="Defence"
type="int64"
tag="defence"
comment="防御"

[[variables]]
name="QnAdd"
type="int32"
tag="qn_add"
comment="可配置的潜能"

[[variables]]
name="XidianGold"
type="int32"
tag="xidian_gold"
comment="洗点所需元宝"

[[variables]]
name="GongdeRatio"
type="int32"
tag="gongde_ratio"
comment="功德的转换比例"

[[variables]]
name="GiveExpRatio"
type="int32"
tag="give_exp_ratio"
comment="赠送经验的转换比例"
 