

file="found_vo.go"
pkg="template"
class="FoundTemplateVO"
comment = "资源找回配置"
[[variables]]
tag="id"
type="int"
name="Id"
comment="id"

[[variables]]
tag="name"
type="string"
name="Name"
comment="任务名称"

[[variables]]
tag="type"
type="int32"
name="Type"
comment="任务类型"

[[variables]]
tag="level_min"
type="int32"
name="LevelMin"
comment="最低限制"

[[variables]]
tag="level_max"
type="int32"
name="LevelMax"
comment="最高限制"

[[variables]]
tag="found_using"
type="int32"
name="FoundUsing"
comment="单次完美找回消耗的绑元"

[[variables]]
tag="found_silver"
type="int32"
name="FoundSilver"
comment="单次完美找回获得的银两数量"

[[variables]]
tag="found_gold"
type="int32"
name="FoundGold"
comment="单次完美找回获得的元宝数量"

[[variables]]
tag="found_bindgold"
type="int32"
name="FoundBindgold"
comment="单次完美找回获得的绑元数量"

[[variables]]
tag="found_exp"
type="int32"
name="FoundExp"
comment="单次完美找回获得的经验值"

[[variables]]
tag="found_exp_point"
type="int32"
name="FoundExpPoint"
comment="单次完美找回获得的经验点"

[[variables]]
tag="found_item_id"
type="string"
name="FoundItemId"
comment="单次完美找回获得的物品id"

[[variables]]
tag="found_item_amount"
type="string"
name="FoundItemAmount"
comment="单次完美找回获得的物品数量"

[[variables]]
tag="found_using_silver"
type="int32"
name="FoundUsingSilver"
comment="单次普通找回消耗的银两数量"

[[variables]]
tag="found_silver2"
type="int32"
name="FoundSilver2"
comment="单次普通找回获得的银两数量"

[[variables]]
tag="found_gold2"
type="int32"
name="FoundGold2"
comment="单次普通找回获得的元宝数量"

[[variables]]
tag="found_bindgold2"
type="int32"
name="FoundBindgold2"
comment="单次普通找回获得的绑元数量"

[[variables]]
tag="found_exp2"
type="int32"
name="FoundExp2"
comment="单次普通找回获得的经验值"

[[variables]]
tag="found_exp_point2"
type="int32"
name="FoundExpPoint2"
comment="单次普通找回获得的经验点"

[[variables]]
tag="found_item_id2"
type="string"
name="FoundItemId2"
comment="单次普通找回获得的物品id"

[[variables]]
tag="found_item_amount2"
type="string"
name="FoundItemAmount2"
comment="单次普通找回获得的物品数量"

[[variables]]
tag="open_id"
type="int32"
name="OpenId"
comment="功能开启id"
