file="four_god_box_vo.go"
pkg="template"
class="FourGodBoxTemplateVO"
comment = "四神遗迹宝箱配置"
[[variables]]
name="Id"
type="int"
tag="id"
comment="id"

[[variables]]
name="NextId"
type="int32"
tag="next_id"
comment="下一个id"

[[variables]]
name="UseItemId"
type="int32"
tag="use_item_id"
comment="消耗物品id"

[[variables]]
name="UseItemCount"
type="int32"
tag="use_item_count"
comment="消耗的物品数量"

[[variables]]
name="Type"
type="int32"
tag="type"
comment="宝箱类型"


[[variables]]
name="BiologyId"
type="int32"
tag="biology_id"
comment="采集物id"

[[variables]]
name="KeyMin"
type="int32"
tag="key_min"
comment="消耗物品的最小数量"

[[variables]]
name="KeyMax"
type="int32"
tag="key_max"
comment="消耗物品的最大数量"

[[variables]]
name="AwardSilver"
type="int32"
tag="award_silver"
comment="奖励的银两"


[[variables]]
name="AwardGold"
type="int32"
tag="award_gold"
comment="奖励的元宝"

[[variables]]
name="AwardBindGold"
type="int32"
tag="award_bindgold"
comment="奖励的绑元"


[[variables]]
name="AwardExp"
type="int32"
tag="award_exp"
comment="奖励的经验"

[[variables]]
name="AwardExpPoint"
type="int32"
tag="award_exp_point"
comment="奖励的经验点"

[[variables]]
name="award_item_id"
type="int32"
tag="award_item_id"
comment="奖励的经验点"

[[variables]]
name="DropId"
type="string"
tag="drop_id"
comment="掉落id"



