file="four_god_vo.go"
pkg="template"
class="FourGodTemplateVO"
comment = "四神遗迹常量配置"
[[variables]]
name="Id"
type="int"
tag="id"
comment="id"


[[variables]]
name="KeyMax"
type="int32"
tag="key_max"
comment="四神遗迹钥匙保存的最大数量"

[[variables]]
name="RobotTime"
type="int32"
tag="robot_time"
comment="假人刷新时间(毫秒)"

[[variables]]
name="RobotNum"
type="int32"
tag="robot_num"
comment="假人属性系数(万分比)"

[[variables]]
name="RobotKeyMin"
type="int32"
tag="robot_key_min"
comment="假人身上钥匙数量区间最小值"


[[variables]]
name="RobotKeyMax"
type="int32"
tag="robot_key_max"
comment="假人身上钥匙数量区间最大值"

[[variables]]
name="SpecialTime"
type="int32"
tag="special_time"
comment="特殊怪刷新时间(毫秒)"

[[variables]]
name="SpecialProbabilityTime"
type="int32"
tag="special_probability_time"
comment="特殊怪持续刷新的时间(毫秒)"


[[variables]]
name="SpecialProbability"
type="int32"
tag="special_probability"
comment="特殊怪刷新概率(万分比)"

[[variables]]
name="SpecialNum"
type="int32"
tag="special_num"
comment="特殊怪的最大数量"


[[variables]]
name="ItemId"
type="int32"
tag="item_id"
comment="触发黑衣人BUFF的物品id"

[[variables]]
name="BlackerBuffId"
type="int32"
tag="blacker_buff_id"
comment="使用蒙面衣获得的BUFFID"

[[variables]]
name="BossTime"
type="int32"
tag="boss_time"
comment="进入活动后BOSS的刷新时间(毫秒)"

[[variables]]
name="BossId"
type="int32"
tag="boss_id"
comment="boss id"

[[variables]]
name="SpecialId"
type="int32"
tag="special_id"
comment="特殊怪 id"

[[variables]]
name="BoxId"
type="int32"
tag="box_id"
comment="宝箱 id"

[[variables]]
name="BlackerModelId"
type="int32"
tag="blacker_model_id"
comment="黑衣人模型id"

[[variables]]
name="MinStack"
type="int32"
tag="min_stack"
comment="击杀玩家掉落最小堆数"


[[variables]]
name="MaxStack"
type="int32"
tag="max_stack"
comment="击杀玩家掉落最大堆数"

[[variables]]
name="ExistTime"
type="int32"
tag="exist_time"
comment="掉落存活时间"

[[variables]]
name="ProtectedTime"
type="int32"
tag="protected_time"
comment="掉落保护时间"

[[variables]]
name="FailTime"
type="int32"
tag="fail_time"
comment="掉落物品失效时间"


[[variables]]
name="BoxTime"
type="int32"
tag="box_time"
comment="宝箱采集时间(毫秒)"


[[variables]]
name="GongGao"
type="string"
tag="gonggao"
comment="死神BOSS发送公告的血量百分比"















