file="fufei_vo.go"
pkg="template"
class="CostLevelTemplateVO"
comment = "消费等级模板配置"
[[variables]]
name="Id"
type="int"
tag="id"
comment="id"

[[variables]]
name="Level"
type="int32"
tag="level"
comment="消费等级"

[[variables]]
name="NextId"
type="int32"
tag="next_id"
comment="下一级"

[[variables]]
name="NeedValue"
type="int32"
tag="need_value"
comment="需要历史消费的元宝"

[[variables]]
name="MountMinCount"
type="int32"
tag="mount_min_count"
comment="坐骑最小次数系数"

[[variables]]
name="MountMaxCount"
type="int32"
tag="mount_max_count"
comment="坐骑最大次数系数"

[[variables]]
name="WingMinCount"
type="int32"
tag="wing_min_count"
comment="战翼最小次数系数"

[[variables]]
name="WingMaxCount"
type="int32"
tag="wing_max_count"
comment="战翼最大次数系数"

[[variables]]
name="AnqiMinCount"
type="int32"
tag="anqi_min_count"
comment="暗器最小次数系数"

[[variables]]
name="AnqiMaxCount"
type="int32"
tag="anqi_max_count"
comment="暗器最大次数系数"

[[variables]]
name="BodyShieldMinCount"
type="int32"
tag="body_shield_min_count"
comment="护体盾最小次数系数"

[[variables]]
name="BodyShieldMaxCount"
type="int32"
tag="body_shield_max_count"
comment="护体盾最大次数系数"

[[variables]]
name="FeatherMinCount"
type="int32"
tag="feather_min_count"
comment="护体仙羽最小次数系数"

[[variables]]
name="FeatherMaxCount"
type="int32"
tag="feather_max_count"
comment="护体仙羽最大次数系数"

[[variables]]
name="ShieldMinCount"
type="int32"
tag="shield_min_count"
comment="盾刺最小次数系数"

[[variables]]
name="ShieldMaxCount"
type="int32"
tag="shield_max_count"
comment="盾刺最大次数系数"

[[variables]]
name="FieldMinCount"
type="int32"
tag="field_min_count"
comment="领域最小次数系数"

[[variables]]
name="FieldMaxCount"
type="int32"
tag="field_max_count"
comment="领域最大次数系数"

[[variables]]
name="ShenfaMinCount"
type="int32"
tag="shenfa_min_count"
comment="身法最小次数系数"

[[variables]]
name="ShenfaMaxCount"
type="int32"
tag="shenfa_max_count"
comment="身法最大次数系数"

[[variables]]
name="MarryRingMinCount"
type="int32"
tag="marry_ring_min_count"
comment="婚戒最小次数系数"

[[variables]]
name="MarryRingMaxCount"
type="int32"
tag="marry_ring_max_count" 
comment="婚戒最大次数系数"

[[variables]]
name="DushiCount1Count"
type="int32"
tag="dushi_count1_count"
comment="赌石固定掉落包系数"

[[variables]]
name="DushiCount2Count"
type="int32"
tag="dushi_count2_count"
comment="赌石固定掉落包系数"

[[variables]]
name="DushiCount3Count"
type="int32"
tag="dushi_count3_count"
comment="赌石固定掉落包系数"

[[variables]]
name="QijvCount1Count"
type="int32"
tag="qijv_count1_count"
comment="棋局固定掉落包系数"

[[variables]]
name="QijvCount2Count"
type="int32"
tag="qijv_count2_count"
comment="棋局固定掉落包系数"

[[variables]]
name="QijvCount3Count"
type="int32"
tag="qijv_count3_count"
comment="棋局固定掉落包系数"

[[variables]]
name="QijvCount4Count"
type="int32"
tag="qijv_count4_count"
comment="棋局固定掉落包系数"

[[variables]]
name="QijvCount5Count"
type="int32"
tag="qijv_count5_count"
comment="棋局固定掉落包系数"

[[variables]]
name="QijvCount6Count"
type="int32"
tag="qijv_count6_count"
comment="棋局固定掉落包系数"

[[variables]]
name="QijvCount7Count"
type="int32"
tag="qijv_count7_count"
comment="棋局固定掉落包系数"

[[variables]]
name="QijvCount8Count"
type="int32"
tag="qijv_count8_count"
comment="棋局固定掉落包系数"

[[variables]]
name="WeaponUpstarMinCount"
type="int32"
tag="weapon_upstar_min_count"
comment="兵魂升星的最小次数系数"

[[variables]]
name="WeaponUpstarMaxCount"
type="int32"
tag="weapon_upstar_max_count"
comment="兵魂升星的最大次数系数"

[[variables]]
name="LuxianrenMinCount"
type="int32"
tag="luxianren_min_count"
comment="戮仙刃最小次数系数"

[[variables]]
name="LuxianrenMaxCount"
type="int32"
tag="luxianren_max_count"
comment="戮仙刃最大次数系数"


[[variables]]
name="FabaoMinCount"
type="int32"
tag="fabao_min_count"
comment="法宝的最小次数系数"


[[variables]]
name="FabaoMaxCount"
type="int32"
tag="fabao_max_count"
comment="法宝的最大次数系数"


[[variables]]
name="XianTiMinCount"
type="int32"
tag="xianti_min_count"
comment="仙体的最小次数系数"


[[variables]]
name="XianTiMaxCount"
type="int32"
tag="xianti_max_count"
comment="仙体的最大次数系数"

[[variables]]
name="DianXingMinCount"
type="int32"
tag="dianxing_min_count"
comment="点星的最小次数系数"

[[variables]]
name="DianXingMaxCount"
type="int32"
tag="dianxing_max_count"
comment="点星的最大次数系数"

[[variables]]
name="ShiHunFanMinCount"
type="int32"
tag="shihunfan_min_count"
comment="噬魂幡的最小次数系数"

[[variables]]
name="ShiHunFanMaxCount"
type="int32"
tag="shihunfan_max_count"
comment="噬魂幡的最大次数系数"

[[variables]]
name="TianmotiMinCount"
type="int32"
tag="tianmoti_min_count"
comment="点星的最小次数系数"

[[variables]]
name="TianmotiMaxCount"
type="int32"
tag="tianmoti_max_count"
comment="点星的最大次数系数"

[[variables]]
name="LingTongWeaponMinCount"
type="int32"
tag="lingtong_weapon_min_count"
comment="灵童武器最小次数系数灵兵"

[[variables]]
name="LingTongWeaponMaxCount"
type="int32"
tag="lingtong_weapon_max_count"
comment="灵童武器最大次数系数灵兵"


[[variables]]
name="LingTongMountMinCount"
type="int32"
tag="lingtong_mount_min_count"
comment="灵童坐骑最小次数系数灵骑"

[[variables]]
name="LingTongMountMaxCount"
type="int32"
tag="lingtong_mount_max_count"
comment="灵童坐骑最大次数系数灵骑"


[[variables]]
name="LingTongWingMinCount"
type="int32"
tag="lingtong_wing_min_count"
comment="灵童战翼最小次数系数灵翼"

[[variables]]
name="LingTongWingMaxCount"
type="int32"
tag="lingtong_wing_max_count"
comment="灵童战翼最大次数系数灵翼"


[[variables]]
name="LingTongShenFaMinCount"
type="int32"
tag="lingtong_shenfa_min_count"
comment="灵童身法最小次数系数灵身"

[[variables]]
name="LingTongShenFaMaxCount"
type="int32"
tag="lingtong_shenfa_max_count"
comment="灵童身法最大次数系数灵身"


[[variables]]
name="LingTongLingYuMinCount"
type="int32"
tag="lingtong_field_min_count"
comment="灵童领域最小次数系数灵域"

[[variables]]
name="LingTongLingYuMaxCount"
type="int32"
tag="lingtong_field_max_count"
comment="灵童领域最大次数系数灵域"

[[variables]]
name="LingTongFaBaoMinCount"
type="int32"
tag="lingtong_fabao_min_count"
comment="灵童法宝最小次数系数灵宝"

[[variables]]
name="LingTongFaBaoMaxCount"
type="int32"
tag="lingtong_fabao_max_count"
comment="灵童法宝最大次数系数灵宝"

[[variables]]
name="LingTongXianTiMinCount"
type="int32"
tag="lingtong_xianti_min_count"
comment="灵童仙体最小次数系数灵体"

[[variables]]
name="LingTongXianTiMaxCount"
type="int32"
tag="lingtong_xianti_max_count"
comment="灵童仙体最大次数系数灵体"

[[variables]]
name="EquipBaoKuCount1Count"
type="string"
tag="equip_baoku_count1_count"
comment="装备宝库固定掉落包系数"

[[variables]]
name="ShenQiMinCount"
type="int32"
tag="shenqi_min_count"
comment="神器的最小次数系数"

[[variables]]
name="ShenQiMaxCount"
type="int32"
tag="shenqi_max_count"
comment="神器的最大次数系数"

[[variables]]
name="MaterialBaoKuCount1Count"
type="string"
tag="cailiao_baoku_count1_count"
comment="材料宝库固定掉落包系数"

[[variables]]
name="BaoKuBagCount1Count"
type="string"
tag="baoku_bag_count1_count"
comment="宝库固定掉落包系数"
