file="fushi_level_vo.go"
pkg="template"
class="FuShiLevelTemplateVO"
comment="八卦符石等级配置"

[[variables]]
name="Id"
type="int"
tag="id"
comment="id"

[[variables]]
name="NextId"
type="int32"
tag="next_id"
comment="下一级id"

[[variables]]
name="Type"
type="int32"
tag="type"
comment="符石类型"

[[variables]]
name="SkillId"
type="int32"
tag="skill_id"
comment="对应开启的技能id"

[[variables]]
name="Level"
type="int32"
tag="level"
comment="符石等级"

[[variables]]
name="UpLevelItem"
type="string"
tag="uplevel_item"
comment="升级所需物品id"

[[variables]]
name="UpLevelItemCount"
type="string"
tag="uplevel_item_count"
comment="升级所需物品数量"

[[variables]]
name="UpLevelRate"
type="int32"
tag="uplevel_rate"
comment="升级概率"
