file="fushi_vo.go"
pkg="template"
class="FuShiTemplateVO"
comment="八卦符石配置"

[[variables]]
name="Id"
type="int"
tag="id"
comment="id"

[[variables]]
name="Type"
type="int32"
tag="type"
comment="符石类型"

[[variables]]
name="Name"
type="string"
tag="name"
comment="符石名称"

[[variables]]
name="NeedBaGuaMiJing"
type="int32"
tag="need_baguamijing"
comment="需要的八卦秘境通关层数"