

file="gambling_vo.go"
pkg="template"
class="GamblingTemplateVO"
comment = "赌石配置"
[[variables]]
name="Id"
type="int"
tag="id"
comment="id"

[[variables]]
name="Type"
type="int32"
tag="type"
comment="赌石类型"

[[variables]]
name="RewardPreview"
type="string"
tag="reward_preview"
comment="奖励预览"

[[variables]]
name="Revenue"
type="int32"
tag="revenue"
comment="收益(间隔时间)"

[[variables]]
name="NeedYinLiang"
type="int32"
tag="need_yinliang"
comment="单次所需银两"

[[variables]]
name="NeedGold"
type="int32"
tag="need_gold"
comment="单次所需元宝"

[[variables]]
name="NeedYuanShi"
type="int32"
tag="need_yuanshi"
comment="单次所需原石数量"

[[variables]]
name="NeedItem"
type="int32"
tag="need_item"
comment="所需物品ID"

[[variables]]
name="NeedItemNum"
type="int32"
tag="need_item_num"
comment="所需物品数量"

[[variables]]
name="IntervalNum1"
type="int32"
tag="interval_num_1"
comment="间隔几次走1的掉落包"

[[variables]]
name="DropId1"
type="int32"
tag="drop_id_1"
comment="掉落包1"

[[variables]]
name="IntervalNum2"
type="int32"
tag="interval_num_2"
comment="间隔几次走2的掉落包"

[[variables]]
name="DropId2"
type="int32"
tag="drop_id_2"
comment="掉落包2"

[[variables]]
name="IntervalNum3"
type="int32"
tag="interval_num_3"
comment="间隔几次走3的掉落包"

[[variables]]
name="DropId3"
type="int32"
tag="drop_id_3"
comment="掉落包3"


[[variables]]
name="FirstDrop"
type="int32"
tag="first_drop"
comment="首次掉落包"

