

file="gemstone_slot_vo.go"
pkg="template"
class="GemstoneSlotTemplateVO"
comment = "宝石格子配置"
[[variables]]
name="Id"
type="int"
tag="id"
comment="id"

[[variables]]
name="Position"
type="int32"
tag="position"
comment="位置"

[[variables]]
name="Order"
type="int32"
tag="order"
comment="槽位顺序"

[[variables]]
name="GemstoneType"
type="int32"
tag="gemstone_type"
comment="宝石类型"

[[variables]]
name="NeedLevel"
type="int32"
tag="need_;evel"
comment="需求等级"

[[variables]]
name="NeedLayer"
type="int32"
tag="need_layer"
comment="需求层数"

[[variables]]
name="NeedItemId"
type="string"
tag="need_item_id"
comment="消耗的物品id"

[[variables]]
name="NeedItemCount"
type="string"
tag="need_item_count"
comment="消耗的物品数量"
