file="godcasting_equip_vo.go"
pkg="template"
class="GodCastingEquipTemplateVO"
comment = "神铸装备配置"
[[variables]]
name="Id"
type="int"
tag="id"
comment="id"

[[variables]]
name="ItemId"
type="int32"
tag="item_id"
comment="物品Id"

[[variables]]
name="UseItemId"
type="string"
tag="use_item_id"
comment="可用来升级的物品"

[[variables]]
name="UseItemCount"
type="string"
tag="use_item_count"
comment="可用来升级的物品对应数量"

[[variables]]
name="UpdateWfb"
type="int32"
tag="update_wfb"
comment="神铸成功率万分比"

[[variables]]
name="TimesMin"
type="int32"
tag="times_min"
comment="神铸最小次数"

[[variables]]
name="TimesMax"
type="int32"
tag="times_max"
comment="神铸最大次数"