file="godcasting_forgesoul_level_vo.go"
pkg="template"
class="GodCastingForgeSoulLevelTemplateVO"
comment = "神铸锻魂升级配置"
[[variables]]
name="Id"
type="int"
tag="id"
comment="id"

[[variables]]
name="NextId"
type="int32"
tag="next_id"
comment="下一id"

[[variables]]
name="Level"
type="int32"
tag="level"
comment="等级"

[[variables]]
name="UseItemCount"
type="int32"
tag="use_item_count"
comment="锻魂消耗的物品数量"

[[variables]]
name="ChufaRate"
type="int32"
tag="chufa_rate"
comment="触发几率万分比"

[[variables]]
name="DikangRate"
type="int32"
tag="dikang_rate"
comment="抵抗几率万分比"

[[variables]]
name="UpdateWfb"
type="int32"
tag="update_wfb"
comment="升级几率万分比"

[[variables]]
name="TimesMin"
type="int32"
tag="times_min"
comment="最小次数"

[[variables]]
name="TimesMax"
type="int32"
tag="times_max"
comment="最大次数"

[[variables]]
name="AddPower"
type="int32"
tag="add_power"
comment="战力增加"
