file="godcasting_castingspirit_vo.go"
pkg="template"
class="GodCastingCastingSpiritTemplateVO"
comment = "神铸铸灵配置"
[[variables]]
name="Id"
type="int"
tag="id"
comment="id"

[[variables]]
name="SubType"
type="int32"
tag="sub_type"
comment="装备部位"

[[variables]]
name="ZhulingType"
type="int32"
tag="zhuling_type"
comment="铸灵类型"

[[variables]]
name="NeedShenzhuLevel"
type="int32"
tag="need_shenzhu_level"
comment="需要的神铸等级"

[[variables]]
name="UseItemId"
type="int32"
tag="use_item_id"
comment="铸灵消耗的物品ID"

[[variables]]
name="ZhulingLevelBegin"
type="int32"
tag="zhuling_level_begin"
comment="关联的铸灵等级表起始ID"