file="godcasting_forgesoul_vo.go"
pkg="template"
class="GodCastingForgeSoulTemplateVO"
comment = "神铸锻魂配置"
[[variables]]
name="Id"
type="int"
tag="id"
comment="id"

[[variables]]
name="Type"
type="int32"
tag="type"
comment="锻魂类型"

[[variables]]
name="SubType"
type="int32"
tag="sub_type"
comment="装备部位"

[[variables]]
name="LevelBeginId"
type="int32"
tag="level_begin_id"
comment="关联的锻魂等级表起始ID"

[[variables]]
name="UseItemId"
type="int32"
tag="use_item_id"
comment="锻魂消耗的物品ID"

[[variables]]
name="TeshuSkillId"
type="int32"
tag="teshu_skill_id"
comment="关联特殊技能表ID"