

file="goldequip_fujia_attr_vo.go"
pkg="template"
class="GoldEquipFuJiaAttrTemplateVO"
comment = "元神金装附加属性池配置"
[[variables]]
name="Id"
type="int"
tag="id"
comment="id"

[[variables]]
name="NextId"
type="int"
tag="next_id"
comment="下一个id"

[[variables]]
name="Rate"
type="int32"
tag="rate"
comment="权重"

[[variables]]
name="Hp"
type="int32"
tag="hp"
comment="生命"

[[variables]]
name="Attack"
type="int32"
tag="attack"
comment="攻击"

[[variables]]
name="Defence"
type="int32"
tag="defence"
comment="防御"

[[variables]]
name="EquipPercent"
type="int32"
tag="equip_percent"
comment="加成该装备基础属性百分比"

[[variables]]
name="Huixie"
type="int32"
tag="15s_huixie"
comment="每15秒回复生命的值"

[[variables]]
name="BossZengshang"
type="int32"
tag="boss_zengshang"
comment="对BOSS类型（策划类型）增伤"

[[variables]]
name="BossJianshang"
type="int32"
tag="boss_jianshang"
comment="对BOSS类型（策划类型）减伤"

[[variables]]
name="KillMonsterBuff"
type="int32"
tag="kill_monster_buff"
comment="击杀怪物后增加的buffId"
