

file="gold_equip_jicheng_vo.go"
pkg="template"
class="GoldEquipJiChengTemplateVO"
comment = "元神金装继承配置"
[[variables]]
name="Id"
type="int"
tag="id"
comment="id"

[[variables]]
name="Level"
type="int32" 
tag="level"
comment="强化等级"

[[variables]]
name="NeedItemId"
type="int32"
tag="need_item_id"
comment="物品id"

[[variables]]
name="NeedItemCount"
type="int32"
tag="need_item_count"
comment="物品数量"
