

file="gold_equip_chongzhu_vo.go"
pkg="template"
class="GoldEquipChongzhuTemplateVO"
comment = "元神金装重铸配置"
[[variables]]
name="Id"
type="int"
tag="id"
comment="id"

[[variables]]
name="Level"
type="int32"
tag="level"
comment="人物转生"

[[variables]]
name="Quality"
type="int32"
tag="quality"
comment="装备品质"

[[variables]]
name="Profession"
type="int32"
tag="profession"
comment="装备职业"

[[variables]]
name="Gender"
type="int32"
tag="gender"
comment="性别"

[[variables]]
name="DropId"
type="int32"
tag="drop_id"
comment="掉落id"
