

file="gold_equip_strengthen_buwei_vo.go"
pkg="template"
class="GoldEquipStrengthenBuWeiTemplateVO"
comment = "元神金装强化部位配置"
[[variables]]
name="Id"
type="int"
tag="id"
comment="id"

[[variables]]
name="NextId"
type="int32"
tag="next_id"
comment="下一个id"

[[variables]]
name="SuccessRate"
type="int32"
tag="success_rate"
comment="成功率"

[[variables]]
name="Level"
type="int32"
tag="level"
comment="强化等级"

[[variables]]
name="Position"
type="int32"
tag="position"
comment="部位"

[[variables]]
name="NeedItem"
type="string"
tag="need_item"
comment="使用物品id"

[[variables]]
name="NeedCount"
type="string"
tag="need_count"
comment="使用物品数量"

[[variables]]
name="FailReturnRate"
type="int32"
tag="fail_return_rate"
comment="失败率"

[[variables]]
name="FailReturnLevel"
type="int32"
tag="fail_return_level"
comment="失败回退等级"

[[variables]]
name="ProtectItemId"
type="int32"
tag="protect_item_id"
comment="防爆物品id"

[[variables]]
name="ProtectItemCount"
type="int32"
tag="protect_item_count"
comment="防爆物品数量"

[[variables]]
name="AddHp"
type="int32"
tag="add_hp"
comment="生命"

[[variables]]
name="AddAttack"
type="int32"
tag="add_attack"
comment="攻击"

[[variables]]
name="AddDef"
type="int32"
tag="add_def"
comment="防御"
