

file="gold_equip_suit_group_vo.go"
pkg="template"
class="GoldEquipSuitGroupTemplateVO"
comment = "元神金装套装配置"
[[variables]]
name="Id"
type="int"
tag="id"
comment="id"

[[variables]]
name="Name"
type="string"
tag="name"
comment="套装名称"

[[variables]]
name="MaxNum"
type="int32"
tag="max_num"
comment="套装最大数量"

[[variables]]
name="SuitId1"
type="int32"
tag="suit_id1"
comment="套装效果一"

[[variables]]
name="SuitId2"
type="int32"
tag="suit_id2"
comment="套装效果二"

[[variables]]
name="SuitId3"
type="int32"
tag="suit_id3"
comment="套装效果三"

[[variables]]
name="SuitId4"
type="int32"
tag="suit_id4"
comment="套装效果四"

[[variables]]
name="Pos1Name"
type="string"
tag="pos1_name"
comment="套装部位一"

[[variables]]
name="Pos1Id"
type="string"
tag="pos1_id"
comment="套装部位装备id"

[[variables]]
name="Pos2Name"
type="string"
tag="pos2_name"
comment="套装部位二"

[[variables]]
name="Pos2Id"
type="string"
tag="pos2_id"
comment="套装部位装备id"

[[variables]]
name="Pos3Name"
type="string"
tag="pos3_name"
comment="套装部位三"

[[variables]]
name="Pos3Id"
type="string"
tag="pos3_id"
comment="套装部位装备id"

[[variables]]
name="Pos4Name"
type="string"
tag="pos4_name"
comment="套装部位四"

[[variables]]
name="Pos4Id"
type="string"
tag="pos4_id"
comment="套装部位装备id"

[[variables]]
name="Pos5Name"
type="string"
tag="pos5_name"
comment="套装部位五"

[[variables]]
name="Pos5Id"
type="string"
tag="pos5_id"
comment="套装部位装备id"

[[variables]]
name="Pos6Name"
type="string"
tag="pos6_name"
comment="套装部位六"

[[variables]]
name="Pos6Id"
type="string"
tag="pos6_id"
comment="套装部位装备id"

[[variables]]
name="Pos7Name"
type="string"
tag="pos7_name"
comment="套装部位七"

[[variables]]
name="Pos7Id"
type="string"
tag="pos7_id"
comment="套装部位装备id"

[[variables]]
name="Pos8Name"
type="string"
tag="pos7_name"
comment="套装部位八"

[[variables]]
name="Pos8Id"
type="string"
tag="pos7_id"
comment="套装部位装备id"
