

file="goldequip_fujia_vo.go"
pkg="template"
class="GoldEquipFuJiaTemplateVO"
comment = "元神金装附加属性配置"
[[variables]]
name="Id"
type="int"
tag="id"
comment="id"

[[variables]]
name="Rate0"
type="int32"
tag="rate_0"
comment="0条属性权重"

[[variables]]
name="Rate1"
type="int32"
tag="rate_1"
comment="1条属性权重"

[[variables]]
name="Rate2"
type="int32"
tag="rate_2"
comment="2条属性权重"

[[variables]]
name="Rate3"
type="int32"
tag="rate_3"
comment="3条属性权重"

[[variables]]
name="Rate4"
type="int32"
tag="rate_4"
comment="4条属性权重"

[[variables]]
name="Rate5"
type="int32"
tag="rate_5"
comment="5条属性权重"

[[variables]]
name="Rate6"
type="int32"
tag="rate_6"
comment="6条属性权重"

[[variables]]
name="Pool1"
type="int32"
tag="pool_1"
comment="第1条属性随机池"

[[variables]]
name="Pool2"
type="int32"
tag="pool_2"
comment="第2条属性随机池"

[[variables]]
name="Pool3"
type="int32"
tag="pool_3"
comment="第3条属性随机池"

[[variables]]
name="Pool4"
type="int32"
tag="pool_4"
comment="第4条属性随机池"

[[variables]]
name="Pool5"
type="int32"
tag="pool_5"
comment="第5条属性随机池"

[[variables]]
name="Pool6"
type="int32"
tag="pool_6"
comment="第6条属性随机池"
