

file="gold_equip_vo.go"
pkg="template"
class="GoldEquipTemplateVO"
comment = "元神金装配置"
[[variables]]
name="Id"
type="int"
tag="id"
comment="id"

[[variables]]
name="SuitGroup"
type="int32"
tag="suit_group"
comment="套装id"

[[variables]]
name="GoldequipStrenId"
type="int32"
tag="goldequip_stren_id"
comment="强化id"

[[variables]]
name="Hp"
type="int32"
tag="hp"
comment="生命"

[[variables]]
name="Attack"
type="int32"
tag="attack"
comment="攻击"

[[variables]]
name="Defence"
type="int32"
tag="defence"
comment="防御"

[[variables]]
name="HpPercent"
type="int32"
tag="hp_percent"
comment="生命加成万分比"

[[variables]]
name="AttPercent"
type="int32"
tag="att_percent"
comment="攻击加成万分比"

[[variables]]
name="DefPercent"
type="int32"
tag="def_percent"
comment="防御加成万分比"

[[variables]]
name="GoldeuipUpstarId"
type="int32"
tag="goldeuip_upstar_id"
comment="新版强化起始id"

[[variables]]
name="GoldeuipOpenlightId"
type="int32"
tag="goldeuip_openlight_id"
comment="开光起始id"

[[variables]]
name="FujiaId"
type="int32"
tag="fujia_id"
comment="附加属性id"


[[variables]]
name="NeedStrengthen1"
type="int32"
tag="need_strengthen_1"
comment="激活第1条属性所需强化等级"

[[variables]]
name="NeedStrengthen2"
type="int32"
tag="need_strengthen_2"
comment="激活第2条属性所需强化等级"

[[variables]]
name="NeedStrengthen3"
type="int32"
tag="need_strengthen_3"
comment="激活第3条属性所需强化等级"

[[variables]]
name="NeedStrengthen4"
type="int32"
tag="need_strengthen_4"
comment="激活第4条属性所需强化等级"

[[variables]]
name="NeedStrengthen5"
type="int32"
tag="need_strengthen_5"
comment="激活第5条属性所需强化等级"

[[variables]]
name="NeedStrengthen6"
type="int32"
tag="need_strengthen_6"
comment="激活第6条属性所需强化等级"

[[variables]]
name="TunshiExp"
type="int32"
tag="tushi_exp"
comment="吞噬经验"

[[variables]]
name="TunshiDrop"
type="int"
tag="tunshi_drop"
comment="掉落无双神器相关物品"

[[variables]]
name="ShenzhuequipId"
type="int"
tag="shenzhuequip_id"
comment="神铸关联序列ID"

[[variables]]
name="ShenzhuequipLevel"
type="int32"
tag="shenzhuequip_level"
comment="神铸装备等级"

[[variables]]
name="DuanhunLevelMax"
type="int32"
tag="duanhun_level_max"
comment="神铸锻魂等级最高级"