

file="gold_equip_strengthen_rate_vo.go"
pkg="template"
class="GoldEquipStrengthenRateTemplateVO"
comment = "元神金装强化概率配置"
[[variables]]
name="Id"
type="int"
tag="id"
comment="id"

[[variables]]
name="GiveRate1"
type="int32"
tag="give_rate1"
comment="0强化到1的概念"

[[variables]]
name="GiveRate2"
type="int32"
tag="give_rate2"
comment="1强化到2的概念"

[[variables]]
name="GiveRate3"
type="int32"
tag="give_rate3"
comment="2强化到3的概念"

[[variables]]
name="GiveRate4"
type="int32"
tag="give_rate4"
comment="3强化到4的概念"

[[variables]]
name="GiveRate5"
type="int32"
tag="give_rate5"
comment="4强化到5的概念"

[[variables]]
name="GiveRate6"
type="int32"
tag="give_rate6"
comment="5强化到6的概念"

[[variables]]
name="GiveRate7"
type="int32"
tag="give_rate7"
comment="6强化到7的概念"

[[variables]]
name="GiveRate8"
type="int32"
tag="give_rate8"
comment="7强化到8的概念"

[[variables]]
name="GiveRate9"
type="int32"
tag="give_rate9"
comment="8强化到9的概念"

[[variables]]
name="GiveRate10"
type="int32"
tag="give_rate10"
comment="9强化到10的概念"
