

file="gold_equip_openlight_vo.go"
pkg="template"
class="GoldEquipOpenLightTemplateVO"
comment = "元神金装开光配置"
[[variables]]
name="Id"
type="int"
tag="id"
comment="id"

[[variables]]
name="NextId"
type="int32"
tag="next_id"
comment="下一个id"

[[variables]]
name="Times"
type="int32"
tag="times"
comment="开光次数"

[[variables]]
name="SuccessRate"
type="int32"
tag="success_rate"
comment="成功率"

[[variables]]
name="UseItem"
type="string"
tag="use_item"
comment="使用物品id"

[[variables]]
name="UseCount"
type="string"
tag="use_count"
comment="使用物品数量"

[[variables]]
name="TimesMin"
type="int32"
tag="times_min"
comment="最小次数"

[[variables]]
name="TimesMax"
type="int32"
tag="times_max"
comment="最大次数"

[[variables]]
name="AttrPercent"
type="int32"
tag="attr_percent"
comment="属性加成"

[[variables]]
name="MeltingReturnId"
type="string"
tag="melting_return_id"
comment="返还物品Id"

[[variables]]
name="MeltingReturnCount"
type="string"
tag="melting_return_count"
comment="返还物品数量"
