

file="gold_equip_strengthen_pool_vo.go"
pkg="template"
class="GoldEquipStrengthenPoolTemplateVO"
comment = "元神金装掉落等级配置"
[[variables]]
name="Id"
type="int"
tag="id"
comment="id"

[[variables]]
name="NextId"
type="int"
tag="next_id"
comment="下一级id"

[[variables]]
name="Level"
type="int32"
tag="level"
comment="等级"

[[variables]]
name="Rate"
type="int32"
tag="rate"
comment="权重"
