

file="gold_equip_tunshi_vo.go"
pkg="template"
class="GoldYuanTemplateVO"
comment = "元神等级配置"
[[variables]]
name="Id"
type="int"
tag="id"
comment="id"

[[variables]]
name="Level"
type="int32"
tag="level"
comment="元神等级"

[[variables]]
name="NextId"
type="int32"
tag="next_id"
comment="下级id"

[[variables]]
name="Exp"
type="int32"
tag="exp"
comment="经验"

[[variables]]
name="AddHp"
type="int32"
tag="hp"
comment="生命"

[[variables]]
name="AddAttack"
type="int32"
tag="attack"
comment="攻击"

[[variables]]
name="AddDefect" 
type="int32"
tag="defence"
comment="防御"
