

file="gongcheng_constant_vo.go"
pkg="template"
class="GongChengConstantTemplateVO"
comment = "神兽攻城配置"
[[variables]]
name="Id"
type="int"
tag="id"
comment="id"

[[variables]]
name="MapId1"
type="int32"
tag="map_id1"
comment="麒麟地图"

[[variables]]
name="MapId2"
type="int32"
tag="map_id2"
comment="火凤地图"

[[variables]]
name="MapId3"
type="int32"
tag="map_id3"
comment="毒龙地图"

[[variables]]
name="BossId1"
type="int32"
tag="boss_id1"
comment="麒麟id"

[[variables]]
name="BossId2"
type="int32"
tag="boss_id2"
comment="火凤id"

[[variables]]
name="BossId3"
type="int32"
tag="boss_id3"
comment="毒龙id"

[[variables]]
name="BossTime"
type="int32"
tag="boss_time"
comment="BOSS刷新时间"

[[variables]]
name="PlayerLimitCount"
type="int32"
tag="player_limit_count"
comment="活动人数上限"


[[variables]]
name="SystemName1"
type="string"
tag="system_name1"
comment="麒麟来袭对应的系统"

[[variables]]
name="SystemName2"
type="string"
tag="system_name2"
comment="火凤来袭对应的系统"

[[variables]]
name="SystemName3"
type="string"
tag="system_name3"
comment="毒龙来袭对应的系统"


[[variables]]
name="YulanId"
type="int32"
tag="yulan_id"
comment="显示固定最高级掉宝符ID"

[[variables]]
name="MapId4"
type="int32"
tag="map_id4"
comment="金银秘窟地图"


[[variables]]
name="MoneyLimitCount"
type="int32"
tag="money_limit_count"
comment="金银秘窟活动人数上限"

[[variables]]
name="CaiJiCountLimit"
type="int32"
tag="caiji_count_limit"
comment="采集次数"


[[variables]]
name="CaijiBiologyId"
type="string"
tag="caiji_biology_id"
comment="特殊采集生物id"
