

file="gongcheng_pos_vo.go"
pkg="template"
class="GongChengPosTemplateVO"
comment = "神兽攻城出生配置"
[[variables]]
name="Id"
type="int"
tag="id"
comment="id"

[[variables]]
name="Type"
type="int32"
tag="type"
comment="坐标点类型"

[[variables]]
name="Pos"
type="int32"
tag="pos"
comment="坐标标识"

[[variables]]
name="ActivityType"
type="int32"
tag="activity_type"
comment="活动类型"

[[variables]]
name="MapId"
type="int32"
tag="map_id"
comment="地图id"

[[variables]]
name="PosX"
type="float64"
tag="pos_x"
comment="坐标x"

[[variables]]
name="PosY"
type="float64"
tag="pos_y"
comment="坐标y"

[[variables]]
name="PosZ"
type="float64"
tag="pos_z"
comment="坐标z"

