file="guide_replica_vo.go"
pkg="template"
class="GuideReplicaTemplateVO"
comment = "引导副本配置"
[[variables]]
name="Id"
type="int"
tag="id"
comment="id"

[[variables]]
name="Type"
type="int32"
tag="type"
comment="引导类型"

[[variables]]
name="MapId"
type="int32"
tag="map_id"
comment="地图id"

[[variables]]
name="BiologyId"
type="int32"
tag="biology_id"
comment="生物id"

[[variables]]
name="SubGuideId"
type="int32"
tag="sub_id"
comment="扩展关联id"