file="guide_replica_catdog_vo.go"
pkg="template"
class="GuideReplicaCatDogTemplateVO"
comment = "猫狗引导副本配置"
[[variables]]
name="Id"
type="int"
tag="id"
comment="id"

[[variables]]
name="CatBiologyId"
type="int32"
tag="biology_id"
comment="猫生物id"

[[variables]]
name="DogBiologyId"
type="int32"
tag="biology_id2"
comment="狗生物id"

[[variables]]
name="CatDropId"
type="string"
tag="drop_id"
comment="猫奖励掉落"

[[variables]]
name="DogDropId"
type="string"
tag="drop_id2"
comment="狗奖励掉落"

[[variables]]
name="DefaultDropId"
type="string"
tag="drop_id3"
comment="默认奖励掉落"
 