file="guide_replica_rescure_vo.go"
pkg="template"
class="GuideReplicaRescureTemplateVO"
comment = "救援引导副本配置"
[[variables]]
name="Id"
type="int"
tag="id"
comment="id"

[[variables]]
name="RescureBiologyId"
type="int32"
tag="biology_id"
comment="小医仙生物id"

[[variables]]
name="CollectBiologyId"
type="int32"
tag="biology_id2"
comment="采集物生物id"

[[variables]]
name="DropId"
type="string"
tag="drop_id"
comment="奖励掉落"

[[variables]]
name="BuffId" 
type="int32"
tag="buff_id"
comment="采集buffId"

 