file="haoyou_tianjia_vo.go"
pkg="template"
class="FriendAddTemplateVO"
comment = "好友添加模板配置"
[[variables]]
name="Id"
type="int"
tag="id"
comment="id"

[[variables]]
name="Num"
type="int32"
tag="num"
comment="好友数量"

[[variables]]
name="RewardSilver"
type="int32"
tag="reward_silver"
comment="奖励银两数量"

[[variables]]
name="RewardItemId"
type="string"
tag="reward_item_id"
comment="奖励物品id"

[[variables]]
name="RewardItemCount"
type="string"
tag="reward_item_count"
comment="奖励物品数量"

[[variables]]
name="RewardExp"
type="int32"
tag="reward_exp"
comment="奖励经验"

[[variables]]
name="RewardExpPoint"
type="int32"
tag="reward_exp_point"
comment="奖励经验点"

