file="haoyou_constant_vo.go"
pkg="template"
class="NoticeConstantTemplateVO"
comment = "推送常量模板配置"
[[variables]]
name="Id"
type="int"
tag="id"
comment="id"

[[variables]]
name="FriendTime"
type="int64"
tag="friend_time"
comment="好友信息弹窗CD"

[[variables]]
name="ChouRenTime"
type="int64"
tag="chouren_time"
comment="仇人信息弹窗CD"

[[variables]]
name="ChouRenSunShiSilver"
type="int32"
tag="chouren_sunshi_silver"
comment="被狗咬损失银两"

[[variables]]
name="BaoHuFei"
type="int32"
tag="baohufei"
comment="购买防狗所需元宝"

[[variables]]
name="BaoHuTime"
type="int32"
tag="baohu_time"
comment="防狗持续时间"

[[variables]]
name="TianjiaJiarenTime"
type="int32"
tag="tianjia_jiaren_time"
comment="虚假好友间隔"

[[variables]]
name="SongliTongyi"
type="string"
tag="songli_tongyi"
comment="同意赠送文本"

[[variables]]
name="SongliJujue"
type="string"
tag="songli_jujue"
comment="拒绝赠送文本"

[[variables]]
name="ShouliTongyi"
type="string"
tag="shouli_tongyi"
comment="索取成功文本"

[[variables]]
name="ShouliJujue"
type="string"
tag="shouli_jujue"
comment="索取失败文本"


[[variables]]
name="ShouliLimitCount"
type="int32"
tag="shouli_limit_count"
comment="被砸蛋收花的次数"

