file="haoyou_tuisong_vo.go"
pkg="template"
class="FriendNoticeTemplateVO"
comment = "好友推送模板配置"
[[variables]]
name="Id"
type="int"
tag="id"
comment="id"

[[variables]]
name="Type"
type="int32"
tag="type"
comment="推送类型"

[[variables]]
name="TiaoJian"
type="int32"
tag="tiaojian"
comment="推送条件"

[[variables]]
name="JiDanRewardExp"
type="int32"
tag="jidan_reward_exp"
comment="反馈奖励1"

[[variables]]
name="XianHuaRewardExp"
type="int32"
tag="xianhua_reward_exp"
comment="反馈奖励2"

[[variables]]
name="JiDanRewardExpPoint"
type="int32"
tag="jidan_reward_exp_point"
comment="反馈奖励1经验点"

[[variables]]
name="XianHuaRewardExpPoint"
type="int32"
tag="xianhua_reward_exp_point"
comment="反馈奖励2经验点"

[[variables]]
name="ZhuheItem"
type="string"
tag="zhuhe_item"
comment="砸鸡蛋或送鲜花的玩家收到的物品"

[[variables]]
name="ZhuheItemCount"
type="string"
tag="zhuhe_item_count"
comment="砸鸡蛋或送鲜花的玩家收到的物品数量"

