file="hongbao_vo.go"
pkg="template"
class="HongBaoTemplateVO"
comment = "红包配置"
[[variables]]
name="Id"
type="int"
tag="id"
comment="id"


[[variables]]
name="Typ"
type="int32"
tag="type"
comment="红包类型"

[[variables]]
name="NeedVipLevel"
type="int32"
tag="need_vip_level"
comment="领取红包需要的VIP最低等级与need_zhuanshu关系为或"

[[variables]]
name="NeedZhuanShu"
type="int32"
tag="need_zhuanshu"
comment="领取红包需要的转数与need_vip_level关系为或"

[[variables]]
name="GeneralRew"
type="int32"
tag="general_rew"
comment="奖励总量"

[[variables]]
name="GoodProportionMax"
type="int32"
tag="good_proportion_max"
comment="最佳手气最大值"

[[variables]]
name="GoodProportionMin"
type="int32"
tag="good_proportion_min"
comment="最佳手气最小值"

[[variables]]
name="ProportionMin"
type="int32"
tag="proportion_min"
comment="普通手气保底值"

[[variables]]
name="ItemId"
type="int32"
tag="item_id"
comment="消耗的物品id"

[[variables]]
name="CountMin"
type="int32"
tag="hb_count_min"
comment="最小领取人数"

[[variables]]
name="CountMax"
type="int32"
tag="hb_count_max"
comment="最大领取人数"