file="huoyue_box_vo.go"
pkg="template"
class="HuoYueBoxTemplateVO"
comment = "活跃度宝箱配置"
[[variables]]
name="Id"
type="int"
tag="id"
comment="id"

[[variables]]
name="NextId"
type="int32"
tag="next_id"
comment="下一星级id"

[[variables]]
name="NeedStar"
type="int32"
tag="need_star"
comment="领取奖励所需要的星级"

[[variables]]
name="AwardSilver"
type="int32"
tag="award_silver"
comment="获得的银两"


[[variables]]
name="AwardGold"
type="int32"
tag="award_gold"
comment="获取的元宝"


[[variables]]
name="AwardBindGold"
type="int32"
tag="award_bindgold"
comment="获取的绑元"

[[variables]]
name="AwardItemId"
type="string"
tag="award_item_id"
comment="获得的物品"


[[variables]]
name="AwardItemIdCount"
type="string"
tag="award_item_id_count"
comment="获得的物品数量"

