file="hunt_times_vo.go"
pkg="template"
class="HuntTimesTemplateVO"
comment = "寻宝次数配置"
[[variables]]
name="Id"
type="int"
tag="id"
comment="id"

[[variables]]
name="NextId"
type="int32"
tag="next_id"
comment="下一级id"

[[variables]]
name="Times"
type="int32"
tag="times"
comment="寻宝次数"

[[variables]]
name="JianGeTime"
type="int64"
tag="jiange_time"
comment="间隔时间"
