file="hunt_vo.go"
pkg="template"
class="HuntTemplateVO"
comment = "寻宝配置"
[[variables]]
name="Id"
type="int"
tag="id"
comment="id"

[[variables]]
name="Type"
type="int32"
tag="type"
comment="寻宝类型"

[[variables]]
name="DropId"
type="int32"
tag="drop_id"
comment="掉落包id"


[[variables]]
name="MustGet"
type="string"
tag="must_get1"
comment="一定次数必定获取的掉落包"

[[variables]]
name="MustAmount"
type="string"
tag="must_amount1"
comment="寻宝后台次数"

[[variables]]
name="SilverUse"
type="int32"
tag="silver_use"
comment="银两消耗"

[[variables]]
name="GoldUse"
type="int32"
tag="gold_use"
comment="元宝消耗"

[[variables]]
name="BindGoldUse"
type="int32"
tag="bindgold_use"
comment="绑元消耗"

[[variables]]
name="UseItemId"
type="int32"
tag="use_item_id"
comment="消耗物品id"

[[variables]]
name="UseItemCount"
type="int32"
tag="use_item_count"
comment="消耗物品数量"
 