

file="huoyue_level_vo.go"
pkg="template"
class="HuoYueLevelTemplateVO"
comment = "活跃度等级奖励配置"
[[variables]]
name="Id"
type="int"
tag="id"
comment="id"


[[variables]]
name="QuestId"
type="int32"
tag="quest_id"
comment="关联任务表的ID"

[[variables]]
name="LevelMin"
type="int32"
tag="level_min"
comment="最小等级"

[[variables]]
name="LevelMax"
type="int32"
tag="level_max"
comment="最大等级"

[[variables]]
name="HuoYue"
type="int32"
tag="huoyue"
comment="完成任务后增加的活跃值"

[[variables]]
name="XueLian"
type="int32"
tag="xuelian"
comment="完成任务后增加的血炼值"
