

file="huoyue_vo.go"
pkg="template"
class="HuoYueTemplateVO"
comment = "活跃度配置"
[[variables]]
name="Id"
type="int"
tag="id"
comment="id"

[[variables]]
name="ModuleOpenedId"
type="int32"
tag="module_opened_id"
comment="关联功能开启"


[[variables]]
name="RewardCountLimit"
type="int32"
tag="reward_count_limit"
comment="完成次数上限"

[[variables]]
name="Remarks"
type="string"
tag="remarks"
comment="备注"

[[variables]]
name="pos"
type="int32"
tag="pos"
comment="任务前端排列顺序"
