

file="item_vo.go"
pkg="template"
class="ItemTemplateVO"
comment = "物品配置"
[[variables]]
name="Id"
type="int"
tag="id"
comment="id"

[[variables]]
name="Name"
type="string"
tag="name"
comment="名字"

[[variables]]
name="Type"
type="int32"
tag="type"
comment="类型"

[[variables]]
name="SubType"
type="int32"
tag="sub_type"
comment="子类型"

[[variables]]
name="BagType"
type="int32"
tag="bag_type"
comment="背包类型"

[[variables]]
name="QuestFlag"
type="int32"
tag="quest_flag"
comment="任务物品标记"

[[variables]]
name="Storage"
type="int32"
tag="storage"
comment="是否能够放入仓库"

[[variables]]
name="LiveTime"
type="int32"
tag="live_time"
comment="掉落时效"

[[variables]]
name="UseFlag"
type="int32"
tag="use_flag"
comment="使用组合字段"

[[variables]]
name="BindType"
type="int32"
tag="bind_type"
comment="绑定类型"

[[variables]]
name="CdGroup"
type="int32"
tag="cd_group"
comment="冷却类型"

[[variables]]
name="CdTime"
type="int32"
tag="cd_time"
comment="冷却时间"


[[variables]]
name="BuySilver"
type="int32"
tag="buy_silver"
comment="购买银两"

[[variables]]
name="BuyGold"
type="int32"
tag="buy_gold"
comment="购买元宝"

[[variables]]
name="BuyBindgold"
type="int32"
tag="buy_bindgold"
comment="购买元宝"

[[variables]]
name="SaleRate"
type="int32"
tag="sale_rate"
comment="销售比例"

[[variables]]
name="MaxOverlap"
type="int32"
tag="max_overlap"
comment="最大叠加上限"

[[variables]]
name="ShengXiaoTime"
type="string"
tag="shengxiao_time"
comment="物品生效时间"


[[variables]]
name="LimitTimeType"
type="int32"
tag="limit_time_type"
comment="物品时效类型"

[[variables]]
name="LimitTime"
type="string"
tag="limit_time"
comment="物品时效"

[[variables]]
name="NeedProfession"
type="int32"
tag="need_profession"
comment="职业需求"


[[variables]]
name="NeedGender"
type="int32"
tag="need_gender"
comment="性别需求"

[[variables]]
name="NeedZhuanShu"
type="int32"
tag="need_zhuanshu"
comment="转生需要"


[[variables]]
name="NeedLevel"
type="int32"
tag="need_level"
comment="等级需求"

[[variables]]
name="TypeFlag1"
type="int32"
tag="type_flag1"
comment="相关参数1"

[[variables]]
name="TypeFlag2"
type="int32"
tag="type_flag2"
comment="相关参数2"

[[variables]]
name="TypeFlag3"
type="int32"
tag="type_flag3"
comment="相关参数3"

[[variables]]
name="TypeFlag4"
type="int32"
tag="type_flag4"
comment="相关参数4"

[[variables]]
name="TypeFlag5"
type="int32"
tag="type_flag5"
comment="相关参数5"

[[variables]]
name="BoyModel"
type="int32"
tag="boy_model"
comment="装备模型"

[[variables]]
name="GirlModel"
type="int32"
tag="girl_model"
comment="装备模型"

[[variables]]
name="Quality"
type="int32"
tag="quality"
comment="品质"

[[variables]]
name="LimitTimeDay"
type="int32"
tag="limit_time_day"
comment="每日限制次数"


[[variables]]
name="LimitTimeAll"
type="int32"
tag="limit_time_all"
comment="总限制次数"


[[variables]]
name="IconItem"
type="int32"
tag="icon_item"
comment="物品图标"

[[variables]]
name="IconDrop"
type="int32"
tag="icon_drop"
comment="掉落图标"

[[variables]]
name="UseBatched"
type="int32"
tag="use_batched"
comment="批量使用"

[[variables]]
name="Classify"
type="int32"
tag="classify"
comment="分类"


[[variables]]
name="IsPopup"
type="int32"
tag="is_popup"
comment="是否提示使用"

[[variables]]
name="Tag"
type="int32"
tag="tag"
comment="标签"

[[variables]]
name="UnionGet"
type="int32"
tag="union_get"
comment="将物品放入仓库获得的贡献值"

[[variables]]
name="UnionUse"
type="int32"
tag="union_use"
comment="将物品取出仓库消耗的贡献值"

[[variables]]
name="RankGroup"
type="string"
tag="rank_group"
comment="关联运营活动排行榜id"

[[variables]]
name="MarketId"
type="int32"
tag="market_id"
comment="交易表id"

[[variables]]
name="MarketMinPrice"
type="int32"
tag="market_min_price"
comment="最小交易价值"

[[variables]]
name="HuigouPrice"
type="int32"
tag="huigou_price"
comment="回购价格"

[[variables]]
name="ChaiJieItemId"
type="string" 
tag="chaijie_item_id"
comment="拆解获得物品id" 
 
[[variables]]
name="ChaiJieItemCount"
type="string"
tag="chaijie_item_count"
comment="拆解获得数量"


