file="jieyi_token_vo.go"
pkg="template"
class="JieYiTokenTemplateVO"
comment = "结义道具配置"
[[variables]]
name="Id"
type="int"
tag="id"
comment="id"

[[variables]]
name="Type"
type="int32"
tag="type"
comment="信物类型"

[[variables]]
name="UseItemId"
type="int32"
tag="use_item_id"
comment="所需物品id"

[[variables]]
name="UseItemCount"
type="int32"
tag="use_item_count"
comment="所需物品数量"

[[variables]]
name="BeginId"
type="int"
tag="xinwu_strengthen_begin_id"
comment="信物强化等级起始id"

[[variables]]
name="SharePercent"
type="int32"
tag="share_percent"
comment="信物分享的万分比属性"