file="jieyi_daoju_vo.go"
pkg="template"
class="JieYiDaoJuTemplateVO"
comment = "结义道具配置"
[[variables]]
name="Id"
type="int"
tag="id"
comment="id"

[[variables]]
name="Type"
type="int32"
tag="type"
comment="道具类型"

[[variables]]
name="UseItemId"
type="int32"
tag="use_item_id"
comment="所需物品id"

[[variables]]
name="UseItemCount"
type="int32"
tag="use_item_count"
comment="所需物品数量"

[[variables]]
name="FashionId"
type="int32"
tag="fashion_id"
comment="激活的时装id 0不激活"

[[variables]]
name="GetItemId"
type="string"
tag="get_item_id"
comment="获得物品id"

[[variables]]
name="GetItemCount"
type="string"
tag="get_item_count"
comment="获得物品数量"
