file="jieyi_constant_vo.go"
pkg="template"
class="JieYiConstantTemplateVO"
comment = "结义常量配置"
[[variables]]
name="Id"
type="int"
tag="id"
comment="id"

[[variables]]
name="ChangeNameItemId"
type="int32"
tag="weiming_gaiming_item_id"
comment="威名改名卡id"

[[variables]]
name="QiuYuanCD"
type="int64"
tag="qiuyuan_cd"
comment="求援CD"

[[variables]]
name="FaBuCD"
type="int64"
tag="fabu_jieyi_cd"
comment="发布结义信息CD"

[[variables]]
name="FaBuJieYiMaxTime"
type="int64"
tag="fabu_jieyi_time_max"
comment="结义信息存在最大的时间" 

[[variables]]
name="ShengWeiMax"
type="int64"
tag="shengwei_max"
comment="存储的最大声威值"

[[variables]]
name="YaoQingCD"
type="int64"
tag="yaoqing_cd"
comment="邀请结义CD" 

[[variables]]
name="YaoQingExistTime"
type="int64"
tag="yaoqing_guoqi_time"
comment="邀请有效时间"

[[variables]]
name="JieChuCD"
type="int64"
tag="jiechu_jieyi_cd"
comment="解除结义CD"

[[variables]]
name="DropRate"
type="int32"
tag="shengwei_drop_rate"
comment="背包内声威掉落概率"

[[variables]]
name="DropPercentMin"
type="int32"
tag="shengwei_drop_percent_min"
comment="背包内声威掉落最小比例"

[[variables]]
name="DropPercentMax"
type="int32"
tag="shengwei_drop_percent_max"
comment="背包内声威掉落最大比例"

[[variables]]
name="DropCD"
type="int64"
tag="shengwei_drop_cd"
comment="声威掉落冷却时间"

[[variables]]
name="DropProtectedTime"
type="int64"
tag="shengwei_drop_protected_time"
comment="声威掉落保护时间"

[[variables]]
name="DropFailTime"
type="int64"
tag="shengwei_drop_fail_time"
comment="声威掉落存活时间" 

[[variables]]
name="DropMinStack"
type="int32"
tag="shengwei_drop_min_stack"
comment="背包声威掉落最小堆数" 

[[variables]]
name="DropMaxStack"
type="int32"
tag="shengwei_drop_max_stack"
comment="背包声威掉落最大堆数" 

[[variables]]
name="DropSystemReturn"
type="int32"
tag="shengwei_drop_system_return"
comment="被击杀声威被系统回收比例" 

[[variables]]
name="MaxPeopleNum"
type="int32"
tag="jieyi_player_max"
comment="结义最大人数"
