file="jieyi_name_level_vo.go"
pkg="template"
class="JieYiNameLevelTemplateVO"
comment = "结义威名等级配置"
[[variables]]
name="Id"
type="int"
tag="id"
comment="id"

[[variables]]
name="NextId"
type="int32"
tag="next_id"
comment="下一级di"

[[variables]]
name="Level"
type="int32"
tag="level"
comment="等级"

[[variables]]
name="UpLevPercent"
type="int32"
tag="update_percent"
comment="升级概率"

[[variables]]
name="UseMoney"
type="int32"
tag="use_money"
comment="所需银两"

[[variables]]
name="UseShengWei"
type="int32"
tag="use_shengwei"
comment="所需声威值"

[[variables]]
name="UseItemId"
type="int32"
tag="use_item"
comment="所需物品id"

[[variables]]
name="UseItemCount"
type="int32"
tag="item_count"
comment="所需物品数量" 

[[variables]]
name="TimesMin"
type="int32"
tag="times_min"
comment="最小次数"

[[variables]]
name="TimesMax"
type="int32"
tag="times_max"
comment="最大次数"

[[variables]]
name="DeathMinLevel"
type="int32"
tag="shengwei_min"
comment="死亡掉落最小声威等级"

[[variables]]
name="DeathMaxLevel"
type="int32"
tag="shengwei_max"
comment="死亡掉落最大声威等级"

[[variables]]
name="DropPercent"
type="int32"
tag="shengwei_percent"
comment="死亡掉落声威等级概率"

[[variables]]
name="StarCount"
type="int32"
tag="star_count"
comment="掉在地上的声威值"

[[variables]]
name="Hp"
type="int64"
tag="hp"
comment="该等级增加的生命"

[[variables]]
name="Attack"
type="int64"
tag="attack"
comment="该等级增加的攻击"

[[variables]]
name="Defence"
type="int64"
tag="defence"
comment="该等级增加的防御"