

file="juexue_vo.go"
pkg="template"
class="JueXueTemplateVO"
comment = "绝学配置"
[[variables]]
name="Id"
type="int"
tag="id"
comment="id"

[[variables]]
name="NextId"
type="int32"
tag="next_id"
comment="后续id"

[[variables]]
name="Type"
type="int32"
tag="type"
comment="绝学类型"

[[variables]]
name="Level"
type="int32"
tag="level"
comment="绝学等级"

[[variables]]
name="IsInsight"
type="int32"
tag="is_insight"
comment="是否可顿悟"

[[variables]]
name="Name"
type="string"
tag="name"
comment="名称"

[[variables]]
name="Power"
type="int32"
tag="power"
comment="获得战力"

[[variables]]
name="Des"
type="string"
tag="des"
comment="技能描述"

[[variables]]
name="NeedItemId"
type="int32"
tag="need_item_id"
comment="激活所需物品ID"

[[variables]]
name="NeedItemNum"
type="int32"
tag="need_item_num"
comment="激活所需物品数量"

[[variables]]
name="Skill"
type="int32"
tag="skill"
comment="关联技能ID"
