file="kaifumubiao_quest_vo.go"
pkg="template"
class="KaiFuMuBiaoQuestTemplateVO"
comment = "开服目标任务模板配置"
[[variables]]
name="Id"
type="int"
tag="id"
comment="id"



[[variables]]
name="NextId"
type="int32"
tag="next_id"
comment="下一个id"

[[variables]]
name="Quest"
type="int32"
tag="quest"
comment="任务id"

