file="kaifumubiao_vo.go"
pkg="template"
class="KaiFuMuBiaoTemplateVO"
comment = "开服目标模板配置"
[[variables]]
name="Id"
type="int"
tag="id"
comment="id"

[[variables]]
name="Name"
type="string"
tag="name"
comment="标签"

[[variables]]
name="NextId"
type="int32"
tag="next_id"
comment="下一个id"

[[variables]]
name="KaiFuTime"
type="int32"
tag="kaifu_time"
comment="开服第几天解锁"

[[variables]]
name="GroupBeginId"
type="int32"
tag="group_begin_id"
comment="任务组起始id"

[[variables]]
name="RewardSilver"
type="int64"
tag="reward_silver"
comment="银两奖励"

[[variables]]
name="ItemId"
type="string"
tag="item_id"
comment="完成任务组目标奖励的物品"

[[variables]]
name="ItemCount"
type="string"
tag="item_count"
comment="完成任务组目标奖励的物品数量"


[[variables]]
name="FinishQuestCount"
type="int32"
tag="finish_quest_count"
comment="完成该任务组内多少个任务才能够领取任务组奖励"
