file="leichong_vo.go"
pkg="template"
class="TimesRewTemplateVO"
comment = "运营活动次数奖励模板配置"
[[variables]]
name="Id"
type="int"
tag="id"
comment="id"

[[variables]]
name="Group"
type="int32"
tag="group"
comment="活动id"

[[variables]]
name="DrawTimes"
type="int32"
tag="draw_times"
comment="抽奖次数"

[[variables]]
name="VipLevel"
type="int32"
tag="vip_level"
comment="vip等级"

[[variables]]
name="RawId"
type="string"
tag="raw_id"
comment="奖励id"

[[variables]]
name="RawCount"
type="string"
tag="raw_count"
comment="奖励数量"
