

file="lianyu_constant_vo.go"
pkg="template"
class="LianYuConstantTemplateVO"
comment = "无间炼狱配置"
[[variables]]
name="Id"
type="int"
tag="id"
comment="id"

[[variables]]
name="Type"
type="int32"
tag="activity_type"
comment="常量类型"

[[variables]]
name="BossId"
type="int32"
tag="boss_id"
comment="bossid"

[[variables]]
name="BossTime"
type="int32"
tag="boss_time"
comment="BOSS刷新时间"

[[variables]]
name="PlayerLimitCount"
type="int32"
tag="player_limit_count"
comment="活动人数上限"

