file="lingtong_fashion_vo.go"
pkg="template"
class="LingTongFashionTemplateVO"
comment = "灵童时装配置"
[[variables]]
name="Id"
type="int"
tag="id"
comment="id"

[[variables]]
name="Name"
type="string"
tag="name"
comment="灵童时装名称"

[[variables]]
name="Type"
type="int32"
tag="type"
comment="时装类型"

[[variables]]
name="NeedItemId"
type="int32"
tag="need_item_id"
comment="激活灵童使用的物品id"


[[variables]]
name="Time"
type="int32"
tag="time"
comment="时效性"

[[variables]]
name="NeedItemCount"
type="int32"
tag="need_item_count"
comment="激活灵童使用的物品数量"

[[variables]]
name="LingTongAttack"
type="int64"
tag="lingtong_attack"
comment="灵童独立攻击力"

[[variables]]
name="LingTongCritical"
type="int64"
tag="lingtong_critical"
comment="灵童独立暴击"

[[variables]]
name="LingTongHit"
type="int64"
tag="lingtong_hit"
comment="灵童独立命中值"

[[variables]]
name="LingTongAbnormality"
type="int64"
tag="lingtong_abnormality"
comment="灵童独立破格"


[[variables]]
name="Hp"
type="int64"
tag="hp"
comment="玩家增加的生命上限"

[[variables]]
name="Attack"
type="int64"
tag="attack"
comment="玩家增加的攻击值"

[[variables]]
name="Defence"
type="int64"
tag="defence"
comment="玩家增加的防御值"

[[variables]]
name="LingTongUpstarId"
type="int32"
tag="lingtong_upstar_id"
comment="灵童升级起始id"




