file="lingtong_vo.go"
pkg="template"
class="LingTongTemplateVO"
comment = "灵童配置"
[[variables]]
name="Id"
type="int"
tag="id"
comment="id"

[[variables]]
name="Name"
type="string"
tag="name"
comment="灵童名称"

[[variables]]
name="JiHuoType"
type="int32"
tag="jihuo_type"
comment="激活类型"

[[variables]]
name="UseItemId"
type="int32"
tag="use_item_id"
comment="激活灵童使用的物品id"

[[variables]]
name="UseItemCount"
type="int32"
tag="use_item_count"
comment="激活灵童使用的物品数量"

[[variables]]
name="LingTongAttack"
type="int64"
tag="lingtong_attack"
comment="灵童独立攻击力"

[[variables]]
name="LingTongCritical"
type="int64"
tag="lingtong_critical"
comment="灵童独立暴击"

[[variables]]
name="LingTongHit"
type="int64"
tag="lingtong_hit"
comment="灵童独立命中值"

[[variables]]
name="LingTongAbnormality"
type="int64"
tag="lingtong_abnormality"
comment="灵童独立破格"

[[variables]]
name="PlayerAttackPercent"
type="int64"
tag="player_attack_percent"
comment="玩家角色攻击力继承到灵童身上万分比"

[[variables]]
name="Hp"
type="int64"
tag="hp"
comment="玩家增加的生命上限"

[[variables]]
name="Attack"
type="int64"
tag="attack"
comment="玩家增加的攻击值"

[[variables]]
name="Defence"
type="int64"
tag="defence"
comment="玩家增加的防御值"

[[variables]]
name="LingTongShengJiId"
type="int32"
tag="lingtong_shengji_id"
comment="灵童升级起始id"

[[variables]]
name="LingTongPeiYangId"
type="int32"
tag="lingtong_peiyang_id"
comment="灵童培养起始id"

[[variables]]
name="NameItemId"
type="int32"
tag="name_item_id"
comment="灵童改名消耗物品"

[[variables]]
name="NameItemCount"
type="int32"
tag="name_item_count"
comment="灵童改名消耗物品数量"

[[variables]]
name="LingTongFashionId"
type="int32"
tag="lingtong_fashion_id"
comment="灵童初始时装关联时装表ID"


[[variables]]
name="LingTongWeapon"
type="int32"
tag="lingtong_weapon"
comment="灵童初始武器关联灵童武器表id"

[[variables]]
name="AttackId"
type="int32"
tag="attack_id"
comment="普通攻击的id,前端控制"

[[variables]]
name="SkillId1"
type="int32"
tag="skill_id_1"
comment="被动技能,服务器触发"


[[variables]]
name="LingTongUpstarBeginId"
type="int32"
tag="lingtong_upstar_begin_id"
comment="升星起始id"

[[variables]]
name="LingzhuOpenLevel"
type="int32"
tag="lingzhu_open_level"
comment="灵珠开启等级"