file="lingyu_vo.go"
pkg="template"
class="LingyuTemplateVO"
comment = "领域配置"
[[variables]]
name="Id"
type="int"
tag="id"
comment="id"

[[variables]]
name="NextId"
type="int32"
tag="next_id"
comment="下一个id"

[[variables]]
name="Name"
type="string"
tag="name"
comment="领域名称"

[[variables]]
name="Number"
type="int32"
tag="number"
comment="身法阶数"

[[variables]]
name="Type"
type="int32"
tag="type"
comment="领域类型"

[[variables]]
name="UpdateWfb"
type="int32"
tag="update_wfb"
comment="进阶成功率"

[[variables]]
name="UseMoney"
type="int32"
tag="use_money"
comment="进级所需元宝"

[[variables]]
name="UseItem"
type="int32"
tag="use_item"
comment="进阶所需物品id"

[[variables]]
name="ItemCount"
type="int32"
tag="item_count"
comment="进阶所需物品数量"

[[variables]]
name="TimesMin"
type="int32"
tag="times_min"
comment="最小次数"

[[variables]]
name="TimesMax"
type="int32"
tag="times_max"
comment="最大次数"

[[variables]]
name="AddMin"
type="int32"
tag="add_min"
comment="每次增加祝福值最小值"

[[variables]]
name="AddMax"
type="int32"
tag="add_max"
comment="每次增加祝福值最大值"


[[variables]]
name="ZhufuMax"
type="int32"
tag="zhufu_max"
comment="前端祝福值显示值"

[[variables]]
name="FieldUpstarBeginId"
type="int32"
tag="field_upstar_begin_id"
comment="升星开始id"

[[variables]]
name="Skill"
type="int32"
tag="skill"
comment="激活技能"

[[variables]]
name="ModelId"
type="int32"
tag="model_id"
comment="模型ID"


[[variables]]
name="UseYinliang"
type="int32"
tag="use_yinliangr"
comment="进阶消耗银两"


[[variables]]
name="ShidanId1"
type="int32"
tag="shidan_id_1"
comment="使用幻化丹id"

[[variables]]
name="ShidanLimit"
type="int32"
tag="shidan_limit"
comment="使用幻化丹数量"

[[variables]]
name="Icon"
type="int32"
tag="icon"
comment="领域图标"

[[variables]]
name="MagicConditionType1"
type="int32"
tag="magic_condition_type1"
comment="幻化条件类型1"

[[variables]]
name="MagicConditionParameter1"
type="string"
tag="magic_condition_parameter1"
comment="根据类型,写入对应参数1"

[[variables]]
name="MagicConditionType2"
type="int32"
tag="magic_condition_type2"
comment="幻化条件类型2"

[[variables]]
name="MagicConditionParameter2"
type="string"
tag="magic_condition_parameter2"
comment="根据类型,写入对应参数2"

[[variables]]
name="MagicConditionType3"
type="int32"
tag="magic_condition_type3"
comment="幻化条件类型3"

[[variables]]
name="MagicConditionParameter3"
type="string"
tag="magic_condition_parameter3"
comment="根据类型,写入对应参数3"

[[variables]]
name="IsClear"
type="int32"
tag="is_clear"
comment="本阶进阶过天是否清空祝福值 0不清 1清"

[[variables]]
name="ShengjieType"
type="int32"
tag="shengjie_type"
comment="激活类型"

[[variables]]
name="ShengjieValue"
type="int32"
tag="shengjie_value1"
comment="激活条件"


[[variables]]
name="Hp"
type="int32"
tag="hp"
comment="hp"

[[variables]]
name="Attack"
type="int32"
tag="attack"
comment="该等级增加的攻击"


[[variables]]
name="Defence"
type="int32"
tag="defence"
comment="该等级增加的防御"