file="lingtong_mount_vo.go"
pkg="template"
class="LingTongMountTemplateVO"
comment = "灵骑配置"
[[variables]]
name="Id"
type="int"
tag="id"
comment="id"

[[variables]]
name="NextId"
type="int32"
tag="next_id"
comment="下一个id"

[[variables]]
name="Name"
type="string"
tag="name"
comment="坐骑名称"

[[variables]]
name="Type"
type="int32"
tag="type"
comment="幻化类型"

[[variables]]
name="Number"
type="int32"
tag="number"
comment="阶数"



[[variables]]
name="UpdateWfb"
type="int32"
tag="update_wfb"
comment="升阶成功率"

[[variables]]
name="UseMoney"
type="int64"
tag="use_money"
comment="升级所需元宝"

[[variables]]
name="UseItem"
type="int32"
tag="use_item"
comment="进阶所需物品id"

[[variables]]
name="ItemCount"
type="int32"
tag="item_count"
comment="进阶所需物品数量"

[[variables]]
name="TimesMin"
type="int32"
tag="times_min"
comment="最小次数"

[[variables]]
name="TimesMax"
type="int32"
tag="times_max"
comment="最大次数"

[[variables]]
name="AddMin"
type="int32"
tag="add_min"
comment="每次增加祝福值最小值"

[[variables]]
name="AddMax"
type="int32"
tag="add_max"
comment="每次增加祝福值最大值"


[[variables]]
name="ZhufuMax"
type="int32"
tag="zhufu_max"
comment="前端祝福值显示值"

[[variables]]
name="Attr"
type="int32"
tag="attr"
comment="坐骑属性"


[[variables]]
name="LingTongMountUpstarBeginId"
type="int32"
tag="upstar_begin_id"
comment="坐骑升星起始id"


[[variables]]
name="ModelId"
type="int32"
tag="model_id"
comment="模型ID"


[[variables]]
name="UseYinliang"
type="int64"
tag="use_yinliangr"
comment="进阶消耗银两"


[[variables]]
name="ShidanLimit"
type="int32"
tag="shidan_limit"
comment="幻化丹食丹等级上限"


[[variables]]
name="CulturingDanLimit"
type="int32"
tag="culturing_dan_limit"
comment="培养丹食丹等级上限"

[[variables]]
name="Icon"
type="int32"
tag="icon"
comment="灵骑头像图标"

[[variables]]
name="MagicConditionType1"
type="int32"
tag="magic_condition_type1"
comment="幻化条件类型1"

[[variables]]
name="MagicConditionParameter1"
type="string"
tag="magic_condition_parameter1"
comment="根据类型,写入对应参数1"

[[variables]]
name="MagicConditionType2"
type="int32"
tag="magic_condition_type2"
comment="幻化条件类型2"

[[variables]]
name="MagicConditionParameter2"
type="string"
tag="magic_condition_parameter2"
comment="根据类型,写入对应参数2"

[[variables]]
name="MagicConditionType3"
type="int32"
tag="magic_condition_type3"
comment="幻化条件类型3"

[[variables]]
name="MagicConditionParameter3"
type="string"
tag="magic_condition_parameter3"
comment="根据类型,写入对应参数3"


[[variables]]
name="IsClear"
type="int32"
tag="is_clear"
comment="本阶进阶过天是否清空祝福值 0不清 1清"

[[variables]]
name="Hp"
type="int64"
tag="hp"
comment="该等级增加的生命"


[[variables]]
name="Attack"
type="int64"
tag="attack"
comment="该等级增加的攻击"



[[variables]]
name="Defence"
type="int64"
tag="defence"
comment="该等级增加的防御"

[[variables]]
name="LingTongAttack"
type="int64"
tag="lingtong_attack"
comment="灵童攻击力"

[[variables]]
name="LingTongCritical"
type="int64"
tag="lingtong_critical"
comment="灵童独立暴击"

[[variables]]
name="LingTongHit"
type="int64"
tag="lingtong_hit"
comment="灵童独立命中值"

[[variables]]
name="LingTongAbnormality"
type="int64"
tag="lingtong_abnormality"
comment="灵童独立破格"


[[variables]]
name="MountId"
type="int32"
tag="mount_id"
comment="客户端需要特殊处理,坐骑id"









