
file="lin_shi_attr_vo.go"
pkg="template"
class="LinShiAttrTemplateVO"
comment = "零食模板配置"
[[variables]]
name="Id"
type="int"
tag="id"
comment="id"


[[variables]]
name="Time"
type="int32"
tag="time"
comment="时间"

[[variables]]
name="Hp"
type="int32"
tag="hp"
comment="血量"

[[variables]]
name="Attack"
type="int32"
tag="attack"
comment="攻击"

[[variables]]
name="Defence"
type="int32"
tag="defence"
comment="防御"

[[variables]]
name="HpPercent"
type="int32"
tag="hp_percent"
comment="奖励绑定元宝"

[[variables]]
name="AttackPercent"
type="int32"
tag="attack_percent"
comment="购买奖励"

[[variables]]
name="DefPercent"
type="int32"
tag="def_percent"
comment="购买奖励数量"

[[variables]]
name="BuffId"
type="int32"
tag="buff_id"
comment="buff"
