file="longgong_constant_vo.go"
pkg="template"
class="LongGongConstantTemplateVO"
comment = "龙宫探宝常量配置"
[[variables]]
name="Id"
type="int"
tag="id"
comment="id"

[[variables]]
name="BossId"
type="int32"
tag="boss_id"
comment="boss生物id"

[[variables]]
name="BossNeedCaiJiCount"
type="int32"
tag="boss_need_caiji_count"
comment="召唤boss需要的珍珠采集数"

[[variables]]
name="BossBeKillCaiJiBiologyId"
type="int32"
tag="boss_bekill_caiji_biology_id"
comment="boss被杀后出现的采集点生物id"

[[variables]]
name="PosX"
type="float64"
tag="pos_x"
comment="boss采集点地图x坐标"

[[variables]]
name="PosY"
type="float64"
tag="pos_y"
comment="boss采集点地图y坐标"

[[variables]]
name="PosZ"
type="float64"
tag="pos_z"
comment="boss采集点地图z坐标"

[[variables]]
name="BossBeKillCaiJiPersonalCount"
type="int32"
tag="boss_bekill_caiji_personal_count"
comment="boss采集点玩家最多采集次数"

[[variables]]
name="XuJiaCaiJiAddTime"
type="int32"
tag="xujia_caiji_add_time"
comment="珍珠采集虚假时间"

[[variables]]
name="XuJiaCaiJiAddCount"
type="int32"
tag="xujia_caiji_add_count"
comment="每次珍珠采集虚假数据增加的数量"

[[variables]]
name="MapId"
type="int32"
tag="map_id"
comment="地图id"