file="map_vo.go"
pkg="template"
class="MapTemplateVO"
comment = "地图配置"
[[variables]]
name="Id"
type="int"
tag="id"
comment="id"

[[variables]]
name="Name"
type="string"
tag="name"
comment="名字"

[[variables]]
name="Resource"
type="string"
tag="resource"
comment="资源"

[[variables]]
name="Type"
type="int32"
tag="type"
comment="类型"

[[variables]]
name="ScriptType"
type="int32"
tag="script_type"
comment="脚本类型"


[[variables]]
name="LastTime"
type="int32"
tag="last_time"
comment="存在时间"

[[variables]]
name="PointsTime"
type="int32"
tag="points_time"
comment="副本失败时间"

[[variables]]
name="BirthPosX"
type="float64"
tag="birthPosX"
comment="出生地点"

[[variables]]
name="BirthPosY"
type="float64"
tag="birthPosY"
comment="出生地点"

[[variables]]
name="BirthPosZ"
type="float64"
tag="birthPosZ"
comment="出生地点"

[[variables]]
name="RebornId"
type="int32"
tag="reborn_id"
comment="回城复活id"

[[variables]]
name="RebornX"
type="float64"
tag="reborn_x"
comment="复活地点x"

[[variables]]
name="RebornY"
type="float64"
tag="reborn_y"
comment="复活地点y"

[[variables]]
name="RebornZ"
type="float64"
tag="reborn_z"
comment="复活地点z"


[[variables]]
name="Orientation"
type="int32"
tag="orientation"
comment="朝向"

[[variables]]
name="Level"
type="int32"
tag="level"
comment="等级"


[[variables]]
name="LimitPkMode"
type="int32"
tag="limit_pkmode"
comment="限制pk模式"

[[variables]]
name="PkMode"
type="int32"
tag="pk_mode"
comment="pk模式"

[[variables]]
name="LimitReborn"
type="int32"
tag="limit_reborn"
comment="限制重生"


[[variables]]
name="LimitSit"
type="int32"
tag="limit_sit"
comment="限制打坐"


[[variables]]
name="LimitSpellType"
type="int32"
tag="limit_spell_type"
comment="限制使用技能类型"

[[variables]]
name="LimitItemId"
type="int32"
tag="limit_item_id"
comment="限制带出的物品"

[[variables]]
name="LimitStatusId"
type="int32"
tag="limit_status_id"
comment="限制带出的状态"


[[variables]]
name="SetFaction"
type="int32"
tag="set_faction"
comment="进入地图的默认阵营"

[[variables]]
name="NeedSilver"
type="int32"
tag="need_silver"
comment="进入地图的需要的银两"

[[variables]]
name="NeedGold"
type="int32"
tag="need_gold"
comment="进入地图的需要的元宝"

[[variables]]
name="NeedItemId"
type="string"
tag="need_item_id"
comment="需要物品id"

[[variables]]
name="NeedItemNum"
type="string"
tag="need_item_num"
comment="需要物品数量"

[[variables]]
name="ReqLev"
type="int32"
tag="req_lev"
comment="需求等级"

[[variables]]
name="LimitUseitem"
type="int32"
tag="limit_useitem"
comment="限制使用物品"

[[variables]]
name="PlayerLimitCount"
type="int32"
tag="player_limit_count"
comment="玩家限制数量"

[[variables]]
name="QuestId"
type="int32"
tag="quest_id"
comment="需要前置任务id"

[[variables]]
name="SuggestPower"
type="int64"
tag="suggest_power"
comment="最低战斗力限制"


[[variables]]
name="ReqModuleId"
type="int32"
tag="req_module_id"
comment="需要功能开启id"

[[variables]]
name="SafeArea"
type="string"
tag="safe_area"
comment="安全区"


[[variables]]
name="OpenLimit"
type="int32"
tag="open_limit"
comment="动态地图上限"

[[variables]]
name="LimitRideHorse"
type="int32"
tag="limit_ride_horse"
comment="限制骑马"


[[variables]]
name="RewardPreview"
type="string"
tag="reward_previwe"
comment="奖励预览"

[[variables]]
name="ShowBossInfo"
type="int32"
tag="show_boss_info"
comment="展示boss信息"

[[variables]]
name="WeatherId"
type="string"
tag="weather_id"
comment="天气id"

[[variables]]
name="MapNameImage"
type="string"
tag="map_name_image"
comment="切换地图显示的图片"


[[variables]]
name="LimitHook"
type="int32"
tag="limit_hook"
comment="限制挂机"


[[variables]]
name="OffsetX"
type="int32"
tag="offsetX"
comment="小地图偏移"

[[variables]]
name="OffsetY"
type="int32"
tag="offsetY"
comment="小地图偏移"

[[variables]]
name="Scale"
type="float64"
tag="scale"
comment="缩放比例"



[[variables]]
name="Rotate"
type="int32"
tag="rotate"
comment="旋转角度"

[[variables]]
name="RotationX"
type="int32"
tag="rotation_x"
comment="旋转角度"

[[variables]]
name="RotationY"
type="int32"
tag="rotation_y"
comment="旋转角度"

[[variables]]
name="Distance"
type="int32"
tag="distance"
comment="距离"

[[variables]]
name="Music"
type="string"
tag="music"
comment="音效"


[[variables]]
name="LimitWindow"
type="int32"
tag="limit_window"
comment="限制弹窗"


[[variables]]
name="ResurrectionType"
type="int32"
tag="resurrection_type"
comment="复活类型"

[[variables]]
name="ResurrectionTime"
type="int32"
tag="resurrection_time"
comment="复活时间"


[[variables]]
name="XianzhiquyuId"
type="string"
tag="xianzhiquyu_id"
comment="限制区"

[[variables]]
name="AnquanquId"
type="string"
tag="anquanqu_id"
comment="安全区"

[[variables]]
name="IsShaqiDrop"
type="int32"
tag="is_shaqi_drop"
comment="该地图是否掉落杀气"

[[variables]]
name="IsShengWeiDrop"
type="int32"
tag="is_shengwei_drop"
comment="该地图是否掉落声威值"

[[variables]]
name="IsChuansong"
type="int32"
tag="is_chuansong"
comment="是否支持飞鞋传送"

[[variables]]
name="FeixieCount"
type="int32"
tag="feixie_count"
comment="飞鞋消耗"

[[variables]]
name="IsFeixie"
type="int32"
tag="is_feixie"
comment="是否支持仙盟求救"

[[variables]]
name="IsTitle"
type="int32"
tag="is_title"
comment="是否隐藏称号"

[[variables]]
name="ProtectLevel"
type="int32"
tag="protect_level"
comment="pk保护等级"

[[variables]]
name="IsPkScene"
type="int32"
tag="is_pk_scene"
comment="是否pk状态切换场景"

[[variables]]
name="IsSceneProtect"
type="int32"
tag="is_scene_protect"
comment="是否场景过场保护"

[[variables]]
name="IsShaLuDrop"
type="int32"
tag="is_shalu_drop"
comment="是否掉落杀戮之心"

[[variables]]
name="IsXueChi"
type="int32"
tag="is_xuechi"
comment="血池"

[[variables]]
name="SceneXianZhi"
type="int64" 
tag="scene_xianzhi"
comment="限制传送类型"

