file="marry_banquet_vo.go"
pkg="template"
class="MarryBanquetTemplateVO"
comment = "婚礼档次配置"
[[variables]]
name="Id"
type="int"
tag="id"
comment="id"

[[variables]]
name="HoutaiType"
type="int32"
tag="houtai_type"
comment="版本类型"

[[variables]]
name="Type"
type="int32"
tag="type"
comment="婚礼类型"

[[variables]]
name="SubType"
type="int32"
tag="sub_type"
comment="婚礼子类型"

[[variables]]
name="Name"
type="string"
tag="name"
comment="婚宴名字"


[[variables]]
name="UseSilver"
type="int32"
tag="use_silver"
comment="花费银两"


[[variables]]
name="UseBinggold"
type="int32"
tag="use_binggold"
comment="消耗的绑元"


[[variables]]
name="UseGold"
type="int32"
tag="use_gold"
comment="花费元宝"

[[variables]]
name="SugarEach"
type="int32"
tag="sugar_each"
comment="撒喜糖操作时间间隔(毫秒)"

[[variables]]
name="DropTime"
type="int32"
tag="drop_time"
comment="手动丢撒喜糖的CD(毫秒)"



[[variables]]
name="DropId"
type="string"
tag="drop_id"
comment="喜糖掉落id"

[[variables]]
name="BanquetBiology"
type="int32"
tag="banquet_biology"
comment="生物表id婚宴"

[[variables]]
name="MapId"
type="int32"
tag="map_id"
comment="刷酒桌的地图id"

[[variables]]
name="PosX1"
type="float64"
tag="pos_x1"
comment="酒桌的坐标x1"

[[variables]]
name="PosY1"
type="float64"
tag="pos_y1"
comment="酒桌的坐标y1"

[[variables]]
name="PosZ1"
type="float64"
tag="pos_z1"
comment="酒桌的坐标z1"

[[variables]]
name="PosX2"
type="float64"
tag="pos_x2"
comment="酒桌的坐标x2"

[[variables]]
name="PosY2"
type="float64"
tag="pos_y2"
comment="酒桌的坐标y2"

[[variables]]
name="PosZ2"
type="float64"
tag="pos_z2"
comment="酒桌的坐标z2"

[[variables]]
name="PosX3"
type="float64"
tag="pos_x3"
comment="酒桌的坐标x3"

[[variables]]
name="PosY3"
type="float64"
tag="pos_y3"
comment="酒桌的坐标y3"

[[variables]]
name="PosZ3"
type="float64"
tag="pos_z3"
comment="酒桌的坐标z3"

[[variables]]
name="IsYouJie"
type="int32"
tag="is_youjie"
comment="是否有游街"

[[variables]]
name="AddBuffId"
type="int32"
tag="add_buff_id"
comment="酒桌buff"

[[variables]]
name="ZiYuan"
type="string"
tag="ziyuan"
comment="资源名称"


[[variables]]
name="Discount"
type="int32"
tag="discount"
comment="折扣值(前端显示用)"


[[variables]]
name="FrontSilver"
type="int32"
tag="front_silver"
comment="前端显示的折扣前银两"

[[variables]]
name="FrontBinggold"
type="int32"
tag="front_binggold"
comment="前端显示的折扣前绑元"

[[variables]]
name="FrontGold"
type="int32"
tag="front_gold"
comment="前端显示的折扣前元宝"

[[variables]]
name="EndRewId"
type="string"
tag="end_rew_id"
comment="婚礼结束后奖励物品ID，配置同服务端实际扣除的消耗，取同类型的相加获得"


[[variables]]
name="EndRewCount"
type="string"
tag="end_rew_count"
comment="婚礼结束后奖励物品数量，配置同服务端实际扣除的消耗，取同类型的相加获得"








