file="marry_jinian_vo.go"
pkg="template"
class="MarryJiNianTemplateVO"
comment = "结婚纪念"
[[variables]]
name="Id"
type="int"
tag="id"
comment="id"

[[variables]]
name="Type"
type="int32"
tag="type"
comment="类型：1低级，2中级，3高级"

[[variables]]
name="NeedNum"
type="int32"
tag="need_num"
comment="对应婚礼到达次数"

[[variables]]
name="ZhuheItem"
type="string"
tag="zhuhe_item"
comment="到达次数后赠送的物品"

[[variables]]
name="ZhuheItemCount"
type="string"
tag="zhuhe_item_count"
comment="到达次数后赠送的物品数量"

[[variables]]
name="TitleId"
type="int32"
tag="title_id"
comment="对应称号Id"