file="marry_xinwu_suit_group_vo.go"
pkg="template"
class="MarryXinWuSuitGroupTemplateVO"
comment = "定情信物套装"
[[variables]]
name="Id"
type="int"
tag="id"
comment="id"

[[variables]]
name="Name"
type="string"
tag="name"
comment="套装名称"

[[variables]]
name="MaxNum"
type="int32"
tag="max_num"
comment="套装部件数量"

[[variables]]
name="SuitId1"
type="int32"
tag="suit_id1"
comment="套装效果1"


[[variables]]
name="SuitId2"
type="int32"
tag="suit_id2"
comment="套装效果2"


[[variables]]
name="SuitId3"
type="int32"
tag="suit_id3"
comment="套装效果3"


[[variables]]
name="SuitId4"
type="int32"
tag="suit_id4"
comment="套装效果4"

[[variables]]
name="Pos1Name"
type="string"
tag="pos1_name"
comment="第一个部件名称"

[[variables]]
name="Pos1Id"
type="int32"
tag="pos1_id"
comment="第一个部件需要物品Id"


[[variables]]
name="Pos2Name"
type="string"
tag="pos2_name"
comment="第2个部件名称"

[[variables]]
name="Pos2Id"
type="int32"
tag="pos2_id"
comment="第2个部件需要物品Id"


[[variables]]
name="Pos3Name"
type="string"
tag="pos3_name"
comment="第3个部件名称"

[[variables]]
name="Pos3Id"
type="int32"
tag="pos3_id"
comment="第3个部件需要物品Id"


[[variables]]
name="Pos4Name"
type="string"
tag="pos4_name"
comment="第4个部件名称"

[[variables]]
name="Pos4Id"
type="int32"
tag="pos4_id"
comment="第4个部件需要物品Id"


[[variables]]
name="Pos5Name"
type="string"
tag="pos5_name"
comment="第5个部件名称"

[[variables]]
name="Pos5Id"
type="int32"
tag="pos5_id"
comment="第5个部件需要物品Id"


[[variables]]
name="Pos6Name"
type="string"
tag="pos6_name"
comment="第6个部件名称"

[[variables]]
name="Pos6Id"
type="int32"
tag="pos6_id"
comment="第6个部件需要物品Id"


[[variables]]
name="Pos7Name"
type="string"
tag="pos7_name"
comment="第7个部件名称"

[[variables]]
name="Pos7Id"
type="int32"
tag="pos7_id"
comment="第7个部件需要物品Id"


[[variables]]
name="Pos8Name"
type="string"
tag="pos8_name"
comment="第8个部件名称"

[[variables]]
name="Pos8Id"
type="int32"
tag="pos8_id"
comment="第8个部件需要物品Id"

[[variables]]
name="KaifuTime"
type="int32"
tag="kaifu_time"
comment="开服天数"