file="marry_xinwu_vo.go"
pkg="template"
class="MarryXinWuTemplateVO"
comment = "定情信物"
[[variables]]
name="Id"
type="int"
tag="id"
comment="id"

[[variables]]
name="SuitGroup"
type="int"
tag="suit_group"
comment="套装id"

[[variables]]
name="Hp"
type="int32"
tag="hp"
comment="增加生命"

[[variables]]
name="Attack"
type="int32"
tag="attack"
comment="增加攻击"

[[variables]]
name="Defence"
type="int32"
tag="defence"
comment="增加防御"

[[variables]]
name="Type"
type="int32"
tag="type"
comment="信物位置"