file="marry_tuisong_vo.go"
pkg="template"
class="MarryTuiSongTemplateVO"
comment = "婚车游车时赠礼配置"
[[variables]]
name="Id"
type="int"
tag="id"
comment="id"

[[variables]]
name="Type"
type="int32"
tag="type"
comment="赠送类型，1鲜花，2赠礼"

[[variables]]
name="NeedGold"
type="int32"
tag="need_gold"
comment="消耗元宝"

[[variables]]
name="RewardExp"
type="int32"
tag="reward_exp"
comment="获得经验"

[[variables]]
name="RewardExpPoint"
type="int32"
tag="reward_exp_point"
comment="获得经验"

[[variables]]
name="ZhuHeItem"
type="string"
tag="zhuhe_item"
comment="回馈物品Id"

[[variables]]
name="ZhuheItemCount"
type="string"
tag="zhuhe_item_count"
comment="回馈物品数量"