file="marry_vo.go"
pkg="template"
class="MarryTemplateVO"
comment = "结婚常量配置"
[[variables]]
name="Id"
type="int"
tag="id"
comment="id"

[[variables]]
name="QinmiduHoutaiType"
type="string"
tag="qinmidu_houtai_type"
comment="结婚亲密度最低要求"

[[variables]]
name="MarryQinmidu"
type="string"
tag="marry_qinmidu"
comment="结婚亲密度最低要求"

[[variables]]
name="DivorceQinmidu"
type="int32"
tag="divorce_qinmidu"
comment="离婚亲密度降低万分比"

[[variables]]
name="RingLevelGap"
type="int32"
tag="ring_level_gap"
comment="婚戒培养最大等级差"

[[variables]]
name="MarryFirstTime"
type="string"
tag="marry_first_time"
comment="第一场婚宴开始的时间"

[[variables]]
name="MarryAmount"
type="int32"
tag="marry_amount"
comment="一天内举办的婚礼场次"


[[variables]]
name="MarryMapId"
type="int32"
tag="marry_map_id"
comment="婚宴场景id"

[[variables]]
name="CarId"
type="int32"
tag="car_id"
comment="婚车生物表id"

[[variables]]
name="CarMapId"
type="int32"
tag="car_map_id"
comment="婚车旅游地图id"

[[variables]]
name="Radius"
type="int32"
tag="radius"
comment="喜糖掉落半径"

[[variables]]
name="MarryTime"
type="int32"
tag="marry_time"
comment="每场婚礼的时间(毫秒)"

[[variables]]
name="QingChangTime"
type="int32"
tag="qingchang_time"
comment="每场婚礼的清场时间(毫秒)"

[[variables]]
name="MarryItem"
type="string"
tag="marry_item"
comment="结婚纪念满了之后赠送物品"

[[variables]]
name="MarryItemCount"
type="string"
tag="marry_item_count"
comment="结婚纪念满了之后赠送物品数量"


[[variables]]
name="FashionId"
type="int32"
tag="fashion_id"
comment="结婚纪念满了之后赠送时装Id"

[[variables]]
name="XinwuCd"
type="int64"
tag="xinwu_cd"
comment="定情信物索要CD时间(毫秒)"