file="marry_xinwu_suit_vo.go"
pkg="template"
class="MarryXinWuSuitTemplateVO"
comment = "定情信物套装增加"
[[variables]]
name="Id"
type="int"
tag="id"
comment="id"

[[variables]]
name="Type"
type="int32"
tag="type"
comment="1技能，2属性"

[[variables]]
name="Value"
type="int32"
tag="value"
comment="Type:1技能Id，Type2属性"

[[variables]]
name="Num"
type="int32"
tag="num"
comment="套装物品数量"

[[variables]]
name="Hp"
type="int32"
tag="hp"
comment="增加生命"

[[variables]]
name="Attack"
type="int32"
tag="attack"
comment="增加攻击"

[[variables]]
name="Defence"
type="int32"
tag="defence"
comment="增加防御"

[[variables]]
name="Describe"
type="string"
tag="describe"
comment="套装描述"