file="marry_gift_vo.go"
pkg="template"
class="MarryGiftTemplateVO"
comment = "婚宴贺礼配置"
[[variables]]
name="Id"
type="int"
tag="id"
comment="id"

[[variables]]
name="Type"
type="int32"
tag="type"
comment="贺礼类型"


[[variables]]
name="UseSilver"
type="int32"
tag="use_silver"
comment="消耗银两"


[[variables]]
name="UseItemId"
type="int32"
tag="use_item_id"
comment="消耗物品id"

[[variables]]
name="UseItemAmount"
type="int32"
tag="use_item_amount"
comment="消耗物品id"

[[variables]]
name="AddNum"
type="int32"
tag="add_num"
comment="增加豪气值"

[[variables]]
name="BuffAmount"
type="int32"
tag="buff_amount"
comment="获得buff数量"
