file="massacre_vo.go"
pkg="template"
class="MassacreTemplateVO"
comment = "戮仙刃配置"
[[variables]]
name="Id"
type="int"
tag="id"
comment="id"

[[variables]]
name="Type"
type="int32"
tag="type"
comment="戮仙刃阶别"

[[variables]]
name="NextId"
type="int32"
tag="next_id"
comment="下一个id"

[[variables]]
name="Star"
type="int32"
tag="star"
comment="不同阶别下对应的星数"

[[variables]]
name="UpdatePercent"
type="int32"
tag="update_percent"
comment="升星成功率"

[[variables]]
name="UseMoney"
type="int32"
tag="use_money"
comment="升阶所需银两"

[[variables]]
name="UseGas"
type="int32"
tag="use_gas"
comment="升阶所需杀气"

[[variables]]
name="UseItem"
type="int32"
tag="use_item"
comment="进阶所需物品id"

[[variables]]
name="ItemCount"
type="int32"
tag="item_count"
comment="进阶所需物品数量"

[[variables]]
name="TimesMin"
type="int32"
tag="times_min"
comment="最小次数"

[[variables]]
name="TimesMax"
type="int32"
tag="times_max"
comment="最大次数"

[[variables]]
name="WeaponId"
type="int32"
tag="weapon_id"
comment="获得兵魂ID"

[[variables]]
name="GasMin"
type="int32"
tag="gas_min"
comment="死亡时掉落星级下限"

[[variables]]
name="GasMax"
type="int32"
tag="gas_max"
comment="死亡时掉落星级上限"

[[variables]]
name="GasPercent"
type="int32"
tag="gas_percent"
comment="掉落星级概率"

[[variables]]
name="StarCount"
type="int32"
tag="star_count"
comment="每个星星代表的杀气值"

[[variables]]
name="Hp"
type="int32"
tag="hp"
comment="生命"

[[variables]]
name="Attack"
type="int32"
tag="attack"
comment="攻击"

[[variables]]
name="Defence"
type="int32"
tag="defence"
comment="防御"
