file="mingge_mingli_vo.go"
pkg="template"
class="MingGeMingLiTemplateVO"
comment = "命格命理配置"
[[variables]]
name="Id"
type="int"
tag="id"
comment="id"

[[variables]]
name="Type"
type="int32"
tag="type"
comment="命理类型"

[[variables]]
name="SubType"
type="int32"
tag="sub_type"
comment="命理部位"

[[variables]]
name="AttrPool"
type="int32"
tag="attr_pool"
comment="该部位能够随机的类型(二进制)"


[[variables]]
name="ZhiDingAttr"
type="int32"
tag="zhiding_attr"
comment="该部位指定的最大收益属性"


[[variables]]
name="AttrOne"
type="int32"
tag="attr_one"
comment="基础属性倍数"

[[variables]]
name="ZhiDingRate1"
type="int32"
tag="zhiding_rate1"
comment="当3条命宫属性中不包含指定属性时洗练单条属性洗练到指定属性的概率(万分比)"

[[variables]]
name="ZhiDingRate2"
type="int32"
tag="zhiding_rate2"
comment="当3条命宫属性中包含1条指定属性时洗练单条属性洗练到指定属性的概率(万分比)"

[[variables]]
name="ZhiDingRate3"
type="int32"
tag="zhiding_rate3"
comment="当3条命宫属性中包含2条指定属性时洗练单条属性洗练到指定属性的概率(万分比)"

[[variables]]
name="UseItemId"
type="int32"
tag="use_item_id"
comment="洗练消耗的物品id"


[[variables]]
name="UseItemOne"
type="int32"
tag="use_item_one"
comment="洗练消耗的物品基础倍数基础数量为1*该字段"

[[variables]]
name="CoefficientUse1"
type="float64"
tag="coefficient_use1"
comment="洗练消耗的物品系数向上取整"


[[variables]]
name="CoefficientUse2"
type="int32"
tag="coefficient_use2"
comment="消耗物品数量的固定值"


[[variables]]
name="CoefficientAttr1"
type="float64"
tag="coefficient_attr1"
comment="洗练获得属性系数向上取整"

[[variables]]
name="CoefficientAttr2"
type="float64"
tag="coefficient_attr2"
comment="洗练属性的固定值"


[[variables]]
name="XilianLimitCount"
type="int32"
tag="xilian_limit_count"
comment="公式里洗练次数的最大值"


[[variables]]
name="ShouYiPercent"
type="int32"
tag="shouyi_percent"
comment="收益万分比"


[[variables]]
name="CoefficientZhiDing"
type="int32"
tag="coefficient_zhiding"
comment="指定属性的收益系数"