file="mingge_vo.go"
pkg="template"
class="MingGeTemplateVO"
comment = "命格配置"
[[variables]]
name="Id"
type="int"
tag="id"
comment="id"

[[variables]]
name="Type"
type="int32"
tag="type"
comment="命格类型"

[[variables]]
name="SubType"
type="int32"
tag="sub_type"
comment="命格子类型"

[[variables]]
name="Hp"
type="int64"
tag="hp"
comment="命格增加的生命"

[[variables]]
name="Attack"
type="int64"
tag="attack"
comment="命格增加的攻击"

[[variables]]
name="Defence"
type="int64"
tag="defence"
comment="命格增加的防御"