file="mingge_minggong_vo.go"
pkg="template"
class="MingGeMingGongTemplateVO"
comment = "命格命宫配置"
[[variables]]
name="Id"
type="int"
tag="id"
comment="id"

[[variables]]
name="Type"
type="int32"
tag="type"
comment="命理类型"

[[variables]]
name="NextId"
type="int32"
tag="next_id"
comment="下一级id"

[[variables]]
name="ParentId"
type="int32"
tag="parent_id"
comment="父命理id"


[[variables]]
name="NeedParentZhanLi"
type="int32"
tag="need_parent_zhanli"
comment="需要父命理达到的战力"


[[variables]]
name="NeedLevel"
type="int32"
tag="need_level"
comment="需要玩家的等级"

[[variables]]
name="NeedZhuanShu"
type="int32"
tag="need_zhuanshu"
comment="需要玩家的转数"

[[variables]]
name="BeginId"
type="int32"
tag="begin_id"
comment="起始id"
