file="mingge_synthesis_vo.go"
pkg="template"
class="MingGeSynthesisTemplateVO"
comment = "命格合成配置"
[[variables]]
name="Id"
type="int"
tag="id"
comment="id"

[[variables]]
name="NeedItemId"
type="string"
tag="need_item_id"
comment="合成所需的物品id"

[[variables]]
name="NeedItemCount"
type="string"
tag="need_item_count"
comment="合成所需的物品数量"

[[variables]]
name="ItemId"
type="int32"
tag="item_id"
comment="合成后的物品ID"

[[variables]]
name="ItemCount"
type="int32"
tag="item_count"
comment="合成后的物品数量"

[[variables]]
name="NeedSilver"
type="int32"
tag="need_silver"
comment="合成所需银两"

[[variables]]
name="ShiBaiDrop"
type="int32"
tag="shibai_drop"
comment="合成失败后获得的物品关联到掉落表"


[[variables]]
name="NeedGold"
type="int32"
tag="need_gold"
comment="合成所需元宝"

[[variables]]
name="NeedBindGold"
type="int32"
tag="need_bind_gold"
comment="合成所需绑定元宝"



[[variables]]
name="SuccessRate"
type="int32"
tag="success_rate"
comment="合成成功率万分比"


