file="mingge_mingpan_vo.go"
pkg="template"
class="MingGeMingPanTemplateVO"
comment = "命格合成配置"
[[variables]]
name="Id"
type="int"
tag="id"
comment="id"

[[variables]]
name="SubType"
type="int32"
tag="sub_type"
comment="命格子类型"

[[variables]]
name="NextId"
type="int32"
tag="next_id"
comment="下一级id"

[[variables]]
name="Number"
type="int32"
tag="number"
comment="命盘阶数"

[[variables]]
name="Star"
type="int32"
tag="star"
comment="命盘星级"

[[variables]]
name="Rate"
type="int32"
tag="rate"
comment="权重"


[[variables]]
name="UseItemId"
type="int32"
tag="use_item_id"
comment="消耗的物品id"


[[variables]]
name="UseItemCount"
type="int32"
tag="use_item_count"
comment="消耗的物品数量"

[[variables]]
name="UpdateWfb"
type="int32"
tag="update_wfb"
comment="成功率"

[[variables]]
name="TimesMin"
type="int32"
tag="times_min"
comment="最小升阶次数"



[[variables]]
name="TimesMax"
type="int32"
tag="times_max"
comment="最大升阶次数"

[[variables]]
name="AddMin"
type="int32"
tag="add_min"
comment="增加的最小祝福值"


[[variables]]
name="AddMax"
type="int32"
tag="add_max"
comment="增加的最大祝福值"


[[variables]]
name="ZhuFuMax"
type="int32"
tag="zhufu_max"
comment="祝福最大总值"


[[variables]]
name="Hp"
type="int64"
tag="hp"
comment="增加的生命"


[[variables]]
name="Attack"
type="int64"
tag="attack"
comment="增加的攻击值"

[[variables]]
name="Defence"
type="int64"
tag="defence"
comment="增加的防御值"


[[variables]]
name="Percent"
type="int32"
tag="percent"
comment="给命盘增加的属性百分比（万分比）"







