file="mingge_danbei_vo.go"
pkg="template"
class="MingGeDanBeiTemplateVO"
comment = "命格单倍配置"
[[variables]]
name="Id"
type="int"
tag="id"
comment="id"

[[variables]]
name="Type"
type="int32"
tag="type"
comment="属性类型"

[[variables]]
name="Attr"
type="int32"
tag="attr"
comment="根据type类型单倍的属性点数"


[[variables]]
name="Rate"
type="int64"
tag="rate"
comment="权重"

