

file="mining_vo.go"
pkg="template"
class="MiningTemplateVO"
comment = "挖矿配置"
[[variables]]
name="Id"
type="int"
tag="id"
comment="id"

[[variables]]
name="Level"
type="int32"
tag="level"
comment="矿工人数(矿山等级)"

[[variables]]
name="IntervalTime"
type="int32"
tag="interval_time"
comment="间隔时间(秒)"

[[variables]]
name="Revenue"
type="int32"
tag="revenue"
comment="收益(间隔时间)"

[[variables]]
name="LimitMax"
type="int32"
tag="limit_max"
comment="收益存储上限"

[[variables]]
name="NeedYinLiang"
type="int32"
tag="need_yinliang"
comment="升级所需银两"

[[variables]]
name="NeedGold"
type="int32"
tag="need_gold"
comment="升级所需元宝"

[[variables]]
name="ItemId1"
type="int32"
tag="item_id_1"
comment="升级所需物品ID1"

[[variables]]
name="ItemCount1"
type="int32"
tag="item_count_1"
comment="升级所需物品数量1"

