file="module_opened_vo.go"
pkg="template"
class="ModuleOpenedTemplateVO"
comment = "功能开启配置"

[[variables]]
name="Id"
type="int"
tag="id"
comment="id"

[[variables]]
name="FuncId"
type="int32"
tag="func_id"
comment="功能id"

[[variables]]
name="Name"
type="string"
tag="name"
comment="名字"

[[variables]]
name="OpenedQuestId"
type="int32"
tag="opened_quest_id"
comment="功能开启id"

[[variables]]
name="OpenedLevel"
type="int32"
tag="opened_level"
comment="开启等级"

[[variables]]
name="OpenedZhuanShu"
type="int32"
tag="opened_zhuanshu"
comment="开启转数"

[[variables]]
name="OpenedTime"
type="int64"
tag="opened_time"
comment="开启时间"

[[variables]]
name="KaifuTime"
type="int64"
tag="kaifu_time"
comment="开服时间"

[[variables]]
name="RewItem"
type="string"
tag="rew_item"
comment="开启后奖励物品id"

[[variables]]
name="RewItemCount"
type="string"
tag="rew_item_count"
comment="开启后奖励物品数量"

[[variables]]
name="RewGold"
type="int64"
tag="rew_gold"
comment="开启后元宝奖励"

[[variables]]
name="RewBindgold"
type="int64"
tag="rew_bindgold"
comment="开启后绑元奖励"

[[variables]]
name="RewYinliang"
type="int64"
tag="rew_yinliang"
comment="开启后银两奖励"

[[variables]]
name="OpenedShouchong"
type="int32"
tag="opened_shouchong"
comment="开启首冲"

[[variables]]
name="OpenedItemId"
type="int32"
tag="opened_item_id"
comment="开启物品id"

[[variables]]
name="OpenedItemCount"
type="int32"
tag="opened_item_count"
comment="开启物品数量"

[[variables]]
name="ParentId"
type="string"
tag="parent_id"
comment="前置功能id"

[[variables]]
name="IsPreview"
type="int32"
tag="is_preview"
comment="显示功能预告"

[[variables]]
name="Description"
type="string"
tag="description"
comment="描述"

[[variables]]
name="Show"
type="string"
tag="show"
comment="显示提示框"

[[variables]]
name="MailRewItem"
type="string"
tag="mail_rew_item"
comment="邮件奖励"

[[variables]]
name="MailRewItemCount"
type="string"
tag="mail_rew_item_count"
comment="邮件奖励数量"

[[variables]]
name="MailDes"
type="string"
tag="mail_des"
comment="邮件内容"

[[variables]]
name="MailTitle"
type="string"
tag="mail_title"
comment="邮件标题"

[[variables]]
name="OpensvId"
type="string"
tag="opensv_id"
comment="关联运营活动时间id"

[[variables]]
name="JianHaoDay"
type="int32"
tag="jianhao_day"
comment="建号几天后开启"

[[variables]]
name="JianHaoIsAuto"
type="int32"
tag="jianhao_is_auto"
comment="是否自动开启"

[[variables]]
name="NeedSysType"
type="int32"
tag="need_sys_type"
comment="功能开启所需系统类型"

[[variables]]
name="NeedSysNum"
type="int32"
tag="need_sys_num"
comment="功能开启所需阶别"
