file="moon_love_vo.go"
pkg="template"
class="MoonloveTemplateVO"
comment = "月下情缘配置"
[[variables]]
name="Id"
type="int"
tag="id"
comment="id"

[[variables]]
name="MinLev"
type="int32"
tag="min_lev"
comment="最小等级"

[[variables]]
name="MaxLev"
type="int32"
tag="max_lev"
comment="最大等级"

[[variables]]
name="FristTiem"
type="int64"
tag="frist_tiem"
comment="进入后多少毫秒获得奖励"

[[variables]]
name="RewTiem"
type="int64"
tag="rew_tiem"
comment="多少毫秒发一次奖励"

[[variables]]
name="RewExp"
type="int64"
tag="rew_exp"
comment="单次发放经验值"

[[variables]]
name="RewExpPoint"
type="int32"
tag="rew_exp_point"
comment="单次发放的经验点"

[[variables]]
name="RewSilver"
type="int64"
tag="rew_silver"
comment="奖励银两"

[[variables]]
name="RewGold"
type="int32"
tag="rew_gold"
comment="奖励元宝"

[[variables]]
name="RewBindGold"
type="int32"
tag="rew_bind_gold"
comment="奖励绑定元宝"

[[variables]]
name="RewItemId"
type="string"
tag="rew_item_id"
comment="奖励物品Id"

[[variables]]
name="RewItemCount"
type="string"
tag="rew_item_count"
comment="奖励物品数量"

[[variables]]
name="DoubleMan"
type="int32"
tag="double_man"
comment="双人奖励倍数（物品不生效，向上取整）"

[[variables]]
name="CollectLimitCount"
type="int32"
tag="caiji_limit_count"
comment="采集次数限制"

