file="moon_love_rank_vo.go"
pkg="template"
class="MoonloveRankTemplateVO"
comment = "月下情缘排行榜配置"
[[variables]]
name="Id"
type="int"
tag="id"
comment="id"

[[variables]]
name="Type"
type="int32"
tag="type"
comment="0豪气榜1魅力榜"

[[variables]]
name="Rank"
type="int32"
tag="rank"
comment="排名"

[[variables]]
name="RewExp"
type="int64"
tag="rew_exp"
comment="奖励经验值"

[[variables]]
name="RewExpPoint"
type="int32"
tag="rew_exp_point"
comment="奖励经验点"

[[variables]]
name="RewSilver"
type="int64"
tag="rew_silver"
comment="奖励银两"

[[variables]]
name="RewGold"
type="int32"
tag="rew_gold"
comment="奖励元宝"

[[variables]]
name="RewBindGold"
type="int32"
tag="rew_bind_gold"
comment="奖励绑定元宝"

[[variables]]
name="RewItemId"
type="string"
tag="rew_item_id"
comment="奖励物品Id"

[[variables]]
name="RewItemCount"
type="string"
tag="rew_item_count"
comment="奖励物品数量"
