file="my_boss_vo.go"
pkg="template"
class="MyBossTemplateVO"
comment = "个人boss配置"
[[variables]]
name="Id"
type="int"
tag="id"
comment="id"

[[variables]]
name="Type"
type="int32"
tag="type"
comment="boss类型"

[[variables]]
name="NeedVipLevel"
type="int32"
tag="need_vip_level"
comment="vip等级限制"

[[variables]]
name="BiologyId"
type="int32"
tag="biology_id"
comment="生物id"

[[variables]]
name="MapId"
type="int32"
tag="map_id"
comment="地图id"

[[variables]]
name="FreeTimes"
type="int32"
tag="free_times"
comment="免费次数"

[[variables]]
name="TimesCount"
type="int32"
tag="times_count"
comment="总次数"

[[variables]]
name="UseItem"
type="int32"
tag="use_item"
comment="挑战所需物品"

[[variables]]
name="UseCount"
type="int32"
tag="use_count"
comment="挑战所需物品数量"