file="onearena_vo.go"
pkg="template"
class="OneArenaTemplateVO"
comment = "灵池争夺配置"
[[variables]]
name="Id"
type="int"
tag="id"
comment="id"

[[variables]]
name="NextId"
type="int32"
tag="next_id"
comment="下一个id"

[[variables]]
name="Name"
type="string"
tag="name"
comment="灵池名字"

[[variables]]
name="Level"
type="int32"
tag="level"
comment="灵池等级"

[[variables]]
name="PosId"
type="int32"
tag="pos_id"
comment="灵池位置"

[[variables]]
name="MapId"
type="int32"
tag="map_id"
comment="战斗场景地图id"

[[variables]]
name="BiologyId"
type="int32"
tag="biology_id"
comment="灵池守护者关联生物表id"

[[variables]]
name="DropId"
type="string"
tag="drop_id"
comment="掉落id"

[[variables]]
name="RefreshTime"
type="int32"
tag="refresh_time"
comment="奖励发送时间"

[[variables]]
name="CoolTime"
type="int32"
tag="cool_time"
comment="战斗失败冷却时间"

[[variables]]
name="RewItemId"
type="string"
tag="rew_item_id"
comment="奖励预览"


[[variables]]
name="PosX"
type="float64"
tag="pos_x"
comment="灵池守卫坐标x"

[[variables]]
name="PosY"
type="float64"
tag="pos_y"
comment="灵池守卫坐标y"

[[variables]]
name="PosZ"
type="float64"
tag="pos_z"
comment="灵池守卫坐标z"


