file="open_activity_xunhun_vo.go"
pkg="template"
class="OpenActivityXunHuanTemplateVO"
comment = "循环活动配置"

[[variables]]
name="Id"
type="int"
tag="id"
comment="id"

[[variables]]
name="TimeType"
type="int32"
tag="time_type"
comment="开服时间分组"

[[variables]]
name="ArrIndex"
type="int32"
tag="type"
comment="活动分组"

[[variables]]
name="CycleDay"
type="int32"
tag="time" 
comment="循环日"

[[variables]]
name="GroupId"
type="string" 
tag="group_id"
comment="活动标识ID"

