file="open_activity_xunhun_time_vo.go"
pkg="template"
class="OpenActivityXunHuanTimeTemplateVO"
comment = "循环活动时间配置"

[[variables]]
name="Id"
type="int"
tag="id"
comment="id"

[[variables]]
name="TimeType"
type="int32"
tag="time_type"
comment="开服时间分组"
  
[[variables]]
name="OpentimeBegin"
type="int32"
tag="opentime_begin" 
comment="开服起始天数"

[[variables]]
name="OpentimeFinish"
type="int32" 
tag="opentime_finish"
comment="开服结束天数"

