file="openserver_activity_vo.go"
pkg="template"
class="OpenserverActivityTemplateVO"
comment = "开服活动配置"

[[variables]]
name="Id"
type="int"
tag="id"
comment="id"

[[variables]]
name="Group"
type="int32"
tag="group"
comment="活动标识"

[[variables]]
name="Type"
type="int32"
tag="type"
comment="活动类型"

[[variables]]
name="SubType"
type="int32"
tag="subtype"
comment="活动子类型"

[[variables]]
name="Value1"
type="int32"
tag="value_1"
comment="参数1"

[[variables]]
name="Value2"
type="int32"
tag="value_2"
comment="参数2"

[[variables]]
name="Value3"
type="int32"
tag="value_3"
comment="参数3"

[[variables]]
name="Value4"
type="int32"
tag="value_4"
comment="参数4"

[[variables]]
name="RewSilver"
type="int32"
tag="rew_silver"
comment="奖励银两"

[[variables]]
name="RewGold"
type="int32"
tag="rew_gold"
comment="奖励元宝"

[[variables]]
name="RewGoldBind"
type="int32"
tag="rew_gold_bind"
comment="奖励绑元"

[[variables]]
name="AwardItemId"
type="string"
tag="award_item_id"
comment="奖励物品id"

[[variables]]
name="AwardItemCount"
type="string"
tag="award_item_count"
comment="奖励物品数量"

[[variables]]
name="Label"
type="string"
tag="label"
comment="活动名"

[[variables]]
name="MailDes"
type="string"
tag="mail_des"
comment="邮件内容"

[[variables]]
name="TimeType"
type="int32"
tag="time_type"
comment="过期类型"

[[variables]]
name="LimitTime"
type="int32" 
tag="limit_time" 
comment="过期时间"

[[variables]]
name="ItemExpireFlag"
type="string" 
tag="item_expire_flag" 
comment="物品过期标识"
