file="openserver_time_vo.go"
pkg="template"
class="OpenserverTimeTemplateVO"
comment = "开服活动时间配置"

[[variables]]
name="Id"
type="int"
tag="id"
comment="id"

[[variables]]
name="Group"
type="int32"
tag="group"
comment="活动标识"

[[variables]]
name="Name"
type="string"
tag="name"
comment="活动名称"

[[variables]]
name="Type"
type="int32"
tag="type"
comment="活动类型"

[[variables]]
name="SubType"
type="int32"
tag="subtype"
comment="活动子类型"

[[variables]]
name="TimeType"
type="int32"
tag="time_type"
comment="活动时间类型"

[[variables]]
name="Value1"
type="int64"
tag="value_1"
comment="参数1"

[[variables]]
name="Value2"
type="int64"
tag="value_2"
comment="参数2"

[[variables]]
name="OpenId"
type="int32"
tag="open_id"
comment="关联功能开启"

[[variables]]
name="MailTitle"
type="string"
tag="mail_title"
comment="功能开启邮件标题"

[[variables]]
name="MailDes"
type="string"
tag="mail_des"
comment="功能开启邮件内容"

[[variables]]
name="MailRewItem"
type="string"
tag="mail_rew_item"
comment="功能开启奖励"

[[variables]]
name="MailRewItemCount"
type="string"
tag="mail_rew_item_count"
comment="功能开启奖励数量"

[[variables]]
name="RelatedActivity"
type="string"
tag="related_activity"
comment="关联活动"

[[variables]]
name="IsCircle"
type="int32"
tag="is_circle"
comment="是否循环活动"

[[variables]]
name="IsMergeCircle"
type="int32"
tag="is_hefu_circle"
comment="是否合服循环活动"

[[variables]]
name="CloseOpenDay"
type="int32"
tag="close_open_day"
comment="开服几天不开启"

[[variables]]
name="IsChuanyin"
type="int32"
tag="is_chuanyin"
comment="是否传音"

[[variables]]
name="ChuanyinText"
type="string"
tag="chuanyin_text"
comment="传音内容"