file="outland_boss_vo.go"
pkg="template"
class="OutlandBossTemplateVO"
comment = "外域boss配置"
[[variables]]
name="Id"
type="int"
tag="id"
comment="id"

[[variables]]
name="Type"
type="int32"
tag="type"
comment="boss类型"

[[variables]]
name="BiologyId"
type="int32"
tag="biology_id"
comment="生物id"

[[variables]]
name="MapId"
type="int32"
tag="map_id"
comment="地图id"

[[variables]]
name="Rate"
type="int32"
tag="rate"
comment="假掉落记录出现概率"

[[variables]]
name="RecForce"
type="int64"
tag="rec_force"
comment="战力推荐"

