file="player_create_vo.go"
pkg="template"
class="PlayerCreateTemplateVO"
comment = "角色初始化配置"

[[variables]]
name="Id"
type="int"
tag="id"
comment="id"

[[variables]]
name="Gender"
type="int32"
tag="gender"
comment="性别"

[[variables]]
name="MapId"
type="int32"
tag="map_id"
comment="地图id"

[[variables]]
name="PositionX"
type="float64"
tag="position_x"
comment="位置x"

[[variables]]
name="PositionY"
type="float64"
tag="position_y"
comment="位置y"

[[variables]]
name="Orientation"
type="int32"
tag="orientation"
comment="朝向"

[[variables]]
name="FaceIcon"
type="int32"
tag="face_icon"
comment="头像"

[[variables]]
name="Money"
type="int32"
tag="money"
comment="银两"

[[variables]]
name="Equipmentstr"
type="int32"
tag="equipmentstr"
comment="装备"

[[variables]]
name="Defaultmodelid"
type="int32"
tag="defaultmodelid"
comment="默认模型"

[[variables]]
name="Spell"
type="string"
tag="spell"
comment="技能"

[[variables]]
name="Item"
type="string"
tag="item"
comment="物品"


[[variables]]
name="Zhiye"
type="int32"
tag="zhiye"
comment="职业"

[[variables]]
name="WeaponId"
type="int32"
tag="weapon_id"
comment="职业"

[[variables]]
name="FashionId"
type="int32"
tag="fashion_id"
comment="时装id"

[[variables]]
name="Juexue"
type="int32"
tag="juexue"
comment="出生自带绝学"

[[variables]]
name="JumpId"
type="int32"
tag="jump_id"
comment="跳跃id"

[[variables]]
name="Mount"
type="int32"
tag="mount"
comment="初始坐骑"

[[variables]]
name="Wing"
type="int32"
tag="wing"
comment="初始战翼"

[[variables]]
name="Field"
type="int32"
tag="field"
comment="初始领域"

[[variables]]
name="Shenfa"
type="int32"
tag="shenfa"
comment="初始身法"

[[variables]]
name="BodyShield"
type="int32"
tag="body_shield"
comment="初始护盾"

[[variables]]
name="Feather"
type="int32"
tag="feather"
comment="初始护羽"

[[variables]]
name="Shield"
type="int32"
tag="shield"
comment="初始神盾"

[[variables]]
name="Anqi"
type="int32"
tag="anqi"
comment="初始暗器"

[[variables]]
name="Massacre"
type="int32"
tag="massacre"
comment="初始戮仙刃"

[[variables]]
name="FaBao"
type="int32"
tag="fabao"
comment="初始法宝"

[[variables]]
name="XianTi"
type="int32"
tag="xianti"
comment="初始仙体"

[[variables]]
name="TianMoTi"
type="int32"
tag="tianmoti"
comment="初始天魔体"

[[variables]]
name="ShiXueFan"
type="int32"
tag="shixuefan"
comment="初始嗜血幡"

[[variables]]
name="TitleId"
type="int32"
tag="title_id"
comment="称号id"

[[variables]]
name="QiXue"
type="int32"
tag="qixue"
comment="泣血枪"

