

file="portal_vo.go"
pkg="template"
class="PortalTemplateVO"
comment = "传送点配置"

[[variables]]
name="Id"
type="int"
tag="id"
comment="id"

[[variables]]
name="Name"
type="string"
tag="name"
comment="名字"

[[variables]]
name="MapId"
type="int32"
tag="map_id"
comment="地图id"

[[variables]]
name="PosX"
type="int32"
tag="pos_x"
comment="位置x"

[[variables]]
name="PosY"
type="int32"
tag="pos_y"
comment="位置y"

[[variables]]
name="PosZ"
type="int32"
tag="pos_z"
comment="位置z"
