

file="qixue_constant_vo.go"
pkg="template"
class="QiXueConstantTemplateVO"
comment = "泣血枪常量配置"
[[variables]]
name="Id"
type="int"
tag="id"
comment="id"

[[variables]]
name="DropRate"
type="int32"
tag="resources_drop_rate"
comment="杀戮心掉落概率"

[[variables]]
name="DropPercentMin"
type="int32"
tag="resources_drop_percent_min"
comment="杀戮心掉落万分比下限"

[[variables]]
name="DropPercentMax"
type="int32"
tag="resources_drop_percent_max"
comment="杀戮心掉落万分比上限"

[[variables]]
name="DropCd"
type="int32"
tag="resources_drop_cd"
comment="掉落CD"

[[variables]]
name="DropProtectedTime"
type="int32"
tag="resources_drop_protected_time"
comment="杀戮心保护时间"

[[variables]]
name="DropFailTime"
type="int32"
tag="resources_drop_fail_time"
comment="杀戮心存在时间"

[[variables]]
name="DropMinStack"
type="int32"
tag="resources_drop_min_stack"
comment="最小堆数"

[[variables]]
name="DropMaxStack"
type="int32"
tag="resources_drop_max_stack"
comment="最大堆数"

[[variables]]
name="DropSystemReturn"
type="int32"
tag="resources_drop_system_return"
comment="背包掉落杀戮心系统回收系数"

