file="qixue_vo.go"
pkg="template"
class="QiXueTemplateVO"
comment = "泣血枪配置"
[[variables]]
name="Id"
type="int"
tag="id"
comment="id"

[[variables]]
name="Level"
type="int32"
tag="type"
comment="泣血枪的等级"

[[variables]]
name="NextId"
type="int32"
tag="next_id"
comment="下一个id"

[[variables]]
name="Star"
type="int32"
tag="star"
comment="不同阶别下对应的星数"

[[variables]]
name="UseResources"
type="int32"
tag="use_resources"
comment="升级需要的杀戮心"

[[variables]]
name="WeaponId"
type="int32"
tag="weapon_id"
comment="获得兵魂ID"

[[variables]]
name="GasMin"
type="int32"
tag="resources_min"
comment="死亡时掉落星级下限"

[[variables]]
name="GasMax"
type="int32"
tag="resources_max"
comment="死亡时掉落星级上限"

[[variables]]
name="GasPercent"
type="int32"
tag="resources_percent"
comment="掉落星级概率"

[[variables]]
name="StarCount"
type="int32"
tag="star_count"
comment="每个星星代表的杀戮心值"

[[variables]]
name="Hp"
type="int32"
tag="hp"
comment="生命"

[[variables]]
name="Attack"
type="int32"
tag="attack"
comment="攻击"

[[variables]]
name="Defence"
type="int32"
tag="defence"
comment="防御"
