file="qiyu_vo.go"
pkg="template"
class="QiYuTemplateVO"
comment = "奇遇模板配置"
[[variables]]
name="Id"
type="int"
tag="id"
comment="id"

[[variables]]
name="Level"
type="string"
tag="level"
comment="接取任务等级"

[[variables]]
name="ZhuanSheng"
type="string"
tag="zhuansheng"
comment="接取转生等级"

[[variables]]
name="FeiSheng"
type="string"
tag="feisheng"
comment="接取飞升等级"

[[variables]]
name="QuestId"
type="string"
tag="quest_id"
comment="奇遇子任务"

[[variables]]
name="RewExp"
type="int32"
tag="rew_exp"
comment="经验"

[[variables]]
name="RewExpPoint"
type="int32"
tag="rew_exp_point"
comment="经验点"

[[variables]]
name="RewSilver"
type="int32"
tag="rew_silver"
comment="奖励银两"

[[variables]]
name="RewBindGold"
type="int32"
tag="rew_bind_gold"
comment="奖励绑定元宝"

[[variables]]
name="RewGold"
type="int32"
tag="rew_gold"
comment="奖励元宝"

[[variables]]
name="RewItemId"
type="string"
tag="rew_item_id" 
comment="奖励物品Id"

[[variables]]
name="RewItemCount"
type="string"
tag="rew_item_count"
comment="奖励物品数量"

[[variables]]
name="GuoQiTime"
type="int32"
tag="guoqi_time"
comment="过期时间"
