file="quest_vo.go"
pkg="template"
class="QuestTemplateVO"
comment = "任务配置"
[[variables]]
name="Id"
type="int"
tag="id"
comment="id"

[[variables]]
name="IsAutoFinishFree"
type="int"
tag="is_auto_finish_free"
comment="免费次数用完是否直接完成任务"

[[variables]]
name="Name"
type="string"
tag="name"
comment="任务名称"

[[variables]]
name="QuestTag"
type="int32"
tag="quest_tag"
comment="标签"

[[variables]]
name="QuestType"
type="int32"
tag="quest_type"
comment="任务类型"

[[variables]]
name="QuestSubType"
type="int32"
tag="quest_sub_type"
comment="任务子类型"

[[variables]]
name="QuestDemand"
type="string"
tag="quest_demand"
comment="任务要求(开天)"

[[variables]]
name="QuestDemandCount"
type="string"
tag="quest_demand_count"
comment="任务要求数量(开天)"

[[variables]]
name="QuestDemand2"
type="string"
tag="quest_demand2"
comment="任务要求(奕剑)"

[[variables]]
name="QuestDemandCount2"
type="string"
tag="quest_demand_count2"
comment="任务要求数量(奕剑)"

[[variables]]
name="QuestDemand3"
type="string"
tag="quest_demand3"
comment="任务要求(破月)"

[[variables]]
name="QuestDemandCount3"
type="string"
tag="quest_demand_count3"
comment="任务要求数量(破月)"

[[variables]]
name="ReqZhuanshu"
type="int32"
tag="req_zhuanshu"
comment="任务需要的转数"

[[variables]]
name="ReqLevel"
type="int32"
tag="req_level"
comment="任务需要的等级"

[[variables]]
name="ReqItemId"
type="string"
tag="req_item_id"
comment="任务物品id(开天)"

[[variables]]
name="ReqItemCount"
type="string"
tag="req_item_count"
comment="任务物品数量(开天)"

[[variables]]
name="ReqItemId2"
type="string"
tag="req_item_id2"
comment="任务物品id(奕剑)"

[[variables]]
name="ReqItemCount2"
type="string"
tag="req_item_count2"
comment="任务物品数量(奕剑)"

[[variables]]
name="ReqItemId3"
type="string"
tag="req_item_id3"
comment="任务物品id(破月)"

[[variables]]
name="ReqItemCount3"
type="string"
tag="req_item_count3"
comment="任务物品数量(破月)"

[[variables]]
name="PrevQuest"
type="string"
tag="prev_quest"
comment="前置任务"

[[variables]]
name="NextQuest"
type="string"
tag="next_quest"
comment="后置任务"


[[variables]]
name="FollowId"
type="string"
tag="follow_id"
comment="后续非主线任务id"

[[variables]]
name="AcceptCreature"
type="int32"
tag="accept_creature"
comment="任务npcId"


[[variables]]
name="CommitCreature"
type="int32"
tag="commit_creature"
comment="执行任务npcid"


[[variables]]
name="IsAutoCommi"
type="int32"
tag="is_auto_commi"
comment="是否自动完成"


[[variables]]
name="IsPopReward"
type="int32"
tag="is_pop_reward"
comment="是否有额外的任务奖励"

[[variables]]
name="Objectives"
type="string"
tag="objectives"
comment="任务文本"

[[variables]]
name="EndText"
type="string"
tag="end_text"
comment="结束对话"

[[variables]]
name="AcceptTaskText"
type="string"
tag="accept_task_text"
comment="接受任务对话"

[[variables]]
name="DeliverTaskText"
type="string"
tag="deliver_task_text"
comment="完成任务时对话"

[[variables]]
name="QuestLevel"
type="int32"
tag="quest_level"
comment="任务品质"

[[variables]]
name="QuestTb"
type="int32"
tag="quest_tb"
comment="任务标记,屠魔任务用到"

[[variables]]
name="SpecialConditions"
type="int32"
tag="special_conditions"
comment="特殊条件"

[[variables]]
name="MinLevel"
type="int32"
tag="min_level"
comment="最小等级"

[[variables]]
name="MaxLevel"
type="int32"
tag="max_level"
comment="最大等级"

[[variables]]
name="MinZhuanshu"
type="int32"
tag="min_zhuanshu"
comment="最小转数"

[[variables]]
name="MaxZhuanshu"
type="int32"
tag="max_zhuanshu"
comment="最大转数"

[[variables]]
name="ConsumeSilver"
type="int32"
tag="consume_silver"
comment="消耗银两"

[[variables]]
name="ConsumeGold"
type="int32"
tag="consume_gold"
comment="消耗元宝"

[[variables]]
name="ConsumeItem"
type="string"
tag="consume_item"
comment="消耗物品(开天)"

[[variables]]
name="ConsumeItemCount"
type="string"
tag="consume_item_count"
comment="消耗物品数量(开天)"

[[variables]]
name="ConsumeItem2"
type="string"
tag="consume_item2"
comment="消耗物品(奕剑)"

[[variables]]
name="ConsumeItemCount2"
type="string"
tag="consume_item_count2"
comment="消耗物品数量(奕剑)"

[[variables]]
name="ConsumeItem3"
type="string"
tag="consume_item3"
comment="消耗物品(破月)"

[[variables]]
name="ConsumeItemCount3"
type="string"
tag="consume_item_count3"
comment="消耗物品数量(破月)"


[[variables]]
name="RewItemId1"
type="string"
tag="rew_item_id_1"
comment="奖励物品id1"

[[variables]]
name="RewItemCount1"
type="string"
tag="rew_item_count_1"
comment="奖励物品id1数量"

[[variables]]
name="RewItemId2"
type="string"
tag="rew_item_id_2"
comment="奖励物品id2"

[[variables]]
name="RewItemCount2"
type="string"
tag="rew_item_count_2"
comment="奖励物品id2数量"


[[variables]]
name="RewItemId3"
type="string"
tag="rew_item_id_3"
comment="奖励物品id3"

[[variables]]
name="RewItemCount3"
type="string"
tag="rew_item_count_3"
comment="奖励物品id3数量"

[[variables]]
name="RewXp"
type="int32"
tag="rew_xp"
comment="奖励经验"

[[variables]]
name="RewExpPoint"
type="int32"
tag="rew_exp_point"
comment="奖励经验点"


[[variables]]
name="RewSilver"
type="int32"
tag="rew_silver"
comment="奖励银两"

[[variables]]
name="RewGold"
type="int32"
tag="rew_gold"
comment="奖励元宝"

[[variables]]
name="RewBindGold"
type="int32"
tag="rew_bind_gold"
comment="奖励绑定元宝"

[[variables]]
name="RewZhuanshu"
type="int32"
tag="rew_zhuanshu"
comment="奖励转数"

[[variables]]
name="AcceptSound"
type="string"
tag="accept_sound"
comment="接受声音"

[[variables]]
name="ExcutedSound"
type="string"
tag="excuted_sound"
comment="执行声音"

[[variables]]
name="AutoTrack"
type="int32"
tag="auto_track"
comment="自动寻路"

[[variables]]
name="IsShowArrow"
type="int32"
tag="is_show_arrow"
comment="引导箭头"

[[variables]]
name="PriorityLevel"
type="int32"
tag="priority_level"
comment="优先级"

[[variables]]
name="IsDeliver"
type="int32"
tag="is_deliver"
comment="窗提示玩家传送到任务目标所在的地图与坐标 0为否1为是"

[[variables]]
name="WindowId"
type="string"
tag="window_id"
comment="弹出相关id"

[[variables]]
name="DirectNumber"
type="int32"
tag="direct_number"
comment="特殊任务类型时使用 天机牌"

[[variables]]
name="IsFeiXie"
type="int32"
tag="is_feixie"
comment="消耗的飞鞋数量"

[[variables]]
name="Tiaoyuedian"
type="int32"
tag="tiaoyuedian"
comment="跳跃点"

[[variables]]
name="FubenId"
type="int32"
tag="fuben_id"
comment="副本id"






