file="quiz_constant_vo.go"
pkg="template"
class="QuizConstantTemplateVO"
comment = "仙尊问答常量模板配置"
[[variables]]
name="Id"
type="int"
tag="id"
comment="id"

[[variables]]
name="BeginTime"
type="string"
tag="activity_begin_time"
comment="问答活动开始时间"

[[variables]]
name="EndTime"
type="string"
tag="activity_end_time"
comment="问答活动结束时间"

[[variables]]
name="RefreshTime"
type="string"
tag="refresh_time"
comment="必定刷新的时间点配置"

[[variables]]
name="IntervalTime"
type="int32"
tag="interval_time"
comment="题目刷新间隔时间(毫秒)"

[[variables]]
name="DaTiTime"
type="int32"
tag="dati_time"
comment="每题题目的答题时间"

[[variables]]
name="MsgTimeMin"
type="int32"
tag="msg_time_min"
comment="假消息时间下限(毫秒)"

[[variables]]
name="MsgTimeMax"
type="int32"
tag="msg_time_max"
comment="假消息时间上限(毫秒)"
