file="quiz_vo.go"
pkg="template"
class="QuizTemplateVO"
comment = "仙尊问答配置"
[[variables]]
name="Id"
type="int"
tag="id"
comment="id"


[[variables]]
name="AnswerA"
type="string"
tag="answer_1"
comment="答题内容1"

[[variables]]
name="AnswerB"
type="string"
tag="answer_2"
comment="答题内容2"

[[variables]]
name="AnswerC"
type="string"
tag="answer_3"
comment="答题内容3"

[[variables]]
name="AnswerD"
type="string"
tag="answer_4"
comment="答题内容4"

[[variables]]
name="QuanZhong"
type="int32"
tag="quanzhong"
comment="出现概率权重"

[[variables]]
name="RightAnswer"
type="int32"
tag="right_answer"
comment="正确答案"

[[variables]]
name="RewExp"
type="int32"
tag="rew_exp"
comment="答对奖励经验点"

[[variables]]
name="RewExpPoint"
type="int32"
tag="rew_exp_point"
comment="答对奖励经验点"

[[variables]]
name="RewardSilver"
type="int32"
tag="reward_silver"
comment="答对奖励银两"

[[variables]]
name="RewardBindGold"
type="int32"
tag="reward_bindgold"
comment="答对奖励绑元"

[[variables]]
name="RewardGold"
type="int32"
tag="reward_gold"
comment="答对奖励元宝"

[[variables]]
name="RewardItemRate"
type="int32"
tag="reward_item_rate"
comment="答对奖励物品的概率"

[[variables]]
name="RewItemId"
type="string"
tag="rew_item_id"
comment="答对奖励物品"

[[variables]]
name="RewItemCount"
type="string"
tag="rew_item_count"
comment="答对奖励物品数量"

[[variables]]
name="ErrorRewExp"
type="int32"
tag="error_rew_exp"
comment="答错奖励经验点"

[[variables]]
name="ErrorRewExpPoint"
type="int32"
tag="error_rew_exp_point"
comment="答错奖励经验点"

[[variables]]
name="ErrorRewardSilver"
type="int32"
tag="error_reward_silver"
comment="答错奖励银两"

[[variables]]
name="ErrorRewardBindGold"
type="int32"
tag="error_reward_bindgold"
comment="答错奖励绑元"

[[variables]]
name="ErrorRewardGold"
type="int32"
tag="error_reward_gold"
comment="答错奖励元宝"

[[variables]]
name="ErrorRewardItemRate"
type="int32"
tag="error_reward_item_rate"
comment="答错奖励物品的概率"

[[variables]]
name="ErrorRewItemId"
type="string"
tag="error_rew_item_id"
comment="答错奖励物品"

[[variables]]
name="ErrorRewItemCount"
type="string"
tag="error_rew_item_count"
comment="答错奖励物品数量"
