file="recruit_money_vo.go"
pkg="template"
class="GoldPigTemplateVO"
comment = "元宝金猪模板配置"
[[variables]]
name="Id"
type="int"
tag="id"
comment="id"

[[variables]]
name="NextId"
type="int"
tag="next_id"
comment="下一级id"

[[variables]]
name="Group"
type="int32"
tag="group"
comment="活动id"

[[variables]]
name="NeedRecharge"
type="int32"
tag="need_recharge"
comment="需充值数"

[[variables]]
name="ReturnPercent"
type="int32"
tag="return_percent"
comment="返回比例"

