file="return_xitong_vo.go"
pkg="template"
class="ReturnXiTongTemplateVO"
comment = "升阶系统补偿配置"
[[variables]]
name="Id"
type="int"
tag="id"
comment="id"
 
[[variables]]
name="Number"
type="int32"
tag="number"
comment="阶数"

[[variables]]
name="Type"
type="int32"
tag="type"
comment="系统类型"
 
[[variables]]
name="ReturnItemId"
type="string"
tag="return_item_id"
comment="补偿的物品id"

[[variables]]
name="ReturnItemCount"
type="string"
tag="return_item_count"
comment="补偿的物品数量"
 