file="ring_advance_vo.go"
pkg="template"
class="RingAdvanceTemplateVO"
comment = "特戒进阶配置"

[[variables]]
name="Id"
type="int"
tag="id"
comment="id"

[[variables]]
name="NextId"
type="int32"
tag="next_id"
comment="下一个id"

[[variables]]
name="Advance"
type="int32"
tag="number"
comment="阶数"

[[variables]]
name="UpdateWfb"
type="int32"
tag="update_wfb"
comment="升阶成功率"

[[variables]]
name="UseItem"
type="int32"
tag="use_item"
comment="升阶所需物品id"

[[variables]]
name="ItemCount"
type="int32"
tag="item_count"
comment="升阶所需物品数量"

[[variables]]
name="TimesMin"
type="int32"
tag="times_min"
comment="最小次数"

[[variables]]
name="TimesMax"
type="int32"
tag="times_max"
comment="最大次数"

[[variables]]
name="AddMin"
type="int32"
tag="add_min"
comment="增加的最小祝福值"

[[variables]]
name="AddMax"
type="int32"
tag="add_max"
comment="增加的最大祝福值"


[[variables]]
name="ZhufuMax"
type="int32"
tag="zhufu_max"
comment="前端显示的祝福值"

[[variables]]
name="Hp"
type="int64"
tag="hp"
comment="该类型增加的生命"

[[variables]]
name="Attack"
type="int64"
tag="attack"
comment="该类型增加的攻击"

[[variables]]
name="Defence"
type="int64"
tag="defence"
comment="该类型增加的防御"

[[variables]]
name="HpPercent"
type="int32"
tag="hp_percent"
comment="生命万分比"

[[variables]]
name="AttackPercent"
type="int32"
tag="attack_percent"
comment="攻击万分比"

[[variables]]
name="DefPercent"
type="int64"
tag="def_percent"
comment="防御万分比"

[[variables]]
name="IsClear"
type="int32"
tag="is_clear"
comment="升阶后祝福值 0不清 1清"