file="ring_vo.go"
pkg="template"
class="RingTemplateVO"
comment = "特戒配置"

[[variables]]
name="Id"
type="int"
tag="id"
comment="物品id"

[[variables]]
name="Type"
type="int32"
tag="type"
comment="特戒类型"

[[variables]]
name="AdvanceBeginId"
type="int32"
tag="jinjie_begin_id"
comment="进阶起始id"

[[variables]]
name="StrengthenBeginId"
type="int32"
tag="strengthen_begin_id"
comment="强化起始id"

[[variables]]
name="JingLingBeginId"
type="int32"
tag="jingling_begin_id"
comment="净灵起始id"

[[variables]]
name="Level"
type="int32"
tag="level"
comment="特戒融合等级"

[[variables]]
name="Hp"
type="int64"
tag="hp"
comment="该类型增加的生命"

[[variables]]
name="Attack"
type="int64"
tag="attack"
comment="该类型增加的攻击"

[[variables]]
name="Defence"
type="int64"
tag="defence"
comment="该类型增加的防御"

[[variables]]
name="SkillId"
type="int32"
tag="skill_id"
comment="特戒技能"

[[variables]]
name="FuseSynthesisId"
type="int32"
tag="ronghe_synthesis_id"
comment="融合合成id"