file="ring_fuse_synthesis_vo.go"
pkg="template"
class="RingFuseSynthesisTemplateVO"
comment = "特戒融合合成配置"

[[variables]]
name="Id"
type="int"
tag="id"
comment="id"

[[variables]]
name="NeedItemId1"
type="int32"
tag="need_item_id_1"
comment="合成所需物品1id"

[[variables]]
name="NeedItemCount1"
type="int32"
tag="need_item_count_1"
comment="合成所需物品1数量"

[[variables]]
name="NeedItemId2"
type="int32"
tag="need_item_id_2"
comment="合成所需物品2id"

[[variables]]
name="NeedItemCount2"
type="int32"
tag="need_item_count_2"
comment="合成所需物品2数量"

[[variables]]
name="ItemId"
type="int32"
tag="item_id"
comment="合成后物品id"

[[variables]]
name="ItemCount"
type="int32"
tag="item_count"
comment="合成后物品数量"

[[variables]]
name="SuccessRate"
type="int32"
tag="success_rate"
comment="合成成功率万分比"

[[variables]]
name="NeedSilver"
type="int32"
tag="need_silver"
comment="合成所需银两"

[[variables]]
name="NeedGold"
type="int32"
tag="need_gold"
comment="合成所需元宝"

[[variables]]
name="NeedBindGold"
type="int32"
tag="need_bind_gold"
comment="合成所需绑元"
