file="ring_baoku_vo.go"
pkg="template"
class="RingBaoKuTemplateVO"
comment = "特戒宝库掉落配置"

[[variables]]
name="Id"
type="int"
tag="id"
comment="id"

[[variables]]
name="Type"
type="int32"
tag="type"
comment="宝库类型"

[[variables]]
name="DropId"
type="int32"
tag="drop_id"
comment="掉落包id"

[[variables]]
name="MustGet1"
type="string"
tag="must_get1"
comment="一定次数必定获取的掉落包"

[[variables]]
name="MustAmount1"
type="string"
tag="must_amount1"
comment="参与次数"

[[variables]]
name="SilverUse"
type="int32"
tag="silver_use"
comment="银两消耗"

[[variables]]
name="GoldUse"
type="int32"
tag="gold_use"
comment="元宝消耗"

[[variables]]
name="BindGoldUse"
type="int32"
tag="bindgold_use"
comment="绑元消耗"

[[variables]]
name="UseItemId"
type="int32"
tag="use_item_id"
comment="消耗物品id"

[[variables]]
name="UseItemCount"
type="int32"
tag="use_item_count"
comment="消耗物品数量"

[[variables]]
name="GiftJiFen"
type="int32"
tag="get_jifen"
comment="探寻一次获得的积分"

[[variables]]
name="GiftXingYunZhi"
type="int32"
tag="get_xingyunzhi"
comment="探寻一次获得的幸运值"

[[variables]]
name="NeedXingYunZhi"
type="int32"
tag="need_xingyunzhi"
comment="幸运宝箱需要的幸运值"

[[variables]]
name="ScriptXingYun"
type="int32"
tag="script_xingyun"
comment="幸运宝箱掉落id"