file="ring_jingling_vo.go"
pkg="template"
class="RingJingLingTemplateVO"
comment = "特戒净灵配置"

[[variables]]
name="Id"
type="int"
tag="id"
comment="id"

[[variables]]
name="NextId"
type="int32"
tag="next_id"
comment="下一个id"

[[variables]]
name="Level"
type="int32"
tag="level"
comment="净灵等级"

[[variables]]
name="UpdateWfb"
type="int32"
tag="update_wfb"
comment="净灵成功率"

[[variables]]
name="UseItem"
type="int32"
tag="need_item_id"
comment="净灵所需物品id"

[[variables]]
name="ItemCount"
type="int32"
tag="need_item_count"
comment="净灵所需物品数量"

[[variables]]
name="TimesMin"
type="int32"
tag="times_min"
comment="最小次数"

[[variables]]
name="TimesMax"
type="int32"
tag="times_max"
comment="最大次数"

[[variables]]
name="AddMin"
type="int32"
tag="add_min"
comment="增加的最小祝福值"

[[variables]]
name="AddMax"
type="int32"
tag="add_max"
comment="增加的最大祝福值"


[[variables]]
name="ZhufuMax"
type="int32"
tag="zhufu_max"
comment="前端显示的祝福值"

[[variables]]
name="Hp"
type="int64"
tag="hp"
comment="该类型增加的生命"

[[variables]]
name="Attack"
type="int64"
tag="attack"
comment="该类型增加的攻击"

[[variables]]
name="Defence"
type="int64"
tag="defence"
comment="该类型增加的防御"