file="robot_vo.go"
pkg="template"
class="RobotTemplateVO"
comment = "机器人配置"
[[variables]]
name="Id"
type="int"
tag="id"
comment="id"

[[variables]]
name="NeedProfession"
type="string"
tag="need_profession"
comment="需要职业"

[[variables]]
name="NeedGender"
type="string"
tag="need_gender"
comment="性别"

[[variables]]
name="LevMin"
type="int32"
tag="level_min"
comment="等级最小"

[[variables]]
name="LevMax"
type="int32"
tag="level_max"
comment="等级最大"

[[variables]]
name="ForceMin"
type="int64"
tag="force_min"
comment="战力"

[[variables]]
name="ForceMax"
type="int64"
tag="force_max"
comment="战力"



[[variables]]
name="FashionId"
type="string"
tag="fashion_id"
comment="时装"

[[variables]]
name="WeaponId"
type="string"
tag="weapon_id"
comment="冰魂"

[[variables]]
name="WingId"
type="string"
tag="wing_id"
comment="战翼"


[[variables]]
name="MountId"
type="string"
tag="mount_id"
comment="坐骑"

[[variables]]
name="FabaoId"
type="string"
tag="fabao_id"
comment="法宝"

[[variables]]
name="ShenfaId"
type="string"
tag="shenfa_id"
comment="身法"


[[variables]]
name="XiantiId"
type="string"
tag="xianti_id"
comment="仙体"

[[variables]]
name="FieldId"
type="string"
tag="field_id"
comment="领域"

[[variables]]
name="TitleId"
type="string"
tag="title_id"
comment="称号"

[[variables]]
name="SkillJuexueId"
type="string"
tag="skill_juexue_id"
comment="绝学"

[[variables]]
name="SkillSoulId"
type="string"
tag="skill_soul_id"
comment="帝魂"


[[variables]]
name="LingTongId"
type="string"
tag="lingtong_id"
comment="灵童"

[[variables]]
name="LingTongFashionId"
type="string"
tag="lingtong_fashion_id"
comment="灵童时装id"

[[variables]]
name="LingTongWeapon"
type="string"
tag="lingtong_weapon"
comment="灵童冰魂"

[[variables]]
name="LingTongWingId"
type="string"
tag="lingtong_wing_id"
comment="灵童战翼"

[[variables]]
name="LingTongMountId"
type="string"
tag="lingtong_mount_id"
comment="灵童坐骑"

[[variables]]
name="LingTongFabaoId"
type="string"
tag="lingtong_fabao_id"
comment="灵童法宝"

[[variables]]
name="LingTongShenfaId"
type="string"
tag="lingtong_shenfa_id"
comment="灵童身法"


[[variables]]
name="LingTongXianTiId"
type="string"
tag="lingtong_xianti_id"
comment="灵童仙体"


[[variables]]
name="LingTongFieldId"
type="string"
tag="lingtong_field_id"
comment="灵童领域"



