file="robot_quest_vo.go"
pkg="template"
class="RobotQuestTemplateVO"
comment = "机器人任务配置"
[[variables]]
name="Id"
type="int"
tag="id"
comment="id"

[[variables]]
name="MapId"
type="int32"
tag="map_id"
comment="地图id"

[[variables]]
name="PlayerLimitCount"
type="int32"
tag="player_limit_count"
comment="玩家数量"

[[variables]]
name="QuestBeginId"
type="int32"
tag="quest_begin_id"
comment="任务起始id"

[[variables]]
name="QuestOverId"
type="int32"
tag="quest_over_id"
comment="任务结束id"

[[variables]]
name="HpMin"
type="int64"
tag="hp_min"
comment="血量最小"

[[variables]]
name="HpMax"
type="int64"
tag="hp_max"
comment="血量最大"

[[variables]]
name="AttackMin"
type="int64"
tag="attack_min"
comment="攻击最小"

[[variables]]
name="AttackMax"
type="int64"
tag="attack_max"
comment="攻击最大"

[[variables]]
name="DefenceMin"
type="int64"
tag="defence_min"
comment="防御最小"

[[variables]]
name="DefenceMax"
type="int64"
tag="defence_max"
comment="防御最大"


[[variables]]
name="ChuansongzhenId"
type="int32"
tag="chuansongzhen_id"
comment="传送阵"


[[variables]]
name="RefreshTime"
type="int32"
tag="refresh_time"
comment="刷新时间"