file="scene_vo.go"
pkg="template"
class="SceneTemplateVO"
comment = "场景部怪配置"
[[variables]]
name="Idx"
type="int"
tag="idx"
comment="idx"

[[variables]]
name="Id"
type="int"
tag="id"
comment="id"

[[variables]]
name="SceneID"
type="int32"
tag="sceneID"
comment="场景id"

[[variables]]
name="TempId"
type="int"
tag="tempID"
comment="模型id"

[[variables]]
name="BiologyType"
type="int32"
tag="biologyType"
comment="生物类型"


[[variables]]
name="IndexID"
type="int32"
tag="indexID"
comment="索引id"

[[variables]]
name="GroupID"
type="int32"
tag="groupID"
comment="组id"

[[variables]]
name="Name"
type="string"
tag="name"
comment="名字"

[[variables]]
name="PosX"
type="float64"
tag="posX"
comment="posX"

[[variables]]
name="PosY"
type="float64"
tag="posY"
comment="posY"

[[variables]]
name="PosZ"
type="float64"
tag="posZ"
comment="posZ"

[[variables]]
name="Angle"
type="float64"
tag="angle"
comment="角度"

[[variables]]
name="AlertRadius"
type="float64"
tag="alertRadius"
comment="警戒半径"

[[variables]]
name="RandRadius"
type="float64"
tag="randRadius"
comment="最大移动半径"