file="shangguzhiling_lingwen_vo.go"
pkg="template"
class="ShangguzhilingLingwenTemplateVO"
comment = "上古之灵灵纹配置"
[[variables]]
name="Id"
type="int"
tag="id"
comment="id"

[[variables]]
name="Type"
type="int32"
tag="type"
comment="灵兽类型"

[[variables]]
name="SubType"
type="int32"
tag="sub_type"
comment="灵纹类型"

[[variables]]
name="Name"
type="string"
tag="name"
comment="名字"

[[variables]]
name="NeedSgzlLevel"
type="int32"
tag="need_sgzl_level"
comment="需要上古之灵的等级"

[[variables]]
name="LingwenLevelBeginId"
type="int32"
tag="lingwen_level_begin_id"
comment="灵纹升级起始Id"

[[variables]]
name="LingwenLevelUseItemId"
type="string"
tag="lingwen_level_use_item_id"
comment="上古之灵灵纹升级使用的物品ID"