file="shangguzhiling_linglian_pool_vo.go"
pkg="template"
class="ShangguzhilingLinglianPoolTemplateVO"
comment = "上古之灵灵炼随机池配置"
[[variables]]
name="Id"
type="int"
tag="id"
comment="id"

[[variables]]
name="NextId"
type="int32"
tag="next_id"
comment="下一Id"

[[variables]]
name="Rate"
type="int32"
tag="rate"
comment="万分比几率"

[[variables]]
name="Star"
type="int32"
tag="star"
comment="星级"

[[variables]]
name="Hp"
type="int32"
tag="hp"
comment="hp"

[[variables]]
name="Attack"
type="int32"
tag="attack"
comment="攻击力"

[[variables]]
name="Defence"
type="int32"
tag="defence"
comment="防御力"

[[variables]]
name="Quality"
type="int32"
tag="quality"
comment="属性品质"

[[variables]]
name="Biaoshi"
type="int32"
tag="biaoshi"
comment="标识号"