file="shangguzhiling_lingwen_level_vo.go"
pkg="template"
class="ShangguzhilingLingwenLevelTemplateVO"
comment = "上古之灵灵纹升级配置"
[[variables]]
name="Id"
type="int"
tag="id"
comment="id"

[[variables]]
name="NextId"
type="int32"
tag="next_id"
comment="下一Id"

[[variables]]
name="Level"
type="int32"
tag="level"
comment="等级"

[[variables]]
name="Experience"
type="int64"
tag="experience"
comment="升级所需经验"

[[variables]]
name="Hp"
type="int32"
tag="hp"
comment="hp"

[[variables]]
name="Attack"
type="int32"
tag="attack"
comment="攻击力"

[[variables]]
name="Defence"
type="int32"
tag="defence"
comment="防御力"