file="shangguzhiling_constant_vo.go"
pkg="template"
class="ShangguzhilingConstantTemplateVO"
comment = "上古之灵常量配置"
[[variables]]
name="Id"
type="int"
tag="id"
comment="id"

[[variables]]
name="LinglianSuodingUseItemId"
type="int32"
tag="linglian_suoding_use_item_id"
comment="上古之灵灵炼锁定使用的物品ID"

[[variables]]
name="LinglianItemId"
type="int32"
tag="linglian_item_id"
comment="灵炼消耗物品ID"

[[variables]]
name="LinglianItemCount"
type="int32"
tag="linglian_item_count"
comment="灵炼消耗物品数量基数"

[[variables]]
name="LinglianCoefficient"
type="int32"
tag="linglian_coefficient"
comment="灵炼消耗物品数量参数1"

[[variables]]
name="LinglianCoefficient2"
type="int32"
tag="linglian_coefficient_2"
comment="灵炼消耗物品数量参数2"

[[variables]]
name="LinglianNum"
type="int32"
tag="linglian_num"
comment="灵炼次数上限"
