file="shangguzhiling_linglian_vo.go"
pkg="template"
class="ShangguzhilingLinglianTemplateVO"
comment = "上古之灵灵炼配置"
[[variables]]
name="Id"
type="int"
tag="id"
comment="id"

[[variables]]
name="Type"
type="int32"
tag="type"
comment="灵兽类型"

[[variables]]
name="SubType"
type="int32"
tag="sub_type"
comment="部位类型"

[[variables]]
name="NeedSgzlLevel"
type="int32"
tag="need_sgzl_level"
comment="需要上古之灵的等级"

[[variables]]
name="ChushiAttrPoolBeginId"
type="int32"
tag="chushi_attr_pool_begin_id"
comment="部位起始属性随机池"

[[variables]]
name="AttrPoolBeginId"
type="int32"
tag="attr_pool_begin_id"
comment="部位属性随机池"