file="shangguzhiling_base_vo.go"
pkg="template"
class="ShangguzhilingBaseTemplateVO"
comment = "上古之灵基础配置"
[[variables]]
name="Id"
type="int"
tag="id"
comment="id"

[[variables]]
name="Type"
type="int32"
tag="type"
comment="类型"

[[variables]]
name="Name"
type="string"
tag="name"
comment="名字"

[[variables]]
name="NeedSgzlId"
type="int32"
tag="need_sgzl_id"
comment="所需的上古之灵ID"

[[variables]]
name="NeedSgzlLevel"
type="int32"
tag="need_sgzl_level"
comment="所需的上古之灵等级"

[[variables]]
name="SgzlLevelBeginId"
type="int32"
tag="sgzl_level_begin_id"
comment="上古之灵升级起始ID"

[[variables]]
name="JinjieBeginId"
type="int32"
tag="jinjie_begin_id"
comment="进阶起始Id"

[[variables]]
name="Hp"
type="int32"
tag="hp"
comment="hp"

[[variables]]
name="Attack"
type="int32"
tag="attack"
comment="攻击力"

[[variables]]
name="Defence"
type="int32"
tag="defence"
comment="防御力"

[[variables]]
name="SgzlLevelUseItemId"
type="string"
tag="sgzl_level_use_item_id"
comment="上古之灵升级使用的物品ID"