file="shenqi_zhuling_vo.go"
pkg="template"
class="ShenQiZhuLingTemplateVO"
comment = "神器注灵配置"
[[variables]]
name="Id"
type="int"
tag="id"
comment="id"

[[variables]]
name="NextId"
type="int32"
tag="next_id"
comment="下一个id"

[[variables]]
name="ShenQiType"
type="int32"
tag="type"
comment="神器类型"

[[variables]]
name="QiLingTyp"
type="int32"
tag="qiling_type"
comment="器灵类型"

[[variables]]
name="QiLingSubTyp"
type="int32"
tag="qiling_sub_type"
comment="器灵部位"

[[variables]]
name="Level"
type="int32"
tag="level"
comment="注灵等级"

[[variables]]
name="UpdateWfb"
type="int32"
tag="update_wfb"
comment="升级成功率"

[[variables]]
name="TimesMin"
type="int32"
tag="times_min"
comment="最小次数"

[[variables]]
name="TimesMax"
type="int32"
tag="times_max"
comment="最大次数"

[[variables]]
name="AddMin"
type="int32"
tag="add_min"
comment="每次增加祝福值最小值"

[[variables]]
name="AddMax"
type="int32"
tag="add_max"
comment="每次增加祝福值最大值"

[[variables]]
name="ZhufuMax"
type="int32"
tag="zhufu_max"
comment="前端祝福值显示值"

[[variables]]
name="Hp"
type="int32"
tag="hp"
comment="生命"

[[variables]]
name="Attack"
type="int32"
tag="attack"
comment="攻击"

[[variables]]
name="Defence"
type="int32"
tag="defence"
comment="防御"

[[variables]]
name="Percent"
type="int32"
tag="percent"
comment="对应器灵属性增加百分比"

[[variables]]
name="NeedZhuLing"
type="int32"
tag="need_zhuling"
comment="消耗灵气值"