file="shenqi_cuilian_vo.go"
pkg="template"
class="ShenQiCuiLianTemplateVO"
comment = "神器淬炼配置"
[[variables]]
name="Id"
type="int"
tag="id"
comment="id"

[[variables]]
name="NextId"
type="int32"
tag="next_id"
comment="下一个id"

[[variables]]
name="ShenQiType"
type="int32"
tag="type"
comment="神器类型"

[[variables]]
name="Level"
type="int32"
tag="level"
comment="神器等级"

[[variables]]
name="Percent"
type="int32"
tag="percent"
comment="提升对应神器属性百分比"