file="shenqi_qiling_effect_vo.go"
pkg="template"
class="ShenQiQiLingEffectTemplateVO"
comment = "神器器灵影响配置"
[[variables]]
name="Id"
type="int"
tag="id"
comment="id"

[[variables]]
name="ShenQiType"
type="int32"
tag="type"
comment="神器类型"

[[variables]]
name="QiLingTyp"
type="int32"
tag="qiling_type"
comment="器灵类型"

[[variables]]
name="QiLingSubTyp"
type="int32"
tag="qiling_sub_type"
comment="器灵部位"

[[variables]]
name="NeedLevel"
type="int32"
tag="need_level"
comment="对应神器需要达到几级开启"