file="shen_yu_rank_vo.go"
pkg="template"
class="ShenYuRankTemplateVO"
comment = "神域之战排行榜配置"
[[variables]]
name="Id"
type="int"
tag="id"
comment="id"

[[variables]]
name="NextId"
type="int"
tag="next_id"
comment="next_id"

[[variables]]
name="RoundType"
type="int32" 
tag="type"
comment="神域类型"

[[variables]]
name="RankMin"
type="int32"
tag="rank_min"
comment="排名区间最小值"

[[variables]]
name="RankMax"
type="int32"
tag="rank_max"
comment="排名区间最大值"

[[variables]]
name="RewExp"
type="int32"
tag="rew_exp"
comment="排名获得的经验值"

[[variables]]
name="RewExpPoint"
type="int32"
tag="rew_exp_point"
comment="排名获得的经验值点"

[[variables]]
name="RewSilver"
type="int32"
tag="rew_silver"
comment="排名获得的银两"

[[variables]]
name="RewBindGold"
type="int32"
tag="rew_bind_gold"
comment="排名获得的绑元"

[[variables]]
name="RewGold"
type="int32"
tag="rew_gold"
comment="排名获得的元宝"

[[variables]]
name="RewItemId"
type="string"
tag="rew_item_id"
comment="排名获得的物品"

[[variables]]
name="RewItemCount"
type="string"
tag="rew_item_count"
comment="排名获得的物品数量"

