file="shenmo_rank_vo.go"
pkg="template"
class="ShenMoRankTemplateVO"
comment = "神魔排行榜配置"
[[variables]]
name="Id"
type="int"
tag="id"
comment="id"

[[variables]]
name="RankMin"
type="int32"
tag="rank_min"
comment="仙盟排名区间最小值"


[[variables]]
name="RankMax"
type="int32"
tag="rank_max"
comment="仙盟排名区间最大值"



[[variables]]
name="GetSilver"
type="int32"
tag="get_silver"
comment="仙盟排名获得的银两"

[[variables]]
name="GetBindGold"
type="int32"
tag="get_bind_gold"
comment="仙盟排名获得的绑元"

[[variables]]
name="GetGongXun"
type="int32"
tag="get_gongxun"
comment="获得的功勋"


[[variables]]
name="GetItemId"
type="string"
tag="get_item_id"
comment="仙盟排名获得的物品"

[[variables]]
name="GetItemCount"
type="string"
tag="get_item_count"
comment="仙盟排名获得的物品数量"

