file="shenqi_qiling_vo.go"
pkg="template"
class="ShenQiQiLingTemplateVO"
comment = "神器器灵配置"
[[variables]]
name="Id"
type="int"
tag="id"
comment="id"

[[variables]]
name="QiLingTyp"
type="int32"
tag="qiling_type"
comment="器灵类型"

[[variables]]
name="QiLingSubTyp"
type="int32"
tag="qiling_sub_type"
comment="器灵部位"

[[variables]]
name="Hp"
type="int32"
tag="hp"
comment="生命属性"

[[variables]]
name="Attack"
type="int32"
tag="attack"
comment="攻击属性"

[[variables]]
name="Defence"
type="int32"
tag="defence"
comment="防御属性"

[[variables]]
name="FenJieGet"
type="int32"
tag="fenjie_get"
comment="分解器灵获得的灵气值"