file="shenqi_cuilian_level_vo.go"
pkg="template"
class="ShenQiCuiLianLevelTemplateVO"
comment = "神器淬炼等级配置"
[[variables]]
name="Id"
type="int"
tag="id"
comment="id"

[[variables]]
name="ShenQiType"
type="int32"
tag="type"
comment="神器类型"

[[variables]]
name="CuiLianType"
type="int32"
tag="cuilian_type"
comment="淬炼类型"

[[variables]]
name="NextId"
type="int32"
tag="next_id"
comment="下一个id"

[[variables]]
name="Level"
type="int32"
tag="level"
comment="淬炼等级"

[[variables]]
name="NeedShenQiLevel"
type="int32"
tag="need_shenqi_level"
comment="需要神器等级"

[[variables]]
name="UseItem"
type="int32"
tag="use_item_id"
comment="升级所需物品id"

[[variables]]
name="ItemCount"
type="int32"
tag="use_item_count"
comment="升级所需物品数量"

[[variables]]
name="UpdateWfb"
type="int32"
tag="update_wfb"
comment="升级成功率"

[[variables]]
name="TimesMin"
type="int32"
tag="times_min"
comment="最小次数"

[[variables]]
name="TimesMax"
type="int32"
tag="times_max"
comment="最大次数"

[[variables]]
name="AddMin"
type="int32"
tag="add_min"
comment="每次增加祝福值最小值"

[[variables]]
name="AddMax"
type="int32"
tag="add_max"
comment="每次增加祝福值最大值"

[[variables]]
name="ZhufuMax"
type="int32"
tag="zhufu_max"
comment="前端祝福值显示值"

[[variables]]
name="Hp"
type="int32"
tag="hp"
comment="生命"

[[variables]]
name="Attack"
type="int32"
tag="attack"
comment="攻击"

[[variables]]
name="Defence"
type="int32"
tag="defence"
comment="防御"