file="shenqi_taozhuang_vo.go"
pkg="template"
class="ShenQiTaoZhuangTemplateVO"
comment = "神器套装配置"
[[variables]]
name="Id"
type="int"
tag="id"
comment="id"

[[variables]]
name="Hp"
type="int32"
tag="hp"
comment="生命属性"

[[variables]]
name="Attack"
type="int32"
tag="attack"
comment="攻击属性"

[[variables]]
name="Defence"
type="int32"
tag="defence"
comment="防御属性"

[[variables]]
name="NeedNumber"
type="int32"
tag="need_num"
comment="穿戴的器灵最低阶数"

[[variables]]
name="NeedCount"
type="int32"
tag="need_count"
comment="达到要求的器灵数量"