file="shenmo_constant_vo.go"
pkg="template"
class="ShenMoConstantTemplateVO"
comment = "神魔常量配置"
[[variables]]
name="Id"
type="int"
tag="id"
comment="id"

[[variables]]
name="WuZiBiologyId"
type="int32"
tag="wuzi_biology_id"
comment="物资生物id"


[[variables]]
name="DaQiBiologyId"
type="int32"
tag="daqi_biology_id"
comment="大旗生物id"



[[variables]]
name="WuZiGetGongXun"
type="int32"
tag="wuzi_get_gongxun"
comment="物资采集获得的功勋"

[[variables]]
name="WuZiGeiJiFen"
type="int32"
tag="wuzi_gei_jifen"
comment="物资采集获得的仙盟积分"

[[variables]]
name="DaQiGetGongXun"
type="int32"
tag="daqi_get_gongxun"
comment="采集大旗获得的功勋"

[[variables]]
name="DaQiGetJiFen"
type="int32"
tag="daqi_get_jifen"
comment="采集大旗获得的仙盟积分"

[[variables]]
name="PlayerLimitCount"
type="int32"
tag="player_limit_count"
comment="活动人数上限"

[[variables]]
name="KillCd"
type="int32"
tag="kill_cd"
comment="同一玩家的击杀cd(毫秒)"

[[variables]]
name="KillCountCd"
type="int32"
tag="kill_count_cd"
comment="击杀同一玩家多次后进入该玩家的cd"

[[variables]]
name="RebornBuff"
type="int32"
tag="reborn_buff"
comment="复活后的buffid"

[[variables]]
name="MapId"
type="int32"
tag="map_id"
comment="地图id"

