file="shenmo_title_vo.go"
pkg="template"
class="ShenMoTitleTemplateVO"
comment = "神魔称号配置"
[[variables]]
name="Id"
type="int"
tag="id"
comment="id"

[[variables]]
name="KillMin"
type="int32"
tag="kill_min"
comment="最小击杀人数"


[[variables]]
name="KillMax"
type="int32"
tag="kill_max"
comment="最大击杀人数"



[[variables]]
name="GiveGongXun"
type="int32"
tag="give_gongxun"
comment="被击杀后，击杀者获得的功勋"

[[variables]]
name="GiveJiFen"
type="int32"
tag="give_jifen"
comment="被击杀后，击杀者仙盟获得的积分"

[[variables]]
name="Title"
type="int32"
tag="title"
comment="称号"

