file="shenqi_vo.go"
pkg="template"
class="ShenQiTemplateVO"
comment = "神器配置"
[[variables]]
name="Id"
type="int"
tag="id"
comment="id"

[[variables]]
name="NextId"
type="int32"
tag="next_id"
comment="下一个id"

[[variables]]
name="ShenQiType"
type="int32"
tag="type"
comment="神器类型"

[[variables]]
name="Name"
type="string"
tag="name"
comment="神器名称"

[[variables]]
name="Level"
type="int32"
tag="level"
comment="神器等级"

[[variables]]
name="SkillId"
type="int32"
tag="skill_id"
comment="技能"