file="shengshou_boss_vo.go"
pkg="template"
class="ShengShouBossTemplateVO"
comment = "圣兽boss配置"

[[variables]]
name="Id"
type="int"
tag="id"
comment="id"


[[variables]]
name="BiologyId"
type="int32"
tag="biology_id"
comment="生物id"

[[variables]]
name="RecForce"
type="int64"
tag="rec_force"
comment="战力"


[[variables]]
name="MapId"
type="int32"
tag="map_id"
comment="地图id"
