file="shen_yu_constant_vo.go"
pkg="template"
class="ShenYuConstantTemplateVO"
comment = "神域常量配置"
[[variables]]
name="Id"
type="int"
tag="id"
comment="id"

[[variables]]
name="KeyMax"
type="int32"
tag="key_max"
comment="神域钥匙保存的最大数量"

[[variables]]
name="KeyKeepMin"
type="int32"
tag="key_min"
comment="神域钥匙最小死亡不掉落数量"

[[variables]]
name="KeyDropPercent"
type="int32"
tag="key_percent"
comment="神域钥匙死亡掉落万分比"

[[variables]]
name="KeyDropCD"
type="int32"
tag="bekill_cd"
comment="神域钥匙死亡掉落CD"

[[variables]]
name="MinStack"
type="int32"
tag="min_stack"
comment="击杀玩家掉落最小堆数"

[[variables]]
name="MaxStack"
type="int32"
tag="max_stack"
comment="击杀玩家掉落最大堆数"

[[variables]]
name="ExistTime"
type="int32"
tag="exist_time"
comment="掉落存活时间"

[[variables]]
name="ProtectedTime"
type="int32"
tag="protected_time"
comment="掉落保护时间"

[[variables]]
name="FailTime"
type="int32"
tag="fail_time"
comment="掉落物品失效时间"

[[variables]]
name="InitKeyNum"
type="int32"
tag="key_begin"
comment="初始钥匙数量"

[[variables]]
name="ResetKeyNum"
type="int32"
tag="key_jiesuan"
comment="重置钥匙数量"

