file="shen_yu_vo.go"
pkg="template"
class="ShenYuTemplateVO"
comment = "神域配置"
[[variables]]
name="Id"
type="int"
tag="id"
comment="id"

[[variables]]
name="NextId"
type="int"
tag="next_id"
comment="下一层id"

[[variables]]
name="RoundType"
type="int32" 
tag="type"
comment="神域类型"

[[variables]]
name="RoundTime"
type="int64" 
tag="jiesuan_time"
comment="活动持续时间"

[[variables]]
name="MapId"
type="int32"
tag="map_id"
comment="地图id"

[[variables]]
name="WinRank"
type="int32"
tag="win_rank"
comment="每轮入围人数"

[[variables]]
name="LuckyRewTime"
type="int32"
tag="lucky_time"
comment="幸运奖时间"

[[variables]]
name="LuckyPalyerCount"
type="int32"
tag="lucky_palyer_count"
comment="幸运奖人数"

[[variables]]
name="LuckyItemId"
type="string"
tag="lucky_item_id"
comment="幸运奖励物品"

[[variables]]
name="LuckyItemCount"
type="string"
tag="lucky_item_count"
comment="幸运奖励物品数量"

[[variables]]
name="ResetKeyFlag"
type="int32"
tag="reset_key_flag"
comment="钥匙重置标志"
