file="shop_vo.go"
pkg="template"
class="ShopTemplateVO"
comment = "商城配置"
[[variables]]
name="Id"
type="int"
tag="id"
comment="id"

[[variables]]
name="Order"
type="int32"
tag="order"
comment="购买规则"


[[variables]]
name="Name"
type="string"
tag="name"
comment="名字"


[[variables]]
name="Type"
type="int32"
tag="type"
comment="商店类型"

[[variables]]
name="Table"
type="int32"
tag="table"
comment="同种商店不同类型道具标签页"

[[variables]]
name="ItemId"
type="int32"
tag="item"
comment="物品模板id"

[[variables]]
name="BuyCount"
type="int32"
tag="buy_count"
comment="一次性购买的数量"

[[variables]]
name="MaxCount"
type="int32"
tag="max_count"
comment="最大购买数量"

[[variables]]
name="ConsumeType"
type="int32"
tag="consume_type"
comment="消耗资源类型"

[[variables]]
name="ConsumeItemId"
type="int32"
tag="consume_item_id" 
comment="消耗物品id"

[[variables]]
name="ConsumeData1"
type="int32"
tag="consume_data1"
comment="消耗资源数量"

[[variables]]
name="IsBind"
type="int32"
tag="is_bind"
comment="是否绑定"

[[variables]]
name="LimitCount"
type="int32"
tag="limit_count"
comment="每日限购次数,第二天清空处理"


