

file="skill_level_vo.go"
pkg="template"
class="SkillLevelTemplateVO"
comment = "技能等级配置"
[[variables]]
name="Id"
type="int"
tag="id"
comment="id"

[[variables]]
name="NextId"
type="int32"
tag="next_id"
comment="下一个等级id"

[[variables]]
name="Typ"
type="int32"
tag="type"
comment="类型"

[[variables]]
name="Level"
type="int32"
tag="level"
comment="等级"

[[variables]]
name="CostSilver"
type="int32"
tag="cost_yinliang"
comment="银两"

	


[[variables]]
name="CostGold"
type="int32"
tag="cost_yuanbao"
comment="元宝"

[[variables]]
name="CostItemId"
type="string"
tag="cost_item_id"
comment="物品"

[[variables]]
name="CostItemCount"
type="string"
tag="cost_item_count"
comment="物品数量"


[[variables]]
name="Force"
type="int32"
tag="force"
comment="战力"

[[variables]]
name="DamageValueBase"
type="int32"
tag="damage_value_base"
comment="伤害基础值"

[[variables]]
name="DamageValue"
type="int32"
tag="damage_value"
comment="伤害值"

[[variables]]
name="SpellDamage"
type="int32"
tag="spell_damage"
comment="技能伤害"

[[variables]]
name="SpellPower"
type="int32"
tag="spell_power"
comment="技能强度"
