

file="skill_vo.go"
pkg="template"
class="SkillTemplateVO"
comment = "技能配置"
[[variables]]
name="Id"
type="int"
tag="id"
comment="id"

[[variables]]
name="Name"
type="string"
tag="name"
comment="名字"

[[variables]]
name="FirstType"
type="int32"
tag="type_1st"
comment="类型1"

[[variables]]
name="SecondType"
type="int32"
tag="type_2nd"
comment="类型2"

[[variables]]
name="ThirdType"
type="int32"
tag="type_3rd"
comment="类型3"


[[variables]]
name="FourthType"
type="int32"
tag="type_4rd"
comment="类型4"

[[variables]]
name="BeTriggered"
type="int32"
tag="be_triggered"
comment="当type_2nd为3，5时，走以下2进制规则：1，被玩家攻击生效,2，被怪物攻击生效"

[[variables]]
name="HpTrigger"
type="int32"
tag="hp_trigger"
comment="当type_2nd为5时，此字段代表被敌人攻击时血量降低的触发点（万分比）"



[[variables]]
name="BuffId"
type="int"
tag="buff_id"
comment="表现buff"

[[variables]]
name="BuffId2"
type="int"
tag="buff_id_2"
comment="受击表现buff"

[[variables]]
name="BuffId3"
type="int32"
tag="buff_id_3"
comment="给自己上buff"

[[variables]]
name="BuffId3Rate"
type="int32"
tag="buff_id3_rate"
comment="给自己上buff概率"

[[variables]]
name="TypeId"
type="int32"
tag="type_id"

[[variables]]
name="Lev"
type="int32"
tag="lev"
comment="等级"

[[variables]]
name="Rate"
type="int32"
tag="rate"
comment="触发几率"

[[variables]]
name="CdTime"
type="int32"
tag="cd_time"
comment="cd时间"

[[variables]]
name="CdGroup"
type="int32"
tag="cd_group"
comment="cd组"


[[variables]]
name="TargetSelect"
type="int32"
tag="target_select"
comment="技能选择目标（二进制）1.自身2.友方 4.敌方"

[[variables]]
name="TargetAction"
type="int32"
tag="target_action"
comment="作用目标（二进制）1.玩家 2.怪物（NPC）"


[[variables]]
name="RuleBreak"
type="int32"
tag="rule_break"
comment="是否无视安全区"

[[variables]]
name="FaceNeed"
type="int32"
tag="face_need"
comment="朝向"

[[variables]]
name="Distance"
type="int32"
tag="distance"
comment="施法距离"

[[variables]]
name="AreaType"
type="int32"
tag="area_type"
comment="作用范围类型"

[[variables]]
name="AreaRadius"
type="int32"
tag="area_radius"
comment="作用范围半径"


[[variables]]
name="AreaRange"
type="int32"
tag="area_range"
comment="作用范围"

[[variables]]
name="TargetCount"
type="int32"
tag="target_count"
comment="目标数量"

[[variables]]
name="ProNeed"
type="int32"
tag="pro_need"
comment="职业需要"

[[variables]]
name="LevNeed"
type="int32"
tag="lev_need"
comment="等级需要"

[[variables]]
name="CostHpValue"
type="int32"
tag="cost_hp_value"
comment="消耗血量"

[[variables]]
name="CostHpPersent"
type="int32"
tag="cost_hp_persent"
comment="消耗血量万分比"

[[variables]]
name="CostTpValue"
type="int32"
tag="cost_tp_value"
comment="消耗体力"

[[variables]]
name="DamageValueBase"
type="int32"
tag="damage_value_base"
comment="基础伤害"

[[variables]]
name="DamageValue"
type="int32"
tag="damage_value"
comment="伤害值"

[[variables]]
name="SpellDamage"
type="int32"
tag="spell_damage"
comment="技能威力值"

[[variables]]
name="SpellPower"
type="int32"
tag="spell_power"
comment="技能伤害"

[[variables]]
name="DamagePersent"
type="int32"
tag="damage_persent"
comment="血量上线万分比"



[[variables]]
name="CureValue"
type="int32"
tag="cure_value"
comment="治疗值"

[[variables]]
name="CurePersent"
type="int32"
tag="cure_persent"
comment="治疗万分比"

[[variables]]
name="HatredValue"
type="int32"
tag="hatred_value"
comment="仇恨值"

[[variables]]
name="HatredPersent"
type="int32"
tag="hatred_persent"
comment="仇恨万分比"

[[variables]]
name="AddStatus"
type="string"
tag="add_status"
comment="添加状态"

[[variables]]
name="AddStatusRate"
type="string"
tag="add_status_rate"
comment="添加状态概率"

[[variables]]
name="AddAttrId"
type="int32"
tag="add_attr_id"
comment="添加属性"


[[variables]]
name="UnionAttrId"
type="int32"
tag="union_attr_id"
comment="仙盟属性光环"

[[variables]]
name="AddHit"
type="int32"
tag="add_hit"
comment="添加命中"

[[variables]]
name="AddCritical"
type="int32"
tag="add_critical"
comment="添加暴击"



[[variables]]
name="SpecialTarget"
type="int32"
tag="special_target"
comment="特殊效果对象"

[[variables]]
name="SpecialEffect"
type="int32"
tag="special_effect"
comment="特殊效果"


[[variables]]
name="SpecialEffectRate"
type="int32"
tag="special_effect_rate"
comment="特殊效果比例"

[[variables]]
name="SpecialEffectValue"
type="int32"
tag="special_effect_value"
comment="特殊效果值"


[[variables]]
name="SpecialEffectValue2"
type="int32"
tag="special_effect_value2"
comment="特殊效果值2"

[[variables]]
name="SpecialEffectValue3"
type="int32"
tag="special_effect_value3"
comment="特殊效果值3"


[[variables]]
name="AddPower"
type="int32"
tag="add_power"
comment="战力添加"

[[variables]]
name="SpellUpgradeBeginId"
type="int32"
tag="spell_upgrade_begin_id"
comment="动态技能升级id"

[[variables]]
name="TianFuBeginId"
type="int32"
tag="tianfu_begin_id"
comment="天赋起始id"

[[variables]]
name="ConsumeGoods"
type="int32"
tag="consume_goods"
comment="消耗物品"

[[variables]]
name="ConsumeGoodsCount"
type="int32"
tag="consume_goods_count"
comment="消耗物品数量"

[[variables]]
name="ConsumeExperience"
type="int32"
tag="consume_experience"
comment="消耗经验"

[[variables]]
name="ConsumeMoney"
type="int32"
tag="consume_money"
comment="消耗银两"


[[variables]]
name="LimitTouch"
type="int32"
tag="limit_touch"
comment="限制被动"

[[variables]]
name="BoyShowId"
type="int32"
tag="boy_show_id"
comment="男技能特效"

[[variables]]
name="GirlShowId"
type="int32"
tag="girl_show_id"
comment="女技能特效"

[[variables]]
name="BoySpellIco"
type="int32"
tag="boy_spell_ico"
comment="男技能ico"

[[variables]]
name="GirlSpellIco"
type="int32"
tag="girl_spell_ico"
comment="女技能ico"

[[variables]]
name="SpellDescription"
type="string"
tag="spell_description"
comment="技能描述"

[[variables]]
name="SpellGetdescription"
type="string"
tag="spell_getdescription"
comment="星盘界面仙魂描述"

[[variables]]
name="SpecialDes"
type="string"
tag="special_des"
comment="仙魂特效描述"

[[variables]]
name="UplevelDes1"
type="string"
tag="uplevel_des1"
comment="仙魂每级的效果描述"

[[variables]]
name="UplevelDes2"
type="string"
tag="uplevel_des2"
comment="仙魂每级的效果持续时间描述"


[[variables]]
name="SpellUiDescription"
type="string"
tag="spell_ui_description"
comment="技能获得描述"

[[variables]]
name="Quality"
type="int32"
tag="quality"
comment="品质"

[[variables]]
name="MultiCount"
type="int32"
tag="multi_count"
comment="多段"

[[variables]]
name="ShowName"
type="int32"
tag="show_name"
comment="展示名字"

[[variables]]
name="AutoSlot"
type="int32"
tag="auto_slot"
comment="自动拖入"

[[variables]]
name="GuaJi"
type="int32"
tag="guaji"
comment="挂机"

[[variables]]
name="SpellNext"
type="int32"
tag="spell_next"
comment="下一个技能"



[[variables]]
name="ActionTime"
type="int32"
tag="action_time"
comment="施法时间"

[[variables]]
name="DelayTimes1"
type="string"
tag="delay_times_1"
comment="延迟时间1"

[[variables]]
name="DelayTimes2"
type="string"
tag="delay_times_2"
comment="延迟时间2"

[[variables]]
name="DelayTimesServer"
type="string"
tag="delay_times_server"
comment="服务器延迟时间"


[[variables]]
name="BeHarmLimitHp"
type="int32"
tag="be_harm_limit_hp"
comment="受到伤害最高上限"

[[variables]]
name="RebornBuff"
type="int32"
tag="reborn_buff"
comment="复活buff"

[[variables]]
name="RebornSkill"
type="int32"
tag="reborn_skill"
comment="复活技能"

[[variables]]
name="RebornSkillRate"
type="int32"
tag="reborn_skill_rate"
comment="复活技能概率"
