file="soul_vo.go"
pkg="template"
class="SoulTemplateVO"
comment = "帝魂配置"
[[variables]]
name="Id"
type="int"
tag="id"
comment="id"

[[variables]]
name="NextId"
type="int32"
tag="next_id"
comment="下一个id"

[[variables]]
name="Name"
type="string"
tag="name"
comment="帝魂名称"

[[variables]]
name="SoulQuality"
type="int32"
tag="soul_quality"
comment="帝魂品质"

[[variables]]
name="Type"
type="int32"
tag="type"
comment="帝魂种类"

[[variables]]
name="SoulType"
type="int32"
tag="soul_type"
comment="帝魂类型(标签)"

[[variables]]
name="Level"
type="int32"
tag="level"
comment="帝魂等级"

[[variables]]
name="NeedItemId"
type="string"
tag="need_item_id"
comment="激活所需要的物品id"

[[variables]]
name="NeedItemCount"
type="string"
tag="need_item_count"
comment="激活所需要的物品数量"

[[variables]]
name="UplevelExp"
type="int32"
tag="uplevel_exp"
comment="升级所需帝魂经验"

[[variables]]
name="DevourId"
type="int32"
tag="devour_id"
comment="可以吞噬的物品"


[[variables]]
name="AttrId"
type="int32"
tag="attr_id"
comment="该等级附带的属性"

[[variables]]
name="Sign"
type="int32"
tag="sign"
comment="界面的标识显示"

[[variables]]
name="NeedSoul"
type="int32"
tag="need_soul"
comment="前置需激活的帝魂类型"

[[variables]]
name="NeedSoulLevel"
type="int32"
tag="need_soul_level"
comment="前置所需的帝魂等级"
