file="soul_awaken_vo.go"
pkg="template"
class="SoulAwakenTemplateVO"
comment = "帝魂觉醒配置"
[[variables]]
name="Id"
type="int"
tag="id"
comment="id"

[[variables]]
name="NextId"
type="int32"
tag="next_id"
comment="下一个id"

[[variables]]
name="Name"
type="string"
tag="name"
comment="帝魂名称"


[[variables]]
name="Type"
type="int32"
tag="type"
comment="帝魂大种类"

[[variables]]
name="SoulType"
type="int32"
tag="soul_type"
comment="帝魂类型(标签)"

[[variables]]
name="Order"
type="int32"
tag="order"
comment="觉醒阶别"


[[variables]]
name="NeedItemId"
type="string"
tag="need_item_id"
comment="觉醒所需要的物品id"

[[variables]]
name="NeedItemCount"
type="string"
tag="need_item_count"
comment="觉醒所需要的物品数量"


[[variables]]
name="SkillId"
type="int32"
tag="skill_id"
comment="该等级附带的技能id"

[[variables]]
name="UplevelNeeditem"
type="string"
tag="uplevel_needitem"
comment="升级所需物品"

[[variables]]
name="UplevelItemCount"
type="string"
tag="uplevel_item_count"
comment="升级所需物品数量"

[[variables]]
name="UplevelSkillId"
type="int32"
tag="uplevel_skill_id"
comment="升级帝魂技能id"













