file="soul_chain_vo.go"
pkg="template"
class="SoulChainTemplateVO"
comment = "帝魂锁链配置"
[[variables]]
name="Id"
type="int"
tag="id"
comment="id"

[[variables]]
name="NeedCount"
type="int32"
tag="need_count"
comment="所需觉醒的帝魂数量"

[[variables]]
name="Type"
type="int32"
tag="type"
comment="效果类型"

[[variables]]
name="Value"
type="int32"
tag="value"
comment="对应的效果加成"

[[variables]]
name="Describe"
type="string"
tag="describe"
comment="该条属性的描述"
