file="soul_ruins_star_vo.go"
pkg="template"
class="SoulRuinsStarTemplateVO"
comment = "帝魂遗迹星级奖励配置"
[[variables]]
name="Id"
type="int"
tag="id"
comment="id"

[[variables]]
name="Chapter"
type="int32"
tag="chapter"
comment="对应章节"

[[variables]]
name="Type"
type="int32"
tag="type"
comment="类型"

[[variables]]
name="NeedStar"
type="int32"
tag="need_star"
comment="领取星数"

[[variables]]
name="RewGold"
type="int32"
tag="rew_gold"
comment="奖励元宝"

[[variables]]
name="RewYinliang"
type="int32"
tag="rew_yinliang"
comment="奖励银两"

[[variables]]
name="RewExp"
type="int32"
tag="rew_exp"
comment="奖励经验固定值"

[[variables]]
name="RewUplev"
type="int32"
tag="rew_uplev"
comment="奖励经验uplev点"

[[variables]]
name="RewItemId1"
type="int32"
tag="rew_item_id1"
comment="奖励物品1 ID"

[[variables]]
name="RewItemCount1"
type="int32"
tag="rew_item_count1"
comment="奖励物品1 数量"

[[variables]]
name="RewItemId2"
type="int32"
tag="rew_item_id2"
comment="奖励物品2 ID"

[[variables]]
name="RewItemCount2"
type="int32"
tag="rew_item_count2"
comment="奖励物品2 数量"

[[variables]]
name="RewItemId3"
type="int32"
tag="rew_item_id3"
comment="奖励物品3 ID"

[[variables]]
name="RewItemCount3"
type="int32"
tag="rew_item_count3"
comment="奖励物品3 数量"


[[variables]]
name="RewardShowItemId"
type="int32"
tag="reward_show_item_id"
comment="关联到物品表,点击查看奖励tips"


[[variables]]
name="RewardShowResult"
type="string"
tag="reward_show_result"
comment="章节界面奖励描述"
