file="soul_ruins_vo.go"
pkg="template"
class="SoulRuinsTemplateVO"
comment = "帝魂遗迹"
[[variables]]
name="Id"
type="int"
tag="id"
comment="id"

[[variables]]
name="NextId"
type="int32"
tag="next_id"
comment="下一个id"

[[variables]]
name="Name"
type="string"
tag="name"
comment="副本名称"

[[variables]]
name="MapId"
type="int32"
tag="map_id"
comment="关联地图id"

[[variables]]
name="Chapter"
type="int32"
tag="chapter"
comment="章节数"

[[variables]]
name="Type"
type="int32"
tag="type"
comment="难度"

[[variables]]
name="Level"
type="int32"
tag="level"
comment="关卡等级"

[[variables]]
name="RewYinliang"
type="int32"
tag="rew_yinliang"
comment="奖励银两"

[[variables]]
name="RewExp"
type="int32"
tag="rew_exp"
comment="奖励经验固定值"

[[variables]]
name="RewUplev"
type="int32"
tag="rew_uplev"
comment="奖励经验"

[[variables]]
name="RewGold"
type="int32"
tag="rew_gold"
comment="奖励元宝"

[[variables]]
name="RewTime"
type="int32"
tag="rew_time"
comment="首次通关奖励挑战次数"

[[variables]]
name="FrontId"
type="int32"
tag="front_id"
comment="前置副本ID"

[[variables]]
name="SpecialBossId"
type="int32"
tag="special_boss_id"
comment="特殊事件-隐藏BOSS的怪物ID"

[[variables]]
name="SpecialBossBuff"
type="int32"
tag="special_boss_buff"
comment="特殊事件-隐藏BOSS给予的BUFFID"

[[variables]]
name="SpecialBossRate"
type="int32"
tag="special_boss_rate"
comment="特殊事件-隐藏BOSS的出现概率"

[[variables]]
name="SpecialBossGroup"
type="int32"
tag="special_boss_group"
comment="特殊事件,隐藏BOSS刷的组"

[[variables]]
name="SoulId"
type="int32"
tag="soul_id"
comment="特殊事件-帝魂降临 出现的帝魂id"


[[variables]]
name="SoulItemId"
type="int32"
tag="soul_item_id"
comment="特殊事件-帝魂降临 给予的物品ID"

[[variables]]
name="SoulItemCount"
type="int32"
tag="soul_item_count"
comment="特殊事件-帝魂降临 给予的物品ID"

[[variables]]
name="SoulRate"
type="int32"
tag="soul_rate"
comment="特殊事件-帝魂降临 出现的概率"

[[variables]]
name="SoulGroup"
type="int32"
tag="soul_group"
comment="特殊事件,神秘高人的组"

[[variables]]
name="RobberId"
type="int32"
tag="robber_id"
comment="特殊事件-马贼 刷新的怪物ID"

[[variables]]
name="RobberCount"
type="int32"
tag="robber_count"
comment="特殊事件-马贼 刷新的怪物数量"

[[variables]]
name="RobberRate"
type="int32"
tag="robber_rate"
comment="特殊事件-马贼 出现的概率"

[[variables]]
name="RobberGroup"
type="int32"
tag="robber_group"
comment="特殊事件,马贼的刷怪组"

[[variables]]
name="RobberSilver"
type="int32"
tag="robber_silver"
comment="马贼索要的银两"

[[variables]]
name="FirstEvent"
type="int32"
tag="first_event"
comment="首次打必出的随机事件"

[[variables]]
name="Time1"
type="int32"
tag="time_1"
comment="星数减少时限1"

[[variables]]
name="Time2"
type="int32"
tag="time_2"
comment="星数减少时限2"

[[variables]]
name="Time3"
type="int32"
tag="time_3"
comment="星数减少时限3"

[[variables]]
name="SweepItemId"
type="int32"
tag="sweep_item_id"
comment="星数减少时限2"

[[variables]]
name="SweepItemCount"
type="int32"
tag="sweep_item_count"
comment="扫荡所需的物品数量"

[[variables]]
name="SweepNeedBag"
type="int32"
tag="sweep_need_bag"
comment="扫荡所需背包空位"

[[variables]]
name="SweepDrop1"
type="string"
tag="sweep_drop1"
comment="掉落包1id"

[[variables]]
name="SweepDrop2"
type="int32"
tag="sweep_drop2"
comment="掉落包2id"

[[variables]]
name="SweepDrop3"
type="int32"
tag="sweep_drop3"
comment="掉落包3id"

[[variables]]
name="SweepDrop4"
type="int32"
tag="sweep_drop4"
comment="掉落包4id"

[[variables]]
name="SpecialBossDrop"
type="int32"
tag="special_boss_drop"
comment="隐藏BOSS掉落包ID"

[[variables]]
name="SoulDrop"
type="int32"
tag="soul_drop"
comment="帝魂降临掉落包"

[[variables]]
name="RobberDrop"
type="int32"
tag="robber_drop"
comment="马贼掉落包ID"

[[variables]]
name="RewPre"
type="string"
tag="rew_pre"
comment="奖励预览"

[[variables]]
name="RecForce"
type="int32"
tag="rec_force"
comment="推荐战力"



