file="synthesis_vo.go"
pkg="template"
class="SynthesisTemplateVO"
comment = "合成配置"

[[variables]]
name="Id"
type="int"
tag="id"
comment="id"

[[variables]]
name="Type1"
type="string"
tag="type1"
comment="左侧标签名称"

[[variables]]
name="FirstTabId"
type="int32"
tag="first_tab_id"
comment="子标签ID"

[[variables]]
name="Name1"
type="string"
tag="name1"
comment="合成配方名称"

[[variables]]
name="NeedGender"
type="int32"
tag="need_gender"
comment="性别需求"

[[variables]]
name="NeedProfession"
type="int32"
tag="need_profession"
comment="职业需求"

[[variables]]
name="NeedItemId1"
type="int32"
tag="need_item_id_1"
comment="合成所需物品ID1"

[[variables]]
name="NeedItemCount1"
type="int32"
tag="need_item_count_1"
comment="合成所需物品的数量1"

[[variables]]
name="NeedItemId2"
type="int32"
tag="need_item_id_2"
comment="合成所需物品ID2"

[[variables]]
name="NeedItemCount2"
type="int32"
tag="need_item_count_2"
comment="合成所需物品的数量2"

[[variables]]
name="NeedItemId3"
type="int32"
tag="need_item_id_3"
comment="合成所需物品ID3"

[[variables]]
name="NeedItemCount3"
type="int32"
tag="need_item_count_3"
comment="合成所需物品的数量3"

[[variables]]
name="NeedItemId4"
type="int32"
tag="need_item_id_4"
comment="合成所需物品ID4"

[[variables]]
name="NeedItemCount4"
type="int32"
tag="need_item_count_4"
comment="合成所需物品的数量4"

[[variables]]
name="NeedItemId5"
type="int32"
tag="need_item_id_5"
comment="合成所需物品ID5"

[[variables]]
name="NeedItemCount5"
type="int32"
tag="need_item_count_5"
comment="合成所需物品的数量5"

[[variables]]
name="ItemId"
type="int32"
tag="item_id"
comment="合成后的物品ID"

[[variables]]
name="ItemCount"
type="int32"
tag="item_count"
comment="合成后的物品数量"

[[variables]]
name="NeedSilver"
type="int32"
tag="need_silver"
comment="合成所需银两"

[[variables]]
name="NeedGold"
type="int32"
tag="need_gold"
comment="合成所需元宝"

[[variables]]
name="NeedBindGold"
type="int32"
tag="need_bind_gold"
comment="合成所需绑定元宝"

[[variables]]
name="SuccessRate"
type="int32"
tag="success_rate"
comment="合成成功率万分比"

[[variables]]
name="MaxCount"
type="int32"
tag="max_count"
comment="单次最大合成数量"

[[variables]]
name="HintContent"
type="int32"
tag="hint_content"
comment="功能开启模块ID"

[[variables]]
name="ExplosionId"
type="int32"
tag="explosion_id"
comment="防爆符物品id"

[[variables]]
name="ExplosionCount"
type="int32"
tag="explosion_count"
comment="防爆符物品数量"




