file="system_lingzhu_uplevel_vo.go"
pkg="template"
class="SystemLingZhuUpLevelTemplateVO"
comment = "附加灵珠升级配置"
[[variables]]
name="Id"
type="int"
tag="id"
comment="id"

[[variables]]
name="NextId"
type="int32"
tag="next_id"
comment="下一个id"

[[variables]]
name="Level"
type="int32"
tag="level"
comment="等级"

[[variables]]
name="Hp"
type="int32"
tag="hp"
comment="该等级增加的生命"

[[variables]]
name="Attack"
type="int32"
tag="attack"
comment="该等级增加的攻击"

[[variables]]
name="Defence"
type="int32"
tag="defence"
comment="该等级增加的防御"

[[variables]]
name="Percent"
type="int32"
tag="percent"
comment="百分比"

[[variables]]
name="UseItemCount"
type="int32"
tag="use_item_count"
comment="升级消耗的物品数量"

[[variables]]
name="UpdateWfb"
type="int32"
tag="update_wfb"
comment="成功率万分比"

[[variables]]
name="TimesMin"
type="int32"
tag="times_min"
comment="每次升级最小次数"

[[variables]]
name="TimesMax"
type="int32"
tag="times_max"
comment="每次升级最大次数"

[[variables]]
name="AddMin"
type="int32"
tag="add_min"
comment="每次升级每次随机增加祝福值最小数目"

[[variables]]
name="AddMax"
type="int32"
tag="add_max"
comment="每次升级每次随机增加祝福值最大数目"

[[variables]]
name="ZhufuMax"
type="int32"
tag="zhufu_max"
comment="祝福值最大"

