file="system_lingzhu_vo.go"
pkg="template"
class="SystemLingZhuTemplateVO"
comment = "附加灵珠配置"
[[variables]]
name="Id"
type="int"
tag="id"
comment="id"

[[variables]]
name="LingtongId"
type="int32"
tag="lingtong_id"
comment="灵童等级"

[[variables]]
name="Type"
type="int32"
tag="type"
comment="灵珠类型"

[[variables]]
name="UseItemId"
type="int32"
tag="use_item_id"
comment="升级消耗物品类型"

[[variables]]
name="LevelBegin"
type="int32"
tag="level_begin"
comment="关联升级表起始Id"