file="item_skill_vo.go"
pkg="template"
class="ItemSkillTemplateVO"
comment = "物品技能配置"
[[variables]]
name="Id"
type="int"
tag="id"
comment="id"

[[variables]]
name="NextId"
type="int32"
tag="next_id"
comment="下一个id"

[[variables]]
name="Type"
type="int32"
tag="type"
comment="技能类型"

[[variables]]
name="Level"
type="int32"
tag="level"
comment="技能等级"

[[variables]]
name="SkillId"
type="int32"
tag="skill_id"
comment="技能id"