

file="system_taozhuang_vo.go"
pkg="template"
class="SystemTaozhuangTemplateVO"
comment = "系统装备套装配置"
[[variables]]
name="Id"
type="int"
tag="id"
comment="id"

[[variables]]
name="Name"
type="string"
tag="name"
comment="套装名称"

[[variables]]
name="Type"
type="int32"
tag="type"
comment="套装类型"

[[variables]]
name="Number"
type="int32"
tag="number"
comment="激活所需数量"

[[variables]]
name="Describe"
type="string"
tag="describe"
comment="套装描述"

[[variables]]
name="Pos1Quality"
type="int32"
tag="pos1_quality"
comment="套装品质"

[[variables]]
name="AttrPercent"
type="int32"
tag="attr_percent"
comment="增加对系统基础属性万分比"
