file="system_shenzhu_use_vo.go"
pkg="template"
class="SystemShenZhuUseTemplateVO"
comment = "附加神铸配置"
[[variables]]
name="Id"
type="int"
tag="id"
comment="id"

[[variables]]
name="SysType"
type="int32"
tag="type"
comment="系统类型"

[[variables]]
name="Pos1UseItemId"
type="int32"
tag="pos1_use_item_id"
comment="部位一神铸消耗的物品id"

[[variables]]
name="Pos2UseItemId"
type="int32"
tag="pos2_use_item_id"
comment="部位二神铸消耗的物品id"

[[variables]]
name="Pos3UseItemId"
type="int32"
tag="pos3_use_item_id"
comment="部位三神铸消耗的物品id"

[[variables]]
name="Pos4UseItemId"
type="int32"
tag="pos4_use_item_id"
comment="部位四神铸消耗的物品id"
