

file="system_skill_shenghen_vo.go"
pkg="template"
class="SystemSkillShengHenTemplateVO"
comment = "系统圣痕技能配置"
[[variables]]
name="Id"
type="int"
tag="id"
comment="id"

[[variables]]
name="NextId"
type="int32"
tag="next_id"
comment="下一个id"

[[variables]]
name="Type"
type="int32"
tag="type"
comment="技能类型"

[[variables]]
name="SubType"
type="int32"
tag="sub_type"
comment="技能子类型"

[[variables]]
name="Number"
type="int32"
tag="number"
comment="需要系统等级"

[[variables]]
name="Level"
type="int32"
tag="level"
comment="技能等级"

[[variables]]
name="CostSilver"
type="int32"
tag="cost_yinliang"
comment="升级消耗的银两"

[[variables]]
name="CostGold"
type="int32"
tag="cost_yuanbao"
comment="升级消耗的元宝"

[[variables]]
name="CostItemId"
type="string"
tag="cost_item_id"
comment="物品"

[[variables]]
name="CostItemCount"
type="string"
tag="cost_item_count"
comment="物品数量"

[[variables]]
name="SkillId"
type="int32"
tag="skill_id"
comment="技能id"

[[variables]]
name="NeedEquipQuality"
type="int32"
tag="need_equip_quality"
comment="需要的装备品质"

[[variables]]
name="NeedEquipCount"
type="int32"
tag="need_equip_count"
comment="需要的装备数量"