file="system_lingzhu_skill_vo.go"
pkg="template"
class="SystemLingZhuSkillTemplateVO"
comment = "附加灵珠技能配置"
[[variables]]
name="Id"
type="int"
tag="id"
comment="id"

[[variables]]
name="NextId"
type="int32"
tag="next_id"
comment="下一个id"

[[variables]]
name="LingtongId"
type="int32"
tag="lingtong_id"
comment="灵童等级"

[[variables]]
name="Level"
type="int32"
tag="level"
comment="等级"

[[variables]]
name="NeedLingzhuLevel"
type="int32"
tag="need_lingzhu_level"
comment="需要灵珠的最低等级"

[[variables]]
name="SkillId"
type="int32"
tag="skill_id"
comment="关联技能Id"