

file="system_equip_shenghen_vo.go"
pkg="template"
class="SystemEquipShengHenTemplateVO"
comment = "系统装备圣痕配置"
[[variables]]
name="Id"
type="int"
tag="id"
comment="id"

[[variables]]
name="Series"
type="int32"
tag="series"
comment="第几阶"

[[variables]]
name="SuitGroup"
type="int32"
tag="suit_group"
comment="套装id"

[[variables]]
name="NeedItem"
type="string"
tag="need_item"
comment="需要物品"

[[variables]]
name="NeedItemNum"
type="string"
tag="need_item_num"
comment="需要物品数量"

[[variables]]
name="SuccessRate"
type="int32"
tag="success_rate"
comment="成功率"

[[variables]]
name="Next"
type="int32"
tag="next"
comment="下一阶物品"

[[variables]]
name="Hp"
type="int32"
tag="hp"
comment="生命"

[[variables]]
name="Attack"
type="int32"
tag="attack"
comment="攻击"

[[variables]]
name="Defence"
type="int32"
tag="defence"
comment="防御"

[[variables]]
name="TushiExp"
type="int32"
tag="tushi_exp"
comment="分解元神经验"

[[variables]]
name="MeltingReturnId"
type="string"
tag="melting_return_id"
comment="分解返还物品id"

[[variables]]
name="MeltingReturnCount"
type="string"
tag="melting_return_count"
comment="分解返还物品数量"
