file="system_awake_vo.go"
pkg="template"
class="SystemAwakeTemplateVO"
comment = "附加系统觉醒丹阶别配置"

[[variables]]
name="Id"
type="int"
tag="id"
comment="id"

[[variables]]
name="NextId"
type="int32"
tag="next_id"
comment="下一个id"

[[variables]]
name="SysType"
type="int32"
tag="type"
comment="系统类型"

[[variables]]
name="Number"
type="int32"
tag="number"
comment="系统阶数"

[[variables]]
name="Hp"
type="int32"
tag="hp"
comment="该等级增加的生命"

[[variables]]
name="Attack"
type="int32"
tag="attack"
comment="该等级增加的攻击"

[[variables]]
name="Defence"
type="int32"
tag="defence"
comment="该等级增加的防御"

[[variables]]
name="BeginId"
type="int"
tag="level_begin_id"
comment="升级表起始id"
