file="system_awake_use_vo.go"
pkg="template"
class="SystemAwakeUseTemplateVO"
comment = "附加使用觉醒丹配置"

[[variables]]
name="Id"
type="int"
tag="id"
comment="id"

[[variables]]
name="SysType"
type="int32"
tag="type"
comment="系统类型"

[[variables]]
name="NeedNumber"
type="int32"
tag="need_number"
comment="需要的最低系统阶别"

[[variables]]
name="UseItem"
type="int32"
tag="item_id"
comment="觉醒使用物品id"