file="taozhuang_vo.go"
pkg="template"
class="TaozhuangTemplateVO"
comment = "套装配置"
[[variables]]
name="Id"
type="int"
tag="id"
comment="id"

[[variables]]
name="Name"
type="string"
tag="name"
comment="名字"

[[variables]]
name="Type"
type="int32"
tag="type"
comment="类型"


[[variables]]
name="AttrId"
type="int32"
tag="attr_id"
comment="属性"

[[variables]]
name="Number"
type="int32"
tag="number"
comment="数量"


[[variables]]
name="Hp"
type="int64"
tag="hp"
comment="血量"

[[variables]]
name="Attack"
type="int64"
tag="attack"
comment="攻击"

[[variables]]
name="Defence"
type="int64"
tag="defence"
comment="防御"


[[variables]]
name="HpPercent"
type="int64"
tag="hp_percent"
comment="血量"

[[variables]]
name="AttPercent"
type="int64"
tag="att_percent"
comment="攻击"

[[variables]]
name="DefPercent"
type="int64"
tag="def_percent"
comment="防御"
