file="taozhuang_mubiao_vo.go"
pkg="template"
class="TaozhuangMuBiaoTemplateVO"
comment = "装备套装目标配置"
[[variables]]
name="Id"
type="int"
tag="id"
comment="id"

[[variables]]
name="Type"
type="int32"
tag="type"
comment="类型"

[[variables]]
name="NextId"
type="int32"
tag="next_id"
comment="下一级"

[[variables]]
name="NeedLevel"
type="int32"
tag="need_level"
comment="所需等级"

[[variables]]
name="Hp"
type="int64"
tag="hp"
comment="血量"

[[variables]]
name="Attack"
type="int64"
tag="attack"
comment="攻击"

[[variables]]
name="Defence"
type="int64"
tag="defence"
comment="防御"