file="teshu_drop_vo.go"
pkg="template"
class="TeShuDropTemplateVO"
comment = "活动怪物掉落模板配置"
[[variables]]
name="Id"
type="int"
tag="id"
comment="id"

[[variables]]
name="GroupId"
type="int32"
tag="group_id"
comment="活动id"

[[variables]]
name="MinCount"
type="int32"
tag="min_count"
comment="最小区间"

[[variables]]
name="MaxCount"
type="int32"
tag="max_count"
comment="最大区间"

[[variables]]
name="DropId"
type="int32"
tag="drop_id"
comment="掉落id"