file="three_robat_vo.go"
pkg="template"
class="ThreeRobatTemplateVO"
comment = "竞技场机器人模板配置"
[[variables]]
name="Id"
type="int"
tag="id"
comment="id"

[[variables]]
name="LevelMin"
type="int32"
tag="level_min"
comment="层数下限"

[[variables]]
name="LevelMax"
type="int32"
tag="level_max"
comment="层数上限"

[[variables]]
name="RobotMin"
type="int32"
tag="robot_min"
comment="机器人下限"

[[variables]]
name="RobotMax"
type="int32"
tag="robot_max"
comment="机器人上限"

[[variables]]
name="RebornMin"
type="int32"
tag="reborn_min"
comment="复活最小"

[[variables]]
name="RebornMax"
type="int32"
tag="reborn_max"
comment="复活最大"

[[variables]]
name="TimeMin"
type="int32"
tag="time_min"
comment="时间最小"

[[variables]]
name="TimeMax"
type="int32"
tag="time_max"
comment="时间最大"




