file="tianjieta_buchang_vo.go"
pkg="template"
class="TianJieTaBuChangTemplateVO"
comment = "天劫塔补偿配置"
[[variables]]
name="Id"
type="int"
tag="id"
comment="id"
 
[[variables]]
name="Number"
type="int32"
tag="number"
comment="天劫塔层数"
 
[[variables]]
name="ReturnItemId"
type="string"
tag="return_item_id"
comment="补偿的物品id"

[[variables]]
name="ReturnItemCount"
type="string"
tag="return_item_count"
comment="补偿的物品数量"
 