file="tianfu_level_vo.go"
pkg="template"
class="TianFuLevelTemplateVO"
comment = "天赋等级配置"
[[variables]]
name="Id"
type="int"
tag="id"
comment="id"

[[variables]]
name="NextId"
type="int32"
tag="next_id"
comment="下一个id"

[[variables]]
name="Level"
type="int32"
tag="level"
comment="天赋等级"

[[variables]]
name="UseItemId"
type="int32"
tag="use_item_id"
comment="升级消耗的物品id"

[[variables]]
name="UseItemCount"
type="int32"
tag="use_item_count"
comment="升级消耗的物品数量"

[[variables]]
name="UseItemIdYiJian"
type="int32"
tag="use_item_id_yijian"
comment="升级消耗的物品id"

[[variables]]
name="UseItemCountYiJian"
type="int32"
tag="use_item_count_yijian"
comment="升级消耗的物品数量"


[[variables]]
name="UseItemIdPoYue"
type="int32"
tag="use_item_id_poyue"
comment="升级消耗的物品id"

[[variables]]
name="UseItemCountPoYue"
type="int32"
tag="use_item_count_poyue"
comment="升级消耗的物品数量"

[[variables]]
name="UpdateWfb"
type="int32"
tag="update_wfb"
comment="升阶成功率"

[[variables]]
name="AreaType"
type="int32"
tag="area_type"
comment="施法范围"

[[variables]]
name="AreaRadius"
type="int32"
tag="area_radius"
comment="技能作用半径"

[[variables]]
name="AreaRange"
type="int32"
tag="area_range"
comment="施法角度"

[[variables]]
name="SpecialTarget"
type="int32"
tag="special_target"
comment="作用对象"

[[variables]]
name="SpecialEffect"
type="int32"
tag="special_effect"
comment="特殊效果标识"

[[variables]]
name="SpecialEffectRate"
type="int32"
tag="special_effect_rate"
comment="特殊效果标识概率"

[[variables]]
name="SpecialEffectValue"
type="int32"
tag="special_effect_value"
comment="产生特殊效果的值"

[[variables]]
name="SpecialEffectValue2"
type="int32"
tag="special_effect_value2"
comment="产生特殊效果的值"


[[variables]]
name="SpecialEffectValue3"
type="int32"
tag="special_effect_value3"
comment="产生特殊效果的值"


[[variables]]
name="AddStatus"
type="string"
tag="add_status"
comment="给予目标的buff"


[[variables]]
name="AddStatusRate"
type="string"
tag="add_status_rate"
comment="增加该状态的概率"

[[variables]]
name="BuffDongTaiId"
type="string"
tag="buff_dongtai_id"
comment="关联到动态buff等级表"







