file="tianjipai_vo.go"
pkg="template"
class="TianJiPaiTemplateVO"
comment = "天机牌配置"
[[variables]]
name="Id"
type="int"
tag="id"
comment="id"

[[variables]]
name="PoolType"
type="int32"
tag="pool_type"
comment="任务类型"

[[variables]]
name="LevelMin"
type="int32"
tag="level_min"
comment="最小等级"

[[variables]]
name="LevelMax"
type="int32"
tag="level_max"
comment="最大等级"

[[variables]]
name="ModuleOpenedId"
type="int32"
tag="module_opened_id"
comment="关联到功能开启表"

[[variables]]
name="QuestId"
type="int32"
tag="quest_id"
comment="关联任务表的ID"

[[variables]]
name="StarMin"
type="int32"
tag="star_min"
comment="最小星级"

[[variables]]
name="StarMax"
type="int32"
tag="star_max"
comment="最大星级"

[[variables]]
name="RewSilver"
type="int32"
tag="rew_silver"
comment="完成任务奖励的银两"

[[variables]]
name="DropCount1"
type="int32"
tag="drop_count1"
comment="间隔多少次走掉落包1"

[[variables]]
name="DropId1"
type="int32"
tag="drop_id1"
comment="掉落包1"

[[variables]]
name="DropCount2"
type="int32"
tag="drop_count2"
comment="间隔多少次走掉落包2"

[[variables]]
name="DropId2"
type="int32"
tag="drop_id2"
comment="掉落包2"

[[variables]]
name="DropCount3"
type="int32"
tag="drop_count3"
comment="间隔多少次走掉落包3"

[[variables]]
name="DropId3"
type="int32"
tag="drop_id3"
comment="掉落包3"

[[variables]]
name="DropCount4"
type="int32"
tag="drop_count4"
comment="间隔多少次走掉落包4"


[[variables]]
name="DropId4"
type="int32"
tag="drop_id4"
comment="掉落包4"

[[variables]]
name="SpeDrop"
type="string"
tag="spe_drop"
comment="前五次掉落"

[[variables]]
name="Remarks"
type="string"
tag="remarks"
comment="备注"

