file="tianjipai_prompt_vo.go"
pkg="template"
class="TianJiPaiPromptTemplateVO"
comment = "天机牌提示配置"
[[variables]]
name="Id"
type="int"
tag="id"
comment="id"

[[variables]]
name="ModuleOpenedId"
type="int32"
tag="module_opened_id"
comment="关联到功能开启表"

[[variables]]
name="IsAuto"
type="int32"
tag="is_auto"
comment="是否可以一键完成"


[[variables]]
name="RewardPreview"
type="string"
tag="reward_preview"
comment="奖励预览"

[[variables]]
name="Remarks"
type="string"
tag="remarks"
comment="备注"

