file="tianshu_vo.go"
pkg="template"
class="TianShuTemplateVO"
comment = "天书配置"
[[variables]]
name="Id"
type="int"
tag="id"
comment="id"

[[variables]]
name="Type"
type="int32"
tag="type"
comment="天书类型"

[[variables]]
name="Level"
type="int32"
tag="level"
comment="天书等级"

[[variables]]
name="SuccessRate"
type="int32"
tag="success_rate"
comment="升级成功率"

[[variables]]
name="LevelItem"
type="string"
tag="level_item"
comment="升级消耗物品id"

[[variables]]
name="LevelItemCount"
type="string"
tag="level_item_count"
comment="升级消耗物品数量"

[[variables]]
name="NextId"
type="int32"
tag="next_id"
comment="下一级id"

[[variables]]
name="NeedGold"
type="int32"
tag="need_gold"
comment="激活需要充值的数量"

[[variables]]
name="Hp"
type="int32"
tag="hp"
comment="激活属性"

[[variables]]
name="Attack"
type="int32"
tag="attack"
comment="激活属性"

[[variables]]
name="Defence"
type="int32"
tag="defence"
comment="激活属性"

[[variables]]
name="FreeGiftId"
type="string"
tag="free_gift_id"
comment="激活奖励id"

[[variables]]
name="FreeGiftCount"
type="string"
tag="free_gift_count"
comment="激活奖励数量"

[[variables]]
name="FreeGiftSilver"
type="int32"
tag="free_gift_silver"
comment="激活奖励银两"

[[variables]]
name="FreeGiftBindgold"
type="int32"
tag="free_gift_bindgold"
comment="激活奖励绑元"

[[variables]]
name="FreeGiftGold"
type="int32"
tag="free_gift_gold"
comment="激活奖励元宝"

[[variables]]
name="Tequan"
type="int32"
tag="tequan"
comment="特权比率"

