file="tianfu_vo.go"
pkg="template"
class="TianFuTemplateVO"
comment = "天赋配置"
[[variables]]
name="Id"
type="int"
tag="id"
comment="id"

[[variables]]
name="NextId"
type="int32"
tag="next_id"
comment="下一个id"

[[variables]]
name="Name"
type="string"
tag="name"
comment="天赋名称"

[[variables]]
name="LevelBegin"
type="int32"
tag="level_begin"
comment="天赋升级起始id"

[[variables]]
name="ParentId"
type="int32"
tag="parent_id"
comment="激活该天赋需要的前置id"
