file="title_vo.go"
pkg="template"
class="TitleTemplateVO"
comment = "称号配置"
[[variables]]
name="Id"
type="int"
tag="id"
comment="id"

[[variables]]
name="Name"
type="string"
tag="name"
comment="称号名称"

[[variables]]
name="Type"
type="int32"
tag="type"
comment="称号类型"

[[variables]]
name="SubType"
type="int32"
tag="sub_type"
comment="称号子类型"

[[variables]]
name="Sort"
type="int32"
tag="sort"
comment="排序"

[[variables]]
name="NeedItemId"
type="int32"
tag="need_item_id"
comment="需要物品id"

[[variables]]
name="NeedItemCount"
type="int32"
tag="need_item_count"
comment="需要物品数量"

[[variables]]
name="Time"
type="int64"
tag="time"
comment="有效性"

[[variables]]
name="Attr"
type="int32"
tag="attr"
comment="属性"

[[variables]]
name="UpStarBeginId"
type="int32"
tag="title_upstar_begin_id"
comment="称号升星起始id"


[[variables]]
name="Access"
type="string"
tag="access"
comment="获取途径"

[[variables]]
name="Resource"
type="string"
tag="resource"
comment="资源"
