file="title_dingzhi_vo.go"
pkg="template"
class="TitleDingZhiTemplateVO"
comment = "称号定制配置"
[[variables]]
name="Id"
type="int"
tag="id"
comment="id"

[[variables]]
name="Name"
type="string"
tag="name"
comment="称号名称"


[[variables]]
name="Sort"
type="int32"
tag="sort"
comment="排序"

[[variables]]
name="NeedItemId"
type="int32"
tag="need_item_id"
comment="需要物品id"

[[variables]]
name="NeedItemCount"
type="int32"
tag="need_item_count"
comment="需要物品数量"


[[variables]]
name="Hp"
type="int64"
tag="hp"
comment="生命上限"

[[variables]]
name="Attack"
type="int64"
tag="attack"
comment="攻击值"

[[variables]]
name="Defence"
type="int64"
tag="defence"
comment="防御值"


[[variables]]
name="BuffId"
type="int32"
tag="buff_id"
comment="buff的id"

[[variables]]
name="Access"
type="string"
tag="access"
comment="获取途径"

