

file="trade_constant_vo.go"
pkg="template"
class="TradeConstantTemplateVO"
comment = "属性配置"
[[variables]]
name="Id"
type="int"
tag="id"
comment="id"

[[variables]]
name="NeedChongzhi"
type="int32"
tag="need_chongzhi"
comment="玩家充值小于额度可以回购"

[[variables]]
name="ShangjiaTime"
type="int32"
tag="shangjia_time"
comment="上架时间超过一定时间"

[[variables]]
name="XiajiaTime"
type="int32"
tag="xiajia_time"
comment="下架时间"


[[variables]]
name="GmMoneyMax"
type="int32"
tag="gm_money_max"
comment="每天回购总量"

[[variables]]
name="PlayerMoneyMax"
type="int32"
tag="player_money_max"
comment="每个玩家回购的最大值"

[[variables]]
name="PersonalCountMax"
type="int32"
tag="personal_count_max"
comment="个人上架数量"

[[variables]]
name="AllCountMax"
type="int32"
tag="all_count_max"
comment="所有数量"

[[variables]]
name="HuigouPriceMax"
type="int32"
tag="huigou_price_max"
comment="回购最大值"

