

file="tulong_equip_vo.go"
pkg="template"
class="TuLongEquipTemplateVO"
comment = "屠龙装备配置"
[[variables]]
name="Id"
type="int"
tag="id"
comment="id"

[[variables]]
name="SuitGroup"
type="int32"
tag="suit_group"
comment="套装id"

[[variables]]
name="Number"
type="int32"
tag="number"
comment="阶数"

[[variables]]
name="Hp"
type="int32"
tag="hp"
comment="生命"

[[variables]]
name="Attack"
type="int32"
tag="attack"
comment="攻击"

[[variables]]
name="Defence"
type="int32"
tag="defence"
comment="防御"

[[variables]]
name="PosType"
type="int32"
tag="type"
comment="部位"
