

file="tulong_equip_strengthen_vo.go"
pkg="template"
class="TuLongEquipStrengthenTemplateVO"
comment = "屠龙装备强化配置"
[[variables]]
name="Id"
type="int"
tag="id"
comment="id"

[[variables]]
name="Type"
type="int32"
tag="type"
comment="套装类型"

[[variables]]
name="SubType"
type="int32"
tag="sub_type"
comment="部位"

[[variables]]
name="Level"
type="int32"
tag="level"
comment="强化等级"

[[variables]]
name="NextId"
type="int32"
tag="next_id"
comment="下级id"

[[variables]]
name="Rate"
type="int32"
tag="rate"
comment="强化概率"

[[variables]]
name="Hp"
type="int32"
tag="hp"
comment="生命"

[[variables]]
name="Attack"
type="int32"
tag="attack"
comment="攻击"

[[variables]]
name="Defence"
type="int32"
tag="defence"
comment="防御"

[[variables]]
name="NeedItem"
type="int32"
tag="need_item"
comment="强化的物品id"

[[variables]]
name="ItemCount"
type="int32"
tag="item_count"
comment="强化的物品数量"

