

file="tulong_equip_skill_vo.go"
pkg="template"
class="TuLongEquipSkillTemplateVO"
comment = "屠龙装备技能配置"
[[variables]]
name="Id"
type="int"
tag="id"
comment="id"

[[variables]]
name="NextId"
type="int32"
tag="next_id"
comment="下一个id"

[[variables]]
name="Level"
type="int32"
tag="level"
comment="技能等级"

[[variables]]
name="Type"
type="int32"
tag="type"
comment="技能类型"

[[variables]]
name="NeedJieShu"
type="int32"
tag="value1"
comment="需要装备阶数"

[[variables]]
name="NeedEquipNum"
type="int32"
tag="value2"
comment="需要装备数量"

[[variables]]
name="NeedStrengthenLevel"
type="int32"
tag="value3"
comment="需要装备总强化等级"

[[variables]]
name="SkillId"
type="int32"
tag="skill_id"
comment="技能id"

[[variables]]
name="UplevelItem"
type="string"
tag="uplevel_item"
comment="物品id"

[[variables]]
name="UplevelItemCount"
type="string"
tag="uplevel_item_count"
comment="物品数量"
 
[[variables]]
name="UplevelRate"
type="int32"
tag="uplevel_rate"
comment="升级成功率"