file="tulong_constant_vo.go"
pkg="template"
class="TuLongConstantTemplateVO"
comment = "屠龙常量配置"
[[variables]]
name="Id"
type="int"
tag="id"
comment="id"

[[variables]]
name="rew_preview_id"
type="string"
tag="rew_preview_id"
comment="奖励预览"

[[variables]] 
name="RewPreviewCount"
type="string"
tag="rew_preview_count"
comment="奖励预览的数量"

[[variables]]
name="BigEgg"
type="int32" 
tag="big_egg"
comment="大龙蛋id"

[[variables]]
name="SmallEgg"
type="int64"
tag="small_egg"
comment="小龙蛋id"

[[variables]]
name="MapId"
type="int32"
tag="map_id"
comment="地图id"

[[variables]]
name="BossTime"
type="int32"
tag="boss_time"
comment="大BOSS刷新时间(活动开始后多少时间,单位:毫秒)"

[[variables]]
name="CaiJiTime"
type="int32"
tag="caiji_time"
comment="采集小龙蛋的时间(毫秒)"

[[variables]]
name="SmallEggShuaXin"
type="int32"
tag="small_egg_shuaxin"
comment="小龙蛋的刷新时间(毫秒)"

[[variables]]
name="PlayerLimitCount"
type="int32"
tag="player_limit_count"
comment="场景人数限制"



