file="tulong_vo.go"
pkg="template"
class="TuLongTemplateVO"
comment = "屠龙配置"
[[variables]]
name="Id"
type="int"
tag="id"
comment="id"

[[variables]]
name="Type"
type="int32"
tag="type"
comment="怪物类型 0为大BOSS 1为小BOSS"

[[variables]]
name="BiologyId"
type="int32"
tag="biology_id"
comment="生物id"

[[variables]]
name="BiaoShi"
type="int32"
tag="biaoshi"
comment="标识,用于服务端区分不同的怪物"

[[variables]]
name="RewSilver"
type="int32"
tag="rew_silver"
comment="仙盟成员获得的银两"

[[variables]]
name="RewGold"
type="int32"
tag="rew_gold"
comment="仙盟成员获得的元宝"

[[variables]]
name="RewBindGold"
type="int32"
tag="rew_bindgold"
comment="仙盟成员获得的绑元"

[[variables]]
name="RewExp"
type="int32"
tag="rew_exp"
comment="仙盟成员获得的经验"


[[variables]]
name="RewItemId"
type="string"
tag="rew_item_id"
comment="仙盟成员获得的物品id"

[[variables]]
name="RewCount"
type="string"
tag="rew_count"
comment="仙盟成员获得的物品数量"

