

file="tulong_equip_zhuanhua_vo.go"
pkg="template"
class="TuLongEquipZhuanHuaTemplateVO"
comment = "屠龙转化配置"
[[variables]]
name="Id"
type="int"
tag="id"
comment="id"

[[variables]]
name="SubType"
type="int32"
tag="type"
comment="装备子类型" 

[[variables]]
name="Level"
type="int32"
tag="level"
comment="强化等级"

[[variables]]
name="DropId"
type="int32"
tag="drop_id"
comment="掉落id"
