file="union_shengtan_vo.go"
pkg="template"
class="UnionShengTanTemplateVO"
comment = "仙盟圣坛模板配置"
[[variables]]
name="Id"
type="int"
tag="id"
comment="id"


[[variables]]
name="FirstTime"
type="int64"
tag="frist_tiem"
comment="进入多少毫秒后获得奖励"


[[variables]]
name="RewTime"
type="int64"
tag="rew_tiem"
comment="多少毫秒发放一次奖励"

[[variables]]
name="ExpAddItemLimit"
type="int32"
tag="exp_add_item_limit"
comment="百年仙酿使用上限"

[[variables]]
name="XiaoguaiTime"
type="int32"
tag="xiaoguai_time"
comment="刷新时间"

[[variables]]
name="ShengtanId"
type="int32"
tag="shengtan_id"
comment="圣坛id"

[[variables]]
name="GonggaoHpPercent"
type="int32"
tag="gonggao_hp_percent"
comment="公告比例"

[[variables]]
name="ShuaguaiBeginTime"
type="int32"
tag="shuaguai_begin_time"
comment="刷怪开始时间"



