file="union_boss_vo.go"
pkg="template"
class="UnionBossTemplateVO"
comment = "仙盟boss模板配置"
[[variables]]
name="Id"
type="int"
tag="id"
comment="id"


[[variables]]
name="NextId"
type="int32"
tag="next_id"
comment="下一个id"

[[variables]]
name="Level"
type="int32"
tag="level"
comment="boss等级"

[[variables]]
name="Experience"
type="int32"
tag="experience"
comment="升级所需经验"

[[variables]]
name="BiologyId"
type="int32"
tag="biology_id"
comment="生物id"

[[variables]]
name="MapId"
type="int32"
tag="map_id"
comment="地图id"

[[variables]]
name="RewPre"
type="string"
tag="rew_pre"
comment="奖励预览"

[[variables]]
name="MzAwardSilver"
type="int32"
tag="mz_award_silver"
comment="盟主额外获得的银两奖励"

[[variables]]
name="MzAwardGold"
type="int32"
tag="mz_award_gold"
comment="盟主额外获得的元宝奖励"

[[variables]]
name="MzAwardBindGold"
type="int32"
tag="mz_award_bindgold"
comment="盟主额外获得的绑元奖励"

[[variables]]
name="MzAwardItemId"
type="string"
tag="mz_award_item_id"
comment="盟主额外获得的物品奖励"

[[variables]]
name="MzAwardItemCount"
type="string"
tag="mz_award_item_count"
comment="盟主额外获得的物品奖励数量"


[[variables]]
name="CyAwardSilver"
type="int32"
tag="cy_award_silver"
comment="仙盟全体成员获得的银两数量"

[[variables]]
name="CyAwardGold"
type="int32"
tag="cy_award_gold"
comment="仙盟全体成员获得的元宝数量"

[[variables]]
name="CyAwardBindGold"
type="int32"
tag="cy_award_bindgold"
comment="仙盟全体成员获得的绑元数量"

[[variables]]
name="CyAwardItemId"
type="string"
tag="cy_award_item_id"
comment="仙盟全体成员获得的物品奖励"


[[variables]]
name="CyAwardItemCount"
type="string"
tag="cy_award_item_count"
comment="仙盟全体成员获得的物品奖励数量"


[[variables]]
name="PosX"
type="float64"
tag="pos_x"
comment="坐标x"

[[variables]]
name="PosY"
type="float64"
tag="pos_y"
comment="坐标y"

[[variables]]
name="PosZ"
type="float64"
tag="pos_z"
comment="坐标z"




