file="union_donate_vo.go"
pkg="template"
class="UnionDonateTemplateVO"
comment = "仙盟捐献配置"
[[variables]]
name="Id"
type="int"
tag="id"
comment="id"

[[variables]]
name="Name"
type="string"
tag="name"
comment="名称"

[[variables]]
name="Type"
type="int32"
tag="type"
comment="类型"

[[variables]]
name="DonateItemId"
type="int32"
tag="donate_item_id"
comment="捐献物品id"

[[variables]]
name="DonateItemCount"
type="int32"
tag="donate_item_count"
comment="捐献物品数量"

[[variables]]
name="DonateSilver"
type="int32"
tag="donate_silver"
comment="捐献银两"

[[variables]]
name="DonateGold"
type="int32"
tag="donate_gold"
comment="捐献元宝"

[[variables]]
name="DonateBuild"
type="int32"
tag="donate_bulid"
comment="建设性"

[[variables]]
name="DonateContribution"
type="int32"
tag="donate_contribution"
comment="贡献"

[[variables]]
name="DonateLimit"
type="int32"
tag="donate_limit"
comment="次数限制"

