file="vip_vo.go"
pkg="template"
class="VipTemplateVO"
comment = "vip模板配置"
[[variables]]
name="Id"
type="int"
tag="id"
comment="id"

[[variables]]
name="Level"
type="int32"
tag="level"
comment="vip等级"

[[variables]]
name="Star"
type="int32"
tag="star"
comment="星级"

[[variables]]
name="NextId"
type="int32"
tag="next_id"
comment="下一级"

[[variables]]
name="NeedValue"
type="int32"
tag="need_value"
comment="需要消费的元宝"

[[variables]]
name="Hp"
type="int32"
tag="hp"
comment="血量加成"

[[variables]]
name="Attack"
type="int32"
tag="attack"
comment="攻击加成"

[[variables]]
name="Defence"
type="int32"
tag="defence"
comment="防御加成"

[[variables]]
name="GiftId"
type="string"
tag="gift_id"
comment="礼包"

[[variables]]
name="GiftCount"
type="string"
tag="gift_count"
comment="数量"

[[variables]]
name="GiftSilver"
type="int64" 
tag="gift_silver"
comment="礼物银两"

[[variables]]
name="FreeGiftId"
type="string"
tag="free_gift_id"
comment="免费礼包"

[[variables]]
name="FreeGiftCount"
type="string"
tag="free_gift_count"
comment="免费礼包数量"

[[variables]]
name="FreeGiftSilver"
type="int64" 
tag="free_gift_silver"
comment="免费礼物银两"

[[variables]]
name="Price"
type="int32"
tag="price"
comment="现价"

[[variables]]
name="CostPrice"
type="int32"
tag="cost_price"
comment="原价"

[[variables]]
name="BuyPilaoCount"
type="int32"
tag="buy_pilao_count"
comment="购买疲劳值上限"

[[variables]]
name="HbSnatchCount"
type="int32"
tag="buy_hb_count"
comment="vip额外领取红包数量"

[[variables]]
name="BabyChaoSheng"
type="int32"
tag="baby_chaosheng"
comment="VIP超生数量"

[[variables]]
name="Shouxu"
type="int32"
tag="shouxu"
comment="手续费"

