file="war_vo.go"
pkg="template"
class="WarTemplateVO"
comment = "城战配置"
[[variables]]
name="Id"
type="int"
tag="id"
comment="id"


[[variables]]
name="PlateMax"
type="int32"
tag="plate_max"
comment="最大获得腰牌的上限"

[[variables]]
name="PalteOdd"
type="int32"
tag="palte_odd"
comment="每次击杀获得腰牌的几率(万分比)"

# [[variables]]
# name="OccupyCityTime"
# type="int32"
# tag="occupy_city_time"
# comment="占领皇城需要的时间(毫秒)"

[[variables]]
name="RebornSitu"
type="int32"
tag="reborn_situ"
comment="原地复活的最高次数"

[[variables]]
name="OccupyFlagTime"
type="int32"
tag="occupy_flag_time"
comment="采集旗子所需要的时间(毫秒)"

[[variables]]
name="PlateTime"
type="int32"
tag="plate_time"
comment="击杀同一个玩家获得腰牌的间隔时间(毫秒)"

[[variables]]
name="DropId"
type="int32"
tag="drop_id"
comment="掉落包"

[[variables]]
name="HuanggongTime"
type="int32"
tag="huanggong_time"
comment="皇宫时间"


[[variables]]
name="FristTiem"
type="int64"
tag="frist_tiem"
comment="进入后多少毫秒获得奖励"

[[variables]]
name="RewTiem"
type="int64"
tag="rew_tiem"
comment="多少毫秒发一次奖励"

[[variables]]
name="RewExp"
type="int64"
tag="rew_exp"
comment="单次发放经验值"

[[variables]]
name="RewExpPoint"
type="int32"
tag="rew_exp_point"
comment="单次发放的经验点"

[[variables]]
name="RewSilver"
type="int64"
tag="rew_silver"
comment="奖励银两"

[[variables]]
name="MapId"
type="int32"
tag="map_id"
comment="地图id"

[[variables]]
name="RewExpSafeArea"
type="int64"
tag="rew_exp_anquanqu"
comment="单次发放经验值"

[[variables]]
name="RewExpPointSafeArea"
type="int32"
tag="rew_exp_point_anquanqu"
comment="单次发放的经验点"

[[variables]]
name="RewSilverSafeArea"
type="int64"
tag="rew_silver_anquanqu"
comment="奖励银两"
 
[[variables]]
name="FirstXianzhi"
type="int32"
tag="first_xianzhi"
comment="限制区域1"

[[variables]]
name="SecondXianzhi"
type="int32"
tag="second_xianzhi"
comment="限制区域2"

[[variables]]
name="ThirdXianzhi"
type="int32"
tag="third_xianzhi"
comment="限制区域3"

[[variables]]
name="FourXianzhi"
type="int32"
tag="four_xianzhi"
comment="限制区域4"

[[variables]]
name="LahuiPos1"
type="string"
tag="lahui_pos1"
comment="区域1固定点"

[[variables]]
name="LahuiPos2"
type="string"
tag="lahui_pos2"
comment="区域2固定点"

[[variables]]
name="LahuiPos3"
type="string"
tag="lahui_pos3"
comment="区域3固定点"


[[variables]]
name="KillJiFen"
type="int32"
tag="kill_jifen"
comment="击杀获得积分"

[[variables]]
name="FristJiFenTime"
type="int64"
tag="frist_jifen_time"
comment="进入后多少毫秒获得奖励"

[[variables]] 
name="RewJiFenTime"
type="int64"
tag="rew_jifen_time"
comment="多少毫秒发一次奖励"

[[variables]]
name="RewJiFen"
type="int32"
tag="rew_jifen"
comment="单次发放经验值"


[[variables]]
name="ProtectPosX"
type="float64"
tag="pos_x1"
comment="保护罩地图x坐标"

[[variables]]
name="ProtectPosY"
type="float64"
tag="pos_y1"
comment="保护罩地图y坐标"

[[variables]]
name="ProtectPosZ"
type="float64"
tag="pos_z1"
comment="保护罩地图z坐标"

[[variables]]
name="ProtectId"
type="int32"
tag="zhaozi_id"
comment="保护罩id"

[[variables]]
name="ProtectRebornTime"
type="int64"
tag="zhaozi_reborn_time"
comment="保护罩生成时间"

[[variables]]
name="YuXiPosX"
type="float64"
tag="pos_x2"
comment="玉玺采集物地图x坐标"

[[variables]]
name="YuXiPosY"
type="float64"
tag="pos_y2"
comment="玉玺采集物地图y坐标"

[[variables]]
name="YuXiPosZ"
type="float64"
tag="pos_z2"
comment="玉玺采集物地图z坐标"

[[variables]]
name="YuxiId"
type="int32"
tag="yuxi_id"
comment="玉玺采集物id"

[[variables]]
name="ProtectBuffId"
type="int32"
tag="wudi_buff_id"
comment="防护罩无敌buff"

[[variables]]
name="ProtectQuYuPos"
type="int32"
tag="zhaozi_quyu_pos"
comment="防护罩限制区域"

[[variables]]
name="ProtectLaHuiPos"
type="string"
tag="zhaozi_lahui_pos"
comment="防护罩驱逐固定点"
