file="war_award_door_vo.go"
pkg="template"
class="WarAwardDoorTemplateVO"
comment = "城门奖励配置"

[[variables]]
name="Id"
type="int"
tag="id"
comment="id"

[[variables]]
name="BiologyId"
type="int32"
tag="biology_id"
comment="生物id"


[[variables]]
name="WarDoorSilver"
type="int32"
tag="war_door_silver"
comment="银两"

[[variables]]
name="WarDoorGold"
type="int32"
tag="war_door_gold"
comment="元宝"

[[variables]]
name="WarDoorBindgold"
type="int32"
tag="war_door_bindgold"
comment="绑元"

[[variables]]
name="WarDoorItemId"
type="string"
tag="war_door_item_id"
comment="物品"

[[variables]]
name="WarDoorItemIdCount"
type="string"
tag="war_door_item_id_count"
comment="物品数量"

[[variables]]
name="NeedJiFen"
type="int32"
tag="need_jifen"
comment="所需积分"
