file="war_award_occupy_vo.go"
pkg="template"
class="WarAwardOccupyTemplateVO"
comment = "城战奖励配置"
[[variables]]
name="Id"
type="int"
tag="id"
comment="id"

[[variables]]
name="OccupyCityContinue"
type="int32"
tag="occupy_city_continue"
comment="连胜"

[[variables]]
name="WarAwardSilver"
type="int32"
tag="war_award_silver"
comment="银两"

[[variables]]
name="WarAwardGold"
type="int32"
tag="war_award_gold"
comment="元宝"

[[variables]]
name="WarAwardBindgold"
type="int32"
tag="war_award_bindgold"
comment="绑定"

[[variables]]
name="WarAwardItemId"
type="string"
tag="war_award_item_id"
comment="物品"


[[variables]]
name="WarAwardItemIdCount"
type="string"
tag="war_award_item_id_count"
comment="数量"
