file="weapon_vo.go"
pkg="template"
class="WeaponTemplateVO"
comment = "兵魂配置"
[[variables]]
name="Id"
type="int"
tag="id"
comment="id"

[[variables]]
name="Name1"
type="string"
tag="name_1"
comment="名称1"

[[variables]]
name="Name2"
type="string"
tag="name_2"
comment="名称2"

[[variables]]
name="Name3"
type="string"
tag="name_3"
comment="名称3"

[[variables]]
name="Pos"
type="int32"
tag="pos"
comment="兵魂排序"

[[variables]]
name="Tag"
type="int32"
tag="tag"
comment="兵魂标识"

[[variables]]
name="Type"
type="int32"
tag="type"
comment="兵魂类型"

[[variables]]
name="Icon"
type="int32"
tag="icon"
comment="图标"

[[variables]]
name="Disc"
type="string"
tag="disc"
comment="兵魂描述"

[[variables]]
name="AttrId"
type="int32"
tag="attr_id"
comment="属性"

[[variables]]
name="NeedItemId"
type="string"
tag="activation_need_item_id"
comment="激活所需物品ID"

[[variables]]
name="NeedItemCount"
type="string"
tag="activation_need_item_count"
comment="激活所需物品数量"

[[variables]]
name="NeedItemId2"
type="string"
tag="activation_need_item_id2"
comment="激活所需物品ID2"

[[variables]]
name="NeedItemCount2"
type="string"
tag="activation_need_item_count2"
comment="激活所需物品数量2"

[[variables]]
name="NeedItemId3"
type="string"
tag="activation_need_item_id3"
comment="激活所需物品ID3"

[[variables]]
name="NeedItemCount3"
type="string"
tag="activation_need_item_count3"
comment="激活所需物品数量3"

[[variables]]
name="IsAwaken"
type="int32"
tag="is_awaken"
comment="是否可以觉醒"

[[variables]]
name="NeedStar"
type="int32"
tag="awaken_need_star"
comment="觉醒所需星级"

[[variables]]
name="AwakenItemId"
type="int32"
tag="awaken_need_item_id"
comment="觉醒所需物品id"

[[variables]]
name="AwakenItemNum"
type="int32"
tag="awaken_need_item_num"
comment="觉醒所需物品数量"

[[variables]]
name="AwakenSuccessRate"
type="int32"
tag="awaken_success_rate"
comment="觉醒成功率"

[[variables]]
name="AwakenAttr"
type="int32"
tag="awaken_attr"
comment="觉醒属性"

[[variables]]
name="Effect"
type="string"
tag="effect"
comment="觉醒光效"

[[variables]]
name="Achieve"
type="string"
tag="achieve"
comment="获取途径描述"


[[variables]]
name="EatDan"
type="int32"
tag="eat_dan"
comment="食丹等级上限"

[[variables]]
name="WeaponUpgradeBeginId"
type="int32"
tag="weapon_upgrade_begin_id"
comment="兵魂起始ID"

[[variables]]
name="WeaponPeiYangBeginId"
type="int32"
tag="weapon_peiyang_begin_id"
comment="兵魂培养起始ID"


[[variables]]
name="WpL1"
type="string"
tag="wp_l_1"
comment="左手武器开天"

[[variables]]
name="WpR1"
type="string"
tag="wp_r_1"
comment="右手武器开天"


[[variables]]
name="WpB1"
type="string"
tag="wp_b_1"
comment="背部挂点开天"

[[variables]]
name="WpA1"
type="string"
tag="wp_a_1"
comment="背部挂点开天"

[[variables]]
name="WpL2"
type="string"
tag="wp_l_2"
comment="左手武器奕剑"

[[variables]]
name="WpR2"
type="string"
tag="wp_r_2"
comment="右手武器奕剑"


[[variables]]
name="WpB2"
type="string"
tag="wp_b_2"
comment="背部挂点奕剑"

[[variables]]
name="WpA2"
type="string"
tag="wp_a_2"
comment="背部挂点奕剑"

[[variables]]
name="WpL3"
type="string"
tag="wp_l_3"
comment="左手武器破月"

[[variables]]
name="WpR3"
type="string"
tag="wp_r_3"
comment="右手武器破月"

[[variables]]
name="WpB3"
type="string"
tag="wp_b_3"
comment="背部挂点破月"

[[variables]]
name="WpA3"
type="string"
tag="wp_a_3"
comment="背部挂点破月"



