file="weapon_upstar_vo.go"
pkg="template"
class="WeaponUpstarTemplateVO"
comment = "兵魂升星配置"
[[variables]]
name="Id"
type="int"
tag="id"
comment="id"

[[variables]]
name="NextId"
type="int32"
tag="next_id"
comment="下个id"


[[variables]]
name="Level"
type="int32"
tag="level"
comment="星级"

[[variables]]
name="Name"
type="string"
tag="name"
comment="名字"


[[variables]]
name="UpstarRate"
type="int32"
tag="upstar_rate"
comment="升星成功率"

[[variables]]
name="UpstarItemId"
type="int32"
tag="upstar_item_id"
comment="升星物品ID(开天)"

[[variables]]
name="UpstarItemCount"
type="int32"
tag="upstar_item_count"
comment="升星物品数量(开天)"

[[variables]]
name="UpstarItemId2"
type="int32"
tag="upstar_item_id2"
comment="升星物品ID(奕剑)"

[[variables]]
name="UpstarItemCount2"
type="int32"
tag="upstar_item_count2"
comment="升星物品数量(奕剑)"

[[variables]]
name="UpstarItemId3"
type="int32"
tag="upstar_item_id3"
comment="升星物品ID(破月)"

[[variables]]
name="UpstarItemCount3"
type="int32"
tag="upstar_item_count3"
comment="升星物品数量(破月)"

[[variables]]
name="TimesMin"
type="int32"
tag="times_min"
comment="最小次数"

[[variables]]
name="TimesMax"
type="int32"
tag="times_max"
comment="最大次数"

[[variables]]
name="AddMin"
type="int32"
tag="add_min"
comment="每次培养增加的进度最小值"

[[variables]]
name="AddMax"
type="int32"
tag="add_max"
comment="每次培养增加的进度最大值"

[[variables]]
name="ZhufuMax"
type="int32"
tag="zhufu_max"
comment="前端显示的进度值"

[[variables]]
name="Hp"
type="int32"
tag="hp"
comment="该等级增加的生命"


[[variables]]
name="Attack"
type="int32"
tag="attack"
comment="该等级增加的攻击"


[[variables]]
name="Defence"
type="int32"
tag="defence"
comment="该等级增加的防御"
