file="welfare_scene_qiyu_vo.go"
pkg="template"
class="WelfareSceneQiYuTemplateVO"
comment = "运营活动奇遇岛副本配置"
[[variables]]
name="Id"
type="int"
tag="id"
comment="id"

[[variables]]
name="BiologyBeginId"
type="int32"
tag="pos_begin_id"
comment="怪物起始配置"
   
[[variables]]
name="RefreshBiologyBeginTime"
type="string" 
tag="refresh_biology_begin_time" 
comment="开始刷新时间"
 
[[variables]]
name="RefreshBiologyTime"
type="int64"
tag="refresh_biology_time" 
comment="刷新间隔时间"
 
[[variables]]
name="RefreshBiologyTimes"
type="int32"
tag="refresh_biology_times" 
comment="刷新次数"