file="welfare_scene_vo.go"
pkg="template"
class="WelfareSceneTemplateVO"
comment = "运营活动副本配置"
[[variables]]
name="Id"
type="int"
tag="id"
comment="id"

[[variables]]
name="GroupId"
type="int32"
tag="groupId"
comment="活动groupId"

[[variables]]
name="Type"
type="int32"
tag="type"
comment="副本类型"

[[variables]]
name="MapId"
type="int32"
tag="map_id"
comment="地图id"
 
[[variables]]
name="SubTemplateId"
type="int32"
tag="yunying_sub_id" 
comment="扩展关联id"
 