file="world_boss_vo.go"
pkg="template"
class="WorldBossTemplateVO"
comment = "世界boss配置"
[[variables]]
name="Id"
type="int"
tag="id"
comment="id"

[[variables]]
name="Type"
type="int32"
tag="type"
comment="boss类型"

[[variables]]
name="BiologyId"
type="int32"
tag="biology_id"
comment="生物id"

[[variables]]
name="MapId"
type="int32"
tag="map_id"
comment="地图id"

[[variables]]
name="Reward"
type="string"
tag="reward"
comment="奖励预览物品id"


[[variables]]
name="RecForce"
type="int64"
tag="rec_force"
comment="战力"

