file="wushuangweapon_buchang_vo.go"
pkg="template"
class="WushuangWeaponBuchangTemplateVO"
comment = "无双神器补偿配置"
[[variables]]
name="Id"
type="int"
tag="id"
comment="id"

[[variables]]
name="Time"
type="int64"
tag="time"
comment="时间"

[[variables]]
name="ItemId"
type="int32"
tag="item_id"
comment="辨识补偿物品id"

[[variables]]
name="RawItem_id"
type="string"
tag="raw_item_id"
comment="奖励物品id"

[[variables]]
name="RawItemCount"
type="string"
tag="raw_item_count"
comment="奖励物品数量"