file="wushuangweapon_base_vo.go"
pkg="template"
class="WushuangWeaponBaseTemplateVO"
comment = "无双神器基本配置"
[[variables]]
name="Id"
type="int"
tag="id"
comment="id"

[[variables]]
name="Hp"
type="int64"
tag="hp"
comment="基础生命值"

[[variables]]
name="Attack"
type="int64"
tag="attack"
comment="基础攻击力"

[[variables]]
name="Defence"
type="int64"
tag="defence"
comment="基础防御力"

[[variables]]
name="StrengthenBeginId"
type="int32"
tag="strengthen_begin_id"
comment="可强化的最大等级"

[[variables]]
name="WaiguanJihuoLevel"
type="int32"
tag="waiguan_jihuo_level"
comment="外观激活需要的"

[[variables]]
name="WaiguanType"
type="int32"
tag="waiguan_type"
comment="外观类型"

[[variables]]
name="WaiguanId"
type="int32"
tag="waiguan_id"
comment="外观Id"
