file="wushuangweapon_strengthen_vo.go"
pkg="template"
class="WushuangWeaponStrengthenTemplateVO"
comment = "无双神器强化配置"
[[variables]]
name="Id"
type="int"
tag="id"
comment="id"

[[variables]]
name="Level"
type="int32"
tag="level"
comment="强化等级"

[[variables]]
name="NextId"
type="int32"
tag="next_id"
comment="下一级强化等级"

[[variables]]
name="Hp"
type="int64"
tag="hp"
comment="强化生命值"

[[variables]]
name="Attack"
type="int64"
tag="attack"
comment="强化攻击力"

[[variables]]
name="Defence"
type="int64"
tag="defence"
comment="强化防御力"

[[variables]]
name="Experience"
type="int64"
tag="experience"
comment="升级所需经验"

[[variables]]
name="TupoZhuanshu"
type="int32"
tag="tupo_zhuanshu"
comment="突破需要的最低转数"

[[variables]]
name="TupoRate"
type="int32"
tag="tupo_rate"
comment="突破成功率"

[[variables]]
name="IsTupo"
type="int32"
tag="is_tupo"
comment="是否需要突破"

[[variables]]
name="TupoNeedCount"
type="int32"
tag="tupo_need_count"
comment="突破需要物品数量"

[[variables]]
name="TupoNeedQuality"
type="int32"
tag="tupo_need_quality"
comment="突破需要物品品质"