file="discount_gift_vo.go"
pkg="template"
class="DiscountTemplateVO"
comment = "折扣配置"
[[variables]]
name="Id"
type="int"
tag="id"
comment="id"

[[variables]]
name="Group"
type="int32"
tag="group"
comment="活动id"

[[variables]]
name="DayGroup"
type="int32"
tag="day_group"
comment="更新天数"

[[variables]]
name="Index"
type="int32"
tag="index"
comment="位置"

[[variables]]
name="ItemId"
type="int32"
tag="item_id"
comment="物品模板id"

[[variables]]
name="Name"
type="string"
tag="name"
comment="名称"

[[variables]]
name="BuyCount"
type="int32"
tag="buy_count"
comment="一次性购买的数量"

[[variables]]
name="MaxCount"
type="int32"
tag="max_count"
comment="最大购买数量"

[[variables]]
name="YuanGold"
type="int32"
tag="yuan_gold"
comment="原价"

[[variables]]
name="UseGold"
type="int32"
tag="use_gold"
comment="实际价格"

[[variables]]
name="Dazhe"
type="int32"
tag="dazhe"
comment="折扣"

[[variables]]
name="IsBind"
type="int32"
tag="is_bind"
comment="是否绑定"

[[variables]]
name="LimitQuanfu"
type="int32"
tag="limit_quanfu"
comment="全服限购"

[[variables]]
name="LimitCount"
type="int32"
tag="limit_count"
comment="每日限购次数,第二天清空处理"


