file="xiantao_constant_vo.go"
pkg="template"
class="XianTaoConstantTemplateVO"
comment = "仙桃大会常量配置"
[[variables]]
name="Id"
type="int"
tag="id"
comment="id"

[[variables]]
name="XianTaoMin"
type="int32"
tag="xiantao_min"
comment="玩家身上仙桃的最低数量"

[[variables]]
name="XianTaoMax"
type="int32"
tag="xiantao_max"
comment="玩家身上仙桃的最高数量"

[[variables]]
name="CaiJiLimit"
type="int32"
tag="caiji_limit"
comment="玩家采集的次数限制"

[[variables]]
name="JieQuLimit"
type="int32"
tag="jiequ_limit"
comment="玩家劫取限制次数"

[[variables]]
name="XianTaoBuff"
type="int32"
tag="xiantao_buff"
comment="千年仙桃的buffid"

[[variables]]
name="XianTaoBuff2"
type="int32"
tag="xiantao_buff2"
comment="百年仙桃的buffid"

[[variables]]
name="BuSunBuff"
type="int32"
tag="busun_buff"
comment="被劫取不再损失仙桃时身上的buff"

[[variables]]
name="TaoXianBiologyId"
type="int32"
tag="taoxian_biology_id"
comment="上交NPC的id"

[[variables]]
name="TiJiaoService"
type="int32"
tag="tijiao_service"
comment="提交仙桃距离"