file="xianzun_card_vo.go"
pkg="template"
class="XianZunCardTemplateVO"
comment = "仙尊特权卡配置"

[[variables]]
name="Id"
type="int"
tag="id"
comment="id"

[[variables]]
name="Type"
type="int32"
tag="type"
comment="仙尊卡类型"

[[variables]]
name="Name"
type="string"
tag="name"
comment="仙尊卡名称"

[[variables]]
name="NeedGold"
type="int32"
tag="need_gold"
comment="所需元宝"

[[variables]]
name="Duration"
type="int64"
tag="duration"
comment="持续时间"

[[variables]]
name="JiHuoRewSilver"
type="int32"
tag="jihuo_rew_silver"
comment="激活奖励银两"

[[variables]]
name="JiHuoRewGold"
type="int32"
tag="jihuo_rew_gold"
comment="激活奖励元宝"

[[variables]]
name="JiHuoRewBindGold"
type="int32"
tag="jihuo_rew_bind_gold"
comment="激活奖励绑元"

[[variables]]
name="ItemId"
type="string"
tag="jihuo_get_item"
comment="激活获得物品id"

[[variables]]
name="ItemCount"
type="string"
tag="jihuo_get_item_count"
comment="激活获得物品数量"

[[variables]]
name="DayRewSilver"
type="int32"
tag="day_rew_silver"
comment="每日领取银两的数量"

[[variables]]
name="DayRewGold"
type="int32"
tag="day_rew_gold"
comment="每日领取元宝的数量"

[[variables]]
name="DayRewBindGold"
type="int32"
tag="day_rew_bind_gold"
comment="每日领取绑元的数量"

[[variables]]
name="DayRewItem"
type="string"
tag="day_rew_item"
comment="每日奖励物品id"

[[variables]]
name="DayRewItemCount"
type="string"
tag="day_rew_item_count"
comment="每日奖励物品数量"

[[variables]]
name="SilverXianFuFreeAdd"
type="int32"
tag="silver_xianfu_free_add"
comment="银两副本增加的每日免费挑战次数"

[[variables]]
name="ExpXianFuFreeAdd"
type="int32"
tag="exp_xianfu_free_add"
comment="经验副本增加的每日免费挑战次数"

[[variables]]
name="BiologySetType"
type="string"
tag="biology_set_type"
comment="获得经验加成的生物类型"

[[variables]]
name="ExpBiologyAddPercent"
type="int32"
tag="exp_biology_add_percent"
comment="杀怪获得的经验加成比例"

[[variables]]
name="MountAttrAddPercent"
type="int32"
tag="mount_attr_add_percent"
comment="坐骑基础属性增加的万分比"

[[variables]]
name="TianJieBossFreeAdd"
type="int32"
tag="tianjie_boss_free_add"
comment="天界Boss免费进入次数"

[[variables]]
name="JiFenAddPercent"
type="int32"
tag="arena_jifen_add_percent"
comment="3V3积分增加万分比"

[[variables]]
name="JiFenMaxAddPercent"
type="int32"
tag="arena_jifen_max_add_percent"
comment="每天获得积分上限增加的万分比"

[[variables]]
name="WingAttrAddPercent"
type="int32"
tag="wing_attr_add_percent"
comment="战翼基础属性增加的万分比"