file="xianfu_silver_vo.go"
pkg="template"
class="XianFuSilverTemplateVO"
comment = "银两副本配置"
[[variables]]
name="Id"
type="int"
tag="id"
comment="id"

[[variables]]
name="Name"
type="string"
tag="name"
comment="名字"

[[variables]]
name="MapId"
type="int32"
tag="map_id"
comment="地图ID"

[[variables]]
name="BossId"
type="int32"
tag="boss_id"
comment="摇钱树怪物Id"

[[variables]]
name="UpgradeYinliang"
type="int64"
tag="upgrade_yinliang"
comment="升级所需银两"

[[variables]]
name="UpgradeGold"
type="int32"
tag="upgrade_gold"
comment="升级所需元宝"

[[variables]]
name="UpgradeBindGold"
type="int32"
tag="upgrade_bind_gold"
comment="升级所需绑元"

[[variables]]
name="UpgradeItemId"
type="int32"
tag="upgrade_item_id"
comment="升级所需物品ID"

[[variables]]
name="UpgradeItemNum"
type="int32"
tag="upgrade_item_num"
comment="升级所需物品数量"

[[variables]]
name="UpgradeTime"
type="int32"
tag="upgrade_time"
comment="升级所需时间（秒）"

[[variables]]
name="SpeedUpNeedGold"
type="float64"
tag="speed_up_need_gold"
comment="加速所需元宝（元宝/小时）"

[[variables]]
name="SaodangNeedGold"
type="int32"
tag="saodang_need_gold"
comment="扫荡所需元宝"

[[variables]]
name="SaodangNeedItemId"
type="string"
tag="saodang_need_item_id"
comment="扫荡所需的物品，支持多个，字符串"

[[variables]]
name="SaodangNeedItemCount"
type="string"
tag="saodang_need_item_count"
comment="扫荡所需的物品的数量，无物品相对应"

[[variables]]
name="RawExp"
type="int64"
tag="raw_exp"
comment="扫荡奖励经验值"

[[variables]]
name="RawExpPoint"
type="int64"
tag="raw_exp_point"
comment="扫荡奖励经验点"

[[variables]]
name="RawSilver"
type="int64"
tag="raw_silver"
comment="扫荡奖励银两"

[[variables]]
name="RawGold"
type="int32"
tag="raw_gold"
comment="扫荡奖励元宝"

[[variables]]
name="RawBindGold"
type="int32"
tag="raw_bind_gold"
comment="扫荡奖励绑定元宝"

[[variables]]
name="RawItemId"
type="string"
tag="raw_item_id"
comment="扫荡奖励物品ID，用逗号隔开"

[[variables]]
name="RawItemCount"
type="string"
tag="raw_item_count"
comment="扫荡奖励物品数量，用逗号隔开"

[[variables]]
name="RawDropId"
type="string"
tag="raw_drop_id"
comment="扫荡奖励掉落包ID，用逗号隔开"

[[variables]]
name="GetItemId"
type="string"
tag="get_item_id"
comment="通关奖励物品ID，用逗号隔开"

[[variables]]
name="GetItemCount"
type="string"
tag="get_item_count"
comment="通关奖励物品数量，用逗号隔开"

[[variables]]
name="RewardPreviewId"
type="string"
tag="reward_preview_id"
comment="奖励预览物品ID，字符串，支持多个"

[[variables]]
name="RewardPreviewCount"
type="string"
tag="reward_preview_count"
comment="奖励预览的个数，字符串，与奖励预览ID相对应"

[[variables]]
name="NeedItemId"
type="int32"
tag="need_item_id"
comment="进入副本所需物品ID"

[[variables]]
name="NeedItemCount"
type="int32"
tag="need_item_count"
comment="进入副本所需物品数量"

[[variables]]
name="NextId"
type="int"
tag="next_id"
comment="下一级ID"

[[variables]]
name="Free"
type="int32"
tag="free"
comment="每日免费次数"
