file="xiantao_times_vo.go"
pkg="template"
class="XianTaoTimesTemplateVO"
comment = "仙桃大会劫取配置"
[[variables]]
name="Id"
type="int"
tag="id"
comment="id"

[[variables]]
name="NextId"
type="int"
tag="next_id"
comment="下一个id"

[[variables]]
name="Times"
type="int32"
tag="times"
comment="第N次"

[[variables]]
name="JieQuPercent"
type="int32"
tag="jiequ_percent"
comment="劫取成功后获得的仙桃比例（万分比）"

[[variables]]
name="SunShiPercent"
type="int32"
tag="sunshi_percent"
comment="被劫取后损失的仙桃比例（万分比）"
