file="xiantao_vo.go"
pkg="template"
class="XianTaoTemplateVO"
comment = "仙桃大会配置"
[[variables]]
name="Id"
type="int"
tag="id"
comment="id"

[[variables]]
name="NextId"
type="int"
tag="next_id"
comment="下一个id"

[[variables]]
name="Typ"
type="int32"
tag="type"
comment="仙桃类型"

[[variables]]
name="XianTaoCount"
type="string"
tag="xiantao_count"
comment="提交的物品数量区间"

[[variables]]
name="RewExp"
type="int32"
tag="rew_xp"
comment="提交获得奖励经验值"

[[variables]]
name="RewExpPoint"
type="int32"
tag="rew_exp_point"
comment="提交获得奖励经验点"

[[variables]]
name="RewSilver"
type="int32"
tag="rew_silver"
comment="提交获得奖励银两"

[[variables]]
name="RewBindGold"
type="int32"
tag="rew_bind_gold"
comment="提交获得奖励绑元"

[[variables]]
name="RewGold"
type="int32"
tag="rew_gold"
comment="提交获得奖励元宝"

[[variables]]
name="RewItemId"
type="string"
tag="rew_item_id"
comment="提交获得奖励物品id"

[[variables]]
name="RewItemCount"
type="string"
tag="rew_item_count"
comment="提交获得奖励物品数量"
