

file="xinfa_vo.go"
pkg="template"
class="XinFaTemplateVO"
comment = "心法配置"
[[variables]]
name="Id"
type="int"
tag="id"
comment="id"

[[variables]]
name="NextId"
type="int32"
tag="next_id"
comment="后续id"

[[variables]]
name="Name"
type="string"
tag="name"
comment="名字"

[[variables]]
name="Type"
type="int32"
tag="type"
comment="类型"

[[variables]]
name="Level"
type="int32"
tag="level"
comment="等级"

[[variables]]
name="Des"
type="string"
tag="des"
comment="描述"

[[variables]]
name="DesInfo"
type="string"
tag="des_info"
comment="扩展描述"

[[variables]]
name="NeedYinLiang"
type="int32"
tag="need_yinliang"
comment="升级所需银两"

[[variables]]
name="NeedItemId"
type="int32"
tag="need_item_id"
comment="激活所需物品ID"

[[variables]]
name="NeedItemNum"
type="int32"
tag="need_item_num"
comment="激活所需物品数量"

[[variables]]
name="SkillId"
type="int32"
tag="skill_id"
comment="技能id"
