file="yazhi_vo.go"
pkg="template"
class="YaZhiTemplateVO"
comment = "收益率模板配置"
[[variables]]
name="Id"
type="int"
tag="id"
comment="id"

[[variables]]
name="LevelMin"
type="int32"
tag="level_min"
comment="最低等级"

[[variables]]
name="LevelMax"
type="int32"
tag="level_max"
comment="最高等级"

[[variables]]
name="ExpPercent"
type="int32"
tag="exp_percent"
comment="经验衰减万分比"

[[variables]]
name="DropPercent"
type="int32"
tag="drop_percent"
comment="掉落率衰落率"
