file="yichu_vo.go"
pkg="template"
class="YiChuTemplateVO"
comment = "衣橱模板配置"
[[variables]]
name="Id"
type="int"
tag="id"
comment="id"


[[variables]]
name="NextId"
type="int32"
tag="next_id"
comment="后续id"



[[variables]]
name="Type"
type="int32"
tag="type"
comment="套装类型"

[[variables]]
name="SubType"
type="int32"
tag="sub_type"
comment="套装类型"

[[variables]]
name="Number"
type="int32"
tag="number"
comment="件数"


[[variables]]
name="ShiDanLimit"
type="int32"
tag="shidan_limit"
comment="食丹上限"



[[variables]]
name="Hp"
type="int64"
tag="hp"
comment="生命上限"


[[variables]]
name="Attack"
type="int64"
tag="attack"
comment="攻击值"


[[variables]]
name="Defence"
type="int64"
tag="defence"
comment="防御值"


[[variables]]
name="HpPercent"
type="int64"
tag="hp_percent"
comment="生命万分比"


[[variables]]
name="AttackPercent"
type="int64"
tag="attack_percent"
comment="攻击万分比"


[[variables]]
name="DefPercent"
type="int64"
tag="def_percent"
comment="防御万分比"


[[variables]]
name="SkillId"
type="int32"
tag="skill_id"
comment="技能id"

[[variables]]
name="SkillId2"
type="int32"
tag="skill_id2"
comment="技能id2"

