file="yichu_suit_vo.go"
pkg="template"
class="YiChuSuitTemplateVO"
comment = "衣橱套装配置"
[[variables]]
name="Id"
type="int"
tag="id"
comment="id"

[[variables]]
name="Type"
type="int32"
tag="type"
comment="衣橱类型"

[[variables]]
name="Name"
type="string"
tag="name"
comment="套装名字"

[[variables]]
name="PeiYangBeginId"
type="int32"
tag="peiyang_begin_id"
comment="食丹等级起始id"

[[variables]]
name="MountId"
type="int32"
tag="mount_id"
comment="坐骑id"

[[variables]]
name="WingId"
type="int32"
tag="wing_id"
comment="战翼id"

[[variables]]
name="WeaponId"
type="int32"
tag="weapon_id"
comment="兵魂id"

[[variables]]
name="FaBaoId"
type="int32"
tag="fabao_id"
comment="法宝id"


[[variables]]
name="ShenFaId"
type="int32"
tag="shenfa_id"
comment="身法id"

[[variables]]
name="XianTiId"
type="int32"
tag="xianti_id"
comment="仙体id"

[[variables]]
name="FieldId"
type="int32"
tag="field_id"
comment="领域id"

[[variables]]
name="FashionId"
type="int32"
tag="fashion_id"
comment="时装id"

[[variables]]
name="TitleId"
type="int32"
tag="title_id"
comment="称号id"
