file="yinglingpu_suipian_vo.go"
pkg="template"
class="YinglingpuSuiPianTemplateVO"
comment = "英灵谱配置碎片"
[[variables]]
name="Id"
type="int"
tag="id"
comment="id"

[[variables]]
name="NextId"
type="int32"
tag="next_id"
comment="下一部位id"


[[variables]]
name="SuipianId"
type="int32"
tag="suipian_id"
comment="碎片部位编号,部位标识从1~4"

[[variables]]
name="UseItemId"
type="int32"
tag="use_item_id"
comment="激活该部位消耗的物品id"

[[variables]]
name="UseItemCount"
type="int32"
tag="use_item_count"
comment="激活该部位消耗的物品数量"

[[variables]]
name="Hp"
type="int32"
tag="hp"
comment="激活该部位后增加的生命"

[[variables]]
name="Attack"
type="int32"
tag="attack"
comment="激活该部位后增加的攻击"

[[variables]]
name="Defence"
type="int32"
tag="defence"
comment="激活该部位后增加的防御"


[[variables]]
name="Resource"
type="string"
tag="resource"
comment="该部位的图片资源"
