file="yinglingpu_vo.go"
pkg="template"
class="YinglingpuTemplateVO"
comment = "英灵谱配置"
[[variables]]
name="Id"
type="int"
tag="id"
comment="id"

[[variables]]
name="Type"
type="int32"
tag="type"
comment="类型,0为英灵图鉴,1为至尊英灵图鉴"

[[variables]]
name="TujianId"
type="int32"
tag="tujian_id"
comment="图鉴id"

[[variables]]
name="Name"
type="string"
tag="name"
comment="图鉴名称"

[[variables]]
name="LevelBeginId"
type="int32"
tag="level_begin_id"
comment="图鉴升级起始id"

[[variables]]
name="SuiPianBeginId"
type="int32"
tag="suipian_begin_id"
comment="碎片起始id"

[[variables]]
name="SpecialTag"
type="int32"
tag="special_tag"
comment="图片标志，0为无标志，1为稀有标志"

[[variables]]
name="PosId"
type="int32"
tag="pos_id"
comment="位置"

[[variables]]
name="Resource"
type="string"
tag="resource"
comment="图鉴图片资源"
