file="yinglingpu_suit_vo.go"
pkg="template"
class="YingLingPuSuitTemplateVO"
comment = "英灵谱套装配置"
[[variables]]
name="Id"
type="int"
tag="id"
comment="id"

[[variables]]
name="YinLingPuId"
type="string"
tag="yinlingpu_id"
comment="凑成套装所需要的id"
 
[[variables]]
name="HpPercent"
type="int32"
tag="hp_percent"
comment="增加的生命"

[[variables]]
name="AttackPercent"
type="int32"
tag="attack_percent"
comment="增加的攻击"

[[variables]]
name="DefPercent"
type="int32"
tag="def_percent"
comment="增加的防御"
 
[[variables]]
name="Hp"
type="int32"
tag="hp"
comment="增加的生命"

[[variables]]
name="Attack"
type="int32"
tag="attack"
comment="增加的攻击"

[[variables]]
name="Defence"
type="int32"
tag="defence"
comment="增加的防御"
