file="yinglingpu_level_suan_vo.go"
pkg="template"
class="YinglingpuLevelSuanTemplateVO"
comment = "英灵谱等级计算配置"

[[variables]]
name="Id"
type="int"
tag="id"
comment="id"

[[variables]]
name="AttrValueA"
type="int32"
tag="attr_value_a"
comment="属性a"

[[variables]]
name="AttrValueB"
type="int32"
tag="attr_value_b"
comment="属性b"

[[variables]]
name="AttrValueC"
type="int32"
tag="attr_value_c"
comment="属性c"

[[variables]]
name="AttrValueD"
type="int32"
tag="attr_value_d"
comment="属性d"

[[variables]]
name="AttrValueE"
type="int32"
tag="attr_value_e"
comment="属性e"

[[variables]]
name="ExpendValueA"
type="int32"
tag="expend_value_a"
comment="消耗属性a"

[[variables]]
name="ExpendValueB"
type="int32"
tag="expend_value_b"
comment="消耗属性b"

[[variables]]
name="ExpendValueC"
type="int32"
tag="expend_value_c"
comment="消耗属性c"

[[variables]]
name="ExpendValueD"
type="int32"
tag="expend_value_d"
comment="消耗属性d"

[[variables]]
name="ExpendValueE"
type="int32"
tag="expend_value_e"
comment="消耗属性e"

[[variables]]
name="Hp"
type="int32"
tag="hp"
comment="hp"

[[variables]]
name="Attack"
type="int32"
tag="attack"
comment="Attack"

[[variables]]
name="Defence"
type="int32"
tag="defence"
comment="defence"

[[variables]]
name="LevelMax"
type="int32"
tag="level_max"
comment="level_max"
