file="yuanbao_laba_vo.go"
pkg="template"
class="GoldLaBaTemplateVo"
comment = "元宝拉霸配置"

[[variables]]
name="Id"
type="int"
tag="id"
comment="id"

[[variables]]
name="NextId"
type="int"
tag="next_id" 
comment="下一级id" 

[[variables]]
name="GroupId"
type="int32"
tag="type" 
comment="关联运营活动id"

[[variables]]
name="Times"
type="int32"
tag="times" 
comment="次数"

[[variables]]
name="InvestmentRecharge"
type="int32"
tag="investment_recharge"
comment="所需玩家充值金额"

[[variables]]
name="Investment"
type="int32"
tag="investment"
comment="所需玩家元宝"

[[variables]]
name="ReturnMin1"
type="int32"
tag="return_min1"
comment="返还元宝下限1"

[[variables]]
name="ReturnMax1"
type="int32"
tag="return_max1"
comment="返还元宝上限1"

[[variables]]
name="Percent1"
type="int32"
tag="percent1"
comment="概率1"

[[variables]]
name="ReturnMin2"
type="int32"
tag="return_min2"
comment="返还元宝下限2"

[[variables]]
name="ReturnMax2"
type="int32"
tag="return_max2"
comment="返还元宝上限2"

[[variables]]
name="Percent2"
type="int32"
tag="percent2"
comment="概率2"