file="yuxi_constant_vo.go"
pkg="template"
class="YuXiConstantTemplateVO"
comment = "玉玺常量配置"
[[variables]]
name="Id"
type="int"
tag="id"
comment="id"

[[variables]]
name="WinTime"
type="int64"
tag="win_time"
comment="占有获胜时间"

[[variables]]
name="YuxiBiologyId"
type="int32"
tag="yuxi_biology_id"
comment="玉玺采集物id"

[[variables]]
name="MailItemId"
type="string"
tag="mail_item_id"
comment="获胜奖励物品id"
  
[[variables]]
name="MailItemCount"
type="string"
tag="mail_item_count"
comment="获胜奖励物品数量"
  
[[variables]]
name="WinDayItemId"
type="string"
tag="win_day_item_id"
comment="获胜每日奖励物品id"
  
[[variables]]
name="WinDayItemCount"
type="string"
tag="win_day_item_count"
comment="获胜每日奖励物品数量"
  
[[variables]]
name="BuffId"
type="int32"
tag="buff_id"
comment="玉玺buffId"
  
[[variables]] 
name="RescueCd"
type="int64"
tag="qianlijiuyuan_cd"
comment="千里救援cd"

[[variables]]
name="PosX"
type="float64"
tag="pos_x"
comment="地图x坐标"

[[variables]]
name="PosY"
type="float64"
tag="pos_y"
comment="地图y坐标"

[[variables]]
name="PosZ"
type="float64"
tag="pos_z"
comment="地图z坐标"

[[variables]]
name="MapId"
type="int32"
tag="map_id"
comment="地图id"


[[variables]]
name="ModelPosX"
type="float64"
tag="pos_x1"
comment="玉玺争夺战获胜仙盟盟主雕像 地图x坐标"

[[variables]]
name="ModelPosY"
type="float64"
tag="pos_y1"
comment="玉玺争夺战获胜仙盟盟主雕像 地图y坐标"

[[variables]]
name="ModelPosZ"
type="float64"
tag="pos_z1"
comment="玉玺争夺战获胜仙盟盟主雕像 地图z坐标"

[[variables]]
name="ModelCouplePosX"
type="float64"
tag="pos_x2"
comment="玉玺争夺战获胜仙盟盟主配偶雕像 地图x坐标"

[[variables]]
name="ModelCouplePosY"
type="float64"
tag="pos_y2"
comment="玉玺争夺战获胜仙盟盟主配偶雕像 地图y坐标"

[[variables]]
name="ModelCouplePosZ"
type="float64"
tag="pos_z2"
comment="玉玺争夺战获胜仙盟盟主配偶雕像 地图z坐标"

[[variables]]
name="ModelMapId"
type="int32"
tag="map_id1" 
comment="雕像地图id"
