file="zhenfa_jihuo_vo.go"
pkg="template"
class="ZhenFaJiHuoTemplateVO"
comment = "阵法激活模板配置"
[[variables]]
name="Id"
type="int"
tag="id"
comment="id"


[[variables]]
name="Type"
type="int"
tag="type"
comment="阵法类型"

[[variables]]
name="Name"
type="string"
tag="name"
comment="阵法总等级"



[[variables]]
name="UpdateWfb"
type="int32"
tag="update_wfb"
comment="成功率"

[[variables]]
name="UseItem"
type="int32"
tag="use_item"
comment="消耗的物品id"

[[variables]]
name="ItemCount"
type="int32"
tag="item_count"
comment="消耗的物品数量"

[[variables]]
name="TimesMin"
type="int32"
tag="times_min"
comment="最小次数"

[[variables]]
name="TimesMax"
type="int32"
tag="times_max"
comment="最大次数"

[[variables]]
name="AddMin"
type="int32"
tag="add_min"
comment="每次增加祝福值最小值"

[[variables]]
name="AddMax"
type="int32"
tag="add_max"
comment="每次增加祝福值最大值"

[[variables]]
name="ZhuFuMax"
type="int32"
tag="zhufu_max"
comment="前端祝福值显示值"

[[variables]]
name="NeedZhenFaType"
type="int32"
tag="need_zhenfa_type"
comment="需要的前置战法类型"

[[variables]]
name="NeedZhenFaLevel"
type="int32"
tag="need_zhenfa_level"
comment="需要的前置战法等级"

[[variables]]
name="Hp"
type="int64"
tag="hp"
comment="生命上限"


[[variables]]
name="Attack"
type="int64"
tag="attack"
comment="攻击值"


[[variables]]
name="Defence"
type="int64"
tag="defence"
comment="防御值"


