file="zhenxi_boss_use_vo.go"
pkg="template"
class="ZhenXiBossUseTemplateVO"
comment = "珍惜boss消耗配置"
[[variables]]
name="Id"
type="int"
tag="id"
comment="id"

[[variables]]
name="MapId"
type="int32"
tag="map_id"
comment="地图id"

[[variables]]
name="UseItem"
type="int32"
tag="use_item"
comment="使用物品"


[[variables]]
name="UseCount"
type="int32"
tag="use_count"
comment="使用数量"

