file="zhenfa_taozhuang_vo.go"
pkg="template"
class="ZhenFaTaoZhuangTemplateVO"
comment = "阵法套装模板配置"
[[variables]]
name="Id"
type="int"
tag="id"
comment="id"

[[variables]]
name="Level"
type="int32"
tag="level"
comment="阵法总等级"

[[variables]]
name="Hp"
type="int64"
tag="hp"
comment="生命上限"

[[variables]]
name="Attack"
type="int64"
tag="attack"
comment="攻击值"

[[variables]]
name="Defence"
type="int64"
tag="defence"
comment="防御值"

