

file="zhuansheng_vo.go"
pkg="template"
class="ZhuanShengTemplateVO"
comment = "转生配置"
[[variables]]
name="Id"
type="int"
tag="id"
comment="id"

[[variables]]
name="NeedZhuanshu"
type="int32"
tag="need_zhuanshu"
comment="转生所需玩家转数"

[[variables]]
name="NeedLevel"
type="int32"
tag="need_level"
comment="转生所需玩家等级"

[[variables]]
name="NeedFeisheng"
type="int32"
tag="need_feisheng"
comment="转生所需玩家飞升等级"

[[variables]]
name="NeedEquipCount"
type="int32"
tag="need_equip_count"
comment="转生所需装备件数"

[[variables]]
name="NeedEquipZhuanshu"
type="int32"
tag="need_equip_zhuanshu"
comment="转生所需玩家装备转数"

[[variables]]
name="NeedEquipLevel"
type="int32"
tag="need_equip_level"
comment="转生所需玩家装备等级"

[[variables]]
name="NeedEquipStreng"
type="int32"
tag="need_equip_streng"
comment="转生所需玩家装备强化等级"

[[variables]]
name="NeedEquipQuality"
type="int32"
tag="need_equip_quality"
comment="新增转生所需装备品质描述"

[[variables]]
name="Hp"
type="int32"
tag="hp"
comment="生命加成（固定值）"

[[variables]]
name="Attack"
type="int32"
tag="attack"
comment="攻击加成（固定值）"

[[variables]]
name="Defence"
type="int32"
tag="defence"
comment="防御加成（固定值）"
