file="zhuansheng_gift_vo.go"
pkg="template"
class="ZhuanShengGiftTemplateVO"
comment = "转生大礼包配置"
[[variables]]
name="Id"
type="int"
tag="id"
comment="id"

[[variables]]
name="Group"
type="int32"
tag="group"
comment="活动id"

[[variables]]
name="Type"
type="int32"
tag="type"
comment="类型"

[[variables]]
name="ItemId"
type="string"
tag="item_id"
comment="物品id"

[[variables]]
name="ItemCount"
type="string"
tag="item_count"
comment="数量"

[[variables]]
name="Profession"
type="int32"
tag="profession"
comment="职业"


[[variables]]
name="Gender"
type="int32"
tag="gender"
comment="性别"

[[variables]]
name="BuyCount"
type="int32"
tag="buy_count"
comment="购买数量"

[[variables]]
name="MaxCount"
type="int32"
tag="max_count"
comment="最大数量"

[[variables]]
name="YuanGold"
type="int32"
tag="yuan_gold"
comment="原价"

[[variables]]
name="UseGold"
type="int32"
tag="use_gold"
comment="现价"

[[variables]]
name="DaZhe"
type="int32"
tag="dazhe"
comment="折数"

[[variables]]
name="IsBind"
type="int32"
tag="is_bind"
comment="是否绑定"

[[variables]]
name="BuyMax"
type="int32"
tag="buy_max"
comment="最大购买"

[[variables]]
name="UseItemId"
type="string"
tag="use_item_id"
comment="消耗id"

[[variables]]
name="UseItemCount"
type="string" 
tag="use_item_count"
comment="消耗数量"

[[variables]]
name="NeedChongZhi"
type="int32" 
tag="need_chongzhi"
comment="充值后可购买"

[[variables]]
name="Bargain"
type="int32" 
tag="bargain" 
comment="批量购买折扣"


[[variables]]
name="GiveItemId"
type="string"
tag="give_item_id"
comment="赠送id"

[[variables]]
name="GiveItemCount"
type="string" 
tag="give_item_count"
comment="赠送数量"

[[variables]]
name="UsePoint"
type="int32"
tag="use_point"
comment="现积分价"