

file="teamcopy_vo.go"
pkg="template"
class="TeamCopyTemplateVO"
comment = "组队副本配置"
[[variables]]
name="Id"
type="int"
tag="id"
comment="id"

[[variables]]
name="Type"
type="int32"
tag="type"
comment="组队类型"

[[variables]]
name="Name"
type="string"
tag="name"
comment="名字"

[[variables]]
name="MapId"
type="int32"
tag="map_id"
comment="地图类型"

[[variables]]
name="BiologyId"
type="string"
tag="biology_id"
comment="生物id"


[[variables]]
name="RewardNumber"
type="int32"
tag="reward_number"
comment="每日奖励次数"

[[variables]]
name="ResurrectionNumber"
type="int32"
tag="resurrection_number"
comment="复活次数"

[[variables]]
name="ItemId"
type="string"
tag="item_id"
comment="奖励物品"

[[variables]]
name="ItemCount"
type="string"
tag="item_count"
comment="对应数量"

[[variables]]
name="RewardGold"
type="int32"
tag="reward_gold"
comment="奖励元宝"


[[variables]]
name="RewardBindgold"
type="int32"
tag="reward_bindgold"
comment="奖励绑元"


[[variables]]
name="RewardSilver"
type="int32"
tag="reward_silver"
comment="奖励银两"


[[variables]]
name="RewardPreviewId"
type="string"
tag="reward_preview_id"
comment="奖励银两"


[[variables]]
name="RecForce"
type="int32"
tag="rec_force"
comment="推荐战力"
