version: "3"
services:
    nsqlookupd:
        image: 192.168.1.210:5000/nsqio/nsq:v0.3.8
        ports:
            - "4160:4160"
            - "4161:4161"
        command: 
            - "/nsqlookupd"
    nsqd:
        image: 192.168.1.210:5000/nsqio/nsq:v0.3.8
        ports: 
            - "4150:4150"
            - "4151:4151"
        command: 
            - "/nsqd"
            - "--lookupd-tcp-address=nsqlookupd:4160"
            - "-broadcast-address=192.168.1.210"
    nsqdadmin:
        image: 192.168.1.210:5000/nsqio/nsq:v0.3.8
        ports: 
            - "4170:4170"
            - "4171:4171"
        command: 
            - "/nsqadmin"
            - "--lookupd-http-address=nsqlookupd:4161"

